#!/bin/bash

JAR=lib/discover.jar

if [ -n "$DEBUG_PORT" ] ; then
    echo "Debug port set to $DEBUG_PORT"
    ARGS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=$DEBUG_PORT"
fi

if [ -e "$JAR" ]
then
    java $ARGS -jar $JAR $@
else
    
    DIR=`dirname "$0"`
    JAR="${DIR}/${JAR}"
    
    if [ -e "$JAR" ]
    then
        java $ARGS -Xmx1024m -jar $JAR $@
    else
        echo "Java jar file not available: $JAR"
    fi
fi
