package discover.vdis.enums;

import java.util.List;

/**
 * ACK_ACKNOWLEDGE_FLAG: This class is auto-generated by vdis.EnumGenerator
 */
public final class ACK_ACKNOWLEDGE_FLAG extends Value {

    public static final ACK_ACKNOWLEDGE_FLAG
       ACK_FLAG_CREATE_ENTITY = new ACK_ACKNOWLEDGE_FLAG(1, "ACK_FLAG_CREATE_ENTITY", "Create Entity", true),
       ACK_FLAG_REMOVE_ENTITY = new ACK_ACKNOWLEDGE_FLAG(2, "ACK_FLAG_REMOVE_ENTITY", "Remove Entity", true),
       ACK_FLAG_START_RESUME = new ACK_ACKNOWLEDGE_FLAG(3, "ACK_FLAG_START_RESUME", "Start Resume", true),
       ACK_FLAG_STOP_FREEZE = new ACK_ACKNOWLEDGE_FLAG(4, "ACK_FLAG_STOP_FREEZE", "Stop Freeze", true),
       ACK_FLAG_TRANSFER_CONTROL_REQUEST = new ACK_ACKNOWLEDGE_FLAG(5, "ACK_FLAG_TRANSFER_CONTROL_REQUEST", "Transfer Control Request", true);

    private ACK_ACKNOWLEDGE_FLAG(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, ACK_ACKNOWLEDGE_FLAG.class);
    }

    /** @see Value#values(Class) */
    public static List<ACK_ACKNOWLEDGE_FLAG> values() {

        return values(ACK_ACKNOWLEDGE_FLAG.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<ACK_ACKNOWLEDGE_FLAG> values(boolean known) {

        return values(ACK_ACKNOWLEDGE_FLAG.class, known);
    }

    /** @see Value#get(int, Class) */
    public static ACK_ACKNOWLEDGE_FLAG get(int value) {

        return get(value, ACK_ACKNOWLEDGE_FLAG.class);
    }
}

