package discover.vdis.enums;

import java.util.List;

/**
 * ACTION_SEQ_DIR: This class is auto-generated by vdis.EnumGenerator
 */
public final class ACTION_SEQ_DIR extends Value {

    public static final ACTION_SEQ_DIR
       ACTN_SEQ_DIR_NOT_SPECIFIED = new ACTION_SEQ_DIR(0, "ACTN_SEQ_DIR_NOT_SPECIFIED", "Not Specified", true),
       ACTN_SEQ_DIR_UP = new ACTION_SEQ_DIR(1, "ACTN_SEQ_DIR_UP", "Up", true),
       ACTN_SEQ_DIR_DOWN = new ACTION_SEQ_DIR(2, "ACTN_SEQ_DIR_DOWN", "Down", true),
       ACTN_SEQ_DIR_LEFT = new ACTION_SEQ_DIR(3, "ACTN_SEQ_DIR_LEFT", "Left", true),
       ACTN_SEQ_DIR_RIGHT = new ACTION_SEQ_DIR(4, "ACTN_SEQ_DIR_RIGHT", "Right", true),
       ACTN_SEQ_DIR_FORWARD = new ACTION_SEQ_DIR(5, "ACTN_SEQ_DIR_FORWARD", "Forward", true),
       ACTN_SEQ_DIR_BACKWARD = new ACTION_SEQ_DIR(6, "ACTN_SEQ_DIR_BACKWARD", "Backward", true),
       ACTN_SEQ_DIR_STATION = new ACTION_SEQ_DIR(7, "ACTN_SEQ_DIR_STATION", "Station", true),
       ACTN_SEQ_DIR_SPECIFIED_GLOBAL_LOCATION = new ACTION_SEQ_DIR(8, "ACTN_SEQ_DIR_SPECIFIED_GLOBAL_LOCATION", "Specified Global Location", true),
       ACTN_SEQ_DIR_SPECIFIED_ORIENTATION_VECTOR = new ACTION_SEQ_DIR(9, "ACTN_SEQ_DIR_SPECIFIED_ORIENTATION_VECTOR", "Specified Orientation Vector", true);

    private ACTION_SEQ_DIR(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, ACTION_SEQ_DIR.class);
    }

    /** @see Value#values(Class) */
    public static List<ACTION_SEQ_DIR> values() {

        return values(ACTION_SEQ_DIR.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<ACTION_SEQ_DIR> values(boolean known) {

        return values(ACTION_SEQ_DIR.class, known);
    }

    /** @see Value#get(int, Class) */
    public static ACTION_SEQ_DIR get(int value) {

        return get(value, ACTION_SEQ_DIR.class);
    }
}

