package discover.vdis.enums;

import java.util.List;

/**
 * ACTREQ_ACTION_IDS: This class is auto-generated by vdis.EnumGenerator
 */
public final class ACTREQ_ACTION_IDS extends Value {

    public static final ACTREQ_ACTION_IDS
       ACTREQ_ID_OTHER = new ACTREQ_ACTION_IDS(0, "ACTREQ_ID_OTHER", "Other", true),
       ACTREQ_ID_LOCAL_STORAGE_REQ_INFO = new ACTREQ_ACTION_IDS(1, "ACTREQ_ID_LOCAL_STORAGE_REQ_INFO", "Local Storage Requested Information", true),
       ACTREQ_ID_INFORM_EVENT_RAN_OUT_OF_AMMO = new ACTREQ_ACTION_IDS(2, "ACTREQ_ID_INFORM_EVENT_RAN_OUT_OF_AMMO", "Inform Event Ran Out of Ammunition", true),
       ACTREQ_ID_INFORM_EVENT_KILLED_IN_ACTION = new ACTREQ_ACTION_IDS(3, "ACTREQ_ID_INFORM_EVENT_KILLED_IN_ACTION", "Inform Event Killed In Action", true),
       ACTREQ_ID_INFORM_EVENT_DAMAGE = new ACTREQ_ACTION_IDS(4, "ACTREQ_ID_INFORM_EVENT_DAMAGE", "Inform Event Damage", true),
       ACTREQ_ID_INFORM_EVENT_MOBILITY_DISABLED = new ACTREQ_ACTION_IDS(5, "ACTREQ_ID_INFORM_EVENT_MOBILITY_DISABLED", "Inform Event Mobility Disabled", true),
       ACTREQ_ID_INFORM_EVENT_FIRE_DISABLED = new ACTREQ_ACTION_IDS(6, "ACTREQ_ID_INFORM_EVENT_FIRE_DISABLED", "Inform Event Fire Disabled", true),
       ACTREQ_ID_INFORM_EVENT_RAN_OUT_OF_FUEL = new ACTREQ_ACTION_IDS(7, "ACTREQ_ID_INFORM_EVENT_RAN_OUT_OF_FUEL", "Inform Event Ran Out of Fuel", true),
       ACTREQ_ID_RECALL_CHECKPOINT_DATA = new ACTREQ_ACTION_IDS(8, "ACTREQ_ID_RECALL_CHECKPOINT_DATA", "Recall Checkpoint Data", true),
       ACTREQ_ID_RECALL_INITIAL_PARMS = new ACTREQ_ACTION_IDS(9, "ACTREQ_ID_RECALL_INITIAL_PARMS", "Recall Initial Parameters", true),
       ACTREQ_ID_INIT_TETHER_LEAD = new ACTREQ_ACTION_IDS(10, "ACTREQ_ID_INIT_TETHER_LEAD", "Initiate Tether-Lead", true),
       ACTREQ_ID_INIT_TETHER_FOLLOW = new ACTREQ_ACTION_IDS(11, "ACTREQ_ID_INIT_TETHER_FOLLOW", "Initiate Tether-Follow", true),
       ACTREQ_ID_UNTETHER = new ACTREQ_ACTION_IDS(12, "ACTREQ_ID_UNTETHER", "Untether", true),
       ACTREQ_ID_INIT_SERVICE_STATION_RESUPPLY = new ACTREQ_ACTION_IDS(13, "ACTREQ_ID_INIT_SERVICE_STATION_RESUPPLY", "Initiate Service Station Resupply", true),
       ACTREQ_ID_INIT_TAILGATE_RESUPPLY = new ACTREQ_ACTION_IDS(14, "ACTREQ_ID_INIT_TAILGATE_RESUPPLY", "Initiate Tailgate Resupply", true),
       ACTREQ_ID_INIT_HITCH_LEAD = new ACTREQ_ACTION_IDS(15, "ACTREQ_ID_INIT_HITCH_LEAD", "Initiate Hitch Lead", true),
       ACTREQ_ID_INIT_HITCH_FOLLOW = new ACTREQ_ACTION_IDS(16, "ACTREQ_ID_INIT_HITCH_FOLLOW", "Initiate Hitch Follow", true),
       ACTREQ_ID_UNHITCH = new ACTREQ_ACTION_IDS(17, "ACTREQ_ID_UNHITCH", "Unhitch", true),
       ACTREQ_ID_MOUNT = new ACTREQ_ACTION_IDS(18, "ACTREQ_ID_MOUNT", "Mount", true),
       ACTREQ_ID_DISMOUNT = new ACTREQ_ACTION_IDS(19, "ACTREQ_ID_DISMOUNT", "Dismount", true),
       ACTREQ_ID_START_DRC = new ACTREQ_ACTION_IDS(20, "ACTREQ_ID_START_DRC", "Start Daily Readiness Check", true),
       ACTREQ_ID_STOP_DRC = new ACTREQ_ACTION_IDS(21, "ACTREQ_ID_STOP_DRC", "Stop Daily Readiness Check", true),
       ACTREQ_ID_DATA_QUERY = new ACTREQ_ACTION_IDS(22, "ACTREQ_ID_DATA_QUERY", "Data Query", true),
       ACTREQ_ID_STATUS_REQ = new ACTREQ_ACTION_IDS(23, "ACTREQ_ID_STATUS_REQ", "Status Request", true),
       ACTREQ_ID_SEND_OBJECT_STATE_DATA = new ACTREQ_ACTION_IDS(24, "ACTREQ_ID_SEND_OBJECT_STATE_DATA", "Send Object State Data", true),
       ACTREQ_ID_RECONSTITUTE = new ACTREQ_ACTION_IDS(25, "ACTREQ_ID_RECONSTITUTE", "Reconstitute", true),
       ACTREQ_ID_LOCK_SITE_CONFIG = new ACTREQ_ACTION_IDS(26, "ACTREQ_ID_LOCK_SITE_CONFIG", "Lock Site Configuration", true),
       ACTREQ_ID_UNLOCK_SITE_CONFIG = new ACTREQ_ACTION_IDS(27, "ACTREQ_ID_UNLOCK_SITE_CONFIG", "Unlock Site Configuration", true),
       ACTREQ_ID_UPDATE_SITE_CONFIG = new ACTREQ_ACTION_IDS(28, "ACTREQ_ID_UPDATE_SITE_CONFIG", "Update Site Configuration", true),
       ACTREQ_ID_QUERY_SITE_CONFIG = new ACTREQ_ACTION_IDS(29, "ACTREQ_ID_QUERY_SITE_CONFIG", "Query Site Configuration", true),
       ACTREQ_ID_TETHERING_INFORMATION = new ACTREQ_ACTION_IDS(30, "ACTREQ_ID_TETHERING_INFORMATION", "Tethering Information", true),
       ACTREQ_ID_MOUNT_INTENT = new ACTREQ_ACTION_IDS(31, "ACTREQ_ID_MOUNT_INTENT", "Mount Intent", true),
       ACTREQ_ID_ACCEPT_SUBSCRIPTION = new ACTREQ_ACTION_IDS(33, "ACTREQ_ID_ACCEPT_SUBSCRIPTION", "Accept Subscription", true),
       ACTREQ_ID_UNSUBSCRIBE = new ACTREQ_ACTION_IDS(34, "ACTREQ_ID_UNSUBSCRIBE", "Unsubscribe", true),
       ACTREQ_ID_TELEPORT_ENTITY = new ACTREQ_ACTION_IDS(35, "ACTREQ_ID_TELEPORT_ENTITY", "Teleport Entity", true),
       ACTREQ_ID_CHANGE_AGGREGATE_STATE = new ACTREQ_ACTION_IDS(36, "ACTREQ_ID_CHANGE_AGGREGATE_STATE", "Change Aggregate State", true),
       ACTREQ_ID_REQ_START_PDU = new ACTREQ_ACTION_IDS(37, "ACTREQ_ID_REQ_START_PDU", "Request Start PDU", true),
       ACTREQ_ID_WAKEUP_GET_READY_FOR_INIT = new ACTREQ_ACTION_IDS(38, "ACTREQ_ID_WAKEUP_GET_READY_FOR_INIT", "Wakeup Get Ready For Initialization", true),
       ACTREQ_ID_INIT_INTERNAL_PARMS = new ACTREQ_ACTION_IDS(39, "ACTREQ_ID_INIT_INTERNAL_PARMS", "Initialize Internal Parameters", true),
       ACTREQ_ID_SEND_PLAN_DATA = new ACTREQ_ACTION_IDS(40, "ACTREQ_ID_SEND_PLAN_DATA", "Send Plan Data", true),
       ACTREQ_ID_SYNC_INTERNAL_CLOCKS = new ACTREQ_ACTION_IDS(41, "ACTREQ_ID_SYNC_INTERNAL_CLOCKS", "Synchronize Internal Clocks", true),
       ACTREQ_ID_RUN = new ACTREQ_ACTION_IDS(42, "ACTREQ_ID_RUN", "Run", true),
       ACTREQ_ID_SAVE_INTERNAL_PARMS = new ACTREQ_ACTION_IDS(43, "ACTREQ_ID_SAVE_INTERNAL_PARMS", "Save Internal Parameters", true),
       ACTREQ_ID_SIMULATE_MALFUNCTION = new ACTREQ_ACTION_IDS(44, "ACTREQ_ID_SIMULATE_MALFUNCTION", "Simulate Malfunction", true),
       ACTREQ_ID_JOIN_EXERCISE = new ACTREQ_ACTION_IDS(45, "ACTREQ_ID_JOIN_EXERCISE", "Join Exercise", true),
       ACTREQ_ID_RESIGN_EXERCISE = new ACTREQ_ACTION_IDS(46, "ACTREQ_ID_RESIGN_EXERCISE", "Resign Exercise", true),
       ACTREQ_ID_TIME_ADVANCE = new ACTREQ_ACTION_IDS(47, "ACTREQ_ID_TIME_ADVANCE", "Time Advance", true),
       ACTREQ_ID_COMMAND_FROM_SIMULATOR = new ACTREQ_ACTION_IDS(48, "ACTREQ_ID_COMMAND_FROM_SIMULATOR", "Command from Simulator", true),
       ACTREQ_ID_TACCSF_LOS_REQ_TYPE_1 = new ACTREQ_ACTION_IDS(100, "ACTREQ_ID_TACCSF_LOS_REQ_TYPE_1", "TACCSF LOS Request-Type 1", true),
       ACTREQ_ID_TACCSF_LOS_REQ_TYPE_2 = new ACTREQ_ACTION_IDS(101, "ACTREQ_ID_TACCSF_LOS_REQ_TYPE_2", "TACCSF LOS Request-Type 2", true),
       ACTREQ_ID_SLING_CAPABILITY_REQ = new ACTREQ_ACTION_IDS(4300, "ACTREQ_ID_SLING_CAPABILITY_REQ", "Sling Load Capability Request", true),
       ACTREQ_ID_SLING_ATTACH_REQ = new ACTREQ_ACTION_IDS(4301, "ACTREQ_ID_SLING_ATTACH_REQ", "Sling Load Attach Request", true),
       ACTREQ_ID_SLING_RELEASE_REQ = new ACTREQ_ACTION_IDS(4302, "ACTREQ_ID_SLING_RELEASE_REQ", "Sling Load Release Request", true);

    private ACTREQ_ACTION_IDS(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, ACTREQ_ACTION_IDS.class);
    }

    /** @see Value#values(Class) */
    public static List<ACTREQ_ACTION_IDS> values() {

        return values(ACTREQ_ACTION_IDS.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<ACTREQ_ACTION_IDS> values(boolean known) {

        return values(ACTREQ_ACTION_IDS.class, known);
    }

    /** @see Value#get(int, Class) */
    public static ACTREQ_ACTION_IDS get(int value) {

        return get(value, ACTREQ_ACTION_IDS.class);
    }
}

