package discover.vdis.enums;

import java.util.List;

/**
 * ACTRES_REQ_STATUS: This class is auto-generated by vdis.EnumGenerator
 */
public final class ACTRES_REQ_STATUS extends Value {

    public static final ACTRES_REQ_STATUS
       ACTRES_REQ_OTHER = new ACTRES_REQ_STATUS(0, "ACTRES_REQ_OTHER", "Other", true),
       ACTRES_REQ_PENDING = new ACTRES_REQ_STATUS(1, "ACTRES_REQ_PENDING", "Pending", true),
       ACTRES_REQ_EXECUTING = new ACTRES_REQ_STATUS(2, "ACTRES_REQ_EXECUTING", "Executing", true),
       ACTRES_REQ_PARTIALLY_COMPLETE = new ACTRES_REQ_STATUS(3, "ACTRES_REQ_PARTIALLY_COMPLETE", "Partially Complete", true),
       ACTRES_REQ_COMPLETE = new ACTRES_REQ_STATUS(4, "ACTRES_REQ_COMPLETE", "Complete", true),
       ACTRES_REQ_REQUEST_REJECTED = new ACTRES_REQ_STATUS(5, "ACTRES_REQ_REQUEST_REJECTED", "Request Rejected", true),
       ACTRES_REQ_RETRANSMIT_REQUEST_NOW = new ACTRES_REQ_STATUS(6, "ACTRES_REQ_RETRANSMIT_REQUEST_NOW", "Retransmit Request Now", true),
       ACTRES_REQ_RETRANSMIT_REQUEST_LATER = new ACTRES_REQ_STATUS(7, "ACTRES_REQ_RETRANSMIT_REQUEST_LATER", "Retransmit Request Later", true),
       ACTRES_REQ_INVALREQ_TIME_PARAMETERS = new ACTRES_REQ_STATUS(8, "ACTRES_REQ_INVALREQ_TIME_PARAMETERS", "Invalid Time Parameters", true),
       ACTRES_REQ_SIM_TIME_EXCEEDED = new ACTRES_REQ_STATUS(9, "ACTRES_REQ_SIM_TIME_EXCEEDED", "Simulation Time Exceeded", true),
       ACTRES_REQ_REQUEST_DONE = new ACTRES_REQ_STATUS(10, "ACTRES_REQ_REQUEST_DONE", "Request Done", true),
       ACTRES_REQ_TACCSF_LOS_REPLY_TYPE_1 = new ACTRES_REQ_STATUS(100, "ACTRES_REQ_TACCSF_LOS_REPLY_TYPE_1", "TACCSF LOS Reply-Type 1", true),
       ACTRES_REQ_TACCSF_LOS_REPLY_TYPE_2 = new ACTRES_REQ_STATUS(101, "ACTRES_REQ_TACCSF_LOS_REPLY_TYPE_2", "TACCSF LOS Reply-Type 2", true),
       ACTRES_REQ_JOIN_EXERCISE_REQ_REJECTED = new ACTRES_REQ_STATUS(201, "ACTRES_REQ_JOIN_EXERCISE_REQ_REJECTED", "Join Exercise Request Rejected", true);

    private ACTRES_REQ_STATUS(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, ACTRES_REQ_STATUS.class);
    }

    /** @see Value#values(Class) */
    public static List<ACTRES_REQ_STATUS> values() {

        return values(ACTRES_REQ_STATUS.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<ACTRES_REQ_STATUS> values(boolean known) {

        return values(ACTRES_REQ_STATUS.class, known);
    }

    /** @see Value#get(int, Class) */
    public static ACTRES_REQ_STATUS get(int value) {

        return get(value, ACTRES_REQ_STATUS.class);
    }
}

