package discover.vdis.enums;

import java.util.List;

/**
 * AFAPD_VERSION_ENUM: This class is auto-generated by vdis.EnumGenerator
 */
public final class AFAPD_VERSION_ENUM extends Value {

    public static final AFAPD_VERSION_ENUM
       AFAPD_VERSION_AV = new AFAPD_VERSION_ENUM(0, "AFAPD_VERSION_AV", "AFAPD AV", true),
       AFAPD_VERSION_BG = new AFAPD_VERSION_ENUM(1, "AFAPD_VERSION_BG", "AFAPD BG", true);

    private AFAPD_VERSION_ENUM(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, AFAPD_VERSION_ENUM.class);
    }

    /** @see Value#values(Class) */
    public static List<AFAPD_VERSION_ENUM> values() {

        return values(AFAPD_VERSION_ENUM.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<AFAPD_VERSION_ENUM> values(boolean known) {

        return values(AFAPD_VERSION_ENUM.class, known);
    }

    /** @see Value#get(int, Class) */
    public static AFAPD_VERSION_ENUM get(int value) {

        return get(value, AFAPD_VERSION_ENUM.class);
    }
}

