package discover.vdis.enums;

import java.util.List;

/**
 * AGGREGATE_STATE: This class is auto-generated by vdis.EnumGenerator
 */
public final class AGGREGATE_STATE extends Value {

    public static final AGGREGATE_STATE
       OTHER = new AGGREGATE_STATE(0, "OTHER", "Other", true),
       AGGREGATED = new AGGREGATE_STATE(1, "AGGREGATED", "Aggregated", true),
       DISAGGREGATED = new AGGREGATE_STATE(2, "DISAGGREGATED", "Disaggregated", true),
       FULLY_DISAGGREGATED = new AGGREGATE_STATE(3, "FULLY_DISAGGREGATED", "Fully Disaggregated", true),
       PSEUDO_DISAGGREGATED = new AGGREGATE_STATE(4, "PSEUDO_DISAGGREGATED", "Pseudo-Disaggregated", true),
       PARTIALLY_DISAGGREGATED = new AGGREGATE_STATE(5, "PARTIALLY_DISAGGREGATED", "Partially-Disaggregated", true);

    private AGGREGATE_STATE(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, AGGREGATE_STATE.class);
    }

    /** @see Value#values(Class) */
    public static List<AGGREGATE_STATE> values() {

        return values(AGGREGATE_STATE.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<AGGREGATE_STATE> values(boolean known) {

        return values(AGGREGATE_STATE.class, known);
    }

    /** @see Value#get(int, Class) */
    public static AGGREGATE_STATE get(int value) {

        return get(value, AGGREGATE_STATE.class);
    }
}

