package discover.vdis.enums;

import java.util.List;

/**
 * AIR_LIGHT_MODE: This class is auto-generated by vdis.EnumGenerator
 */
public final class AIR_LIGHT_MODE extends Value {

    public static final AIR_LIGHT_MODE
       AIRPLAT_LIGHT_MODE_OFF = new AIR_LIGHT_MODE(0, "AIRPLAT_LIGHT_MODE_OFF", "Off", true),
       AIRPLAT_LIGHT_MODE_DIM = new AIR_LIGHT_MODE(1, "AIRPLAT_LIGHT_MODE_DIM", "Dim", true),
       AIRPLAT_LIGHT_MODE_BRIGHT = new AIR_LIGHT_MODE(2, "AIRPLAT_LIGHT_MODE_BRIGHT", "Bright", true),
       AIRPLAT_LIGHT_MODE_FLASHING = new AIR_LIGHT_MODE(3, "AIRPLAT_LIGHT_MODE_FLASHING", "Flashing", true);

    private AIR_LIGHT_MODE(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, AIR_LIGHT_MODE.class);
    }

    /** @see Value#values(Class) */
    public static List<AIR_LIGHT_MODE> values() {

        return values(AIR_LIGHT_MODE.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<AIR_LIGHT_MODE> values(boolean known) {

        return values(AIR_LIGHT_MODE.class, known);
    }

    /** @see Value#get(int, Class) */
    public static AIR_LIGHT_MODE get(int value) {

        return get(value, AIR_LIGHT_MODE.class);
    }
}

