package discover.vdis.enums;

import java.util.List;

/**
 * AIR_FORM_PAT: This class is auto-generated by vdis.EnumGenerator
 */
public final class AIR_FORM_PAT extends Value {

    public static final AIR_FORM_PAT
       AIRPLAT_FORM_PAT_OFF = new AIR_FORM_PAT(0, "AIRPLAT_FORM_PAT_OFF", "Off", true),
       AIRPLAT_FORM_PAT_FORMATION_1 = new AIR_FORM_PAT(1, "AIRPLAT_FORM_PAT_FORMATION_1", "Formation 1", true),
       AIRPLAT_FORM_PAT_FORMATION_2 = new AIR_FORM_PAT(2, "AIRPLAT_FORM_PAT_FORMATION_2", "Formation 2", true),
       AIRPLAT_FORM_PAT_FORMATION_3 = new AIR_FORM_PAT(3, "AIRPLAT_FORM_PAT_FORMATION_3", "Formation 3", true),
       AIRPLAT_FORM_PAT_FORMATION_4 = new AIR_FORM_PAT(4, "AIRPLAT_FORM_PAT_FORMATION_4", "Formation 4", true),
       AIRPLAT_FORM_PAT_FORMATION_5 = new AIR_FORM_PAT(5, "AIRPLAT_FORM_PAT_FORMATION_5", "Formation 5", true);

    private AIR_FORM_PAT(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, AIR_FORM_PAT.class);
    }

    /** @see Value#values(Class) */
    public static List<AIR_FORM_PAT> values() {

        return values(AIR_FORM_PAT.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<AIR_FORM_PAT> values(boolean known) {

        return values(AIR_FORM_PAT.class, known);
    }

    /** @see Value#get(int, Class) */
    public static AIR_FORM_PAT get(int value) {

        return get(value, AIR_FORM_PAT.class);
    }
}

