package discover.vdis.enums;

import java.util.List;

/**
 * AIR_AC_LIGHTS: This class is auto-generated by vdis.EnumGenerator
 */
public final class AIR_AC_LIGHTS extends Value {

    public static final AIR_AC_LIGHTS
       AIRPLAT_AC_LIGHTS_DIM = new AIR_AC_LIGHTS(0, "AIRPLAT_AC_LIGHTS_DIM", "Dim (night)", true),
       AIRPLAT_AC_LIGHTS_BRIGHT = new AIR_AC_LIGHTS(1, "AIRPLAT_AC_LIGHTS_BRIGHT", "Bright (day)", true),
       AIRPLAT_AC_LIGHTS_FLASHING_DIM = new AIR_AC_LIGHTS(2, "AIRPLAT_AC_LIGHTS_FLASHING_DIM", "Flashing (dim/night)", true),
       AIRPLAT_AC_LIGHTS_FLASHING_BRIGHT = new AIR_AC_LIGHTS(3, "AIRPLAT_AC_LIGHTS_FLASHING_BRIGHT", "Flashing (bright/day)", true);

    private AIR_AC_LIGHTS(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, AIR_AC_LIGHTS.class);
    }

    /** @see Value#values(Class) */
    public static List<AIR_AC_LIGHTS> values() {

        return values(AIR_AC_LIGHTS.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<AIR_AC_LIGHTS> values(boolean known) {

        return values(AIR_AC_LIGHTS.class, known);
    }

    /** @see Value#get(int, Class) */
    public static AIR_AC_LIGHTS get(int value) {

        return get(value, AIR_AC_LIGHTS.class);
    }
}

