package discover.vdis.enums;

import java.util.List;

/**
 * AMPLITUDE: This class is auto-generated by vdis.EnumGenerator
 */
public final class AMPLITUDE extends Value {

    public static final AMPLITUDE
       OTHER = new AMPLITUDE(0, "OTHER", "Other", true),
       AFSK = new AMPLITUDE(1, "AFSK", "AFSK (Audio Frequency Shift Keying)", true),
       AM = new AMPLITUDE(2, "AM", "AM (Amplitude Modulation)", true),
       CW = new AMPLITUDE(3, "CW", "CW (Continuous Wave Modulation)", true),
       DSB = new AMPLITUDE(4, "DSB", "DSB (Double Sideband)", true),
       ISB = new AMPLITUDE(5, "ISB", "ISB (Independent Sideband)", true),
       LSB = new AMPLITUDE(6, "LSB", "LSB (Single Band Suppressed Carrier, Lower Sideband Mode)", true),
       SSB_FULL = new AMPLITUDE(7, "SSB_FULL", "SSB-Full (Single Sideband Full Carrier)", true),
       SSB_REDUC = new AMPLITUDE(8, "SSB_REDUC", "SSB-Reduc (Single Band Reduced Carrier)", true),
       USB = new AMPLITUDE(9, "USB", "USB (Single Band Suppressed Carrier, Upper Sideband Mode)", true),
       VSB = new AMPLITUDE(10, "VSB", "VSB (Vestigial Sideband)", true);

    private AMPLITUDE(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, AMPLITUDE.class);
    }

    /** @see Value#values(Class) */
    public static List<AMPLITUDE> values() {

        return values(AMPLITUDE.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<AMPLITUDE> values(boolean known) {

        return values(AMPLITUDE.class, known);
    }

    /** @see Value#get(int, Class) */
    public static AMPLITUDE get(int value) {

        return get(value, AMPLITUDE.class);
    }
}

