package discover.vdis.enums;

import java.util.List;

/**
 * AMPLITUDE_AND_ANGLE: This class is auto-generated by vdis.EnumGenerator
 */
public final class AMPLITUDE_AND_ANGLE extends Value {

    public static final AMPLITUDE_AND_ANGLE
       AMP_ANG_OTHER = new AMPLITUDE_AND_ANGLE(0, "AMP_ANG_OTHER", "Other", true),
       AMP_ANG_AMPLITUDE_AND_ANGLE = new AMPLITUDE_AND_ANGLE(1, "AMP_ANG_AMPLITUDE_AND_ANGLE", "Amplitude and Angle", true);

    private AMPLITUDE_AND_ANGLE(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, AMPLITUDE_AND_ANGLE.class);
    }

    /** @see Value#values(Class) */
    public static List<AMPLITUDE_AND_ANGLE> values() {

        return values(AMPLITUDE_AND_ANGLE.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<AMPLITUDE_AND_ANGLE> values(boolean known) {

        return values(AMPLITUDE_AND_ANGLE.class, known);
    }

    /** @see Value#get(int, Class) */
    public static AMPLITUDE_AND_ANGLE get(int value) {

        return get(value, AMPLITUDE_AND_ANGLE.class);
    }
}

