package discover.vdis.enums;

import java.util.List;

/**
 * ANGLE: This class is auto-generated by vdis.EnumGenerator
 */
public final class ANGLE extends Value {

    public static final ANGLE
       OTHER = new ANGLE(0, "OTHER", "Other", true),
       FM = new ANGLE(1, "FM", "FM (Frequency Modulation)", true),
       FSK = new ANGLE(2, "FSK", "FSK (Frequency Shift Keying)", true),
       PM = new ANGLE(3, "PM", "PM (Phase Modulation)", true);

    private ANGLE(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, ANGLE.class);
    }

    /** @see Value#values(Class) */
    public static List<ANGLE> values() {

        return values(ANGLE.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<ANGLE> values(boolean known) {

        return values(ANGLE.class, known);
    }

    /** @see Value#get(int, Class) */
    public static ANGLE get(int value) {

        return get(value, ANGLE.class);
    }
}

