package discover.vdis.enums;

import java.util.List;

/**
 * APP_CTRL_APPLICATION_TYPE: This class is auto-generated by vdis.EnumGenerator
 */
public final class APP_CTRL_APPLICATION_TYPE extends Value {

    public static final APP_CTRL_APPLICATION_TYPE
       OTHER = new APP_CTRL_APPLICATION_TYPE(0, "OTHER", "Other", true),
       RESOURCE_MANAGER = new APP_CTRL_APPLICATION_TYPE(1, "RESOURCE_MANAGER", "Resource Manager", true),
       SIMULATION_MANAGER = new APP_CTRL_APPLICATION_TYPE(2, "SIMULATION_MANAGER", "Simulation Manager", true),
       GATEWAY = new APP_CTRL_APPLICATION_TYPE(3, "GATEWAY", "Gateway", true),
       STEALTH = new APP_CTRL_APPLICATION_TYPE(4, "STEALTH", "Stealth", true),
       TACTICAL_INTEGERNET_INTERFACE = new APP_CTRL_APPLICATION_TYPE(5, "TACTICAL_INTEGERNET_INTERFACE", "Tactical Integernet Interface", true);

    private APP_CTRL_APPLICATION_TYPE(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, APP_CTRL_APPLICATION_TYPE.class);
    }

    /** @see Value#values(Class) */
    public static List<APP_CTRL_APPLICATION_TYPE> values() {

        return values(APP_CTRL_APPLICATION_TYPE.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<APP_CTRL_APPLICATION_TYPE> values(boolean known) {

        return values(APP_CTRL_APPLICATION_TYPE.class, known);
    }

    /** @see Value#get(int, Class) */
    public static APP_CTRL_APPLICATION_TYPE get(int value) {

        return get(value, APP_CTRL_APPLICATION_TYPE.class);
    }
}

