package discover.vdis.enums;

import java.util.List;

/**
 * AREAL_MINEFIELD_BREACH: This class is auto-generated by vdis.EnumGenerator
 */
public final class AREAL_MINEFIELD_BREACH extends Value {

    public static final AREAL_MINEFIELD_BREACH
       NO_BREACHING = new AREAL_MINEFIELD_BREACH(0, "NO_BREACHING", "No breaching", true),
       BREACHED = new AREAL_MINEFIELD_BREACH(1, "BREACHED", "Breached", true),
       CLEARED = new AREAL_MINEFIELD_BREACH(2, "CLEARED", "Cleared", true);

    private AREAL_MINEFIELD_BREACH(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, AREAL_MINEFIELD_BREACH.class);
    }

    /** @see Value#values(Class) */
    public static List<AREAL_MINEFIELD_BREACH> values() {

        return values(AREAL_MINEFIELD_BREACH.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<AREAL_MINEFIELD_BREACH> values(boolean known) {

        return values(AREAL_MINEFIELD_BREACH.class, known);
    }

    /** @see Value#get(int, Class) */
    public static AREAL_MINEFIELD_BREACH get(int value) {

        return get(value, AREAL_MINEFIELD_BREACH.class);
    }
}

