package discover.vdis.enums;

import java.util.List;

/**
 * ARTICULATED_PARTS_METRIC: This class is auto-generated by vdis.EnumGenerator
 */
public final class ARTICULATED_PARTS_METRIC extends Value {

    public static final ARTICULATED_PARTS_METRIC
       EMPTY = new ARTICULATED_PARTS_METRIC(0, "EMPTY", "Empty", true),
       POSITION = new ARTICULATED_PARTS_METRIC(1, "POSITION", "Position", true),
       POSITION_RATE = new ARTICULATED_PARTS_METRIC(2, "POSITION_RATE", "Position Rate", true),
       EXTENSION = new ARTICULATED_PARTS_METRIC(3, "EXTENSION", "Extension", true),
       EXTENSION_RATE = new ARTICULATED_PARTS_METRIC(4, "EXTENSION_RATE", "Extension Rate", true),
       X = new ARTICULATED_PARTS_METRIC(5, "X", "X", true),
       X_RAT = new ARTICULATED_PARTS_METRIC(6, "X_RAT", ",X Rate", true),
       Y = new ARTICULATED_PARTS_METRIC(7, "Y", "Y", true),
       Y_RATE = new ARTICULATED_PARTS_METRIC(8, "Y_RATE", "Y Rate", true),
       Z = new ARTICULATED_PARTS_METRIC(9, "Z", "Z", true),
       Z_RATE = new ARTICULATED_PARTS_METRIC(10, "Z_RATE", "Z Rate", true),
       AZIMUTH = new ARTICULATED_PARTS_METRIC(11, "AZIMUTH", "Azimuth", true),
       AZIMUTH_RATE = new ARTICULATED_PARTS_METRIC(12, "AZIMUTH_RATE", "Azimuth Rate", true),
       ELEVATION = new ARTICULATED_PARTS_METRIC(13, "ELEVATION", "Elevation", true),
       ELEVATION_RATE = new ARTICULATED_PARTS_METRIC(14, "ELEVATION_RATE", "Elevation Rate", true),
       ROTATION = new ARTICULATED_PARTS_METRIC(15, "ROTATION", "Rotation", true),
       ROTATION_RATE = new ARTICULATED_PARTS_METRIC(16, "ROTATION_RATE", "Rotation Rate", true);

    private ARTICULATED_PARTS_METRIC(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, ARTICULATED_PARTS_METRIC.class);
    }

    /** @see Value#values(Class) */
    public static List<ARTICULATED_PARTS_METRIC> values() {

        return values(ARTICULATED_PARTS_METRIC.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<ARTICULATED_PARTS_METRIC> values(boolean known) {

        return values(ARTICULATED_PARTS_METRIC.class, known);
    }

    /** @see Value#get(int, Class) */
    public static ARTICULATED_PARTS_METRIC get(int value) {

        return get(value, ARTICULATED_PARTS_METRIC.class);
    }
}

