package discover.vdis.enums;

import discover.vdis.EnumInterface;

/**
 * This file is auto-generated (see vdis.EnumGenerator)
 */
public enum ARTICULATED_PARTS implements EnumInterface {

    ARTPART_RUDDER(1024, "Rudder"),
    ARTPART_LEFT_FLAP(1056, "Left Flap"),
    ARTPART_RIGHT_FLAP(1088, "Right Flap"),
    ARTPART_LEFT_AILERON(1120, "Left Aileron"),
    ARTPART_RIGHT_AILERON(1152, "Right Aileron"),
    ARTPART_HELI_MAIN_ROTOR(1184, "Helicopter-Main Rotor"),
    ARTPART_HELI_TAIL_ROTOR(1216, "Helicopter-Tail Rotor"),
    ARTPART_OTHER_AIRCRAFT_CTRL_SURFACES(1248, "Other Aircraft Control Surfaces"),
    ARTPART_PROP_NUM_1(1280, "Propeller Number 1"),
    ARTPART_PROP_NUM_2(1312, "Propeller Number 2"),
    ARTPART_PROP_NUM_3(1344, "Propeller Number 3"),
    ARTPART_PROP_NUM_4(1376, "Propeller Number 4"),
    ARTPART_LEFT_STABILATOR(1408, "Left Stabilator (Stabilator Number 1)"),
    ARTPART_RIGHT_STABILATOR(1440, "Right Stabilator (Stabilator Number 2)"),
    ARTPART_LEFT_RUDDERVATOR(1472, "Left Ruddervator (Ruddervator Number 1)"),
    ARTPART_RIGHT_RUDDERVATOR(1504, "Right Ruddervator (Ruddervator Number 2)"),
    ARTPART_LEFT_LEADING_EDGE_FLAP(1536, "Left Leading Edge Flap/Slat"),
    ARTPART_RIGHT_LEADING_EDGE_FLAP(1568, "Right Leading Edge Flap/Slat"),
    ARTPART_PERISCOPE(2048, "Periscope"),
    ARTPART_GENERIC_ANTENNA(2080, "Generic Antenna"),
    ARTPART_SNORKEL(2112, "Snorkel"),
    ARTPART_OTHER_EXT_PARTS(2144, "Other Extendible Parts"),
    ARTPART_LANDING_GEAR(3072, "Landing Gear"),
    ARTPART_TAIL_HOOK(3104, "Tail Hook"),
    ARTPART_SPEED_BRAKE(3136, "Speed Brake"),
    ARTPART_LEFT_WEAPON_BAY_DOOR(3168, "Left Weapon Bay Door"),
    ARTPART_RIGHT_WEAPON_BAY_DOORS(3200, "Right Weapon Bay Doors"),
    ARTPART_TANK_OR_APC_HATCH(3232, "Tank or APC Hatch"),
    ARTPART_WINGSWEEP(3264, "Wingsweep"),
    ARTPART_BRIDGE_LAUNCHER(3296, "Bridge Launcher"),
    ARTPART_BRIDGE_SECTION_1(3328, "Bridge Section 1"),
    ARTPART_BRIDGE_SECTION_2(3360, "Bridge Section 2"),
    ARTPART_BRIDGE_SECTION_3(3392, "Bridge Section 3"),
    ARTPART_PRIMARY_BLADE_1(3424, "Primary Blade 1"),
    ARTPART_PRIMARY_BLADE_2(3456, "Primary Blade 2"),
    ARTPART_PRIMARY_BOOM(3488, "Primary Boom"),
    ARTPART_PRIMARY_LAUNCHER_ARM(3520, "Primary Launcher Arm"),
    ARTPART_OTHER_FIXED_POSITION_PARTS(3552, "Other Fixed Position Parts"),
    ARTPART_LANDING_GEAR_NOSE(3584, "Landing Gear - Nose"),
    ARTPART_LANDING_GEAR_LEFT_MAIN(3616, "Landing Gear - Left Main"),
    ARTPART_LANDING_GEAR_RIGHT_MAIN(3648, "Landing Gear - Right Main"),
    ARTPART_LEFT_SECONDARY_WEAPON_BAY_DOOR(3680, "Left Side/Secondary Weapon Bay Doors"),
    ARTPART_RIGHT_SECONDARY_WEAPON_BAY_DOORS(3712, "Right Side/Secondary Weapon Bay Doors"),
    ARTPART_SPOT_LIGHT_1(3744, "Spot/Search Light #1"),
    ARTPART_SPOT_LIGHT_2(3776, "Spot/Search Light #2"),
    ARTPART_SPOT_LIGHT_3(3808, "Spot/Search Light #3"),
    ARTPART_SPOT_LIGHT_4(3840, "Spot/Search Light #4"),
    ARTPART_PRIMARY_TURRET_NUM_1(4096, "Primary Turret Number 1"),
    ARTPART_PRIMARY_TURRET_NUM_2(4128, "Primary Turret Number 2"),
    ARTPART_PRIMARY_TURRET_NUM_3(4160, "Primary Turret Number 3"),
    ARTPART_PRIMARY_TURRET_NUM_4(4192, "Primary Turret Number 4"),
    ARTPART_PRIMARY_TURRET_NUM_5(4224, "Primary Turret Number 5"),
    ARTPART_PRIMARY_TURRET_NUM_6(4256, "Primary Turret Number 6"),
    ARTPART_PRIMARY_TURRET_NUM_7(4288, "Primary Turret Number 7"),
    ARTPART_PRIMARY_TURRET_NUM_8(4320, "Primary Turret Number 8"),
    ARTPART_PRIMARY_TURRET_NUM_9(4352, "Primary Turret Number 9"),
    ARTPART_PRIMARY_TURRET_NUM_10(4384, "Primary Turret Number 10"),
    ARTPART_PRIMARY_GUN_NUM_1(4416, "Primary Gun Number 1"),
    ARTPART_PRIMARY_GUN_NUM_2(4448, "Primary Gun Number 2"),
    ARTPART_PRIMARY_GUN_NUM_3(4480, "Primary Gun Number 3"),
    ARTPART_PRIMARY_GUN_NUM_4(4512, "Primary Gun Number 4"),
    ARTPART_PRIMARY_GUN_NUM_5(4544, "Primary Gun Number 5"),
    ARTPART_PRIMARY_GUN_NUM_6(4576, "Primary Gun Number 6"),
    ARTPART_PRIMARY_GUN_NUM_7(4608, "Primary Gun Number 7"),
    ARTPART_PRIMARY_GUN_NUM_8(4640, "Primary Gun Number 8"),
    ARTPART_PRIMARY_GUN_NUM_9(4672, "Primary Gun Number 9"),
    ARTPART_PRIMARY_GUN_NUM_10(4704, "Primary Gun Number 10"),
    ARTPART_PRIMARY_LAUNCHER_1(4736, "Primary Launcher 1"),
    ARTPART_PRIMARY_LAUNCHER_2(4768, "Primary Launcher 2"),
    ARTPART_PRIMARY_LAUNCHER_3(4800, "Primary Launcher 3"),
    ARTPART_PRIMARY_LAUNCHER_4(4832, "Primary Launcher 4"),
    ARTPART_PRIMARY_LAUNCHER_5(4864, "Primary Launcher 5"),
    ARTPART_PRIMARY_LAUNCHER_6(4896, "Primary Launcher 6"),
    ARTPART_PRIMARY_LAUNCHER_7(4928, "Primary Launcher 7"),
    ARTPART_PRIMARY_LAUNCHER_8(4960, "Primary Launcher 8"),
    ARTPART_PRIMARY_LAUNCHER_9(4992, "Primary Launcher 9"),
    ARTPART_PRIMARY_LAUNCHER_10(5024, "Primary Launcher 10"),
    ARTPART_PRIMARY_DEF_SYS_1(5056, "Primary Defense Systems 1"),
    ARTPART_PRIMARY_DEF_SYS_2(5088, "Primary Defense Systems 2"),
    ARTPART_PRIMARY_DEF_SYS_3(5120, "Primary Defense Systems 3"),
    ARTPART_PRIMARY_DEF_SYS_4(5152, "Primary Defense Systems 4"),
    ARTPART_PRIMARY_DEF_SYS_5(5184, "Primary Defense Systems 5"),
    ARTPART_PRIMARY_DEF_SYS_6(5216, "Primary Defense Systems 6"),
    ARTPART_PRIMARY_DEF_SYS_7(5248, "Primary Defense Systems 7"),
    ARTPART_PRIMARY_DEF_SYS_8(5280, "Primary Defense Systems 8"),
    ARTPART_PRIMARY_DEF_SYS_9(5312, "Primary Defense Systems 9"),
    ARTPART_PRIMARY_DEF_SYS_10(5344, "Primary Defense Systems 10"),
    ARTPART_PRIMARY_RADAR_1(5376, "Primary Radar 1"),
    ARTPART_PRIMARY_RADAR_2(5408, "Primary Radar 2"),
    ARTPART_PRIMARY_RADAR_3(5440, "Primary Radar 3"),
    ARTPART_PRIMARY_RADAR_4(5472, "Primary Radar 4"),
    ARTPART_PRIMARY_RADAR_5(5504, "Primary Radar 5"),
    ARTPART_PRIMARY_RADAR_6(5536, "Primary Radar 6"),
    ARTPART_PRIMARY_RADAR_7(5568, "Primary Radar 7"),
    ARTPART_PRIMARY_RADAR_8(5600, "Primary Radar 8"),
    ARTPART_PRIMARY_RADAR_9(5632, "Primary Radar 9"),
    ARTPART_PRIMARY_RADAR_10(5664, "Primary Radar 10"),
    ARTPART_SEC_TURRET_NUM_1(5696, "Secondary Turret Number 1"),
    ARTPART_SEC_TURRET_NUM_2(5728, "Secondary Turret Number 2"),
    ARTPART_SEC_TURRET_NUM_3(5760, "Secondary Turret Number 3"),
    ARTPART_SEC_TURRET_NUM_4(5792, "Secondary Turret Number 4"),
    ARTPART_SEC_TURRET_NUM_5(5824, "Secondary Turret Number 5"),
    ARTPART_SEC_TURRET_NUM_6(5856, "Secondary Turret Number 6"),
    ARTPART_SEC_TURRET_NUM_7(5888, "Secondary Turret Number 7"),
    ARTPART_SEC_TURRET_NUM_8(5920, "Secondary Turret Number 8"),
    ARTPART_SEC_TURRET_NUM_9(5952, "Secondary Turret Number 9"),
    ARTPART_SEC_TURRET_NUM_10(5984, "Secondary Turret Number 10"),
    ARTPART_SEC_GUN_NUM_1(6016, "Secondary Gun Number 1"),
    ARTPART_SEC_GUN_NUM_2(6048, "Secondary Gun Number 2"),
    ARTPART_SEC_GUN_NUM_3(6080, "Secondary Gun Number 3"),
    ARTPART_SEC_GUN_NUM_4(6112, "Secondary Gun Number 4"),
    ARTPART_SEC_GUN_NUM_5(6144, "Secondary Gun Number 5"),
    ARTPART_SEC_GUN_NUM_6(6176, "Secondary Gun Number 6"),
    ARTPART_SEC_GUN_NUM_7(6208, "Secondary Gun Number 7"),
    ARTPART_SEC_GUN_NUM_8(6240, "Secondary Gun Number 8"),
    ARTPART_SEC_GUN_NUM_9(6272, "Secondary Gun Number 9"),
    ARTPART_SEC_GUN_NUM_10(6304, "Secondary Gun Number 10"),
    ARTPART_SEC_LAUNCHER_1(6336, "Secondary Launcher 1"),
    ARTPART_SEC_LAUNCHER_2(6368, "Secondary Launcher 2"),
    ARTPART_SEC_LAUNCHER_3(6400, "Secondary Launcher 3"),
    ARTPART_SEC_LAUNCHER_4(6432, "Secondary Launcher 4"),
    ARTPART_SEC_LAUNCHER_5(6464, "Secondary Launcher 5"),
    ARTPART_SEC_LAUNCHER_6(6496, "Secondary Launcher 6"),
    ARTPART_SEC_LAUNCHER_7(6528, "Secondary Launcher 7"),
    ARTPART_SEC_LAUNCHER_8(6560, "Secondary Launcher 8"),
    ARTPART_SEC_LAUNCHER_9(6592, "Secondary Launcher 9"),
    ARTPART_SEC_LAUNCHER_10(6624, "Secondary Launcher 10"),
    ARTPART_SEC_DEF_SYS_1(6656, "Secondary Defense Systems 1"),
    ARTPART_SEC_DEF_SYS_2(6688, "Secondary Defense Systems 2"),
    ARTPART_SEC_DEF_SYS_3(6720, "Secondary Defense Systems 3"),
    ARTPART_SEC_DEF_SYS_4(6752, "Secondary Defense Systems 4"),
    ARTPART_SEC_DEF_SYS_5(6784, "Secondary Defense Systems 5"),
    ARTPART_SEC_DEF_SYS_6(6816, "Secondary Defense Systems 6"),
    ARTPART_SEC_DEF_SYS_7(6848, "Secondary Defense Systems 7"),
    ARTPART_SEC_DEF_SYS_8(6880, "Secondary Defense Systems 8"),
    ARTPART_SEC_DEF_SYS_9(6912, "Secondary Defense Systems 9"),
    ARTPART_SEC_DEF_SYS_10(6944, "Secondary Defense Systems 10"),
    ARTPART_SEC_RADAR_1(6976, "Secondary Radar 1"),
    ARTPART_SEC_RADAR_2(7008, "Secondary Radar 2"),
    ARTPART_SEC_RADAR_3(7040, "Secondary Radar 3"),
    ARTPART_SEC_RADAR_4(7072, "Secondary Radar 4"),
    ARTPART_SEC_RADAR_5(7104, "Secondary Radar 5"),
    ARTPART_SEC_RADAR_6(7136, "Secondary Radar 6"),
    ARTPART_SEC_RADAR_7(7168, "Secondary Radar 7"),
    ARTPART_SEC_RADAR_8(7200, "Secondary Radar 8"),
    ARTPART_SEC_RADAR_9(7232, "Secondary Radar 9"),
    ARTPART_SEC_RADAR_10(7264, "Secondary Radar 10"),
    ARTPART_DECK_ELEVATOR_1(7296, "Deck Elevator 1"),
    ARTPART_DECK_ELEVATOR_2(7328, "Deck Elevator 2"),
    ARTPART_CATAPULT_1(7360, "Catapult 1"),
    ARTPART_CATAPULT_2(7392, "Catapult 2"),
    ARTPART_JET_BLAST_DEFLECTOR_1(7424, "Jet Blast Deflector 1"),
    ARTPART_JET_BLAST_DEFLECTOR_2(7456, "Jet Blast Deflector 2"),
    ARTPART_ARRESTOR_WIRES_1(7488, "Arrestor Wires 1"),
    ARTPART_ARRESTOR_WIRES_2(7520, "Arrestor Wires 2"),
    ARTPART_ARRESTOR_WIRES_3(7552, "Arrestor Wires 3"),
    ARTPART_WING_FOLD(7584, "Wing Fold"),
    ARTPART_FUSELAGE_FOLD(7616, "Fuselage Fold"),
    ARTPART_CARGO_DOOR(7648, "Cargo Door"),
    ARTPART_CARGO_RAMP(7680, "Cargo Ramp"),
    ARTPART_AIR_TO_AIR_REFUELING_BOOM(7712, "Air-to-Air Refueling Boom");

    private final int value;
    private final String description;

    private ARTICULATED_PARTS(int value, String description) {

        this.value = value;
        this.description = description;
    }

    @Override
    public int getValue() {

        return value;
    }

    @Override
    public String getDescription() {

        return description;
    }
}

