package discover.vdis.enums;

import java.util.List;

/**
 * CF_CAT_SURFACE: This class is auto-generated by vdis.EnumGenerator
 */
public final class CF_CAT_SURFACE extends Value {

    public static final CF_CAT_SURFACE
       OTH = new CF_CAT_SURFACE(0, "OTH", "Other", true),
       OIL = new CF_CAT_SURFACE(1, "OIL", "Oil Derrick", true),
       BUOY = new CF_CAT_SURFACE(2, "BUOY", "Buoy", true),
       PIER = new CF_CAT_SURFACE(3, "PIER", "Pier", true),
       MARK = new CF_CAT_SURFACE(4, "MARK", "Marker", true),
       DAT = new CF_CAT_SURFACE(5, "DAT", "Datum", true),
       SPNT = new CF_CAT_SURFACE(6, "SPNT", "Special Point", true);

    private CF_CAT_SURFACE(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, CF_CAT_SURFACE.class);
    }

    /** @see Value#values(Class) */
    public static List<CF_CAT_SURFACE> values() {

        return values(CF_CAT_SURFACE.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<CF_CAT_SURFACE> values(boolean known) {

        return values(CF_CAT_SURFACE.class, known);
    }

    /** @see Value#get(int, Class) */
    public static CF_CAT_SURFACE get(int value) {

        return get(value, CF_CAT_SURFACE.class);
    }
}

