package discover.vdis.enums;

import java.util.List;

/**
 * CF_CAT_SUBSURFACE: This class is auto-generated by vdis.EnumGenerator
 */
public final class CF_CAT_SUBSURFACE extends Value {

    public static final CF_CAT_SUBSURFACE
       OTH = new CF_CAT_SUBSURFACE(0, "OTH", "Other", true),
       OIL = new CF_CAT_SUBSURFACE(1, "OIL", "Oil Derrick", true),
       BUOY = new CF_CAT_SUBSURFACE(2, "BUOY", "Buoy", true),
       SHIP = new CF_CAT_SUBSURFACE(3, "SHIP", "Sunken Ship", true);

    private CF_CAT_SUBSURFACE(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, CF_CAT_SUBSURFACE.class);
    }

    /** @see Value#values(Class) */
    public static List<CF_CAT_SUBSURFACE> values() {

        return values(CF_CAT_SUBSURFACE.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<CF_CAT_SUBSURFACE> values(boolean known) {

        return values(CF_CAT_SUBSURFACE.class, known);
    }

    /** @see Value#get(int, Class) */
    public static CF_CAT_SUBSURFACE get(int value) {

        return get(value, CF_CAT_SUBSURFACE.class);
    }
}

