package discover.vdis.enums;

import java.util.List;

/**
 * COLLISION: This class is auto-generated by vdis.EnumGenerator
 */
public final class COLLISION extends Value {

    public static final COLLISION
       INELASTIC = new COLLISION(0, "INELASTIC", "Inelastic", true),
       ELASTIC = new COLLISION(1, "ELASTIC", "Elastic", true);

    private COLLISION(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, COLLISION.class);
    }

    /** @see Value#values(Class) */
    public static List<COLLISION> values() {

        return values(COLLISION.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<COLLISION> values(boolean known) {

        return values(COLLISION.class, known);
    }

    /** @see Value#get(int, Class) */
    public static COLLISION get(int value) {

        return get(value, COLLISION.class);
    }
}

