package discover.vdis.enums;

import java.util.List;

/**
 * COLLISION_ORIGIN: This class is auto-generated by vdis.EnumGenerator
 */
public final class COLLISION_ORIGIN extends Value {

    public static final COLLISION_ORIGIN
       COLL_ORIGIN_NO_STATEMENT = new COLLISION_ORIGIN(0, "COLL_ORIGIN_NO_STATEMENT", "No Statement", true),
       COLL_ORIGIN_COLL_ATTACHED_PART = new COLLISION_ORIGIN(1, "COLL_ORIGIN_COLL_ATTACHED_PART", "Collision with Attached Part", true),
       COLL_ORIGIN_COLL_ARTICULATED_PART = new COLLISION_ORIGIN(2, "COLL_ORIGIN_COLL_ARTICULATED_PART", "Collision with Articulated Part", true),
       COLL_ORIGIN_COLL_MOUNTED_ENTITY = new COLLISION_ORIGIN(3, "COLL_ORIGIN_COLL_MOUNTED_ENTITY", "Collision with Mounted Entity", true),
       COLL_ORIGIN_COLL_SLING_LOAD = new COLLISION_ORIGIN(4, "COLL_ORIGIN_COLL_SLING_LOAD", "Collision with Sling Load", true),
       COLL_ORIGIN_COLL_TOWED_ENTITY = new COLLISION_ORIGIN(5, "COLL_ORIGIN_COLL_TOWED_ENTITY", "Collision with Towed Entity", true);

    private COLLISION_ORIGIN(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, COLLISION_ORIGIN.class);
    }

    /** @see Value#values(Class) */
    public static List<COLLISION_ORIGIN> values() {

        return values(COLLISION_ORIGIN.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<COLLISION_ORIGIN> values(boolean known) {

        return values(COLLISION_ORIGIN.class, known);
    }

    /** @see Value#get(int, Class) */
    public static COLLISION_ORIGIN get(int value) {

        return get(value, COLLISION_ORIGIN.class);
    }
}

