package discover.vdis.enums;

import discover.vdis.EnumInterface;

/**
 * This file is auto-generated (see vdis.EnumGenerator)
 */
public enum COLORS implements EnumInterface {

    COLOR_NOT_SPECIFIED(0, "Not Specified"),
    COLOR_WHITE_VGA(1, "White VGA"),
    COLOR_RED_VGA(2, "Red VGA"),
    COLOR_YELLOW_VGA(3, "Yellow VGA"),
    COLOR_LIME_VGA(4, "Lime VGA"),
    COLOR_CYAN_VGA(5, "Cyan VGA"),
    COLOR_BLUE_VGA(6, "Blue VGA"),
    COLOR_MAGENTA_VGA(7, "Magenta VGA"),
    COLOR_GREY_VGA(8, "Grey VGA"),
    COLOR_SILVER_VGA(9, "Silver VGA"),
    COLOR_MAROON_VGA(10, "Maroon VGA"),
    COLOR_OLIVE_VGA(11, "Olive VGA"),
    COLOR_GREEN_VGA(12, "Green VGA"),
    COLOR_TEAL_VGA(13, "Teal VGA"),
    COLOR_NAVY_VGA(14, "Navy VGA"),
    COLOR_PURPLE_VGA(15, "Purple VGA"),
    COLOR_RESERVED1(16, "Reserved"),
    COLOR_RESERVED2(17, "Reserved"),
    COLOR_RESERVED3(18, "Reserved"),
    COLOR_RESERVED4(19, "Reserved"),
    COLOR_BLACK(20, "Black"),
    COLOR_NAVY(21, "Navy"),
    COLOR_DARK_BLUE(22, "Dark Blue"),
    COLOR_MEDIUM_BLUE(23, "Medium Blue"),
    COLOR_BLUE(24, "Blue"),
    COLOR_DARK_GREEN(25, "Dark Green"),
    COLOR_GREEN(26, "Green"),
    COLOR_TEAL(27, "Teal"),
    COLOR_DARK_CYAN(28, "Dark Cyan"),
    COLOR_DEEP_SKY_BLUE(29, "Deep Sky Blue"),
    COLOR_DARK_TURQUOISE(30, "Dark Turquoise"),
    COLOR_MEDIUM_SPRING_GREEN(31, "Medium Spring Green"),
    COLOR_LIME(32, "Lime"),
    COLOR_SPRING_GREEN(33, "Spring Green"),
    COLOR_CYAN(34, "Cyan"),
    COLOR_MIDNIGHT_BLUE(35, "Midnight Blue"),
    COLOR_DODGER_BLUE(36, "Dodger Blue"),
    COLOR_LIGHT_SEA_GREEN(37, "Light Sea Green"),
    COLOR_FOREST_GREEN(38, "Forest Green"),
    COLOR_SEA_GREEN(39, "Sea Green"),
    COLOR_DARK_SLATE_GRAY(40, "Dark Slate Gray"),
    COLOR_LIME_GREEN(41, "Lime Green"),
    COLOR_MEDIUM_SEA_GREEN(42, "Medium Sea Green"),
    COLOR_TURQUOISE(43, "Turquoise"),
    COLOR_ROYAL_BLUE(44, "Royal Blue"),
    COLOR_STEEL_BLUE(45, "Steel Blue"),
    COLOR_DARK_SLATE_BLUE(46, "Dark Slate Blue"),
    COLOR_MEDIUM_TURQUOISE(47, "Medium Turquoise"),
    COLOR_INDIGO(48, "Indigo"),
    COLOR_DARK_OLIVE_GREEN(49, "Dark Olive Green"),
    COLOR_CADET_BLUE(50, "Cadet Blue"),
    COLOR_CORNFLOWER_BLUE(51, "Cornflower Blue"),
    COLOR_MEDIUM_AQUAMARINE(52, "Medium Aquamarine"),
    COLOR_DIM_GRAY(53, "Dim Gray"),
    COLOR_SLATE_BLUE(54, "Slate Blue"),
    COLOR_OLIVE_DRAB(55, "Olive Drab"),
    COLOR_SLATE_GRAY(56, "Slate Gray"),
    COLOR_LIGHT_SLATE_GRAY(57, "Light Slate Gray"),
    COLOR_MEDIUM_SLATE_BLUE(58, "Medium Slate Blue"),
    COLOR_LAWN_GREEN(59, "Lawn Green"),
    COLOR_CHARTREUSE(60, "Chartreuse"),
    COLOR_AQUAMARINE(61, "Aquamarine"),
    COLOR_MAROON(62, "Maroon"),
    COLOR_PURPLE(63, "Purple"),
    COLOR_OLIVE(64, "Olive"),
    COLOR_GRAY(65, "Gray"),
    COLOR_GREY(66, "Grey"),
    COLOR_SKY_BLUE(67, "Sky Blue"),
    COLOR_LIGHT_SKY_BLUE(68, "Light Sky Blue"),
    COLOR_BLUE_VIOLET(69, "Blue Violet"),
    COLOR_DARK_RED(70, "Dark Red"),
    COLOR_DARK_MAGENTA(71, "Dark Magenta"),
    COLOR_SADDLE_BROWN(72, "Saddle Brown"),
    COLOR_DARK_SEA_GREEN(73, "Dark Sea Green"),
    COLOR_LIGHT_GREEN(74, "Light Green"),
    COLOR_MEDIUM_PURPLE(75, "Medium Purple"),
    COLOR_DARK_VIOLET(76, "Dark Violet"),
    COLOR_PALE_GREEN(77, "Pale Green"),
    COLOR_DARK_ORCHID(78, "Dark Orchid"),
    COLOR_YELLOW_GREEN(79, "Yellow Green"),
    COLOR_SIENNA(80, "Sienna"),
    COLOR_BROWN(81, "Brown"),
    COLOR_DARK_GRAY(82, "Dark Gray"),
    COLOR_LIGHT_BLUE(83, "Light Blue"),
    COLOR_GREEN_YELLOW(84, "Green Yellow"),
    COLOR_PALE_TURQUOISE(85, "Pale Turquoise"),
    COLOR_LIGHT_STEEL_BLUE(86, "Light Steel Blue"),
    COLOR_POWDER_BLUE(87, "Powder Blue"),
    COLOR_FIRE_BRICK(88, "Fire Brick"),
    COLOR_DARK_GOLDEN_ROD(89, "Dark Golden Rod"),
    COLOR_MEDIUM_ORCHID(90, "Medium Orchid"),
    COLOR_ROSY_BROWN(91, "Rosy Brown"),
    COLOR_DARK_KHAKI(92, "Dark Khaki"),
    COLOR_SILVER(93, "Silver"),
    COLOR_MEDIUM_VIOLET_RED(94, "Medium Violet Red"),
    COLOR_INDIAN_RED(95, "Indian Red"),
    COLOR_PERU(96, "Peru"),
    COLOR_CHOCOLATE(97, "Chocolate"),
    COLOR_TAN(98, "Tan"),
    COLOR_LIGHT_GRAY(99, "Light Gray"),
    COLOR_PALE_VIOLET_RED(100, "Pale Violet Red"),
    COLOR_THISTLE(101, "Thistle"),
    COLOR_ORCHID(102, "Orchid"),
    COLOR_GOLDEN_ROD(103, "Golden Rod"),
    COLOR_CRIMSON(104, "Crimson"),
    COLOR_GAINSBORO(105, "Gainsboro"),
    COLOR_PLUM(106, "Plum"),
    COLOR_BURLY_WOOD(107, "Burly Wood"),
    COLOR_LIGHT_CYAN(108, "Light Cyan"),
    COLOR_LAVENDER(109, "Lavender"),
    COLOR_DARK_SALMON(110, "Dark Salmon"),
    COLOR_VIOLET(111, "Violet"),
    COLOR_PALE_GOLDEN_ROD(112, "Pale Golden Rod"),
    COLOR_LIGHT_CORAL(113, "Light Coral"),
    COLOR_KHAKI(114, "Khaki"),
    COLOR_ALICE_BLUE(115, "Alice Blue"),
    COLOR_HONEY_DEW(116, "Honey Dew"),
    COLOR_AZURE(117, "Azure"),
    COLOR_SANDY_BROWN(118, "Sandy Brown"),
    COLOR_WHEAT(119, "Wheat"),
    COLOR_BEIGE(120, "Beige"),
    COLOR_WHITE_SMOKE(121, "White Smoke"),
    COLOR_MINT_CREAM(122, "Mint Cream"),
    COLOR_GHOST_WHITE(123, "Ghost White"),
    COLOR_SALMON(124, "Salmon"),
    COLOR_ANTIQUE_WHITE(125, "Antique White"),
    COLOR_LINEN(126, "Linen"),
    COLOR_LIGHT_GOLDEN_ROD_YELLOW(127, "Light Golden Rod Yellow"),
    COLOR_OLD_LACE(128, "Old Lace"),
    COLOR_RED(129, "Red"),
    COLOR_FUCHSIA(130, "Fuchsia"),
    COLOR_MAGENTA(131, "Magenta"),
    COLOR_DEEP_PINK(132, "Deep Pink"),
    COLOR_ORANGE_RED(133, "Orange Red"),
    COLOR_TOMATO(134, "Tomato"),
    COLOR_HOT_PINK(135, "Hot Pink"),
    COLOR_CORAL(136, "Coral"),
    COLOR_DARK_ORANGE(137, "Dark Orange"),
    COLOR_LIGHT_SALMON(138, "Light Salmon"),
    COLOR_ORANGE(139, "Orange"),
    COLOR_LIGHT_PINK(140, "Light Pink"),
    COLOR_PINK(141, "Pink"),
    COLOR_GOLD(142, "Gold"),
    COLOR_PEACH_PUFF(143, "Peach Puff"),
    COLOR_NAVAJO_WHITE(144, "Navajo White"),
    COLOR_MOCCASIN(145, "Moccasin"),
    COLOR_BISQUE(146, "Bisque"),
    COLOR_MISTY_ROSE(147, "Misty Rose"),
    COLOR_BLANCHED_ALMOND(148, "Blanched Almond"),
    COLOR_PAPAYA_WHIP(149, "Papaya Whip"),
    COLOR_LAVENDER_BLUSH(150, "Lavender Blush"),
    COLOR_SEA_SHELL(151, "Sea Shell"),
    COLOR_CORNSILK(152, "Cornsilk"),
    COLOR_LEMON_CHIFFON(153, "Lemon Chiffon"),
    COLOR_FLORAL_WHITE(154, "Floral White"),
    COLOR_SNOW(155, "Snow"),
    COLOR_YELLOW(156, "Yellow"),
    COLOR_LIGHT_YELLOW(157, "Light Yellow"),
    COLOR_IVORY(158, "Ivory"),
    COLOR_WHITE(159, "White");

    private final int value;
    private final String description;

    private COLORS(int value, String description) {

        this.value = value;
        this.description = description;
    }

    @Override
    public int getValue() {

        return value;
    }

    @Override
    public String getDescription() {

        return description;
    }
}

