package discover.vdis.enums;

import java.util.List;

/**
 * COMBINATION: This class is auto-generated by vdis.EnumGenerator
 */
public final class COMBINATION extends Value {

    public static final COMBINATION
       COMBO_OTHER = new COMBINATION(0, "COMBO_OTHER", "Other", true),
       COMBO_AMPLITUDE_ANGLE_PULSE = new COMBINATION(1, "COMBO_AMPLITUDE_ANGLE_PULSE", "Amplitude-Angle-Pulse", true);

    private COMBINATION(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, COMBINATION.class);
    }

    /** @see Value#values(Class) */
    public static List<COMBINATION> values() {

        return values(COMBINATION.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<COMBINATION> values(boolean known) {

        return values(COMBINATION.class, known);
    }

    /** @see Value#get(int, Class) */
    public static COMBINATION get(int value) {

        return get(value, COMBINATION.class);
    }
}

