package discover.vdis.enums;

import java.util.List;

/**
 * COMMAND: This class is auto-generated by vdis.EnumGenerator
 */
public final class COMMAND extends Value {

    public static final COMMAND
       NO_COMMAND = new COMMAND(0, "NO_COMMAND", "No Command", true),
       STATUS = new COMMAND(1, "STATUS", "Status", true),
       CONNECT = new COMMAND(2, "CONNECT", "Connect", true),
       DISCONNECT = new COMMAND(3, "DISCONNECT", "Disconnect", true),
       RESET = new COMMAND(4, "RESET", "Reset", true),
       ON = new COMMAND(5, "ON", "On", true),
       OFF = new COMMAND(6, "OFF", "Off", true);

    private COMMAND(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, COMMAND.class);
    }

    /** @see Value#values(Class) */
    public static List<COMMAND> values() {

        return values(COMMAND.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<COMMAND> values(boolean known) {

        return values(COMMAND.class, known);
    }

    /** @see Value#get(int, Class) */
    public static COMMAND get(int value) {

        return get(value, COMMAND.class);
    }
}

