package discover.vdis.enums;

import java.util.List;

/**
 * COMMS_TYPE: This class is auto-generated by vdis.EnumGenerator
 */
public final class COMMS_TYPE extends Value {

    public static final COMMS_TYPE
       COMMS_RESERVED = new COMMS_TYPE(0, "COMMS_RESERVED", "Reserved", true),
       COMMS_CONNECTION_FDX = new COMMS_TYPE(1, "COMMS_CONNECTION_FDX", "Connection FDX", true),
       COMMS_CONNECTION_HDX_DESTINATION_IS_RECEIVE_ONLY = new COMMS_TYPE(2, "COMMS_CONNECTION_HDX_DESTINATION_IS_RECEIVE_ONLY", "Connection HDX - Destination Is Receive Only", true),
       COMMS_CONNECTION_HDX_DESTINATION_IS_TRANSMIT_ONLY = new COMMS_TYPE(3, "COMMS_CONNECTION_HDX_DESTINATION_IS_TRANSMIT_ONLY", "Connection HDX - Destination Is Transmit Only", true),
       COMMS_CONNECTION_HDX = new COMMS_TYPE(4, "COMMS_CONNECTION_HDX", "Connection HDX", true);

    private COMMS_TYPE(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, COMMS_TYPE.class);
    }

    /** @see Value#values(Class) */
    public static List<COMMS_TYPE> values() {

        return values(COMMS_TYPE.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<COMMS_TYPE> values(boolean known) {

        return values(COMMS_TYPE.class, known);
    }

    /** @see Value#get(int, Class) */
    public static COMMS_TYPE get(int value) {

        return get(value, COMMS_TYPE.class);
    }
}

