package discover.vdis.enums;

import java.util.List;

/**
 * CONST_GRID: This class is auto-generated by vdis.EnumGenerator
 */
public final class CONST_GRID extends Value {

    public static final CONST_GRID
       CONSTANT_GRID = new CONST_GRID(0, "CONSTANT_GRID", "Constant Grid", true),
       UPDATED_GRID = new CONST_GRID(1, "UPDATED_GRID", "Updated Grid", true);

    private CONST_GRID(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, CONST_GRID.class);
    }

    /** @see Value#values(Class) */
    public static List<CONST_GRID> values() {

        return values(CONST_GRID.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<CONST_GRID> values(boolean known) {

        return values(CONST_GRID.class, known);
    }

    /** @see Value#get(int, Class) */
    public static CONST_GRID get(int value) {

        return get(value, CONST_GRID.class);
    }
}

