package discover.vdis.enums;

/**
 * This file is auto-generated (see vdis.EnumGenerator)
 */
public enum COUNTRY implements VdisEnum {

    OTHER(0, "Other"),
    AF(1, "Afghanistan"),
    ALB(2, "Albania"),
    ALG(3, "Algeria"),
    ASOM(4, "American Samoa (United States)"),
    AND(5, "Andorra"),
    ANGO(6, "Angola"),
    ANGU(7, "Anguilla"),
    ANTA(8, "Antarctica (International)"),
    ANTBAR(9, "Antigua and Barbuda"),
    ARG(10, "Argentina"),
    ARU(11, "Aruba"),
    ASH(12, "Ashmore and Cartier Islands (Australia)"),
    AUL(13, "Australia"),
    AUA(14, "Austria"),
    BAHA(15, "Bahamas"),
    BAHR(16, "Bahrain"),
    BAK(17, "Baker Island (United States)"),
    BANG(18, "Bangladesh"),
    BAR(19, "Barbados"),
    BDI(20, "Bassas da India (France)"),
    BELG(21, "Belgium"),
    BELZ(22, "Belize"),
    BEN(23, "Benin (aka Dahomey)"),
    DAH(23, "Dahomey (aka Benin)"),
    BER(24, "Bermuda (United Kingdom)"),
    BHU(25, "Bhutan"),
    BOL(26, "Bolivia"),
    BOT(27, "Botswana"),
    BIN(28, "Bouvet Island (Norway)"),
    BRA(29, "Brazil"),
    BIOT(30, "British Indian Ocean Territory (United Kingdom)"),
    BVI(31, "British Virgin Islands (United Kingdom)"),
    BRU(32, "Brunei"),
    BUL(33, "Bulgaria"),
    BUR(34, "Burkina (aka Burkina Faso or Upper Volta)"),
    UV(34, "Upper Volta (aka Burkina or Burkina Faso)"),
    BURM(35, "Burma (Myanmar)"),
    MYA(35, "Myanmar (aka Burma)"),
    BURU(36, "Burundi"),
    CAMB(37, "Cambodia (aka Kampuchea)"),
    CAMR(38, "Cameroon"),
    CAN(39, "Canada"),
    CV(40, "Cape Verde, Republic of"),
    CAY(41, "Cayman Islands (United Kingdom)"),
    CAR(42, "Central African Republic"),
    CHAD(43, "Chad"),
    CHILE(44, "Chile"),
    CH(45, "China, People's Republic of"),
    CIA(46, "Christmas Island (Australia)"),
    COCO(47, "Cocos (Keeling) Islands (Australia)"),
    COL(48, "Colombia"),
    COM(49, "Comoros"),
    CONGO(50, "Congo, Republic of"),
    COOK(51, "Cook Islands (New Zealand)"),
    CSI(52, "Coral Sea Islands (Australia)"),
    CR(53, "Costa Rica"),
    CUBA(54, "Cuba"),
    CYP(55, "Cyprus"),
    CZ(56, "Czechoslovakia (separating into Czech Republic and Slovak Republic)"),
    DEN(57, "Denmark"),
    DJI(58, "Djibouti"),
    DOM(59, "Dominica"),
    DR(60, "Dominican Republic"),
    ECU(61, "Ecuador"),
    EGY(62, "Egypt"),
    ES(63, "El Salvador"),
    EQG(64, "Equatorial Guinea"),
    ETH(65, "Ethiopia"),
    EIF(66, "Europa Island (France)"),
    FALK(67, "Falkland Islands (aka Islas Malvinas) (United Kingdom)"),
    FID(68, "Faroe Islands (Denmark)"),
    FIJI(69, "Fiji"),
    FIN(70, "Finland"),
    FR(71, "France"),
    FRG(72, "French Guiana (France)"),
    FRP(73, "French Polynesia (France)"),
    FSAI(74, "French Southern and Antarctic Islands (France)"),
    GAB(75, "Gabon"),
    GAM(76, "Gambia, The"),
    GAZA(77, "Gaza Strip (Israel)"),
    GER(78, "Germany"),
    GH(79, "Ghana"),
    GIB(80, "Gibraltar (United Kingdom)"),
    GLO(81, "Glorioso Islands (France)"),
    GRE(82, "Greece"),
    GRLND(83, "Greenland (Denmark)"),
    GREN(84, "Grenada"),
    GUAD(85, "Guadaloupe (France)"),
    GUAM(86, "Guam (United States)"),
    GUAT(87, "Guatemala"),
    GUER(88, "Guernsey (United Kingdom)"),
    GUI(89, "Guinea"),
    GUIB(90, "Guinea- Bissau"),
    GUY(91, "Guyana"),
    HAITI(92, "Haiti"),
    HIMI(93, "Heard Island and McDonald Islands (Australia)"),
    HOND(94, "Honduras"),
    HK(95, "Hong Kong (United Kingdom)"),
    HOWI(96, "Howland Island (United States)"),
    HUN(97, "Hungary"),
    ICE(98, "Iceland"),
    INDIA(99, "India"),
    INDO(100, "Indonesia"),
    IRAN(101, "Iran"),
    IRAQ(102, "Iraq"),
    IRE(104, "Ireland"),
    IS(105, "Israel"),
    IT(106, "Italy"),
    IVORY(107, "(Cote D'Ivoire (aka Ivory Coast)"),
    JAM(108, "Jamaica"),
    JMN(109, "Jan Mayen (Norway)"),
    JAP(110, "Japan"),
    JI(111, "Jarvis Island (United States)"),
    JER(112, "Jersey (United Kingdom)"),
    JOHN(113, "Johnston Atoll (United States)"),
    JOR(114, "Jordan"),
    JDNI(115, "Juan  de Nova Island"),
    KEN(116, "Kenya"),
    KING(117, "Kingman Reef  (United States)"),
    KIRI(118, "Kiribati"),
    DPRNK(119, "Korea, Democratic People's Republic of (North)"),
    ROK(120, "Korea, Republic of (South)"),
    KUW(121, "Kuwait"),
    LAOS(122, "Laos"),
    LEB(123, "Lebanon"),
    LES(124, "Lesotho"),
    LIBE(125, "Liberia"),
    LIBYA(126, "Libya"),
    LIE(127, "Liechtenstein"),
    LUX(128, "Luxembourg"),
    MAD(129, "Madagascar"),
    MAC(130, "Macau (Portugal)"),
    MALW(131, "Malawi"),
    MALY(132, "Malaysia"),
    MALD(133, "Maldives"),
    MALI(134, "Mali"),
    MALTA(135, "Malta"),
    IOM(136, "Man, Isle of (United Kingdom)"),
    MI(137, "Marshall Islands"),
    MART(138, "Martinique  (France)"),
    MAURN(139, "Mauritania"),
    MAURS(140, "Mauritius"),
    MAY(141, "Mayotte (France)"),
    MEX(142, "Mexico"),
    FSM(143, "Micronesia, Federative States of"),
    MONC(144, "Monaco"),
    MONG(145, "Mongolia"),
    MONTS(146, "Montserrat (United Kingdom)"),
    MORC(147, "Morocco"),
    MOZ(148, "Mozambique"),
    NAM(149, "Namibia (South West Africa)"),
    NAURU(150, "Nauru"),
    NAV(151, "Navassa Island (United States)"),
    NEP(152, "Nepal"),
    NETH(153, "Netherlands"),
    NETHA(154, "Netherlands Antilles (Curacao, Bonaire, Saba, Sint Maarten Sint Eustatius)"),
    NC(155, "New Caledonia (France)"),
    NZ(156, "New Zealand"),
    NIC(157, "Nicaragua"),
    NIGER(158, "Niger"),
    NIGERIA(159, "Nigeria"),
    NIUE(160, "Niue (New Zealand)"),
    NORI(161, "Norfolk Island (Australia)"),
    NMI(162, "Northern Mariana Islands (United States)"),
    NOR(163, "Norway"),
    OMAN(164, "Oman"),
    PAK(165, "Pakistan"),
    PAA(166, "Palmyra Atoll (United States)"),
    PAN(168, "Panama"),
    PNG(169, "Papua New Guinea"),
    PI(170, "Paracel Islands (International - Occupied by China, also claimed by Taiwan and Vietnam)"),
    PAR(171, "Paraguay"),
    PERU(172, "Peru"),
    PHIL(173, "Philippines"),
    PITI(174, "Pitcairn Islands (United Kingdom)"),
    PL(175, "Poland"),
    PORT(176, "Portugal"),
    PR(177, "Puerto Rico (United States)"),
    QAT(178, "Qatar"),
    REUN(179, "Reunion (France)"),
    ROM(180, "Romania"),
    RWA(181, "Rwanda"),
    STKN(182, "St. Kitts and Nevis"),
    STH(183, "St. Helena (United Kingdom)"),
    STLU(184, "St. Lucia"),
    STPI(185, "St. Pierre and Miquelon (France)"),
    STVG(186, "St. Vincent and the Grenadines"),
    SANM(187, "San Marino"),
    SAO(188, "Sao Tome and Principe"),
    SARAB(189, "Saudi Arabia"),
    SEN(190, "Senegal"),
    SEY(191, "Seychelles"),
    SILE(192, "Sierra Leone"),
    SING(193, "Singapore"),
    SOLI(194, "Solomon Islands"),
    SOM(195, "Somalia"),
    SGSI(196, "South Georgia and the South Sandwich Islands (United Kingdom)"),
    SA(197, "South Africa"),
    SP(198, "Spain"),
    SPI(199, "Spratly Islands (International - parts occupied and claimed by China,Malaysia, Philippines, Taiwan, Vietnam)"),
    SRI(200, "Sri Lanka"),
    SUD(201, "Sudan"),
    SUR(202, "Suriname"),
    SVA(203, "Svalbard (Norway)"),
    SWA(204, "Swaziland"),
    SWE(205, "Sweden"),
    SWI(206, "Switzerland"),
    SYR(207, "Syria"),
    TAI(208, "Taiwan"),
    TAN(209, "Tanzania"),
    THAI(210, "Thailand"),
    TOGO(211, "Togo"),
    TOK(212, "Tokelau (New Zealand)"),
    TON(213, "Tonga"),
    TAT(214, "Trinidad and Tobago"),
    TIF(215, "Tromelin Island (France)"),
    PITTP(216, "Pacific Islands, Trust Territory of the (Palau)"),
    TUN(217, "Tunisia"),
    TUR(218, "Turkey"),
    TCI(219, "Turks and Caicos Islands (United Kingdom)"),
    TUV(220, "Tuvalu"),
    UGA(221, "Uganda"),
    CIS(222, "Commonwealth of Independent States"),
    UAE(223, "United Arab Emirates"),
    UK(224, "United Kingdom"),
    US(225, "United States"),
    URU(226, "Uruguay"),
    VAN(227, "Vanuatu"),
    VAT(228, "Vatican City (Holy See)"),
    VEN(229, "Venezuela"),
    VIET(230, "Vietnam"),
    VIR(231, "Virgin Islands (United States)"),
    WAKE(232, "Wake Island (United States)"),
    WF(233, "Wallis and Futuna (France)"),
    WSAH(234, "Western Sahara"),
    WB(235, "West Bank (Israel)"),
    WSAM(236, "Western Samoa"),
    YEM(237, "Yemen"),
    SEMO(240, "Serbia and Montenegro"),
    ZAI(241, "Zaire"),
    ZAM(242, "Zambia"),
    ZIM(243, "Zimbabwe"),
    ARM(244, "Armenia"),
    AZER(245, "Azerbaijan"),
    BEL(246, "Belarus"),
    BOHE(247, "Bosnia and Herzegovina"),
    CLIP(248, "Clipperton Island (France)"),
    CRO(249, "Croatia"),
    EST(250, "Estonia"),
    GEO(251, "Georgia"),
    KAZ(252, "Kazakhstan"),
    KYR(253, "Kyrgyzstan"),
    LAT(254, "Latvia"),
    LITH(255, "Lithuania"),
    MACE(256, "Macedonia"),
    MIDI(257, "Midway Islands (United States)"),
    MOLD(258, "Moldova"),
    MONTE(259, "Montenegro"),
    RS(260, "Russia"),
    SEMOS(261, "Serbia and Montenegro (Montenegro to separate)"),
    SLOV(262, "Slovenia"),
    TAJ(263, "Tajikistan"),
    TUM(264, "Turkmenistan"),
    UKR(265, "Ukraine"),
    UZB(266, "Uzbekistan");

    private final int value;
    private final String description;

    private COUNTRY(int value, String description) {

        this.value = value;
        this.description = description;
    }

    @Override
    public int getValue() {

        return value;
    }

    @Override
    public String getDescription() {

        return description;
    }
}

