package discover.vdis.enums;

import java.util.List;

/**
 * CRYPTO_SYS: This class is auto-generated by vdis.EnumGenerator
 */
public final class CRYPTO_SYS extends Value {

    public static final CRYPTO_SYS
       CRYPTO_OTHER = new CRYPTO_SYS(0, "CRYPTO_OTHER", "Other", true),
       CRYPTO_KY_28 = new CRYPTO_SYS(1, "CRYPTO_KY_28", "KY-28", true),
       CRYPTO_VINSON = new CRYPTO_SYS(2, "CRYPTO_VINSON", "VINSON (KY-57, KY-58, SINCGARS ICOM)", true),
       CRYPTO_NSVE = new CRYPTO_SYS(3, "CRYPTO_NSVE", "Narrow Spectrum Secure Voice (NSVE)", true),
       CRYPTO_WSVE = new CRYPTO_SYS(4, "CRYPTO_WSVE", "Wide Spectrum Secure Voice (WSVE)", true);

    private CRYPTO_SYS(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, CRYPTO_SYS.class);
    }

    /** @see Value#values(Class) */
    public static List<CRYPTO_SYS> values() {

        return values(CRYPTO_SYS.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<CRYPTO_SYS> values(boolean known) {

        return values(CRYPTO_SYS.class, known);
    }

    /** @see Value#get(int, Class) */
    public static CRYPTO_SYS get(int value) {

        return get(value, CRYPTO_SYS.class);
    }
}

