package discover.vdis.enums;

import java.util.List;

/**
 * DATA_REP: This class is auto-generated by vdis.EnumGenerator
 */
public final class DATA_REP extends Value {

    public static final DATA_REP
       TYPE_0 = new DATA_REP(0, "TYPE_0", "Type 0", true),
       TYPE_1 = new DATA_REP(1, "TYPE_1", "Type 1", true),
       TYPE_2 = new DATA_REP(2, "TYPE_2", "Type 2", true);

    private DATA_REP(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, DATA_REP.class);
    }

    /** @see Value#values(Class) */
    public static List<DATA_REP> values() {

        return values(DATA_REP.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<DATA_REP> values(boolean known) {

        return values(DATA_REP.class, known);
    }

    /** @see Value#get(int, Class) */
    public static DATA_REP get(int value) {

        return get(value, DATA_REP.class);
    }
}

