package discover.vdis.enums;

import discover.vdis.EnumInterface;
import discover.vdis.Enumerations;

/**
 * This file is auto-generated (see vdis.EnumGenerator)
 */
public enum DATUM_IDS implements EnumInterface {

    DID_ENVIRONMENT_PROCESS_STATE_COMBIC(256, "COMBIC State"),
    DID_ENVIRONMENT_PROCESS_STATE_FLARE(259, "Flare State"),
    DID_DE_PRECISION_AIMPOINT(4000, "DE Precision Aimpoint record"),
    DID_DE_AREA_AIMPOINT(4001, "DE Area Aimpoint record"),
    DID_DE_DAMAGE_DESCRIPTION(4500, "DE Damage Description record"),
    DID_IDENTIFICATION_AGGR(10000, "Identification (Aggregate)"),
    DID_ENTITY_TYPE_AGGR(11000, "Entity Type (Aggregate)"),
    DID_ENTITY_TYPE_CONCAT_AGGR(11100, "Entity Type - Concatenated (Aggregate)"),
    DID_ENTITY_TYPE_CONCAT_KIND(11110, "Entity Type - Concatenated - Kind"),
    DID_ENTITY_TYPE_CONCAT_DOMAIN(11120, "Entity Type - Concatenated - Domain"),
    DID_ENTITY_TYPE_CONCAT_COUNTRY(11130, "Entity Type - Concatenated - Country"),
    DID_ENTITY_TYPE_CONCAT_CATEGORY(11140, "Entity Type - Concatenated - Category"),
    DID_ENTITY_TYPE_CONCAT_SUBCATEGORY(11150, "Entity Type - Concatenated - Subcategory"),
    DID_ENTITY_TYPE_CONCAT_SPECIFIC(11160, "Entity Type - Concatenated - Specific "),
    DID_ENTITY_TYPE_CONCAT_EXTRA(11170, "Entity Type - Concatenated - Extra"),
    DID_TASK_ORG_FORCE_ID(11200, "Task Organization - Force ID"),
    DID_TASK_ORG_FORCE_ID_AFFILIATION(11250, "Task Organization - Force ID - Affiliation"),
    DID_ENTITY_TYPE_DESC(11300, "Entity Type - Description"),
    DID_ENTITY_TYPE_ENTITY_ROLE_RECORD_ID(11400, "Entity Type - Entity Role Record ID"),
    DID_ENTITY_TYPE_ENTITY_ORG_RECORD_ID(11410, "Entity Type - Entity Organization Record ID"),
    DID_ALTERNATIVE_ENTITY_TYPE_AGGR(12000, "Alternative Entity Type (Aggregate)"),
    DID_ALTERNATIVE_ENTITY_ROLE_RECORD_ID(12100, "Alternative Entity Role Record ID "),
    DID_ALTERNATIVE_ENTITY_TYPE_KIND(12110, "Alternative Entity Type - Kind"),
    DID_ALTERNATIVE_ENTITY_TYPE_DOMAIN(12120, "Alternative Entity Type - Domain"),
    DID_ALTERNATIVE_ENTITY_TYPE_COUNTRY(12130, "Alternative Entity Type - Country"),
    DID_ALTERNATIVE_ENTITY_TYPE_CATEGORY(12140, "Alternative Entity Type - Category"),
    DID_ALTERNATIVE_ENTITY_TYPE_SUBCATEGORY(12150, "Alternative Entity Type - Subcategory "),
    DID_ALTERNATIVE_ENTITY_TYPE_SPECIFIC(12160, "Alternative Entity Type - Specific"),
    DID_ALTERNATIVE_ENTITY_TYPE_EXTRA(12170, "Alternative Entity Type - Extra"),
    DID_ALTERNATIVE_ENTITY_TYPE_DESC(12300, "Alternative Entity Type - Description"),
    DID_ENTITY_MARKING_ENTITY_MARKING(13000, "Entity Marking - Entity Marking"),
    DID_ENTITY_MARKING_CHARACTERS(13100, "Entity Marking Characters"),
    DID_ENTITY_MARKING_CREW_ID(13200, "Entity Marking - Crew ID"),
    DID_TASK_ORG_AGGR(14000, "Task Organization (Aggregate)"),
    DID_TASK_ORG_REGIMENT_NAME(14200, "Task Organization - Regiment Name"),
    DID_TASK_ORG_BATTALION_NAME(14300, "Task Organization - Battalion Name"),
    DID_TASK_ORG_COMPANY_NAME(14400, "Task Organization - Company Name"),
    DID_TASK_ORG_PLATOON_NAME(14500, "Task Organization - Platoon Name"),
    DID_TASK_ORG_SQUAD_NAME(14520, "Task Organization - Squad Name"),
    DID_TASK_ORG_TEAM_NAME(14540, "Task Organization - Team Name"),
    DID_TASK_ORG_BUMPER_NUMBER(14600, "Task Organization - Bumper Number"),
    DID_TASK_ORG_VEHICLE_NUMBER(14700, "Task Organization - Vehicle Number"),
    DID_TASK_ORG_UNIT_NUMBER(14800, "Task Organization - Unit Number"),
    DID_TASK_ORG_ARMY(14900, "Army Task Organization"),
    DID_TASK_ORG_ARMY_ECHELON_DESC_SHORT(14950, "Army Echelon Description - Short"),
    DID_TASK_ORG_ARMY_ECHELON_DESC_SHORT_DIVISION(14951, "Division Echelon Description - Short"),
    DID_TASK_ORG_ARMY_ECHELON_DESC_SHORT_BRIGADE(14952, "Brigade Echelon Description - Short"),
    DID_TASK_ORG_ARMY_ECHELON_DESC_SHORT_BN(14953, "Battalion Echelon Description - Short"),
    DID_TASK_ORG_ARMY_ECHELON_DESC_SHORT_COMPANY(14954, "Company Echelon Description - Short"),
    DID_TASK_ORG_ARMY_ECHELON_DESC_SHORT_PLATOON(14955, "Platoon Echelon Description - Short"),
    DID_TASK_ORG_ARMY_ECHELON_DESC_SHORT_SECT(14956, "Section Echelon Description - Short"),
    DID_TASK_ORG_ARMY_ECHELON_DESC_SHORT_SQUAD(14957, "Squad Echelon Description - Short"),
    DID_TASK_ORG_ARMY_ECHELON_DESC_SHORT_FIRE_TEAM(14958, "Fire Team Echelon Description - Short"),
    DID_TASK_ORG_ARMY_ECHELON_DESC_LONG(14970, "Army Echelon Description - Long"),
    DID_TASK_ORG_ARMY_ECHELON_DESC_LONG_DIVISION(14971, "Division Echelon Description - Long"),
    DID_TASK_ORG_ARMY_ECHELON_DESC_LONG_BRIGADE(14972, "Brigade Echelon Description - Long"),
    DID_TASK_ORG_ARMY_ECHELON_DESC_LONG_BN(14973, "Battalion Echelon Description - Long"),
    DID_TASK_ORG_ARMY_ECHELON_DESC_LONG_COMPANY(14974, "Company Echelon Description - Long"),
    DID_TASK_ORG_ARMY_ECHELON_DESC_LONG_PLATOON(14975, "Platoon Echelon Description - Long"),
    DID_TASK_ORG_ARMY_ECHELON_DESC_LONG_SECT(14976, "Section Echelon Description - Long"),
    DID_TASK_ORG_ARMY_ECHELON_DESC_LONG_SQUAD(14977, "Squad Echelon Description - Long"),
    DID_TASK_ORG_ARMY_ECHELON_DESC_LONG_FIRE_TEAM(14978, "Fire Team Echelon Description - Long"),
    DID_DIS_IDENTITY_DIS_IDENTITY(15000, "DIS Identity - DIS Identity"),
    DID_DIS_IDENTITY_DIS_SITE_ID(15100, "DIS Identity - DIS Site ID"),
    DID_DIS_IDENTITY_DIS_HOST_ID(15200, "DIS Identity - DIS Host ID"),
    DID_DIS_IDENTITY_DIS_ENTITY_ID(15300, "DIS Identity - DIS Entity ID"),
    DID_DIS_IDENTITY_MOUNT_INTENT(15400, "DIS Identity - Mount Intent"),
    DID_CFS_TETHER_UNTETHER_COMMAND(15500, "CFS - Tether-Untether Command"),
    DID_COMMAND_FROM_SIMULATOR(15505, "Command from Simulator (CFS)"),
    DID_DIS_IDENTITY_TELEPORT_ENTITY_DATA_RECORD(15510, "DIS Identity - Teleport Entity Data Record"),
    DID_DIS_IDENTITY_DIS_AGGR_ID(15600, "DIS Identity - DIS Aggregate ID"),
    DID_OWNERSHIP_STATUS(15800, "Ownership Status Record"),
    DID_DI_INITIALIZATION_RECORD_ID(16200, "DI Initialization Record ID "),
    DID_DI_JOB_ASSIGNMENT_ID(16201, "DI Job Assignment ID "),
    DID_DI_PRIMARY_WEAPON_ID(16202, "DI Primary Weapon ID "),
    DID_DI_PRIMARY_MUNITION_QTY_ID(16203, "DI Primary Munition Quantity ID "),
    DID_DI_SECONDARY_WEAPON_ID(16204, "DI Secondary Weapon ID "),
    DID_DI_SECONDARY_MUNITION_QTY_ID(16205, "DI Secondary Munition Quantity ID "),
    DID_DI_STANCE_ID(16206, "DI Stance ID "),
    DID_NUMBER_TO_MOUNT_DISMOUNT_ID(16210, "Number To Mount Dismount ID "),
    DID_MOUNT_DATA_ID(16215, "Mount Data"),
    DID_CARRIER_MOUNT_ID(16220, "Carrier Mount ID"),
    DID_DI_MOUNTED_STATUS_ID(16225, "DI Mounted Status ID "),
    DID_TROOP_STRENGTH_ID(16230, "Troop Strength ID "),
    DID_WEAPON_QTY_RECORD_ID(16240, "Weapon Quantity Record ID "),
    DID_FORCE_ID(17000, "Force ID "),
    DID_LOADS_AGGR(20000, "Loads (Aggregate)"),
    DID_LOADS_CARGO_LOAD_REQUEST(20001, "Loads - Cargo Load Request"),
    DID_LOADS_SLING_LOAD_TYPE(20006, "Loads - Sling load Type"),
    DID_LOADS_SLING_LOAD_HOOK(20007, "Loads - Sling load Hook"),
    DID_LOADS_AIRMOUNT_STATION(20008, "Loads - Airmount Station"),
    DID_LOADS_AIRMOUNT_WEIGHT(20009, "Loads - Airmount Weight"),
    DID_LOADS_AIRMOUNT_IS_DI(20010, "Loads - Airmount Is DI"),
    DID_LOADS_AIRMOUNT_NUM_DI(20011, "Loads - Airmount Num DI"),
    DID_LOADS_AIRMOUNT_DI_KG(20012, "Loads - Airmount DI KG"),
    DID_LOADS_AIRMOUNT_CARGO_KG(20013, "Loads - Airmount Cargo KG"),
    DID_LOADS_AIRMOUNT_VEHICLE_SITE(20014, "Loads - Airmount Vehicle Site"),
    DID_LOADS_AIRMOUNT_VEHICLE_HOST(20015, "Loads - Airmount Vehicle Host"),
    DID_LOADS_AIRMOUNT_VEHICLE_VEHICLE(20016, "Loads - Airmount Vehicle Vehicle"),
    DID_LOADS_AIRMOUNT_RESPONSE_ACTION(20017, "Loads - Airmount Response Action"),
    DID_LOADS_CHECKPOINT_RESTORE_STATUS(20020, "Loads - Checkpoint Restore Status"),
    DID_LOADS_CHECKPOINT_ENTITIES_LEFT(20021, "Loads - Checkpoint Entities Left"),
    DID_LOADS_TOTAL_ENTITIES(20022, "Loads - Total Entities"),
    DID_SLING_LOAD_CAPABILITY(20030, "Sling Load Capability"),
    DID_CREW_MEMBERS_AGGR(21000, "Crew Members (Aggregate)"),
    DID_CREW_MEMBERS_CREW_MEMBER_ID(21100, "Crew Members - Crew Member ID"),
    DID_CREW_MEMBERS_HEALTH(21200, "Crew Members - Health"),
    DID_CREW_MEMBERS_JOB_ASSIGNMENT(21300, "Crew Members - Job Assignment"),
    DID_FUEL_AGGR(23000, "Fuel (Aggregate)"),
    DID_FUEL_QTY_LITERS(23100, "Fuel - Quantity - Liters"),
    DID_FUEL_QTY_GALLONS(23105, "Fuel - Quantity - Gallons"),
    DID_AMMO_AGGR(24000, "Ammunition (Aggregate)"),
    DID_AMMO_120_MM_HEAT_QTY(24001, "Ammunition - 120-mm HEAT - quantity"),
    DID_AMMO_120_MM_SABOT_QTY(24002, "Ammunition - 120-mm SABOT - quantity"),
    DID_AMMO_12_7_MM_M8_QTY(24003, "Ammunition - 12.7-mm M8 - quantity"),
    DID_AMMO_12_7_MM_M20_QTY(24004, "Ammunition - 12.7-mm M20 - quantity"),
    DID_AMMO_7_62_MM_M62_QTY(24005, "Ammunition - 7.62-mm M62 - quantity"),
    DID_AMMO_M250_UKL8A1_QTY(24006, "Ammunition - M250 UKL8A1 - quantity"),
    DID_AMMO_M250_UKL8A3_QTY(24007, "Ammunition - M250 UKL8A3 - quantity"),
    DID_AMMO_7_62_MM_M80_QTY(24008, "Ammunition - 7.62-mm M80 - quantity"),
    DID_AMMO_12_7_MM_QTY(24009, "Ammunition - 12.7-mm - quantity"),
    DID_AMMO_7_62_MM_QTY(24010, "Ammunition - 7.62-mm - quantity"),
    DID_AMMO_DISPLAY_AVIATOR(24011, "Ammunition - Display Aviator"),
    DID_AMMO_MUNITIONS_25_HEI_T_QTY_ID_B120(24012, "Ammunition - Munitions 25 Hei T Quantity ID B120"),
    DID_AMMO_MUNITIONS_25_SABOT_QTY_ID(24013, "Ammunition - Munitions 25 Sabot Quantity ID "),
    DID_AMMO_MUNITIONS_TOW_II_QTY_ID(24014, "Ammunition - Munitions Tow Ii Quantity ID "),
    DID_AMMO_BATTLE_DAMAGE_STATUS(24015, "Ammunition - Battle Damage Status"),
    DID_AMMO_BATTLE_DAMAGE_INHIBIT_STATUS(24016, "Ammunition - Battle Damage Inhibit Status"),
    DID_AMMO_BCIS_EQUIPPED_ID(24017, "Ammunition - Bcis Equipped ID "),
    DID_AMMO_SIMSTATUS(24020, "Ammunition - SimStatus"),
    DID_AMMO_RUNSTATUS(24021, "Ammunition - RunStatus"),
    DID_AMMO_DISPLAY_STATE(24022, "Ammunition - Display State"),
    DID_AMMO_MUNITIONS_25_APDS_QTY_ID(24023, "Ammunition - Munitions 25 Apds Quantity ID "),
    DID_AMMO_MUNITIONS_M257_L8A1_QTY_ID(24024, "Ammunition - Munitions M257 L8A1 Quantity ID "),
    DID_AMMO_MUNITIONS_M257_L8A3_QTY_ID(24025, "Ammunition - Munitions M257 L8A3 Quantity ID "),
    DID_AMMO_MINES_QTY(24060, "Ammunition - Mines - quantity"),
    DID_AMMO_TYPE(24100, "Ammunition - Type"),
    DID_AMMO_KIND(24110, "Ammunition - Kind"),
    DID_AMMO_DOMAIN(24120, "Ammunition - Domain"),
    DID_AMMO_COUNTRY(24130, "Ammunition - Country"),
    DID_AMMO_CATEGORY(24140, "Ammunition - Category"),
    DID_AMMO_SUBCATEGORY(24150, "Ammunition - Subcategory"),
    DID_AMMO_EXTRA(24160, "Ammunition - Extra"),
    DID_AMMO_DESC(24300, "Ammunition - Description"),
    DID_CARGO_AGGR(25000, "Cargo (Aggregate)"),
    DID_VEHICLE_MASS(26000, "Vehicle Mass"),
    DID_SUPPLY_QTY(27000, "Supply Quantity"),
    DID_ARMAMENT(28000, "Armament"),
    DID_STATUS_AGGR(30000, "Status (Aggregate)"),
    DID_STATUS_ACTIVATE_ENTITY(30010, "Status - Activate entity"),
    DID_STATUS_SUBSCRIPTION_STATE(30100, "Status - Subscription State"),
    DID_STATUS_ROUND_TRIP_TIME_DELAY(30300, "Status - Round trip time delay"),
    DID_STATUS_TADIL_J_MSG_COUNT_LABEL_0(30400, "Status - TADIL J message count (label 0)"),
    DID_STATUS_TADIL_J_MSG_COUNT_LABEL_1(30401, "Status - TADIL J message count (label 1)"),
    DID_STATUS_TADIL_J_MSG_COUNT_LABEL_2(30402, "Status - TADIL J message count (label 2)"),
    DID_STATUS_TADIL_J_MSG_COUNT_LABEL_3(30403, "Status - TADIL J message count (label 3)"),
    DID_STATUS_TADIL_J_MSG_COUNT_LABEL_4(30404, "Status - TADIL J message count (label 4)"),
    DID_STATUS_TADIL_J_MSG_COUNT_LABEL_5(30405, "Status - TADIL J message count (label 5)"),
    DID_STATUS_TADIL_J_MSG_COUNT_LABEL_6(30406, "Status - TADIL J message count (label 6)"),
    DID_STATUS_TADIL_J_MSG_COUNT_LABEL_7(30407, "Status - TADIL J message count (label 7)"),
    DID_STATUS_TADIL_J_MSG_COUNT_LABEL_8(30408, "Status - TADIL J message count (label 8)"),
    DID_STATUS_TADIL_J_MSG_COUNT_LABEL_9(30409, "Status - TADIL J message count (label 9)"),
    DID_STATUS_TADIL_J_MSG_COUNT_LABEL_10(30410, "Status - TADIL J message count (label 10)"),
    DID_STATUS_TADIL_J_MSG_COUNT_LABEL_11(30411, "Status - TADIL J message count (label 11)"),
    DID_STATUS_TADIL_J_MSG_COUNT_LABEL_12(30412, "Status - TADIL J message count (label 12)"),
    DID_STATUS_TADIL_J_MSG_COUNT_LABEL_13(30413, "Status - TADIL J message count (label 13)"),
    DID_STATUS_TADIL_J_MSG_COUNT_LABEL_14(30414, "Status - TADIL J message count (label 14)"),
    DID_STATUS_TADIL_J_MSG_COUNT_LABEL_15(30415, "Status - TADIL J message count (label 15)"),
    DID_STATUS_TADIL_J_MSG_COUNT_LABEL_16(30416, "Status - TADIL J message count (label 16)"),
    DID_STATUS_TADIL_J_MSG_COUNT_LABEL_17(30417, "Status - TADIL J message count (label 17)"),
    DID_STATUS_TADIL_J_MSG_COUNT_LABEL_18(30418, "Status - TADIL J message count (label 18)"),
    DID_STATUS_TADIL_J_MSG_COUNT_LABEL_19(30419, "Status - TADIL J message count (label 19)"),
    DID_STATUS_TADIL_J_MSG_COUNT_LABEL_20(30420, "Status - TADIL J message count (label 20)"),
    DID_STATUS_TADIL_J_MSG_COUNT_LABEL_21(30421, "Status - TADIL J message count (label 21)"),
    DID_STATUS_TADIL_J_MSG_COUNT_LABEL_22(30422, "Status - TADIL J message count (label 22)"),
    DID_STATUS_TADIL_J_MSG_COUNT_LABEL_23(30423, "Status - TADIL J message count (label 23)"),
    DID_STATUS_TADIL_J_MSG_COUNT_LABEL_24(30424, "Status - TADIL J message count (label 24)"),
    DID_STATUS_TADIL_J_MSG_COUNT_LABEL_25(30425, "Status - TADIL J message count (label 25)"),
    DID_STATUS_TADIL_J_MSG_COUNT_LABEL_26(30426, "Status - TADIL J message count (label 26)"),
    DID_STATUS_TADIL_J_MSG_COUNT_LABEL_27(30427, "Status - TADIL J message count (label 27)"),
    DID_STATUS_TADIL_J_MSG_COUNT_LABEL_28(30428, "Status - TADIL J message count (label 28)"),
    DID_STATUS_TADIL_J_MSG_COUNT_LABEL_29(30429, "Status - TADIL J message count (label 29)"),
    DID_STATUS_TADIL_J_MSG_COUNT_LABEL_30(30430, "Status - TADIL J message count (label 30)"),
    DID_STATUS_TADIL_J_MSG_COUNT_LABEL_31(30431, "Status - TADIL J message count (label 31)"),
    DID_STATUS_POSITION_AGGR(31000, "Status - Position (Aggregate)"),
    DID_STATUS_ROUTE_WAYPOINT_TYPE(31010, "Status - Route (Waypoint) type"),
    DID_STATUS_MIL_GRID_10(31100, "Status - Mil Grid 10"),
    DID_STATUS_GEOCENTRIC_COORDINATES_AGGR(31200, "Status - Geocentric Coordinates (Aggregate)"),
    DID_STATUS_GEOCENTRIC_COORDINATES_X(31210, "Status - Geocentric Coordinates - X "),
    DID_STATUS_GEOCENTRIC_COORDINATES_Y(31220, "Status - Geocentric Coordinates - Y"),
    DID_STATUS_GEOCENTRIC_COORDINATES_Z(31230, "Status - Geocentric Coordinates - Z"),
    DID_STATUS_LAT(31300, "Status - Latitude"),
    DID_STATUS_LONG(31400, "Status - Longitude"),
    DID_STATUS_LOS_AGGR(31500, "Status - Line of Sight (Aggregate)"),
    DID_STATUS_LOS_X(31510, "Status - Line of Sight - X"),
    DID_STATUS_LOS_Y(31520, "Status - Line of Sight - Y"),
    DID_STATUS_LOS_Z(31530, "Status - Line of Sight - Z"),
    DID_STATUS_ALTITUDE(31600, "Status - Altitude"),
    DID_STATUS_DESTINATION_LAT(31700, "Status - Destination Latitude"),
    DID_STATUS_DESTINATION_LONG(31800, "Status - Destination Longitude"),
    DID_STATUS_DESTINATION_ALTITUDE(31900, "Status - Destination Altitude"),
    DID_STATUS_ORIENT(32000, "Status - Orientation"),
    DID_STATUS_HULL_HEADING_ANGLE(32100, "Status - Hull Heading Angle"),
    DID_STATUS_HULL_PITCH_ANGLE(32200, "Status - Hull Pitch Angle"),
    DID_STATUS_ROLL_ANGLE(32300, "Status - Roll Angle"),
    DID_STATUS_ROLL_ANGLE_X(32500, "Status - Roll Angle - X"),
    DID_STATUS_ROLL_ANGLE_Y(32600, "Status - Roll Angle - Y"),
    DID_STATUS_ROLL_ANGLE_Z(32700, "Status - Roll Angle - Z"),
    DID_STATUS_APPEARANCE_AGGR(33000, "Status - Appearance (Aggregate)"),
    DID_STATUS_APPEARANCE_AMBIENT_LIGHTING(33100, "Status - Appearance - Ambient Lighting"),
    DID_STATUS_APPEARANCE_LIGHTS(33101, "Status - Appearance - Lights"),
    DID_STATUS_APPEARANCE_PAINT_SCHEME(33200, "Status - Appearance - Paint Scheme"),
    DID_STATUS_APPEARANCE_SMOKE(33300, "Status - Appearance - Smoke"),
    DID_STATUS_APPEARANCE_TRAILING_EFFECTS(33400, "Status - Appearance - Trailing Effects"),
    DID_STATUS_APPEARANCE_FLAMING(33500, "Status - Appearance - Flaming"),
    DID_STATUS_APPEARANCE_MARKING(33600, "Status - Appearance - Marking"),
    DID_STATUS_APPEARANCE_MINE_PLOWS_ATTACHED(33710, "Status - Appearance - Mine Plows Attached"),
    DID_STATUS_APPEARANCE_MINE_ROLLERS_ATTACHED(33720, "Status - Appearance - Mine Rollers Attached"),
    DID_STATUS_APPEARANCE_TANK_TURRET_AZIMUTH(33730, "Status - Appearance - Tank Turret Azimuth"),
    DID_STATUS_FAILURES_AND_MALFUNCTIONS_AGGR(34000, "Status - Failures and Malfunctions (Aggregate)"),
    DID_STATUS_AGE(34100, "Status - Age"),
    DID_STATUS_KILOMETERS(34110, "Status - Kilometers"),
    DID_STATUS_DAMAGE_AGGR(35000, "Status - Damage (Aggregate)"),
    DID_STATUS_DAMAGE_CAUSE(35050, "Status - Damage - Cause"),
    DID_STATUS_DAMAGE_MOBILITY_KILL(35100, "Status - Damage - Mobility Kill"),
    DID_STATUS_DAMAGE_FIRE_POWER_KILL(35200, "Status - Damage - Fire-Power Kill"),
    DID_STATUS_DAMAGE_PERSONNEL_CASUALTIES(35300, "Status - Damage - Personnel Casualties"),
    DID_STATUS_DAMAGE_INFO(35400, "Status - Damage Info"),
    DID_STATUS_VEL_AGGR(36000, "Status - Velocity (Aggregate)"),
    DID_STATUS_X_VEL(36100, "Status - X-velocity"),
    DID_STATUS_Y_VEL(36200, "Status - Y-velocity"),
    DID_STATUS_Z_VEL(36300, "Status - Z-velocity"),
    DID_STATUS_SPEED(36400, "Status - Speed"),
    DID_STATUS_ACCEL_AGGR(37000, "Status - Acceleration (Aggregate)"),
    DID_STATUS_X_ACCEL(37100, "Status - X-acceleration"),
    DID_STATUS_Y_ACCEL(37200, "Status - Y-acceleration"),
    DID_STATUS_Z_ACCEL(37300, "Status - Z-acceleration"),
    DID_STATUS_ENGINE_STATUS_AGGR(38100, "Status - Engine Status (Aggregate)"),
    DID_STATUS_PRIMARY_TARGET_LINE_PTL(39000, "Status - Primary Target Line (PTL)"),
    DID_EXERCISE_AGGR(40000, "Exercise (Aggregate)"),
    DID_EXERCISE_EXERCISE_STATE(40010, "Exercise - Exercise State"),
    DID_EXERCISE_RESTART_REFRESH(40015, "Exercise - Restart/Refresh"),
    DID_EXERCISE_AFATDS_FILE_NAME(40020, "Exercise - AFATDS File Name"),
    DID_TERRAIN_DATABASE(41000, "Terrain Database"),
    DID_TERRAINDATABASENAME(41010, "TerrainDatabaseName"),
    DID_MISSIONS_AGGR(42000, "Missions (Aggregate)"),
    DID_MISSIONS_MISSION_REQUEST_RECORD_ID(42050, "Missions - Mission Request Record ID "),
    DID_MISSIONS_INDIRECT_OR_CAS_FIRE_RECORD_ID(42060, "Missions - Indirect Or Cas Fire Record ID "),
    DID_MISSIONS_MINEFIELD_ENTRY_RECORD_ID(42070, "Missions - Minefield Entry Record ID "),
    DID_MISSIONS_MINE_DETONATION_RECORD_ID(42080, "Missions - Mine Detonation Record ID "),
    DID_MISSIONS_MISSION_ID(42100, "Missions - Mission ID"),
    DID_MISSIONS_MISSION_TYPE(42200, "Missions - Mission Type"),
    DID_MISSIONS_MISSION_REQUEST_TIME_STAMP(42300, "Missions - Mission Request Time Stamp"),
    DID_MISSIONS_MISSION_DESC_ID(42400, "Missions - Mission Description ID "),
    DID_EXERCISE_DESC(43000, "Exercise Description"),
    DID_EXERCISE_DESC_NAME(43100, "Exercise Description - Name"),
    DID_EXERCISE_DESC_ENTITIES(43200, "Exercise Description - Entities"),
    DID_EXERCISE_DESC_VERSION(43300, "Exercise Description - Version"),
    DID_EXERCISE_DESC_EXERCISE_CONCEPT_OF_OPERATION_ID(43400, "Exercise Description - Exercise Concept Of Operation ID "),
    DID_EXERCISE_DESC_GUISE_MODE(43410, "Exercise Description - Guise Mode"),
    DID_EXERCISE_DESC_SIMULATION_APPLICATION_ACTIVE_STATUS(43420, "Exercise Description - Simulation Application Active Status"),
    DID_EXERCISE_DESC_SIMULATION_APPLICATION_ROLE_RECORD(43430, "Exercise Description - Simulation Application Role Record"),
    DID_EXERCISE_DESC_SIMULATION_APPLICATION_STATE(43440, "Exercise Description - Simulation Application State"),
    DID_EXERCISE_DESC_EXERCISE_ENEMY_FORCES_DESC_ID(43500, "Exercise Description - Exercise Enemy Forces Description ID "),
    DID_EXERCISE_DESC_EXERCISE_FRIENDLY_FORCES_DESC_ID(43600, "Exercise Description - Exercise Friendly Forces Description ID "),
    DID_VISUAL_OUTPUT_MODE_AGGR(44000, "Visual Output Mode (Aggregate)"),
    DID_SIMULATION_MGR_ROLE(44100, "Simulation Manager Role"),
    DID_SIMULATION_MGR_SITE_ID(44110, "Simulation Manager Site ID"),
    DID_SIMULATION_MGR_APPLIC_ID(44120, "Simulation Manager Applic. ID"),
    DID_SIMULATION_MGR_ENTITY_ID(44130, "Simulation Manager Entity ID"),
    DID_SIMULATION_MGR_ACTIVE_STATUS(44140, "Simulation Manager Active Status"),
    DID_AFTER_ACTION_REVIEW_ROLE(44200, "After Action Review Role"),
    DID_AFTER_ACTION_REVIEW_SITE_ID(44210, "After Action Review Site ID"),
    DID_AFTER_ACTION_APPLIC_ID(44220, "After Action Applic. ID"),
    DID_AFTER_ACTION_REVIEW_ENTITY_ID(44230, "After Action Review Entity ID"),
    DID_AFTER_ACTION_REVIEW_ACTIVE_STATUS(44240, "After Action Review Active Status"),
    DID_EXERCISE_LOGGER_ROLE(44300, "Exercise Logger Role"),
    DID_EXERCISE_LOGGER_SITE_ID(44310, "Exercise Logger Site ID"),
    DID_EXERCISE_LOGGER_APPLIC_ID(44320, "Exercise Logger Applic. ID"),
    DID_EXERCISE_ENTITY_ID(44330, "Exercise Entity ID"),
    DID_EXERCISE_LOGGER_ACTIVE_STATUS(44340, "Exercise Logger Active Status"),
    DID_SYNTHETIC_ENVIR_MGR_ROLE(44400, "Synthetic Environment Manager Role"),
    DID_SYNTHETIC_ENVIR_MGR_SITE_ID(44410, "Synthetic Environment Manager Site ID"),
    DID_SYNTHETIC_ENVIR_MGR_APPLIC_ID(44420, "Synthetic Environment Manager Applic. ID"),
    DID_SYNTHETIC_ENVIR_MGR_ENTITY_ID(44430, "Synthetic Environment Manager Entity ID"),
    DID_SYNTHETIC_ENVIR_MGR_ACTIVE_STATUS(44440, "Synthetic Environment Manager Active Status"),
    DID_SIMNET_DIS_TRANSLATOR_ROLE(44500, "SIMNET-DIS Translator Role"),
    DID_SIMNET_DIS_TRANSLATOR_SITE_ID(44510, "SIMNET-DIS Translator Site ID"),
    DID_SIMNET_DIS_TRANSLATOR_APPLIC_ID(44520, "SIMNET-DIS Translator Applic. ID"),
    DID_SIMNET_DIS_TRANSLATOR_ENTITY_ID(44530, "SIMNET-DIS Translator Entity ID"),
    DID_SIMNET_DIS_TRANSLATOR_ACTIVE_STATUS(44540, "SIMNET-DIS Translator Active Status"),
    DID_APPLICATION_RATE(45000, "Application Rate"),
    DID_APPLICATION_RATE_APPLICATION_TIME(45005, "Application Rate - Application Time"),
    DID_APPLICATION_RATE_APPLICATION_TIMESTEP(45010, "Application Rate - Application Timestep"),
    DID_APPLICATION_RATE_FEEDBACK_TIME(45020, "Application Rate - Feedback Time"),
    DID_APPLICATION_RATE_SIMULATION_RATE(45030, "Application Rate - Simulation Rate"),
    DID_APPLICATION_RATE_SIMULATION_TIME(45040, "Application Rate - Simulation Time"),
    DID_APPLICATION_RATE_SIMULATION_TIMESTEP(45050, "Application Rate - Simulation Timestep"),
    DID_APPLICATION_RATE_TIME_INTERVAL(45060, "Application Rate - Time Interval"),
    DID_APPLICATION_RATE_TIME_LATENCY(45070, "Application Rate - Time Latency"),
    DID_APPLICATION_RATE_TIME_SCHEME(45080, "Application Rate - Time Scheme"),
    DID_EXERCISE_ELAPSED_TIME_1(46000, "Exercise Elapsed Time 1"),
    DID_EXERCISE_ELAPSED_TIME_2(46010, "Exercise Elapsed Time 2"),
    DID_APPLICATION_STATE_RECORD(47100, "Application State Record"),
    DID_APPLICATION_HEALTH_STATUS_RECORD(47200, "Application Health Status Record"),
    DID_APPLICATION_STATUS__TYPE_DESC_RECORD(47210, "Application Status Type Description Record"),
    DID_APPLICATION_STATUS_DESC_RECORD(47220, "Application Status Description Record"),
    DID_APPLICATION_HEALTH_STATUS_CAP_RECORD(47230, "Application Health Status Capability Record"),
    DID_APPLICATION_HEALTH_STATUS_HBT_REQ_RECORD(47240, "Application Health Status Heartbeat Request Record"),
    DID_APPLICATION_INITIALIZATION_DATA_RECORD(47300, "Application Initialization Data Record"),
    DID_EXERCISE_ID(47400, "Exercise ID"),
    DID_APPLICATION_CAPABILITY_RECORD(47500, "Application Capability Record"),
    DID_DATA_QUERY_REQ_RECORD(47600, "Data Query Request Record"),
    DID_ENVIR_AGGR(50000, "Environment (Aggregate)"),
    DID_OWNERSHIP_MUNITION(50001, "Munition"),
    DID_OWNERSHIP_ENGINE_FUEL(50002, "Engine Fuel"),
    DID_OWNERSHIP_STORAGE_FUEL(50003, "Storage Fuel"),
    DID_OWNERSHIP_NOT_USED(50004, "Not used"),
    DID_OWNERSHIP_EXPENDABLE(50005, "Expendable"),
    DID_OWNERSHIP_TOTAL_RECORD_SETS(50006, "Total Record Sets"),
    DID_OWNERSHIP_LAUNCHED_MUNITION(50007, "Launched Munition"),
    DID_OWNERSHIP_ASSOCIATION(50008, "Association"),
    DID_OWNERSHIP_SENSOR(50009, "Sensor"),
    DID_OWNERSHIP_MUNITION_RELOAD(50010, "Munition Reload"),
    DID_OWNERSHIP_ENGINE_FUEL_RELOAD(50011, "Engine Fuel Reload"),
    DID_OWNERSHIP_STORAGE_FUEL_RELOAD(50012, "Storage Fuel Reload"),
    DID_OWNERSHIP_EXPENDABLE_RELOAD(50013, "Expendable Reload"),
    DID_ENVIR_WEATHER(51000, "Environment - Weather"),
    DID_ENVIR_WEATHER_CONDITION(51010, "Environment - Weather Condition"),
    DID_ENVIR_THERMAL_CONDITION(51100, "Environment - Thermal Condition"),
    DID_ENVIR_THERMAL_VISIBILITY_FLOATING_POINT(51110, "Environment - Thermal Visibility (floating point)"),
    DID_ENVIR_THERMAL_VISIBILITY_UNSIGNED_INTEGER(51111, "Environment - Thermal Visibility (unsigned integer)"),
    DID_ENVIR_TIME_AGGR(52000, "Environment - Time (Aggregate)"),
    DID_ENVIR_TIME(52001, "Environment - Time"),
    DID_ENVIR_TIME_OF_DAY_DISCRETE(52100, "Environment - Time of Day - Discrete"),
    DID_ENVIR_TIME_OF_DAY_CONTINUOUS(52200, "Environment - Time of Day - Continuous"),
    DID_ENVIR_TIME_MODE(52300, "Environment - Time Mode"),
    DID_ENVIR_TIME_SCENE(52305, "Environment - Time Scene"),
    DID_ENVIR_CURRENT_HOUR(52310, "Environment - Current Hour"),
    DID_ENVIR_CURRENT_MINUTE(52320, "Environment - Current Minute"),
    DID_ENVIR_CURRENT_SECOND(52330, "Environment - Current Second"),
    DID_ENVIR_AZIMUTH(52340, "Environment - Azimuth"),
    DID_ENVIR_MAXIMUM_ELEVATION(52350, "Environment - Maximum Elevation"),
    DID_ENVIR_TIME_ZONE(52360, "Environment - Time Zone"),
    DID_ENVIR_TIME_RATE(52370, "Environment - Time Rate"),
    DID_ENVIR_SIMULATION_TIME(52380, "Environment - Simulation Time"),
    DID_ENVIR_TIME_SUNRISE_ENABLED(52400, "Environment - Time Sunrise Enabled"),
    DID_ENVIR_SUNRISE_HOUR(52410, "Environment - Sunrise Hour"),
    DID_ENVIR_SUNRISE_MINUTE(52420, "Environment - Sunrise Minute"),
    DID_ENVIR_SUNRISE_SECOND(52430, "Environment - Sunrise Second"),
    DID_ENVIR_SUNRISE_AZIMUTH(52440, "Environment - Sunrise Azimuth"),
    DID_ENVIR_TIME_SUNSET_ENABLED(52500, "Environment - Time Sunset Enabled"),
    DID_ENVIR_SUNSET_HOUR(52510, "Environment - Sunset Hour"),
    DID_ENVIR_SUNSET_HOUR_2(52511, "Environment - Sunset Hour 2"),
    DID_ENVIR_SUNSET_MINUTE(52520, "Environment - Sunset Minute"),
    DID_ENVIR_SUNSET_SECOND(52530, "Environment - Sunset Second"),
    DID_ENVIR_DATE_AGGR(52600, "Environment - Date (Aggregate)"),
    DID_ENVIR_DATE_EUROPEAN(52601, "Environment - Date (European)"),
    DID_ENVIR_DATE_US(52602, "Environment - Date (US)"),
    DID_ENVIR_MONTH(52610, "Environment - Month"),
    DID_ENVIR_DAY(52620, "Environment - Day"),
    DID_ENVIR_YEAR(52630, "Environment - Year"),
    DID_ENVIR_CLOUDS(53000, "Environment - Clouds"),
    DID_ENVIR_CLOUDS_CLOUD_LAYER_ENABLE(53050, "Environment - Clouds - Cloud Layer Enable"),
    DID_ENVIR_CLOUDS_CLOUD_LAYER_SELECTION(53060, "Environment - Clouds - Cloud Layer Selection"),
    DID_ENVIR_CLOUDS_VISIBILITY(53100, "Environment - Clouds - Visibility"),
    DID_ENVIR_CLOUDS_BASE_ALTITUDE(53200, "Environment - Clouds - Base Altitude"),
    DID_ENVIR_CLOUDS_BASE_ALTITUDE_FEET(53250, "Environment - Clouds - Base Altitude - Feet"),
    DID_ENVIR_CLOUDS_CEILING(53300, "Environment - Clouds - Ceiling"),
    DID_ENVIR_CLOUDS_CEILING_FEET(53350, "Environment - Clouds - Ceiling - Feet"),
    DID_ENVIR_CLOUDS_CHARACTERISTICS(53400, "Environment - Clouds - Characteristics"),
    DID_ENVIR_CLOUDS_CONCENTRATION_LENGTH(53410, "Environment - Clouds - Concentration Length"),
    DID_ENVIR_CLOUDS_TRANSMITTANCE(53420, "Environment - Clouds - Transmittance"),
    DID_ENVIR_CLOUDS_RADIANCE(53430, "Environment - Clouds - Radiance"),
    DID_ENVIR_PRECIPITATION(54000, "Environment - Precipitation"),
    DID_ENVIR_PRECIPITATION_RAIN(54100, "Environment - Precipitation - Rain"),
    DID_ENVIR_FOG(55000, "Environment - Fog"),
    DID_ENVIR_FOG_VISIBILITY_REAL_METERS(55100, "Environment - Fog - Visibility - real meters"),
    DID_ENVIR_FOG_VISIBILITY_METERS(55101, "Environment - Fog - Visibility - meters"),
    DID_ENVIR_FOG_VISIBILITY_MILES(55105, "Environment - Fog - Visibility - miles"),
    DID_ENVIR_FOG_DENSITY(55200, "Environment - Fog - Density"),
    DID_ENVIR_FOG_BASE(55300, "Environment - Fog - Base"),
    DID_ENVIR_FOG_VIEW_LAYER_FROM_ABOVE_(55401, "Environment - Fog - View Layer from above."),
    DID_ENVIR_FOG_TRANSITION_RANGE(55410, "Environment - Fog - Transition Range"),
    DID_ENVIR_FOG_BOTTOM_METERS(55420, "Environment - Fog - Bottom - meters"),
    DID_ENVIR_FOG_BOTTOM_FEET(55425, "Environment - Fog - Bottom - feet "),
    DID_ENVIR_FOG_CEILING_METERS(55430, "Environment - Fog - Ceiling - meters "),
    DID_ENVIR_FOG_CEILING_FEET(55435, "Environment - Fog - Ceiling - feet "),
    DID_ENVIR_HBODIES_AGGR(56000, "Environment - Heavenly Bodies (Aggregate)"),
    DID_ENVIR_HBODIES_SUN_AGGR(56100, "Environment - Heavenly Bodies - Sun (Aggregate)"),
    DID_ENVIR_ASSEMBLY_AREA_LIGHTING(56101, "Environment - Assembly Area Lighting"),
    DID_ENVIR_FARP_LIGHTING(56102, "Environment - FARP Lighting"),
    DID_ENVIR_DB_CULTURAL_LIGHTING(56103, "Environment - DB Cultural Lighting"),
    DID_ENVIR_HBODIES_SUN_VISIBLE(56105, "Environment - Heavenly Bodies - Sun Visible"),
    DID_ENVIR_RUNWAYLIGHTING(56106, "Environment - RunwayLighting"),
    DID_ENVIR_APPROACH_LIGHTING(56107, "Environment - Approach Lighting"),
    DID_ENVIR_VASI_VAPI_LIGHTING(56108, "Environment - VASI VAPI Lighting"),
    DID_ENVIR_BEACONLIGHTING(56109, "Environment - BeaconLighting"),
    DID_ENVIR_HBODIES_POSITION_AGGR(56110, "Environment - Heavenly Bodies - Position (Aggregate)"),
    DID_ENVIR_HBODIES_SUN_POSITION_ELEVATION_DEGREES(56111, "Environment - Heavenly Bodies - Sun Position Elevation - Degrees"),
    DID_ENVIR_HBODIES_POSITION_AZIMUTH_AGGR(56120, "Environment - Heavenly Bodies - Position Azimuth (Aggregate)"),
    DID_ENVIR_HBODIES_SUN_POSITION_AZIMUTH_DEGREES(56121, "Environment - Heavenly Bodies - Sun Position Azimuth - Degrees"),
    DID_ENVIR_HBODIES_POSITION_ELEVATION(56130, "Environment - Heavenly Bodies - Position Elevation"),
    DID_ENVIR_HBODIES_POSITION_INTENSITY(56140, "Environment - Heavenly Bodies - Position Intensity"),
    DID_ENVIR_HBODIES_MOON_AGGR(56200, "Environment - Heavenly Bodies - Moon (Aggregate)"),
    DID_ENVIR_HBODIES_MOON_VISIBLE(56205, "Environment - Heavenly Bodies - Moon Visible"),
    DID_ENVIR_HBODIES_MOON_POSITION(56210, "Environment - Heavenly Bodies - Moon Position"),
    DID_ENVIR_HBODIES_MOON_POSITION_AZIMUTH(56220, "Environment - Heavenly Bodies - Moon Position Azimuth"),
    DID_ENVIR_HBODIES_MOON_POSITION_AZIMUTH_DEGREES(56221, "Environment - Heavenly Bodies - Moon Position Azimuth - Degrees"),
    DID_ENVIR_HBODIES_MOON_POSITION_ELEVATION(56230, "Environment - Heavenly Bodies - Moon Position Elevation"),
    DID_ENVIR_HBODIES_MOON_POSITION_ELEVATION_DEGREES(56231, "Environment - Heavenly Bodies - Moon Position Elevation - Degrees"),
    DID_ENVIR_HBODIES_MOON_POSITION_INTENSITY(56240, "Environment - Heavenly Bodies - Moon Position Intensity"),
    DID_ENVIR_HBODIES_LUNAR_ILLUMINATION_ID(56250, "Environment - Heavenly Bodies - Lunar Illumination ID "),
    DID_ENVIR_HBODIES_HORIZON_AGGR(56310, "Environment - Heavenly Bodies - Horizon (Aggregate)"),
    DID_ENVIR_HBODIES_HORIZON_AZIMUTH(56320, "Environment - Heavenly Bodies - Horizon Azimuth"),
    DID_ENVIR_HBODIES_HORIZON_ELEVATION(56330, "Environment - Heavenly Bodies - Horizon Elevation"),
    DID_ENVIR_HBODIES_HORIZON_HEADING(56340, "Environment - Heavenly Bodies - Horizon Heading"),
    DID_ENVIR_HBODIES_HORIZON_INTENSITY(56350, "Environment - Heavenly Bodies - Horizon Intensity"),
    DID_ENVIR_METEOR_AGGR(57000, "Environment - Meteorological (Aggregate)"),
    DID_ENVIR_METEOR_BAROMETRIC_PRESSURE(57001, "Environment - Meteorological - Barometric Pressure"),
    DID_ENVIR_METEOR_HF_SIG_PROP_ADJ(57007, "Environment - Meteorological - HF Sig Prop Adj"),
    DID_ENVIR_METEOR_GPS_NUM_SATS(57008, "Environment - Meteorological - GPS Num Sats"),
    DID_ENVIR_METEOR_GPS_JAMMING_STATE(57009, "Environment - Meteorological - GPS Jamming State"),
    DID_ENVIR_METEOR_HF_PROP_MODE(57010, "Environment - Meteorological - HF Prop Mode"),
    DID_ENVIR_METEOR_IR_CROSSOVER_STATE(57020, "Environment - Meteorological - IR Crossover State"),
    DID_ENVIR_METEOR_IR_CROSSOVER_MINIMUM(57021, "Environment - Meteorological - IR Crossover Minimum"),
    DID_ENVIR_METEOR_IR_CROSSOVER_MAXIMUM(57022, "Environment - Meteorological - IR Crossover Maximum"),
    DID_ENVIR_METEOR_IR_CROSSOVER_DURATION(57023, "Environment - Meteorological - IR Crossover Duration"),
    DID_ENVIR_METEOR_IR_CROSSOVER_CURRENT(57024, "Environment - Meteorological - IR Crossover Current"),
    DID_ENVIR_METEOR_IR_CROSSOVER_GMT_SECONDS(57025, "Environment - Meteorological - IR Crossover GMT Seconds"),
    DID_ENVIR_METEOR_IR_CROSSOVER_GMT_DAY(57026, "Environment - Meteorological - IR Crossover GMT Day"),
    DID_ENVIR_METEOR_IR_CROSSOVER_GMT_MONTH(57027, "Environment - Meteorological - IR Crossover GMT Month"),
    DID_ENVIR_METEOR_IR_CROSSOVER_GMT_YEAR(57028, "Environment - Meteorological - IR Crossover GMT Year"),
    DID_ENVIR_METEOR_IR_CROSSOVER_TIME_LEFT(57029, "Environment - Meteorological - IR Crossover Time Left"),
    DID_ENVIR_METEOR_IR_CROSSOVER_TIME_FLAG(57030, "Environment - Meteorological - IR Crossover Time Flag"),
    DID_ENVIR_TEMPERATURE(57100, "Environment - Temperature"),
    DID_ENVIR_HUMIDITY(57200, "Environment - Humidity"),
    DID_ENVIR_VISIBILITY(57300, "Environment - Visibility"),
    DID_ENVIR_AMBIENT_VISIBILITY(57301, "Environment - Ambient Visibility"),
    DID_ENVIR_SCUD_ENABLE(57308, "Environment - Scud Enable"),
    DID_ENVIR_SCATTERED_CLOUD_DENSITY(57309, "Environment - Scattered Cloud Density"),
    DID_ENVIR_SCENE_ILLUMINATION_STATE(57310, "Environment - Scene Illumination State"),
    DID_ENVIR_ROTOR_WASH_ENABLE(57311, "Environment - Rotor Wash Enable"),
    DID_ENVIR_WINDS_AGGR(57400, "Environment - Winds (Aggregate)"),
    DID_ENVIR_WIND_SPEED_AGGR(57410, "Environment - Wind Speed (Aggregate)"),
    DID_ENVIR_WIND_SPEED_KNOTS(57411, "Environment - Wind Speed - Knots"),
    DID_ENVIR_WIND_DIRECTION(57420, "Environment - Wind Direction"),
    DID_ENVIR_WIND_DIRECTION_DEGREES(57421, "Environment - Wind Direction - Degrees"),
    DID_ENVIR_PRESSURE(57430, "Environment - Pressure"),
    DID_ENVIR_RAINSOAK(57500, "Environment - Rainsoak"),
    DID_ENVIR_TIDE_SPEED(57610, "Environment - Tide Speed"),
    DID_ENVIR_TIDE_SPEED_KNOTS(57611, "Environment - Tide Speed - Knots"),
    DID_ENVIR_TIDE_DIRECTION(57620, "Environment - Tide Direction"),
    DID_ENVIR_TIDE_DIRECTION_DEGREES(57621, "Environment - Tide Direction - Degrees"),
    DID_ENVIR_SEASON(57700, "Environment - Season"),
    DID_ENVIR_HAZE(58000, "Environment - Haze"),
    DID_ENVIR_HAZE_VISIBILITY_METERS(58100, "Environment - Haze - Visibility - Meters"),
    DID_ENVIR_HAZE_VISIBILITY_MILES(58105, "Environment - Haze - Visibility - Miles"),
    DID_ENVIR_HAZE_DENSITY(58200, "Environment - Haze - Density"),
    DID_ENVIR_HAZE_CEILING_METERS(58430, "Environment - Haze - Ceiling - Meters"),
    DID_ENVIR_HAZE_CEILING_FEET(58435, "Environment - Haze - Ceiling - Feet"),
    DID_ENVIR_CONTAM_AND_OBS_AGGR(59000, "Environment - Contaminants and Obscurants (Aggregate)"),
    DID_ENVIR_CONTAM_AND_OBS_TYPE(59100, "Environment - Contaminants and Obscurants - Type"),
    DID_ENVIR_CONTAM_AND_OBS_PERSISTENCE(59110, "Environment - Contaminants and Obscurants - Persistence"),
    DID_ENVIR_CONTAM_AND_OBS_CHEM_DOSAGE(59115, "Environment - Contaminants and Obscurants - Chemical Dosage"),
    DID_ENVIR_CONTAM_AND_OBS_CHEM_AIR_CONCENTRATION(59120, "Environment - Contaminants and Obscurants - Chemical Air Concentration"),
    DID_ENVIR_CONTAM_AND_OBS_CHEM_GROUND_DEPOSITION(59125, "Environment - Contaminants and Obscurants - Chemical Ground Deposition"),
    DID_ENVIR_CONTAM_AND_OBS_CHEM_MAXIMUM_GROUND_DEPOSITION(59130, "Environment - Contaminants and Obscurants - Chemical Maximum Ground Deposition"),
    DID_ENVIR_CONTAM_AND_OBS_CHEM_DOSAGE_THRESHOLD(59135, "Environment - Contaminants and Obscurants - Chemical Dosage Threshold"),
    DID_ENVIR_CONTAM_AND_OBS_BIO_DOSAGE(59140, "Environment - Contaminants and Obscurants - Biological Dosage"),
    DID_ENVIR_CONTAM_AND_OBS_BIO_AIR_CONCENTRATION(59145, "Environment - Contaminants and Obscurants - Biological Air Concentration"),
    DID_ENVIR_CONTAM_AND_OBS_BIO_DOSAGE_THRESHOLD(59150, "Environment - Contaminants and Obscurants - Biological Dosage Threshold"),
    DID_ENVIR_CONTAM_AND_OBS_BIO_BINNED_PARTICLE_COUNT(59155, "Environment - Contaminants and Obscurants - Biological Binned Particle Count"),
    DID_ENVIR_CONTAM_AND_OBS_RAD_DOSAGE(59160, "Environment - Contaminants and Obscurants - Radiological Dosage"),
    DID_COMMS_AGGR(60000, "Communications (Aggregate)"),
    DID_COMMS_CHANNEL_TYPE(61100, "Communications - Channel Type"),
    DID_COMMS_CHANNEL_TYPE_2(61101, "Communications - Channel Type 2"),
    DID_COMMS_CHANNEL_IDENTIFICATION(61200, "Communications - Channel Identification"),
    DID_COMMS_ALPHA_IDENTIFICATION(61300, "Communications - Alpha Identification"),
    DID_COMMS_RADIO_IDENTIFICATION(61400, "Communications - Radio Identification"),
    DID_COMMS_LAND_LINE_IDENTIFICATION(61500, "Communications - Land Line Identification"),
    DID_COMMS_INTERCOM_IDENTIFICATION(61600, "Communications - Intercom Identification"),
    DID_COMMS_GROUP_NETWORK_CHANNEL_NUMBER(61700, "Communications - Group Network Channel Number"),
    DID_COMMS_RADIO_COMMS_STATUS(62100, "Communications - Radio Communications Status"),
    DID_COMMS_STATIONARY_RADIO_TRANS_DEFAULT_TIME(62200, "Communications - Stationary Radio Transmitters Default Time"),
    DID_COMMS_MOVING_RADIO_TRANS_DEFAULT_TIME(62300, "Communications - Moving Radio Transmitters Default Time"),
    DID_COMMS_MOVING_RADIO_TRANS_DEFAULT_TIME_XET_ELAPSED_SECONDS(62330, "Communications - Moving Radio Transmitters Default Time - Xet Elapsed Seconds"),
    DID_COMMS_MOVING_RADIO_TRANS_DEFAULT_TIME_SYNC_BMC_FREEZE(62331, "Communications - Moving Radio Transmitters Default Time - Sync Bmc Freeze"),
    DID_COMMS_MOVING_RADIO_TRANS_DEFAULT_TIME_SYNC_BMC_HF_SIG_DEG(62332, "Communications - Moving Radio Transmitters Default Time - Sync Bmc HF sig Deg"),
    DID_COMMS_STATIONARY_RADIO_SIGNALS_DEFAULT_TIME(62400, "Communications - Stationary Radio Signals Default Time"),
    DID_COMMS_MOVING_RADIO_SIGNAL_DEFAULT_TIME(62500, "Communications - Moving Radio Signal Default Time"),
    DID_COMMS_RADIO_INITIALIZATION_TRANSEC_SECURITY_KEY(63101, "Communications - Radio Initialization Transec Security Key"),
    DID_COMMS_RADIO_INITIALIZATION_INTERNAL_NOISE_LEVEL(63102, "Communications - Radio Initialization Internal Noise Level"),
    DID_COMMS_RADIO_INITIALIZATION_SQUELCH_THRESHOLD(63103, "Communications - Radio Initialization Squelch Threshold"),
    DID_COMMS_RADIO_INITIALIZATION_ANTENNA_LOCATION(63104, "Communications - Radio Initialization Antenna Location"),
    DID_COMMS_RADIO_INITIALIZATION_ANTENNA_PATTERN_TYPE(63105, "Communications - Radio Initialization Antenna Pattern Type"),
    DID_COMMS_RADIO_INITIALIZATION_ANTENNA_PATTERN_LENGTH(63106, "Communications - Radio Initialization Antenna Pattern Length"),
    DID_COMMS_RADIO_INITIALIZATION_BEAM_DEFINITION(63107, "Communications - Radio Initialization Beam Definition"),
    DID_COMMS_RADIO_INITIALIZATION_TRANSMIT_HEARTBEAT_TIME(63108, "Communications - Radio Initialization Transmit Heartbeat Time"),
    DID_COMMS_RADIO_INITIALIZATION_TRANSMIT_DISTANCE_THRESHOLD(63109, "Communications - Radio Initialization Transmit Distance Threshold "),
    DID_COMMS_RADIO_CHANNEL_INITIALIZATION_LOCKOUT_ID(63110, "Communications - Radio Channel Initialization Lockout ID"),
    DID_COMMS_RADIO_CHANNEL_INITIALIZATION_HOPSET_ID(63111, "Communications - Radio Channel Initialization Hopset ID"),
    DID_COMMS_RADIO_CHANNEL_INITIALIZATION_PRESET_FREQUENCY(63112, "Communications - Radio Channel Initialization Preset Frequency"),
    DID_COMMS_RADIO_CHANNEL_INITIALIZATION_FREQUENCY_SYNC_TIME(63113, "Communications - Radio Channel Initialization Frequency Sync Time "),
    DID_COMMS_RADIO_CHANNEL_INITIALIZATION_COMSEC_KEY(63114, "Communications - Radio Channel Initialization Comsec Key"),
    DID_COMMS_RADIO_CHANNEL_INITIALIZATION_ALPHA(63115, "Communications - Radio Channel Initialization Alpha"),
    DID_COMMS_RADIO_SC_NET_INITIALIZATION_ID(63200, "Communications - Radio Sc Net Initialization ID "),
    DID_COMMS_RADIO_FH_NET_INITIALIZATION_ID(63202, "Communications - Radio Fh Net Initialization ID "),
    DID_COMMS_RADIO_NET_DELETION_ID(63204, "Communications - Radio Net Deletion ID "),
    DID_COMMS_RADIO_SYSTEM_INITIALIZATION_ID(63206, "Communications - Radio System Initialization ID "),
    DID_COMMS_RADIO_INITIALIZATION_ID(63208, "Communications - Radio Initialization ID "),
    DID_COMMS_RADIO_CHANNEL_INITIALIZATION_ID(63210, "Communications - Radio Channel Initialization ID "),
    DID_COMMS_RADIO_CHANNEL_COMSEC_INITIALIZATION_ID(63212, "Communications - Radio Channel Comsec Initialization ID "),
    DID_COMMS_RESPONSE_RECORD_ID(63250, "Communications - Response Record ID "),
    DID_COMMS_BISEPS_RECORD_ID(63260, "Communications - Biseps Record ID "),
    DID_ENVIRONMENT_PROCESS_GEOMETRY_BOUNDING_SPHERE(65536, "EP Geometry - Bounding Sphere Record"),
    DID_ALGORITHM_PARMS_AGGR(70000, "Algorithm Parameters (Aggregate)"),
    DID_DRA_AGGR(71000, "Dead Reckoning Algorithm (DRA) (Aggregate)"),
    DID_DRA_LOCATION_THRESHOLD(71100, "Dead Reckoning Algorithm (DRA) - DRA Location Threshold"),
    DID_DRA_ORIENT_THRESHOLD(71200, "Dead Reckoning Algorithm (DRA) - DRA Orientation Threshold"),
    DID_DRA_TIME_THRESHOLD(71300, "Dead Reckoning Algorithm (DRA) - DRA Time Threshold"),
    DID_FBCB2_TIME_THRESHOLD_ID_FBCB2_TIME_THRESHOLD_ID(71400, "FBCB2 Time Threshold ID - FBCB2 Time Threshold ID"),
    DID_FBCB2_MOTION_THRESHOLD_ID_FBCB2_MOTION_THRESHOLD_ID(71500, "FBCB2 Motion Threshold ID - FBCB2 Motion Threshold ID"),
    DID_SIMULATION_MANAGEMENT_PARMS(72000, "Simulation Management Parameters"),
    DID_CHECKPOINT_INTERVAL(72100, "Checkpoint Interval"),
    DID_TRANS_TIME_THRESHOLD(72600, "Transmitter Time Threshold"),
    DID_RECEIVER_TIME_THRESHOLD(72700, "Receiver Time Threshold"),
    DID_INTEROPERABILITY_MODE(73000, "Interoperability Mode"),
    DID_SIMNET_DATA_COLLECTION(74000, "SIMNET Data Collection"),
    DID_EVENT_ID(75000, "Event ID"),
    DID_SOURCE_SITE_ID(75100, "Source Site ID"),
    DID_SOURCE_HOST_ID(75200, "Source Host ID"),
    DID_EMULATION_STATUS_ID(76000, "Emulation Status ID"),
    DID_EVENT_REPORT_RECORD_ID(77000, "Event Report Record ID"),
    DID_SLAVED_VIEWPORT_GENERAL_ID(78100, "Slaved Viewport General ID"),
    DID_SLAVED_EYEPOINT_ID(78200, "Slaved Eyepoint ID"),
    DID_SLAVED_GAS_SYMBOLOGY(78201, "Slaved Gas Symbology"),
    DID_SLAVED_GUNNER_SYMBOLOGY(78202, "Slaved Gunner Symbology"),
    DID_SLAVED_CITV_SYMBOLOGY(78203, "Slaved CITV Symbology"),
    DID_SLAVED_BUS_SYMBOLOGY(78204, "Slaved Bus Symbology"),
    DID_SLAVED_ISU_SYMBOLOGY(78205, "Slaved ISU Symbology"),
    DID_SLAVED_TELESCOPE_SYMBOLOGY(78206, "Slaved Telescope Symbology"),
    DID_SLAVED_CIV_IBAS_SYMBOLOGY(78207, "Slaved Civ Ibas Symbology"),
    DID_SLAVED_DVO_SYMBOLOGY(78208, "Slaved Dvo Symbology"),
    DID_SLAVED_LASER_RANGE_FINDER_ID(78220, "Slaved Laser Range Finder ID"),
    DID_SLAVED_VIEWPORT_DATA_ID(78300, "Slaved Viewport Data ID"),
    DID_SLAVED_SYMBOLOGY_ID(78400, "Slaved Symbology ID"),
    DID_AAR_MODE_ID(78410, "AAR Mode ID"),
    DID_AAR_RECORD_READY_ID(78420, "AAR Record Ready ID"),
    DID_AAR_REMAINING_MEDIA_TIME_ID(78430, "AAR Remaining Media Time ID"),
    DID_AAR_VOICE_CHANNEL_ID(78440, "AAR Voice Channel ID"),
    DID_AAR_RECORDING_INIT_ID(78450, "AAR Recording Init ID"),
    DID_SELF_TEST_STATUS_RECORD_ID(78500, "Self Test Status Record ID"),
    DID_CHECKPOINT_DATA_RECORD_ID(78600, "Checkpoint Data Record ID"),
    DID_CHECKPOINT_RESET_TIME_RECORD_ID(78700, "Checkpoint Reset Time Record ID"),
    DID_OPERATIONS_CENTER_FLAGS_RECORD_ID(78800, "Operations Center Flags Record ID"),
    DID_OPERATIONS_CENTER_RADIO_STATUS_ID(78820, "Operations Center Radio Status ID"),
    DID_PORT_ADDRESS_RECORD_ID(78920, "Port Address Record ID"),
    DID_SEND_OBJECT_STATE_DATA_RECORD_ID(79000, "Send Object State Data Record ID"),
    DID_SAF_BOSS_INDICATOR_ID(79100, "Saf Boss Indicator ID"),
    DID_NUMBER_OF_CGF_SIMULATORS_ID(79200, "Number Of CGF Simulators ID"),
    DID_BLUFOR_SIM_LOAD_ID(79300, "Blufor Sim Load ID"),
    DID_OPFOR_SIM_LOAD_ID(79400, "Opfor Sim Load ID"),
    DID_SAF_EXERCISE_FILENAME_ID(79500, "Saf Exercise Filename ID"),
    DID_VISUAL_OBJECT_UPDATE_REQUEST(80000, "Visual Object Update Request"),
    DID_VISUAL_OBJECT_STATE_REQUEST(80001, "Visual Object State Request"),
    DID_ART_PARTS_AGGR(90000, "Articulated Parts (Aggregate)"),
    DID_ART_PARTS_PART_ID(90050, "Articulated Parts - Part ID"),
    DID_ART_PARTS_INDEX(90070, "Articulated Parts - Index"),
    DID_ART_PARTS_POSITION(90100, "Articulated Parts - Position"),
    DID_ART_PARTS_POSITION_RATE(90200, "Articulated Parts - Position Rate"),
    DID_ART_PARTS_EXTENSION(90300, "Articulated Parts - Extension"),
    DID_ART_PARTS_EXTENSION_EXTENSION_RATE(90400, "Articulated Parts - Extension - Extension Rate"),
    DID_ART_PARTS_EXTENSION_X(90500, "Articulated Parts - Extension - X"),
    DID_ART_PARTS_EXTENSION_X_RATE(90600, "Articulated Parts - Extension - X-rate"),
    DID_ART_PARTS_EXTENSION_Y(90700, "Articulated Parts - Extension - Y"),
    DID_ART_PARTS_EXTENSION_Y_RATE(90800, "Articulated Parts - Extension - Y-rate"),
    DID_ART_PARTS_EXTENSION_Z(90900, "Articulated Parts - Extension - Z"),
    DID_ART_PARTS_EXTENSION_Z_RATE(91000, "Articulated Parts - Extension - Z-rate"),
    DID_ART_PARTS_AZIMUTH(91100, "Articulated Parts - Azimuth"),
    DID_ART_PARTS_AZIMUTH_RATE(91200, "Articulated Parts - Azimuth Rate"),
    DID_ART_PARTS_ELEVATION(91300, "Articulated Parts - Elevation"),
    DID_ART_PARTS_ELEVATION_RATE(91400, "Articulated Parts - Elevation Rate"),
    DID_ART_PARTS_ROTATION(91500, "Articulated Parts - Rotation"),
    DID_ART_PARTS_ROTATION_RATE(91600, "Articulated Parts - Rotation Rate"),
    DID_DRA_ANGULAR_X_VEL(100001, "DRA Angular X-Velocity"),
    DID_DRA_ANGULAR_Y_VEL(100002, "DRA Angular Y-Velocity"),
    DID_DRA_ANGULAR_Z_VEL(100003, "DRA Angular Z-Velocity"),
    DID_APPEARANCE_TRAILING_EFFECTS(100004, "Appearance - Trailing Effects"),
    DID_APPEARANCE_HATCH(100005, "Appearance - Hatch"),
    DID_APPEARANCE_CHARACTER_SET(100008, "Appearance - Character Set"),
    DID_CAPABILITY_AMMO_SUPPLIER(100010, "Capability - Ammunition Supplier"),
    DID_CAPABILITY_MISCELLANEOUS_SUPPLIER(100011, "Capability - Miscellaneous Supplier"),
    DID_CAPABILITY_REPAIR_PROVIDER(100012, "Capability - Repair Provider"),
    DID_ART_PARAMETER(100014, "Articulation Parameter"),
    DID_ART_PARAMETER_TYPE(100047, "Articulation Parameter Type"),
    DID_ART_PARAMETER_VALUE(100048, "Articulation Parameter Value"),
    DID_TIME_OF_DAY_SCENE(100058, "Time of Day - Scene"),
    DID_LAT_NORTH(100061, "Latitude-North (Location of weather cell)"),
    DID_LONG_EAST(100063, "Longitude-East (Location of weather cell)"),
    DID_TACTICAL_DRIVER_STATUS(100068, "Tactical Driver Status"),
    DID_SONAR_SYSTEM_STATUS(100100, "Sonar System Status"),
    DID_ACCOMPLISHED_ACCEPT(100160, "Accomplished Accept"),
    DID_UPPER_LAT(100161, "Upper latitude"),
    DID_LAT_SOUTH(100162, "Latitude-South (Location of weather cell)"),
    DID_WESTERN_LONG(100163, "Western longitude"),
    DID_LONG_WEST(100164, "Longitude-West (location of weather cell)"),
    DID_CD_ROM_NUMBER_DISK_ID_FOR_TERRAIN(100165, "CD ROM Number (Disk ID for terrain)"),
    DID_DTED_DISK_ID(100166, "DTED Disk ID"),
    DID_TACTICAL_SYSTEM_STATUS(100169, "Tactical System Status"),
    DID_JTIDS_STATUS(100170, "JTIDS Status"),
    DID_TADIL_J_STATUS(100171, "TADIL-J Status"),
    DID_DSDD_STATUS(100172, "DSDD Status"),
    DID_WEAPON_SYSTEM_STATUS(100200, "Weapon System Status"),
    DID_SUBSYSTEM_STATUS(100205, "Subsystem status"),
    DID_NUMBER_OF_INTERCEPTORS_FIRED(100206, "Number of interceptors fired"),
    DID_NUMBER_OF_INTERCEPTOR_DETONATIONS(100207, "Number of interceptor detonations"),
    DID_NUMBER_OF_MSG_BUFFERS_DROPPED(100208, "Number of message buffers dropped"),
    DID_SATELLITE_SENSOR_BACKGROUND_YEAR_DAY(100213, "Satellite sensor background (year - day)"),
    DID_SATELLITE_SENSOR_BACKGROUND_HOUR_MINUTE(100214, "Satellite sensor background (hour - minute)"),
    DID_SCRIPT_NUMBER(100218, "Script Number"),
    DID_ENTITY_TRACK_UPDATE_DATA(100300, "Entity/Track/Update Data"),
    DID_LOCAL_FORCE_TRAINING(100400, "Local/Force Training"),
    DID_ENTITY_TRACK_IDENTITY_DATA_AGGR(100500, "Entity/Track Identity Data (Aggregate)"),
    DID_ENTITY_FOR_TRACK_EVENT(100510, "Entity for Track Event"),
    DID_IFF_FRIEND_FOE_STATUS(100520, "IFF (Friend-Foe) status"),
    DID_ENGAGE_DATA(100600, "Engagement Data"),
    DID_ENGAGE_DATA_TARGET_LAT(100610, "Engagement Data - Target Latitude"),
    DID_ENGAGE_DATA_TARGET_LONG(100620, "Engagement Data - Target Longitude"),
    DID_ENGAGE_DATA_AOI_GROUND_IMPACT_CIRCLE_CENTER_LAT(100631, "Engagement Data - AOI (Ground Impact Circle) Center Latitude"),
    DID_ENGAGE_DATA_AOI_GROUND_IMPACT_CIRCLE_CENTER_LONG(100632, "Engagement Data - AOI (Ground Impact Circle) Center Longitude"),
    DID_ENGAGE_DATA_AOI_GROUND_IMPACT_CIRCLE_RADIUS(100633, "Engagement Data - AOI (Ground Impact Circle) Radius"),
    DID_ENGAGE_DATA_AOI_TYPE(100634, "Engagement Data - AOI Type"),
    DID_ENGAGE_DATA_TARGET_AGGR_ID(100640, "Engagement Data - Target Aggregate ID"),
    DID_ENGAGE_DATA_GIC_IDENTIFICATION_NUMBER(100650, "Engagement Data - GIC Identification Number"),
    DID_ENGAGE_DATA_EST_TIME_OF_FLIGHT_TO_TBM_IMPACT(100660, "Engagement Data - Estimated Time of Flight to TBM Impact"),
    DID_ENGAGE_DATA_EST_INTERCEPT_TIME(100661, "Engagement Data - Estimated Intercept Time"),
    DID_ENGAGE_DATA_EST_TIME_OF_FLIGHT_TO_NEXT_WAYPOINT(100662, "Engagement Data - Estimated Time of Flight to Next Waypoint"),
    DID_ENTITY_TRACK_EQUIPMENT_DATA(100700, "Entity/Track Equipment Data"),
    DID_EMISSION_EW_DATA(100800, "Emission/EW Data"),
    DID_APPEARANCE_DATA_AGGR(100900, "Appearance Data (Aggregate)"),
    DID_COMMAND_ORDER_DATA_AGGR(101000, "Command/Order Data (Aggregate)"),
    DID_ENVIRAL_DATA(101100, "Environmental Data"),
    DID_SIGNIFICANT_EVENT_DATA(101200, "Significant Event Data"),
    DID_OP_ACTION_DATA(101300, "Operator Action Data"),
    DID_OP_ACTION_DATA_ADA_ENGAGE_MODE(101310, "Operator Action Data - ADA Engagement Mode"),
    DID_OP_ACTION_DATA_ADA_SHOOTING_STATUS(101320, "Operator Action Data - ADA Shooting Status"),
    DID_OP_ACTION_DATA_ADA_MODE(101321, "Operator Action Data - ADA Mode"),
    DID_OP_ACTION_DATA_ADA_RADAR_STATUS(101330, "Operator Action Data - ADA Radar Status"),
    DID_OP_ACTION_DATA_SHOOT_COMMAND(101340, "Operator Action Data - Shoot Command"),
    DID_OP_ACTION_DATA_ADA_WEAPON_STATUS(101350, "Operator Action Data - ADA Weapon Status"),
    DID_OP_ACTION_DATA_ADA_FIRING_DISCIPLE(101360, "Operator Action Data - ADA Firing Disciple"),
    DID_OP_ACTION_DATA_ORDER_STATUS(101370, "Operator Action Data - Order Status"),
    DID_TIME_SYNCHRONIZATION(101400, "Time Synchronization"),
    DID_TOMAHAWK_DATA(101500, "Tomahawk Data"),
    DID_NUMBER_OF_DETONATIONS(102100, "Number of Detonations"),
    DID_NUMBER_OF_INTERCEPTS(102200, "Number of Intercepts"),
    DID_VEHICLE_DRIVER_STATUS_ID(109993, "Vehicle Driver Status ID "),
    DID_VEHICLE_COMMANDER_STATUS_ID(109994, "Vehicle Commander Status ID "),
    DID_VEHICLE_LOADER_STATUS_ID(109995, "Vehicle Loader Status ID "),
    DID_VEHICLE_GUNNER_STATUS_ID(109996, "Vehicle Gunner Status ID "),
    DID_SIMULATION_DATE_ID(109997, "Simulation Date ID "),
    DID_SIMULATION_TIME_OF_DAY_ID(109998, "Simulation Time Of Day ID "),
    DID_RAIN_LEVEL_ID(109999, "Rain Level ID "),
    DID_SAF_LOAD_CONFIG_ID(120000, "Saf Load Config ID "),
    DID_ENDSCRIPT_ID(120001, "Endscript ID "),
    DID_FBCB2_AUTO_DETECT_ID(120002, "FBCB2 Auto Detect ID "),
    DID_ENDGAME_ID(120003, "Endgame ID "),
    DID_COMPUTATION_LEVEL_ID(120004, "Computation Level ID "),
    DID_OBT_CONTROL_M_1(200201, "OBT Control (M) 1"),
    DID_SENSOR_DATA_M_1(200202, "Sensor Data (M) 1"),
    DID_ENVIRAL_DATA_M_1(200203, "Environmental Data (M) 1"),
    DID_OWNSHIP_DATA_M_1(200204, "Ownship Data (M) 1"),
    DID_ACOUSTIC_CONTACT_DATA_M_1(200205, "Acoustic Contact Data (M) 1"),
    DID_SONOBUOY_DATA_M_1(200207, "Sonobuoy Data (M) 1"),
    DID_SONOBUOY_CONTACT_DATA_M_1(200210, "Sonobuoy Contact Data (M) 1"),
    DID_HELO_CONTROL_M(200211, "Helo Control (M)"),
    DID_ESM_CONTROL_DATA(200213, "ESM Control Data"),
    DID_ESM_CONTACT_DATA_M_1(200214, "ESM Contact Data (M) 1"),
    DID_ESM_EMITTER_DATA_M_1(200215, "ESM Emitter Data (M) 1"),
    DID_WEAPON_DEFINITION_DATA_M_1(200216, "Weapon Definition Data (M) 1"),
    DID_WEAPON_PRESET_DATA_M_1(200217, "Weapon Preset Data (M) 1"),
    DID_OBT_CONTROL_M_2(200301, "OBT Control (M) 2"),
    DID_SENSOR_DATA_M_2(200302, "Sensor Data (M) 2"),
    DID_ENVIRAL_DATA_M_2(200303, "Environmental Data (M) 2"),
    DID_OWNSHIP_DATA_M_2(200304, "Ownship Data (M) 2"),
    DID_ACOUSTIC_CONTACT_DATA_M_2(200305, "Acoustic Contact Data (M) 2"),
    DID_SONOBUOY_DATA_M_2(200307, "Sonobuoy Data (M) 2"),
    DID_SONOBUOY_CONTACT_DATA_M_2(200310, "Sonobuoy Contact Data (M) 2"),
    DID_HELO_SCENARIO_EQUIPMENT_STATUS(200311, "Helo Scenario / Equipment Status"),
    DID_ESM_CONTROL_DATA_M(200313, "ESM Control Data (M)"),
    DID_ESM_CONTACT_DATA_M_2(200314, "ESM Contact Data (M) 2"),
    DID_ESM_EMITTER_DATA_M_2(200315, "ESM Emitter Data (M) 2"),
    DID_WEAPON_DEFINITION_DATA_M_2(200316, "Weapon Definition Data (M) 2"),
    DID_WEAPON_PRESET_DATA_M_2(200317, "Weapon Preset Data (M) 2"),
    DID_PAIRING_ASSOCIATION_EM(200400, "Pairing/Association (eM)"),
    DID_POINTER_EM(200401, "Pointer (eM)"),
    DID_REPORTING_RESPONSIBILITY_EM(200402, "Reporting Responsibility (eM)"),
    DID_TRACK_NUMBER_EM(200403, "Track Number (eM)"),
    DID_ID_FOR_LINK_11_REPORTING_EM(200404, "ID for Link-11 Reporting (eM)"),
    DID_REMOTE_TRACK_EM(200405, "Remote Track (eM)"),
    DID_LINK_11_ERROR_RATE_EM(200406, "Link-11 Error Rate (eM)"),
    DID_TRACK_QUALITY_EM(200407, "Track Quality (eM)"),
    DID_GRIDLOCK_EM(200408, "Gridlock (eM)"),
    DID_KILL_EM(200409, "Kill (eM)"),
    DID_TRACK_ID_CHANGE_RESOLUTION_EM(200410, "Track ID Change / Resolution (eM)"),
    DID_WEAPONS_STATUS_EM(200411, "Weapons Status (eM)"),
    DID_LINK_11_OP_EM(200412, "Link-11 Operator (eM)"),
    DID_FORCE_TRAINING_TRANSMIT_EM(200413, "Force Training Transmit (eM)"),
    DID_FORCE_TRAINING_RECEIVE_EM(200414, "Force Training Receive (eM)"),
    DID_INTERCEPTOR_AMPLIFICATION_EM(200415, "Interceptor Amplification (eM)"),
    DID_CONSUMABLES_EM(200416, "Consumables (eM)"),
    DID_LINK_11_LOCAL_TRACK_QUALITY_EM(200417, "Link-11 Local Track Quality (eM)"),
    DID_DLRP_EM(200418, "DLRP (eM)"),
    DID_FORCE_ORDER_EM(200419, "Force Order (eM)"),
    DID_WILCO_CANTCO_EM(200420, "Wilco / Cantco (eM)"),
    DID_EMC_BEARING_EM(200421, "EMC Bearing (eM)"),
    DID_CHANGE_TRACK_ELIGIBILITY_EM(200422, "Change Track Eligibility (eM)"),
    DID_LAND_MASS_REFERENCE_POINT(200423, "Land Mass Reference Point"),
    DID_SYSTEM_REFERENCE_POINT(200424, "System Reference Point"),
    DID_PU_AMPLIFICATION(200425, "PU Amplification"),
    DID_SET_DRIFT(200426, "Set/Drift"),
    DID_BEGIN_INITIALIZATION_M(200427, "Begin Initialization (M)"),
    DID_STATUS_AND_CONTROL_M(200428, "Status and Control (M)"),
    DID_SCINTILLATION_CHANGE_M(200429, "Scintillation Change (M)"),
    DID_LINK_11_ID_CONTROL_M(200430, "Link 11 ID Control (M)"),
    DID_PU_GUARD_LIST(200431, "PU Guard List"),
    DID_WINDS_ALOFT_M(200432, "Winds Aloft (M)"),
    DID_SURFACE_WINDS_M(200433, "Surface Winds (M)"),
    DID_SEA_STATE_M(200434, "Sea State (M)"),
    DID_MAGNETIC_VARIATION_M(200435, "Magnetic Variation (M)"),
    DID_TRACK_ELIGIBILITY_M(200436, "Track Eligibility (M)"),
    DID_TRAINING_TRACK_NOTIFICATION(200437, "Training Track Notification"),
    DID_TACAN_DATA_M(200501, "Tacan Data (M)"),
    DID_INTERCEPTOR_AMPLIFICATION_M(200502, "Interceptor Amplification (M)"),
    DID_TACAN_ASSIGNMENT_M(200503, "Tacan Assignment (M)"),
    DID_AUTOPILOT_STATUS_M(200504, "Autopilot Status (M)"),
    DID_CONSUMABLES_M(200505, "Consumables (M)"),
    DID_DOWNLINK_M(200506, "Downlink (M)"),
    DID_TIN_REPORT_M(200507, "TIN Report (M)"),
    DID_SPECIAL_POINT_CONTROL_M(200508, "Special Point Control (M)"),
    DID_CONTROL_DISCRETES_M(200509, "Control Discretes (M)"),
    DID_REQUEST_TARGET_DISCRETES_M(200510, "Request Target Discretes (M)"),
    DID_TARGET_DISCRETES_M(200511, "Target Discretes (M)"),
    DID_REPLY_DISCRETES_M(200512, "Reply Discretes (M)"),
    DID_COMMAND_MANEUVERS_M(200513, "Command Maneuvers (M)"),
    DID_TARGET_DATA_M(200514, "Target Data (M)"),
    DID_TARGET_POINTER_M(200515, "Target Pointer (M)"),
    DID_INTERCEPT_DATA_M(200516, "Intercept Data (M)"),
    DID_DECREMENT_MISSILE_INVENTORY_M(200517, "Decrement Missile Inventory (M)"),
    DID_LINK_4A_ALERT_M(200518, "Link-4A Alert (M)"),
    DID_STRIKE_CONTROL_M(200519, "Strike Control (M)"),
    DID_SPEED_CHANGE_M(200521, "Speed Change (M)"),
    DID_COURSE_CHANGE_M(200522, "Course Change (M)"),
    DID_ALTITUDE_CHANGE_M(200523, "Altitude Change (M)"),
    DID_ACLS_AN_SPN_46_STATUS(200524, "ACLS AN/SPN-46 Status"),
    DID_ACLS_AIRCRAFT_REPORT(200525, "ACLS Aircraft Report"),
    DID_SPS_67_RADAR_OP_FUNCTIONS(200600, "SPS-67 Radar Operator Functions"),
    DID_SPS_55_RADAR_OP_FUNCTIONS(200601, "SPS-55 Radar Operator Functions"),
    DID_SPQ_9A_RADAR_OP_FUNCTIONS(200602, "SPQ-9A Radar Operator Functions "),
    DID_SPS_49_RADAR_OP_FUNCTIONS(200603, "SPS-49 Radar Operator Functions"),
    DID_MK_23_RADAR_OP_FUNCTIONS(200604, "MK-23 Radar Operator Functions"),
    DID_SPS_48_RADAR_OP_FUNCTIONS(200605, "SPS-48 Radar Operator Functions"),
    DID_SPS_40_RADAR_OP_FUNCTIONS(200606, "SPS-40 Radar Operator Functions"),
    DID_MK_95_RADAR_OP_FUNCTIONS(200607, "MK-95 Radar Operator Functions"),
    DID_KILL_NO_KILL(200608, "Kill/No Kill"),
    DID_CMT_PC(200609, "CMT pc"),
    DID_CMC4_AIR_GLOBAL_DATA(200610, "CMC4 Air Global Data"),
    DID_CMC4_GLOBAL_DATA(200611, "CMC4 Global Data"),
    DID_LINKSIM_COMMENT_PDU(200612, "LINKSIM COMMENT PDU"),
    DID_NSST_OWNSHIP_CONTROL(200613, "NSST Ownship Control"),
    DID_OTHER(240000, "Other"),
    DID_OTHER_MASS_OF_THE_VEHICLE(240001, "Other - Mass Of The Vehicle"),
    DID_OTHER_ENTITY_LOCATION_X(240017, "Other - Entity Location X"),
    DID_OTHER_ENTITY_LOCATION_Y(240018, "Other - Entity Location Y"),
    DID_OTHER_ENTITY_LOCATION_Z(240019, "Other - Entity Location Z"),
    DID_OTHER_ENTITY_LINEAR_VEL_X(240020, "Other - Entity Linear Velocity X"),
    DID_OTHER_ENTITY_LINEAR_VEL_Y(240021, "Other - Entity Linear Velocity Y"),
    DID_OTHER_ENTITY_LINEAR_VEL_Z(240022, "Other - Entity Linear Velocity Z"),
    DID_OTHER_ENTITY_ORIENT_PSI(240023, "Other - Entity Orientation Psi"),
    DID_OTHER_ENTITY_ORIENT_THETA(240024, "Other - Entity Orientation Theta"),
    DID_OTHER_ENTITY_ORIENT_PHI(240025, "Other - Entity Orientation Phi"),
    DID_OTHER_DR_LINEAR_ACCEL_X(240027, "Other - Dead Reckoning Linear Acceleration X"),
    DID_OTHER_DR_LINEAR_ACCEL_Y(240028, "Other - Dead Reckoning Linear Acceleration Y"),
    DID_OTHER_DR_LINEAR_ACCEL_Z(240029, "Other - Dead Reckoning Linear Acceleration Z"),
    DID_OTHER_ENTITY_APPEARANCE(240033, "Other - Entity Appearance"),
    DID_OTHER_CAPABILITY(240036, "Other - Capability"),
    DID_OTHER_NUMBER_ART_PARMS(240037, "Other - Number Articulation Parameters"),
    DID_OTHER_TYPE_OF_STORES(240041, "Other - Type Of Stores"),
    DID_OTHER_QTY_OF_STORES(240042, "Other - Quantity Of Stores"),
    DID_OTHER_RADAR_SYSTEM_STATUS(240044, "Other - Radar System Status"),
    DID_OTHER_RADIO_COMM_SYSTEM_STATUS(240045, "Other - Radio Communication System Status"),
    DID_OTHER_DEFAULT_TIME_STATIONARY_TRANS(240046, "Other - Default Time For Radio Transmission For Stationary Transmitters"),
    DID_OTHER_DEFAULT_TIME_MOVING_TRANS(240047, "Other - Default Time For Radio Transmission For Moving Transmitters"),
    DID_OTHER_BODY_PART_DAMAGED_RATIO(240048, "Other - Body Part Damaged Ratio"),
    DID_OTHER_NAME_OF_THE_TERRAIN_DATABASE_FILE(240049, "Other - Name Of The Terrain Database File"),
    DID_OTHER_NAME_OF_LOCAL_FILE(240050, "Other - Name Of Local File"),
    DID_OTHER_AIMPOINT_BEARING(240051, "Other - Aimpoint Bearing"),
    DID_OTHER_AIMPOINT_ELEVATION(240052, "Other - Aimpoint Elevation"),
    DID_OTHER_AIMPOINT_RANGE(240053, "Other - Aimpoint Range"),
    DID_OTHER_AIR_SPEED(240054, "Other - Air Speed"),
    DID_OTHER_ALTITUDE(240055, "Other - Altitude"),
    DID_OTHER_APPLICATION_STATUS(240056, "Other - Application Status"),
    DID_OTHER_AUTO_IFF(240057, "Other - Auto Iff"),
    DID_OTHER_BEACON_DELAY(240058, "Other - Beacon Delay"),
    DID_OTHER_BINGO_FUEL_SETTING(240059, "Other - Bingo Fuel Setting"),
    DID_OTHER_DIRECTION(240062, "Other - Direction"),
    DID_OTHER_END_ACTION(240063, "Other - End Action"),
    DID_OTHER_FREQUENCY(240064, "Other - Frequency"),
    DID_OTHER_FREEZE(240065, "Other - Freeze"),
    DID_OTHER_HEADING(240066, "Other - Heading"),
    DID_OTHER_IDENTIFICATION(240067, "Other - Identification"),
    DID_OTHER_INITIAL_POINT_DATA(240068, "Other - Initial Point Data"),
    DID_OTHER_LAT(240069, "Other - Latitude"),
    DID_OTHER_LIGHTS(240070, "Other - Lights"),
    DID_OTHER_LINEAR(240071, "Other - Linear"),
    DID_OTHER_LONG(240072, "Other - Longitude"),
    DID_OTHER_LOW_ALTITUDE(240073, "Other - Low Altitude"),
    DID_OTHER_MFD_FORMATS(240074, "Other - Mfd Formats"),
    DID_OTHER_NCTR(240075, "Other - Nctr"),
    DID_OTHER_NUMBER_PROJECTILES(240076, "Other - Number Projectiles"),
    DID_OTHER_OPERATION_CODE(240077, "Other - Operation Code"),
    DID_OTHER_PITCH(240078, "Other - Pitch"),
    DID_OTHER_PROFILES(240079, "Other - Profiles"),
    DID_OTHER_QTY(240080, "Other - Quantity"),
    DID_OTHER_RADAR_MODES(240081, "Other - Radar Modes"),
    DID_OTHER_RADAR_SEARCH_VOLUME(240082, "Other - Radar Search Volume"),
    DID_OTHER_ROLL(240083, "Other - Roll"),
    DID_OTHER_ROTATION(240084, "Other - Rotation"),
    DID_OTHER_SCALE_FACTOR_X(240085, "Other - Scale Factor X"),
    DID_OTHER_SCALE_FACTOR_Y(240086, "Other - Scale Factor Y"),
    DID_OTHER_SHIELDS(240087, "Other - Shields"),
    DID_OTHER_STEERPOINT(240088, "Other - Steerpoint"),
    DID_OTHER_SPARE1(240089, "Other - Spare1"),
    DID_OTHER_SPARE2(240090, "Other - Spare2"),
    DID_OTHER_TEAM(240091, "Other - Team"),
    DID_OTHER_TEXT(240092, "Other - Text"),
    DID_OTHER_TIME_OF_DAY(240093, "Other - Time Of Day"),
    DID_OTHER_TRAIL_FLAG(240094, "Other - Trail Flag"),
    DID_OTHER_TRAIL_SIZE(240095, "Other - Trail Size"),
    DID_OTHER_TYPE_OF_PROJECTILE(240096, "Other - Type Of Projectile"),
    DID_OTHER_TYPE_OF_TARGET(240097, "Other - Type Of Target"),
    DID_OTHER_TYPE_OF_THREAT(240098, "Other - Type Of Threat"),
    DID_OTHER_UHF_FREQUENCY(240099, "Other - Uhf Frequency"),
    DID_OTHER_UTM_ALTITUDE(240100, "Other - Utm Altitude"),
    DID_OTHER_UTM_LAT(240101, "Other - Utm Latitude"),
    DID_OTHER_UTM_LONG(240102, "Other - Utm Longitude"),
    DID_OTHER_VHF_FREQUENCY(240103, "Other - Vhf Frequency"),
    DID_OTHER_VISIBILITY_RANGE(240104, "Other - Visibility Range"),
    DID_OTHER_VOID_AAA_HIT(240105, "Other - Void Aaa Hit"),
    DID_OTHER_VOID_COLLISION(240106, "Other - Void Collision"),
    DID_OTHER_VOID_EARTH_HIT(240107, "Other - Void Earth Hit"),
    DID_OTHER_VOID_FRIENDLY(240108, "Other - Void Friendly"),
    DID_OTHER_VOID_GUN_HIT(240109, "Other - Void Gun Hit"),
    DID_OTHER_VOID_ROCKET_HIT(240110, "Other - Void Rocket Hit"),
    DID_OTHER_VOID_SAM_HIT(240111, "Other - Void Sam Hit"),
    DID_OTHER_WEAPON_DATA(240112, "Other - Weapon Data"),
    DID_OTHER_WEAPON_TYPE(240113, "Other - Weapon Type"),
    DID_OTHER_WEATHER(240114, "Other - Weather"),
    DID_OTHER_WING_STATION(240117, "Other - Wing Station"),
    DID_OTHER_YAW(240118, "Other - Yaw"),
    DID_OTHER_MEMORY_OFFSET(240119, "Other - Memory Offset"),
    DID_OTHER_MEMORY_DATA(240120, "Other - Memory Data"),
    DID_OTHER_VASI(240121, "Other - VASI"),
    DID_OTHER_BEACON(240122, "Other - Beacon"),
    DID_OTHER_STROBE(240123, "Other - Strobe"),
    DID_OTHER_CULTURE(240124, "Other - Culture"),
    DID_OTHER_APPROACH(240125, "Other - Approach"),
    DID_OTHER_RUNWAY_END(240126, "Other - Runway End"),
    DID_OTHER_OBSTRUCTION(240127, "Other - Obstruction"),
    DID_OTHER_RUNWAY_EDGE(240128, "Other - Runway Edge"),
    DID_OTHER_RAMP_TAXIWAY(240129, "Other - Ramp Taxiway"),
    DID_OTHER_LASER_BOMB_CODE(240130, "Other - Laser Bomb Code"),
    DID_OTHER_RACK_TYPE(240131, "Other - Rack Type"),
    DID_OTHER_HUD(240132, "Other - HUD"),
    DID_OTHER_ROLEFILENAME(240133, "Other - RoleFileName"),
    DID_OTHER_PILOTNAME(240134, "Other - PilotName"),
    DID_OTHER_PILOTDESIGNATION(240135, "Other - PilotDesignation"),
    DID_OTHER_MODEL_TYPE(240136, "Other - Model Type"),
    DID_OTHER_DIS_TYPE(240137, "Other - DIS Type"),
    DID_OTHER_CLASS(240138, "Other - Class"),
    DID_OTHER_CHANNEL(240139, "Other - Channel"),
    DID_OTHER_ENTITY_TYPE(240140, "Other - Entity Type"),
    DID_OTHER_ALTERNATIVE_ENTITY_TYPE(240141, "Other - Alternative Entity Type"),
    DID_OTHER_ENTITY_LOCATION(240142, "Other - Entity Location"),
    DID_OTHER_ENTITY_LINEAR_VEL(240143, "Other - Entity Linear Velocity"),
    DID_OTHER_ENTITY_ORIENT(240144, "Other - Entity Orientation"),
    DID_OTHER_DR(240145, "Other - Dead Reckoning"),
    DID_OTHER_FAILURE_SYMPTOM(240146, "Other - Failure Symptom"),
    DID_OTHER_MAX_FUEL(240147, "Other - Max Fuel"),
    DID_OTHER_REFUELING_BOOM_CONNECT(240148, "Other - Refueling Boom Connect"),
    DID_OTHER_ALTITUDE_AGL(240149, "Other - Altitude AGL"),
    DID_OTHER_CALIBRATED_AIRSPEED(240150, "Other - Calibrated Airspeed"),
    DID_OTHER_TACAN_CHANNEL(240151, "Other - TACAN Channel"),
    DID_OTHER_TACAN_BAND(240152, "Other - TACAN Band"),
    DID_OTHER_TACAN_MODE(240153, "Other - TACAN Mode"),
    DID_OTHER_GUNNER_CONTROL(240154, "Other - GUNNER CONTROL "),
    DID_OTHER_DRIVER_CONTROL(240155, "Other - DRIVER CONTROL "),
    DID_OTHER_FIRE_DESIGNATOR_CONTROL(240156, "Other - FIRE DESIGNATOR CONTROL "),
    DID_OTHER_STEALTH_SPECTRUM(240160, "Other - Stealth spectrum"),
    DID_OTHER_STEALTH_LOCATION(240161, "Other - Stealth location"),
    DID_OTHER_STEALTH_ORIENT(240162, "Other - Stealth orientation"),
    DID_OTHER_STEALTH_ATTACHMENT_DATA(240163, "Other - Stealth attachment data"),
    DID_OTHER_STEALTH_VEL(240164, "Other - Stealth velocity"),
    DID_OTHER_STEALTH_FIELD_OF_VIEW(240165, "Other - Stealth Field of view"),
    DID_OTHER_STEALTH_EYEPOINT_OFFSET(240166, "Other - Stealth eyepoint offset"),
    DID_OTHER_STEALTH_MAGNIFICATION(240167, "Other - Stealth magnification"),
    DID_OTHER_STEALTH_SENSOR_MODE(240168, "Other - Stealth sensor mode"),
    DID_OTHER_STEALTH_HEIGHT_ABOVE_TERRAIN(240169, "Other - Stealth height above terrain"),
    DID_OTHER_STEALTH_FLY_TO_LOCATION(240170, "Other - Stealth fly to Location"),
    DID_GATEWAY_INFORMATION_REQUEST(250110, "Gateway Control - Gateway Information Request"),
    DID_GATEWAY_SUPPORTED_DIALECTS(250120, "Gateway Control - Gateway Supported Dialects"),
    DID_GATEWAY_DIALECT_INDEX_REPORT(250130, "Gateway Control - Gateway Dialect Index Report"),
    DID_GATEWAY_DESTINATION_INFORMATION(250140, "Gateway Control - Gateway Destination Information"),
    DID_GATEWAY_GENERAL_INFORMATION(250150, "Gateway Control - Gateway General Information"),
    DID_GATEWAY_ENTITY_PROXIMITY_FILTER_INFORMATION(250160, "Gateway Control - Gateway Entity Proximity Filter Information"),
    DID_GATEWAY_ENTITY_PROXIMITY_FILTERS(250161, "Gateway Control - Gateway Entity Proximity Filters"),
    DID_GATEWAY_STATIC_GEOGRAPHIC_FILTER_INFORMATION(250170, "Gateway Control - Gateway Static Geographic Filter Information"),
    DID_GATEWAY_STATIC_GEOGRAPHIC_FILTER_EXTENTS(250171, "Gateway Control - Gateway Static Geographic Filter Extents"),
    DID_GATEWAY_NAMED_STATIC_GEOGRAPHIC_FILTER_EXTENTS(250172, "Gateway Control - Gateway Named Static Geographic Filter Extents"),
    DID_GATEWAY_DYNAMIC_GEOGRAPHIC_FILTER_INFORMATION(250180, "Gateway Control - Gateway Dynamic Geographic Filter Information"),
    DID_GATEWAY_DYNAMIC_GEOGRAPHIC_FILTER_EXTENTS(250181, "Gateway Control - Gateway Dynamic Geographic Filter Extents"),
    DID_WEATHER_STATE_ATMOSPHERIC(260100, "Weather State Atmospheric"),
    DID_WEATHER_STATE_CELESTIAL(260200, "Weather State Celestial"),
    DID_WEATHER_STATE_WIND(260300, "Weather State Wind"),
    DID_WEATHER_STATE_PRECIPITATION(260400, "Weather State Precipitation"),
    DID_WEATHER_STATE_CLOUDS(260500, "Weather State Clouds"),
    DID_WEATHER_STATE_GROUND_FOG(260600, "Weather State Ground Fog"),
    DID_WEATHER_STATE_HAZE(260700, "Weather State Haze"),
    DID_WEATHER_STATE_LIGHTNING(260800, "Weather State Lightning"),
    DID_WEATHER_STATE_THUNDER(260900, "Weather State Thunder"),
    DID_WEATHER_STATE_LAYER(261000, "Weather State Layer"),
    DID_MALF01(300000, "Malf01"),
    DID_MALF01STATE(300001, "Malf01State"),
    DID_MALF02(300002, "Malf02"),
    DID_MALF02STATE(300003, "Malf02State"),
    DID_MALF03(300004, "Malf03"),
    DID_MALF03STATE(300005, "Malf03State"),
    DID_MALF04(300006, "Malf04"),
    DID_MALF04STATE(300007, "Malf04State"),
    DID_MALF05(300008, "Malf05"),
    DID_MALF05STATE(300009, "Malf05State"),
    DID_MALF06(300010, "Malf06"),
    DID_MALF06STATE(300011, "Malf06State"),
    DID_MALF07(300012, "Malf07"),
    DID_MALF07STATE(300013, "Malf07State"),
    DID_MALF08(300014, "Malf08"),
    DID_MALF08STATE(300015, "Malf08State"),
    DID_MALF09(300016, "Malf09"),
    DID_MALF09STATE(300017, "Malf09State"),
    DID_MALF10(300018, "Malf10"),
    DID_MALF10STATE(300019, "Malf10State"),
    DID_MALF11(300020, "Malf11"),
    DID_MALF11STATE(300021, "Malf11State"),
    DID_MALF12(300022, "Malf12"),
    DID_MALF12STATE(300023, "Malf12State"),
    DID_STEALTHRESTART(300027, "StealthRestart"),
    DID_STEALTHSHUTDOWN(300028, "StealthShutdown"),
    DID_STEALTHSTART(300030, "StealthStart"),
    DID_CARGO_TYPE_1(300100, "Cargo Type 1"),
    DID_LOAD_WEIGHT_1(300101, "Load Weight 1"),
    DID_LOAD_MOMENT_1(300102, "Load Moment 1"),
    DID_LOAD_STATUS_1(300103, "Load Status 1"),
    DID_CARGO_TYPE_2(300104, "Cargo Type 2"),
    DID_LOAD_WEIGHT_2(300105, "Load Weight 2"),
    DID_LOAD_MOMENT_2(300106, "Load Moment 2"),
    DID_LOAD_STATUS_2(300107, "Load Status 2"),
    DID_CARGO_TYPE_3(300108, "Cargo Type 3"),
    DID_LOAD_WEIGHT_3(300109, "Load Weight 3"),
    DID_LOAD_MOMENT_3(300110, "Load Moment 3"),
    DID_LOAD_STATUS_3(300111, "Load Status 3"),
    DID_CARGO_TYPE_4(300112, "Cargo Type 4"),
    DID_LOAD_WEIGHT_4(300113, "Load Weight 4"),
    DID_LOAD_MOMENT_4(300114, "Load Moment 4"),
    DID_LOAD_STATUS_4(300115, "Load Status 4"),
    DID_CARGO_TYPE_5(300116, "Cargo Type 5"),
    DID_LOAD_WEIGHT_5(300117, "Load Weight 5"),
    DID_LOAD_MOMENT_5(300118, "Load Moment 5"),
    DID_LOAD_STATUS_5(300119, "Load Status 5"),
    DID_CARGO_TYPE_6(300120, "Cargo Type 6"),
    DID_LOAD_WEIGHT_6(300121, "Load Weight 6"),
    DID_LOAD_MOMENT_6(300122, "Load Moment 6"),
    DID_LOAD_STATUS_6(300123, "Load Status 6"),
    DID_CARGO_TYPE_7(300124, "Cargo Type 7"),
    DID_LOAD_WEIGHT_7(300125, "Load Weight 7"),
    DID_LOAD_MOMENT_7(300126, "Load Moment 7"),
    DID_LOAD_STATUS_7(300127, "Load Status 7"),
    DID_CARGO_TYPE_8(300128, "Cargo Type 8"),
    DID_LOAD_WEIGHT_8(300129, "Load Weight 8"),
    DID_LOAD_MOMENT_8(300130, "Load Moment 8"),
    DID_LOAD_STATUS_8(300131, "Load Status 8"),
    DID_CARGO_TYPE_9(300132, "Cargo Type 9"),
    DID_LOAD_WEIGHT_9(300133, "Load Weight 9"),
    DID_LOAD_MOMENT_9(300134, "Load Moment 9"),
    DID_LOAD_STATUS_9(300135, "Load Status 9"),
    DID_CARGO_TYPE_10(300136, "Cargo Type 10"),
    DID_LOAD_WEIGHT_10(300137, "Load Weight 10"),
    DID_LOAD_MOMENT_10(300138, "Load Moment 10"),
    DID_LOAD_STATUS_10(300139, "Load Status 10"),
    DID_CARGO_TYPE_11(300140, "Cargo Type 11"),
    DID_LOAD_WEIGHT_11(300141, "Load Weight 11"),
    DID_LOAD_MOMENT_11(300142, "Load Moment 11"),
    DID_LOAD_STATUS_11(300143, "Load Status 11"),
    DID_CARGO_TYPE_12(300144, "Cargo Type 12"),
    DID_LOAD_WEIGHT_12(300145, "Load Weight 12"),
    DID_LOAD_MOMENT_12(300146, "Load Moment 12"),
    DID_LOAD_STATUS_12(300147, "Load Status 12"),
    DID_CARGO_TYPE_13(300148, "Cargo Type 13"),
    DID_LOAD_WEIGHT_13(300149, "Load Weight 13"),
    DID_LOAD_MOMENT_13(300150, "Load Moment 13"),
    DID_LOAD_STATUS_13(300151, "Load Status 13"),
    DID_CARGO_TYPE_14(300152, "Cargo Type 14"),
    DID_LOAD_WEIGHT_14(300153, "Load Weight 14"),
    DID_LOAD_MOMENT_14(300154, "Load Moment 14"),
    DID_LOAD_STATUS_14(300155, "Load Status 14"),
    DID_CARGO_TYPE_15(300156, "Cargo Type 15"),
    DID_LOAD_WEIGHT_15(300157, "Load Weight 15"),
    DID_LOAD_MOMENT_15(300158, "Load Moment 15"),
    DID_LOAD_STATUS_15(300159, "Load Status 15"),
    DID_PYLON_1_SETUP(300300, "Pylon 1 Setup"),
    DID_PYLON_2_SETUP(300301, "Pylon 2 Setup"),
    DID_PYLON_3_SETUP(300302, "Pylon 3 Setup"),
    DID_PYLON_4_SETUP(300303, "Pylon 4 Setup"),
    DID_RCKT_ZONE_1_SETUP(300304, "Rocket Zone 1 Setup"),
    DID_RCKT_ZONE_2_SETUP(300305, "Rocket Zone 2 Setup"),
    DID_RCKT_ZONE_3_SETUP(300306, "Rocket Zone 3 Setup"),
    DID_RCKT_ZONE_4_SETUP(300307, "Rocket Zone 4 Setup"),
    DID_RCKT_ZONE_5_SETUP(300308, "Rocket Zone 5 Setup"),
    DID_RCKT_PYLON_1_Z1_QTY(300309, "Rocket Pylon 1 Z1 Quantity"),
    DID_RCKT_PYLON_1_Z2_QTY(300310, "Rocket Pylon 1 Z2 Quantity"),
    DID_RCKT_PYLON_1_Z3_QTY(300311, "Rocket Pylon 1 Z3 Quantity"),
    DID_RCKT_PYLON_1_Z4_QTY(300312, "Rocket Pylon 1 Z4 Quantity"),
    DID_RCKT_PYLON_1_Z5_QTY(300313, "Rocket Pylon 1 Z5 Quantity"),
    DID_RCKT_PYLON_2_Z1_QTY(300314, "Rocket Pylon 2 Z1 Quantity"),
    DID_RCKT_PYLON_2_Z2_QTY(300315, "Rocket Pylon 2 Z2 Quantity"),
    DID_RCKT_PYLON_2_Z3_QTY(300316, "Rocket Pylon 2 Z3 Quantity"),
    DID_RCKT_PYLON_2_Z4_QTY(300317, "Rocket Pylon 2 Z4 Quantity"),
    DID_RCKT_PYLON_2_Z5_QTY(300318, "Rocket Pylon 2 Z5 Quantity"),
    DID_RCKT_PYLON_3_Z1_QTY(300319, "Rocket Pylon 3 Z1 Quantity"),
    DID_RCKT_PYLON_3_Z2_QTY(300320, "Rocket Pylon 3 Z2 Quantity"),
    DID_RCKT_PYLON_3_Z3_QTY(300321, "Rocket Pylon 3 Z3 Quantity"),
    DID_RCKT_PYLON_3_Z4_QTY(300322, "Rocket Pylon 3 Z4 Quantity"),
    DID_RCKT_PYLON_3_Z5_QTY(300323, "Rocket Pylon 3 Z5 Quantity"),
    DID_RCKT_PYLON_4_Z1_QTY(300324, "Rocket Pylon 4 Z1 Quantity"),
    DID_RCKT_PYLON_4_Z2_QTY(300325, "Rocket Pylon 4 Z2 Quantity"),
    DID_RCKT_PYLON_4_Z3_QTY(300326, "Rocket Pylon 4 Z3 Quantity"),
    DID_RCKT_PYLON_4_Z4_QTY(300327, "Rocket Pylon 4 Z4 Quantity"),
    DID_RCKT_PYLON_4_Z5_QTY(300328, "Rocket Pylon 4 Z5 Quantity"),
    DID_HELLFIRE_P1_R1_SETUP(300329, "Hellfire P1 R1 Setup"),
    DID_HELLFIRE_P1_R2_SETUP(300330, "Hellfire P1 R2 Setup"),
    DID_HELLFIRE_P1_R3_SETUP(300331, "Hellfire P1 R3 Setup"),
    DID_HELLFIRE_P1_R4_SETUP(300332, "Hellfire P1 R4 Setup"),
    DID_HELLFIRE_P2_R1_SETUP(300333, "Hellfire P2 R1 Setup"),
    DID_HELLFIRE_P2_R2_SETUP(300334, "Hellfire P2 R2 Setup"),
    DID_HELLFIRE_P2_R3_SETUP(300335, "Hellfire P2 R3 Setup"),
    DID_HELLFIRE_P2_R4_SETUP(300336, "Hellfire P2 R4 Setup"),
    DID_HELLFIRE_P3_R1_SETUP(300337, "Hellfire P3 R1 Setup"),
    DID_HELLFIRE_P3_R2_SETUP(300338, "Hellfire P3 R2 Setup"),
    DID_HELLFIRE_P3_R3_SETUP(300339, "Hellfire P3 R3 Setup"),
    DID_HELLFIRE_P3_R4_SETUP(300340, "Hellfire P3 R4 Setup"),
    DID_HELLFIRE_P4_R1_SETUP(300341, "Hellfire P4 R1 Setup"),
    DID_HELLFIRE_P4_R2_SETUP(300342, "Hellfire P4 R2 Setup"),
    DID_HELLFIRE_P4_R3_SETUP(300343, "Hellfire P4 R3 Setup"),
    DID_HELLFIRE_P4_R4_SETUP(300344, "Hellfire P4 R4 Setup"),
    DID_ATAS_P1_R1_SETUP(300345, "ATAS P1 R1 Setup"),
    DID_ATAS_P1_R2_SETUP(300346, "ATAS P1 R2 Setup"),
    DID_ATAS_P2_R1_SETUP(300347, "ATAS P2 R1 Setup"),
    DID_ATAS_P2_R2_SETUP(300348, "ATAS P2 R2 Setup"),
    DID_ATAS_P3_R1_SETUP(300349, "ATAS P3 R1 Setup"),
    DID_ATAS_P3_R2_SETUP(300350, "ATAS P3 R2 Setup"),
    DID_ATAS_P4_R1_SETUP(300351, "ATAS P4 R1 Setup"),
    DID_ATAS_P4_R2_SETUP(300352, "ATAS P4 R2 Setup"),
    DID_GUN_ROUNDS_SETUP(300353, "Gun Rounds Setup"),
    DID_FUEL_TANK_1_SETUP(300354, "Fuel Tank 1 Setup"),
    DID_FUEL_TANK_2_SETUP(300355, "Fuel Tank 2 Setup"),
    DID_FUEL_TANK_3_SETUP(300356, "Fuel Tank 3 Setup"),
    DID_FUEL_TANK_4_SETUP(300357, "Fuel Tank 4 Setup"),
    DID_LASER_CODE_1_SETUP(300358, "Laser Code 1 Setup"),
    DID_LASER_CODE_2_SETUP(300359, "Laser Code 2 Setup"),
    DID_LASER_CODE_3_SETUP(300360, "Laser Code 3 Setup"),
    DID_LASER_CODE_4_SETUP(300361, "Laser Code 4 Setup"),
    DID_LASER_CODE_5_SETUP(300362, "Laser Code 5 Setup"),
    DID_LASER_CODE_6_SETUP(300363, "Laser Code 6 Setup"),
    DID_LASER_CODE_7_SETUP(300364, "Laser Code 7 Setup"),
    DID_LASER_CODE_8_SETUP(300365, "Laser Code 8 Setup"),
    DID_LASER_CODE_9_SETUP(300366, "Laser Code 9 Setup"),
    DID_LASER_CODE_10_SETUP(300367, "Laser Code 10 Setup"),
    DID_LASER_CODE_11_SETUP(300368, "Laser Code 11 Setup"),
    DID_LASER_CODE_12_SETUP(300369, "Laser Code 12 Setup"),
    DID_LASER_CODE_13_SETUP(300370, "Laser Code 13 Setup"),
    DID_LASER_CODE_14_SETUP(300371, "Laser Code 14 Setup"),
    DID_LASER_CODE_15_SETUP(300372, "Laser Code 15 Setup"),
    DID_LASER_CODE_16_SETUP(300373, "Laser Code 16 Setup"),
    DID_RCKT_PYLON_1_Z1_STATE(300500, "Rocket Pylon 1 Z1 State"),
    DID_RCKT_PYLON_1_Z2_STATE(300501, "Rocket Pylon 1 Z2 State"),
    DID_RCKT_PYLON_1_Z3_STATE(300502, "Rocket Pylon 1 Z3 State"),
    DID_RCKT_PYLON_1_Z4_STATE(300503, "Rocket Pylon 1 Z4 State"),
    DID_RCKT_PYLON_1_Z5_STATE(300504, "Rocket Pylon 1 Z5 State"),
    DID_RCKT_PYLON_2_Z1_STATE(300505, "Rocket Pylon 2 Z1 State"),
    DID_RCKT_PYLON_2_Z2_STATE(300506, "Rocket Pylon 2 Z2 State"),
    DID_RCKT_PYLON_2_Z3_STATE(300507, "Rocket Pylon 2 Z3 State"),
    DID_RCKT_PYLON_2_Z4_STATE(300508, "Rocket Pylon 2 Z4 State"),
    DID_RCKT_PYLON_2_Z5_STATE(300509, "Rocket Pylon 2 Z5 State"),
    DID_RCKT_PYLON_3_Z1_STATE(300510, "Rocket Pylon 3 Z1 State"),
    DID_RCKT_PYLON_3_Z2_STATE(300511, "Rocket Pylon 3 Z2 State"),
    DID_RCKT_PYLON_3_Z3_STATE(300512, "Rocket Pylon 3 Z3 State"),
    DID_RCKT_PYLON_3_Z4_STATE(300513, "Rocket Pylon 3 Z4 State"),
    DID_RCKT_PYLON_3_Z5_STATE(300514, "Rocket Pylon 3 Z5 State"),
    DID_RCKT_PYLON_4_Z1_STATE(300515, "Rocket Pylon 4 Z1 State"),
    DID_RCKT_PYLON_4_Z2_STATE(300516, "Rocket Pylon 4 Z2 State"),
    DID_RCKT_PYLON_4_Z3_STATE(300517, "Rocket Pylon 4 Z3 State"),
    DID_RCKT_PYLON_4_Z4_STATE(300518, "Rocket Pylon 4 Z4 State"),
    DID_RCKT_PYLON_4_Z5_STATE(300519, "Rocket Pylon 4 Z5 State"),
    DID_HELLFIRE_P1_R1_STATE(300520, "Hellfire P1 R1 State"),
    DID_HELLFIRE_P1_R2_STATE(300521, "Hellfire P1 R2 State"),
    DID_HELLFIRE_P1_R3_STATE(300522, "Hellfire P1 R3 State"),
    DID_HELLFIRE_P1_R4_STATE(300523, "Hellfire P1 R4 State"),
    DID_HELLFIRE_P2_R1_STATE(300524, "Hellfire P2 R1 State"),
    DID_HELLFIRE_P2_R2_STATE(300525, "Hellfire P2 R2 State"),
    DID_HELLFIRE_P2_R3_STATE(300526, "Hellfire P2 R3 State"),
    DID_HELLFIRE_P2_R4_STATE(300527, "Hellfire P2 R4 State"),
    DID_HELLFIRE_P3_R1_STATE(300528, "Hellfire P3 R1 State"),
    DID_HELLFIRE_P3_R2_STATE(300529, "Hellfire P3 R2 State"),
    DID_HELLFIRE_P3_R3_STATE(300530, "Hellfire P3 R3 State"),
    DID_HELLFIRE_P3_R4_STATE(300531, "Hellfire P3 R4 State"),
    DID_HELLFIRE_P4_R1_STATE(300532, "Hellfire P4 R1 State"),
    DID_HELLFIRE_P4_R2_STATE(300533, "Hellfire P4 R2 State"),
    DID_HELLFIRE_P4_R3_STATE(300534, "Hellfire P4 R3 State"),
    DID_HELLFIRE_P4_R4_STATE(300535, "Hellfire P4 R4 State"),
    DID_ATAS_P1_R1_STATE(300536, "ATAS P1 R1 State"),
    DID_ATAS_P1_R2_STATE(300537, "ATAS P1 R2 State"),
    DID_ATAS_P2_R1_STATE(300538, "ATAS P2 R1 State"),
    DID_ATAS_P2_R2_STATE(300539, "ATAS P2 R2 State"),
    DID_ATAS_P3_R1_STATE(300540, "ATAS P3 R1 State"),
    DID_ATAS_P3_R2_STATE(300541, "ATAS P3 R2 State"),
    DID_ATAS_P4_R1_STATE(300542, "ATAS P4 R1 State"),
    DID_ATAS_P4_R2_STATE(300543, "ATAS P4 R2 State"),
    DID_GUN_STATE(300544, "Gun State"),
    DID_FUEL_TANK_1_STATE(300545, "Fuel Tank 1 State"),
    DID_FUEL_TANK_2_STATE(300546, "Fuel Tank 2 State"),
    DID_FUEL_TANK_3_STATE(300547, "Fuel Tank 3 State"),
    DID_FUEL_TANK_4_STATE(300548, "Fuel Tank 4 State"),
    DID_LASER_CODE_1_STATE(300549, "Laser Code 1 State"),
    DID_LASER_CODE_2_STATE(300550, "Laser Code 2 State"),
    DID_LASER_CODE_3_STATE(300551, "Laser Code 3 State"),
    DID_LASER_CODE_4_STATE(300552, "Laser Code 4 State"),
    DID_LASER_CODE_5_STATE(300553, "Laser Code 5 State"),
    DID_LASER_CODE_6_STATE(300554, "Laser Code 6 State"),
    DID_LASER_CODE_7_STATE(300555, "Laser Code 7 State"),
    DID_LASER_CODE_8_STATE(300556, "Laser Code 8 State"),
    DID_UPPER_CHANNEL_LASER_CODE(300557, "Upper Channel Laser Code"),
    DID_LOWER_CHANNEL_LASER_CODE(300558, "Lower Channel Laser Code"),
    DID_LASER_SPOT_TRACKER_CODE(300559, "Laser Spot Tracker Code"),
    DID_LRFD_DESIGNATOR_CODE(300560, "Lrfd Designator Code"),
    DID_TOTAL_MOMENT_STATE(300600, "Total Moment State"),
    DID_FUEL_MOMENT_STATE(300601, "Fuel Moment State"),
    DID_LASER_CODE_10_STATE(300602, "Laser Code 10 State"),
    DID_LASER_CODE_11_STATE(300603, "Laser Code 11 State"),
    DID_LASER_CODE_12_STATE(300604, "Laser Code 12 State"),
    DID_LASER_CODE_13_STATE(300605, "Laser Code 13 State"),
    DID_LASER_CODE_14_STATE(300606, "Laser Code 14 State"),
    DID_LASER_CODE_15_STATE(300607, "Laser Code 15 State"),
    DID_LASER_CODE_16_STATE(300608, "Laser Code 16 State"),
    DID_FUEL_INTERNAL_AUX_QTY(300650, "Fuel Internal Aux Quantity"),
    DID_COMBO_PACK_INSTALLED(300651, "Combo Pack Installed"),
    DID_DISPLAY_MODE_1(301100, "Display Mode 1"),
    DID_DISPLAY_MODE_2(301101, "Display Mode 2"),
    DID_DISPLAY_MODE_3(301102, "Display Mode 3"),
    DID_ENVIRONMENT_PROCESS_GEOMETRY_UNIFORM(327680, "EP Geometry - Uniform"),
    DID_ENTITY_STATUS_MUNITION_RECORD(500001, "Entity Status - Munition Record"),
    DID_ENTITY_STATUS_ENGINE_FUEL_RECORD(500002, "Entity Status - Engine Fuel Record"),
    DID_ENTITY_STATUS_STORAGE_FUEL_RECORD(500003, "Entity Status - Storage Fuel Record"),
    DID_ENTITY_STATUS_EXPENDABLE_RECORD(500005, "Entity Status - Expendable Record"),
    DID_ENTITY_TOTAL_RECORD_SETS(500006, "Entity Status - Total Record Sets"),
    DID_ENTITY_STATUS_LAUNCHED_MUNITION_RECORD(500007, "Entity Status - Launched Munition Record"),
    DID_ENTITY_STATUS_ASSOCIATION_RECORD(500008, "Entity Status - Association Record"),
    DID_ENTITY_STATUS_SENSOR_RECORD(500009, "Entity Status - Sensor Record"),
    DID_ENTITY_STATUS_MUNITION_RELOAD(500010, "Munition Reload"),
    DID_ENTITY_STATUS_ENGINE_FUEL_RELOAD(500011, "Engine Fuel Reload"),
    DID_ENTITY_STATUS_STORAGE_FUEL_RELOAD(500012, "Storage Fuel Reload"),
    DID_ENTITY_STATUS_EXPENDABLE_RELOAD(500013, "Expendable Reload"),
    DID_ENVIRONMENT_PROCESS_GEOMETRY_POINT_RECORD_1(655360, "EP Geometry - Point Record 1"),
    DID_ENVIRONMENT_PROCESS_GEOMETRY_LINE_RECORD_1(786432, "EP Geometry - Line Record 1"),
    DID_ENVIRONMENT_PROCESS_GEOMETRY_SPHERE_RECORD_1(851968, "EP Geometry - Sphere Record 1"),
    DID_DATUM_SCENARIO_NAME(1000011, "Datum Scenario Name"),
    DID_DATUM_CHECKPOINT_NAME(1000012, "Datum Checkpoint Name"),
    DID_DATUM_KILL_SAF(1000016, "Datum Kill SAF"),
    DID_DATUM_SHUTDOWN_LINUX(1000017, "Datum Shutdown Linux"),
    DID_DATUM_REBOOT_LINUX(1000018, "Datum Reboot Linux"),
    DID_DATUM_SAF_CHECK_ALIVE(1000019, "Datum SAF Check Alive"),
    DID_ENVIRONMENT_PROCESS_GEOMETRY_ELLIPSOID_RECORD_1(1048576, "EP Geometry - Ellipsoid Record 1"),
    DID_ENVIRONMENT_PROCESS_GEOMETRY_CONE_RECORD_1(3145728, "EP Geometry - Cone Record 1"),
    DID_ENVIRONMENT_PROCESS_GEOMETRY_RECTANGULAR_VOLUME_RECORD_1(5242880, "EP Geometry - Rectangular Volume Record 1"),
    DID_ENVIRONMENT_PROCESS_GEOMETRY_RECTANGULAR_VOLUME_RECORD_3(83886080, "EP Geometry - Rectangular Volume Record 3"),
    DID_ENVIRONMENT_PROCESS_GEOMETRY_POINT_RECORD_2(167772160, "EP Geometry - Point Record 2"),
    DID_ENVIRONMENT_PROCESS_GEOMETRY_LINE_RECORD_2(201326592, "EP Geometry - Line Record 2"),
    DID_ENVIRONMENT_PROCESS_GEOMETRY_SPHERE_RECORD_2(218103808, "EP Geometry - Sphere Record 2"),
    DID_ENVIRONMENT_PROCESS_GEOMETRY_ELLIPSOID_RECORD_2(268435456, "EP Geometry - Ellipsoid Record 2"),
    DID_ENVIRONMENT_PROCESS_GEOMETRY_CONE_RECORD_2(805306368, "EP Geometry - Cone Record 2"),
    DID_ENVIRONMENT_PROCESS_GEOMETRY_RECTANGULAR_VOLUME_RECORD_2(1342177280, "EP Geometry - Rectangular Volume Record 2"),
    DID_ENVIRONMENT_PROCESS_GEOMETRY_GAUSSIAN_PLUME_RECORD(1610612736, "EP Geometry - Gaussian Plume Record"),
    DID_ENVIRONMENT_PROCESS_GEOMETRY_GAUSSIAN_PUFF_RECORD(1879048192, "EP Geometry - Gaussian Puff Record");

    private final int value;
    private final String description;

    private DATUM_IDS(int value, String description) {

        this.value = value;
        this.description = description;
    }

    @Override
    public int getValue() {

        return value;
    }

    @Override
    public String getName() {

        return name();
    }

    @Override
    public String getDescription() {

        return description;
    }

    public static EnumInterface getValue(int value) {

        for(EnumInterface element : values()) {

            if (element.getValue() == value) {

                return element;
            }
        }

        return Enumerations.getUnknownValue(value, DATUM_IDS.class);
    }
}

