package discover.vdis.enums;

import java.util.List;

/**
 * DEAD_RECKONING: This class is auto-generated by vdis.EnumGenerator
 */
public final class DEAD_RECKONING extends Value {

    public static final DEAD_RECKONING
       DEAD_RECK_OTHER = new DEAD_RECKONING(0, "DEAD_RECK_OTHER", "Other", true),
       DEAD_RECK_STATIC = new DEAD_RECKONING(1, "DEAD_RECK_STATIC", "Static (Entity does not move)", true),
       DEAD_RECK_DRM_F_P_W = new DEAD_RECKONING(2, "DEAD_RECK_DRM_F_P_W", "DRM(F, P, W)", true),
       DEAD_RECK_DRM_R_P_W = new DEAD_RECKONING(3, "DEAD_RECK_DRM_R_P_W", "DRM(R, P, W)", true),
       DEAD_RECK_DRM_R_V_W = new DEAD_RECKONING(4, "DEAD_RECK_DRM_R_V_W", "DRM(R, V, W)", true),
       DEAD_RECK_DRM_F_V_W = new DEAD_RECKONING(5, "DEAD_RECK_DRM_F_V_W", "DRM(F, V, W)", true),
       DEAD_RECK_DRM_F_P_B = new DEAD_RECKONING(6, "DEAD_RECK_DRM_F_P_B", "DRM(F, P, B)", true),
       DEAD_RECK_DRM_R_P_B = new DEAD_RECKONING(7, "DEAD_RECK_DRM_R_P_B", "DRM(R, P, B)", true),
       DEAD_RECK_DRM_R_V_B = new DEAD_RECKONING(8, "DEAD_RECK_DRM_R_V_B", "DRM(R, V, B)", true),
       DEAD_RECK_DRM_F_V_B = new DEAD_RECKONING(9, "DEAD_RECK_DRM_F_V_B", "DRM(F, V, B)", true);

    private DEAD_RECKONING(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, DEAD_RECKONING.class);
    }

    /** @see Value#values(Class) */
    public static List<DEAD_RECKONING> values() {

        return values(DEAD_RECKONING.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<DEAD_RECKONING> values(boolean known) {

        return values(DEAD_RECKONING.class, known);
    }

    /** @see Value#get(int, Class) */
    public static DEAD_RECKONING get(int value) {

        return get(value, DEAD_RECKONING.class);
    }
}

