package discover.vdis.enums;

import java.util.List;

/**
 * DESIG_SPOT_TYPE: This class is auto-generated by vdis.EnumGenerator
 */
public final class DESIG_SPOT_TYPE extends Value {

    public static final DESIG_SPOT_TYPE
       DES_SPOT_TYPE_NOT_SPECIFIED = new DESIG_SPOT_TYPE(0, "DES_SPOT_TYPE_NOT_SPECIFIED", "Not Specified", true),
       DES_SPOT_TYPE_TERRAIN_MODEL = new DESIG_SPOT_TYPE(1, "DES_SPOT_TYPE_TERRAIN_MODEL", "Terrain - terrain model", true),
       DES_SPOT_TYPE_NO_TERRAIN_MODEL = new DESIG_SPOT_TYPE(2, "DES_SPOT_TYPE_NO_TERRAIN_MODEL", "Terrain - no terrain model (zero-elevation)", true),
       DES_SPOT_TYPE_WATER_SURFACE = new DESIG_SPOT_TYPE(3, "DES_SPOT_TYPE_WATER_SURFACE", "Water Surface", true),
       DES_SPOT_TYPE_FOLIAGE = new DESIG_SPOT_TYPE(4, "DES_SPOT_TYPE_FOLIAGE", "Foliage or other natural object attached to terrain", true),
       DES_SPOT_TYPE_MAN_MADE_OBJECT = new DESIG_SPOT_TYPE(5, "DES_SPOT_TYPE_MAN_MADE_OBJECT", "Man-made object attached to terrain", true),
       DES_SPOT_TYPE_CLOUDS = new DESIG_SPOT_TYPE(6, "DES_SPOT_TYPE_CLOUDS", "Clouds", true),
       DES_SPOT_TYPE_OBSCURANT = new DESIG_SPOT_TYPE(7, "DES_SPOT_TYPE_OBSCURANT", "Obscurant (e.g. smoke)", true),
       DES_SPOT_TYPE_NON_INCIDENT = new DESIG_SPOT_TYPE(8, "DES_SPOT_TYPE_NON_INCIDENT", "Non-incident (e.g. clear sky)", true);

    private DESIG_SPOT_TYPE(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, DESIG_SPOT_TYPE.class);
    }

    /** @see Value#values(Class) */
    public static List<DESIG_SPOT_TYPE> values() {

        return values(DESIG_SPOT_TYPE.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<DESIG_SPOT_TYPE> values(boolean known) {

        return values(DESIG_SPOT_TYPE.class, known);
    }

    /** @see Value#get(int, Class) */
    public static DESIG_SPOT_TYPE get(int value) {

        return get(value, DESIG_SPOT_TYPE.class);
    }
}

