package discover.vdis.enums;

import java.util.List;

/**
 * DESIG_SYSTEM_NAME: This class is auto-generated by vdis.EnumGenerator
 */
public final class DESIG_SYSTEM_NAME extends Value {

    public static final DESIG_SYSTEM_NAME
       DES_SYS_NAME_NO_STATEMENT = new DESIG_SYSTEM_NAME(0, "DES_SYS_NAME_NO_STATEMENT", "No Statement", true),
       DES_SYS_NAME_AN_AAQ_16 = new DESIG_SYSTEM_NAME(1, "DES_SYS_NAME_AN_AAQ_16", "AN/AAQ-16: FLIR Imaging System", true),
       DES_SYS_NAME_AN_AAQ_22A = new DESIG_SYSTEM_NAME(2, "DES_SYS_NAME_AN_AAQ_22A", "AN/AAQ-22A: SAFIRE-LRF (USMC UH1N, MH60G)", true),
       DES_SYS_NAME_AN_AAQ_22B = new DESIG_SYSTEM_NAME(3, "DES_SYS_NAME_AN_AAQ_22B", "AN/AAQ-22B: SAFIRE-LP (USAF)", true),
       DES_SYS_NAME_AN_AAQ_22C = new DESIG_SYSTEM_NAME(4, "DES_SYS_NAME_AN_AAQ_22C", "AN/AAQ-22C: Star SAFIRE-I LRF (USMC)", true),
       DES_SYS_NAME_AN_AAQ_22D = new DESIG_SYSTEM_NAME(5, "DES_SYS_NAME_AN_AAQ_22D", "AN/AAQ-22D: BRITE Star (USMC)", true),
       DES_SYS_NAME_AN_AAQ_28_LITENING = new DESIG_SYSTEM_NAME(6, "DES_SYS_NAME_AN_AAQ_28_LITENING", "AN/AAQ-28: LITENING Airborne Targeting and Navigation POD", true),
       DES_SYS_NAME_AN_AAQ_7 = new DESIG_SYSTEM_NAME(7, "DES_SYS_NAME_AN_AAQ_7", "AN/AAQ-7 Laser Range Finder (AC-130A/H)", true),
       DES_SYS_NAME_AN_AAS_35V_PAVE_PENNY = new DESIG_SYSTEM_NAME(8, "DES_SYS_NAME_AN_AAS_35V_PAVE_PENNY", "AN/AAS-35(V): Pave Penny Airborne Ground Attack Pod", true),
       DES_SYS_NAME_AN_AAS_37 = new DESIG_SYSTEM_NAME(9, "DES_SYS_NAME_AN_AAS_37", "AN/AAS-37 Laser Range Finder and Designator (OV-10 and OV-1D)", true),
       DES_SYS_NAME_AN_AAS_38 = new DESIG_SYSTEM_NAME(10, "DES_SYS_NAME_AN_AAS_38", "AN/AAS-38 NITE HAWK FLIR and Laser Designator Pod (F/A-18)", true),
       DES_SYS_NAME_AN_AAS_44 = new DESIG_SYSTEM_NAME(11, "DES_SYS_NAME_AN_AAS_44", "AN/AAS-44 IR Laser Detecting/Ranging/Tracking Set (SH-60B)", true),
       DES_SYS_NAME_AN_AAS_49 = new DESIG_SYSTEM_NAME(12, "DES_SYS_NAME_AN_AAS_49", "AN/AAS-49 IR Laser Detecting/Ranging/Tracking Set (derivative of AN/AAS-44)", true),
       DES_SYS_NAME_AN_AAS_51 = new DESIG_SYSTEM_NAME(13, "DES_SYS_NAME_AN_AAS_51", "AN/AAS-51 IR Laser Detecting/Ranging/Tracking Set (derivative of AN/AAS-44 used in helicopters)", true),
       DES_SYS_NAME_AN_AAS_53 = new DESIG_SYSTEM_NAME(14, "DES_SYS_NAME_AN_AAS_53", "AN/AAS-53 Electro Optical/IR/Laser sensor turret for Army ARH (AN/AAS-52 in MQ-1)", true),
       DES_SYS_NAME_AN_GVS_5 = new DESIG_SYSTEM_NAME(15, "DES_SYS_NAME_AN_GVS_5", "AN/GVS-5: Hand Held LRF", true),
       DES_SYS_NAME_AN_TVQ_2 = new DESIG_SYSTEM_NAME(16, "DES_SYS_NAME_AN_TVQ_2", "AN/TVQ-2: Ground Vehicle Laser Locator Designator (GVLLD)", true),
       DES_SYS_NAME_DAK_1_SAGE_GLOSS = new DESIG_SYSTEM_NAME(17, "DES_SYS_NAME_DAK_1_SAGE_GLOSS", "DAK-1: Russian LRF Sage Gloss (artillery weapons)", true),
       DES_SYS_NAME_DHY_307 = new DESIG_SYSTEM_NAME(18, "DES_SYS_NAME_DHY_307", "DHY 307: Ground Laser Designator", true),
       DES_SYS_NAME_SACLOS = new DESIG_SYSTEM_NAME(19, "DES_SYS_NAME_SACLOS", "Semi Automatic Command Line of Sight (SACLOS) - Wired / Beam Rider / Laser Designator", true),
       DES_SYS_NAME_TPDK_1 = new DESIG_SYSTEM_NAME(20, "DES_SYS_NAME_TPDK_1", "TPDK-1: Russian LRF", true),
       DES_SYS_NAME_1D15 = new DESIG_SYSTEM_NAME(21, "DES_SYS_NAME_1D15", "1D15: Russian Laser Target Designator", true),
       DES_SYS_NAME_1D20 = new DESIG_SYSTEM_NAME(22, "DES_SYS_NAME_1D20", "1D20: Russian Laser Target Designator", true),
       DES_SYS_NAME_1D22 = new DESIG_SYSTEM_NAME(23, "DES_SYS_NAME_1D22", "1D22: Russian Laser Target Designator", true),
       DES_SYS_NAME_IZLID_428P_W = new DESIG_SYSTEM_NAME(24, "DES_SYS_NAME_IZLID_428P_W", "IZLID 428P-W", true),
       DES_SYS_NAME_AIM_1_SLX_SUPER_LONG_RANGE_IR_AIMING_LASER = new DESIG_SYSTEM_NAME(25, "DES_SYS_NAME_AIM_1_SLX_SUPER_LONG_RANGE_IR_AIMING_LASER", "AIM-1/SLX Super Long Range IR Aiming Laser (Helicopter mounted)", true),
       DES_SYS_NAME_AIM_1_SLR_SUPER_LONG_RANGE_IR_AIMING_LASER = new DESIG_SYSTEM_NAME(26, "DES_SYS_NAME_AIM_1_SLR_SUPER_LONG_RANGE_IR_AIMING_LASER", "AIM-1/SLR Super Long Range IR Aiming Laser", true),
       DES_SYS_NAME_AN_PEQ_2A_IR_AIMING_LASER = new DESIG_SYSTEM_NAME(27, "DES_SYS_NAME_AN_PEQ_2A_IR_AIMING_LASER", "AN/PEQ-2A IR Aiming Laser", true),
       DES_SYS_NAME_ACP_2A_AIR_COMMANDER_POINTER_IR_AIMING_LASER = new DESIG_SYSTEM_NAME(28, "DES_SYS_NAME_ACP_2A_AIR_COMMANDER_POINTER_IR_AIMING_LASER", "ACP-2A Air Commander Pointer IR Aiming Laser", true);

    private DESIG_SYSTEM_NAME(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, DESIG_SYSTEM_NAME.class);
    }

    /** @see Value#values(Class) */
    public static List<DESIG_SYSTEM_NAME> values() {

        return values(DESIG_SYSTEM_NAME.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<DESIG_SYSTEM_NAME> values(boolean known) {

        return values(DESIG_SYSTEM_NAME.class, known);
    }

    /** @see Value#get(int, Class) */
    public static DESIG_SYSTEM_NAME get(int value) {

        return get(value, DESIG_SYSTEM_NAME.class);
    }
}

