package discover.vdis.enums;

import java.util.List;

/**
 * DESIG_MOTION_PATTERN: This class is auto-generated by vdis.EnumGenerator
 */
public final class DESIG_MOTION_PATTERN extends Value {

    public static final DESIG_MOTION_PATTERN
       DES_MOT_PATT_NO_STATEMENT = new DESIG_MOTION_PATTERN(0, "DES_MOT_PATT_NO_STATEMENT", "No Statement", true),
       DES_MOT_PATT_ROPING = new DESIG_MOTION_PATTERN(1, "DES_MOT_PATT_ROPING", "Roping", true),
       DES_MOT_PATT_SNAKING = new DESIG_MOTION_PATTERN(2, "DES_MOT_PATT_SNAKING", "Snaking", true);

    private DESIG_MOTION_PATTERN(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, DESIG_MOTION_PATTERN.class);
    }

    /** @see Value#values(Class) */
    public static List<DESIG_MOTION_PATTERN> values() {

        return values(DESIG_MOTION_PATTERN.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<DESIG_MOTION_PATTERN> values(boolean known) {

        return values(DESIG_MOTION_PATTERN.class, known);
    }

    /** @see Value#get(int, Class) */
    public static DESIG_MOTION_PATTERN get(int value) {

        return get(value, DESIG_MOTION_PATTERN.class);
    }
}

