package discover.vdis.enums;

import java.util.List;

/**
 * DESTINATION_LINE: This class is auto-generated by vdis.EnumGenerator
 */
public final class DESTINATION_LINE extends Value {

    public static final DESTINATION_LINE
       DESTINATION_NONE = new DESTINATION_LINE(0, "DESTINATION_NONE", "None", true),
       DESTINATION_SET_LINE_STATE_TRANSMITTING = new DESTINATION_LINE(1, "DESTINATION_SET_LINE_STATE_TRANSMITTING", "Set Line State - Transmitting", true),
       DESTINATION_SET_LINE_STATE_NOT_TRANSMITTING = new DESTINATION_LINE(2, "DESTINATION_SET_LINE_STATE_NOT_TRANSMITTING", "Set Line State - Not Transmitting", true),
       DESTINATION_RETURN_TO_LOCAL_LINE_STATE_CONTROL = new DESTINATION_LINE(3, "DESTINATION_RETURN_TO_LOCAL_LINE_STATE_CONTROL", "Return to Local Line State Control", true);

    private DESTINATION_LINE(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, DESTINATION_LINE.class);
    }

    /** @see Value#values(Class) */
    public static List<DESTINATION_LINE> values() {

        return values(DESTINATION_LINE.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<DESTINATION_LINE> values(boolean known) {

        return values(DESTINATION_LINE.class, known);
    }

    /** @see Value#get(int, Class) */
    public static DESTINATION_LINE get(int value) {

        return get(value, DESTINATION_LINE.class);
    }
}

