package discover.vdis.enums;

import java.util.List;

/**
 * DISGUISE_STATUS: This class is auto-generated by vdis.EnumGenerator
 */
public final class DISGUISE_STATUS extends Value {

    public static final DISGUISE_STATUS
       NOT_SPECIFIED = new DISGUISE_STATUS(0, "NOT_SPECIFIED", "Not Specified", true),
       NO_DISGUISE = new DISGUISE_STATUS(1, "NO_DISGUISE", "No Disguise", true),
       DISGUISED = new DISGUISE_STATUS(2, "DISGUISED", "Disguised", true),
       INDISTINGUISHABLE = new DISGUISE_STATUS(3, "INDISTINGUISHABLE", "Indistinguishable", true);

    private DISGUISE_STATUS(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, DISGUISE_STATUS.class);
    }

    /** @see Value#values(Class) */
    public static List<DISGUISE_STATUS> values() {

        return values(DISGUISE_STATUS.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<DISGUISE_STATUS> values(boolean known) {

        return values(DISGUISE_STATUS.class, known);
    }

    /** @see Value#get(int, Class) */
    public static DISGUISE_STATUS get(int value) {

        return get(value, DISGUISE_STATUS.class);
    }
}

