package discover.vdis.enums;

import java.util.List;

/**
 * DR_TYPE: This class is auto-generated by vdis.EnumGenerator
 */
public final class DR_TYPE extends Value {

    public static final DR_TYPE
       DRVP_DR_TYPE_NOT_SPECIFIED = new DR_TYPE(0, "DRVP_DR_TYPE_NOT_SPECIFIED", "Not Specified", true),
       DRVP_DR_TYPE_LINEAR_VELOCITY = new DR_TYPE(1, "DRVP_DR_TYPE_LINEAR_VELOCITY", "Linear Velocity", true),
       DRVP_DR_TYPE_LINEAR_ACCELERATION = new DR_TYPE(2, "DRVP_DR_TYPE_LINEAR_ACCELERATION", "Linear Acceleration", true),
       DRVP_DR_TYPE_ANGULAR_VELOCITY = new DR_TYPE(3, "DRVP_DR_TYPE_ANGULAR_VELOCITY", "Angular Velocity", true);

    private DR_TYPE(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, DR_TYPE.class);
    }

    /** @see Value#values(Class) */
    public static List<DR_TYPE> values() {

        return values(DR_TYPE.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<DR_TYPE> values(boolean known) {

        return values(DR_TYPE.class, known);
    }

    /** @see Value#get(int, Class) */
    public static DR_TYPE get(int value) {

        return get(value, DR_TYPE.class);
    }
}

