package discover.vdis.enums;

import java.util.List;

/**
 * EDS_COMP_ID: This class is auto-generated by vdis.EnumGenerator
 */
public final class EDS_COMP_ID extends Value {

    public static final EDS_COMP_ID
       OTHER = new EDS_COMP_ID(0, "OTHER", "Other", true),
       ENTITY_STRUCTURE = new EDS_COMP_ID(1, "ENTITY_STRUCTURE", "Entity Structure", true),
       CTRL_SYSTEM = new EDS_COMP_ID(2, "CTRL_SYSTEM", "Control System", true),
       CTRL_SURFACE = new EDS_COMP_ID(3, "CTRL_SURFACE", "Control Surface", true),
       ENGINE_PROP_SYS = new EDS_COMP_ID(4, "ENGINE_PROP_SYS", "Engine / Propulsion System", true),
       CREW_MEMBER = new EDS_COMP_ID(5, "CREW_MEMBER", "Crew Member", true),
       FUSE = new EDS_COMP_ID(6, "FUSE", "Fuse", true),
       ACQ_SENSOR = new EDS_COMP_ID(7, "ACQ_SENSOR", "Acquisition Sensor", true),
       TRACKING_SENSOR = new EDS_COMP_ID(8, "TRACKING_SENSOR", "Tracking Sensor", true),
       FUEL_TANK_SOLID_ROCKET_MOTOR = new EDS_COMP_ID(9, "FUEL_TANK_SOLID_ROCKET_MOTOR", "Fuel Tank / Solid Rocket Motor", true);

    private EDS_COMP_ID(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, EDS_COMP_ID.class);
    }

    /** @see Value#values(Class) */
    public static List<EDS_COMP_ID> values() {

        return values(EDS_COMP_ID.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<EDS_COMP_ID> values(boolean known) {

        return values(EDS_COMP_ID.class, known);
    }

    /** @see Value#get(int, Class) */
    public static EDS_COMP_ID get(int value) {

        return get(value, EDS_COMP_ID.class);
    }
}

