package discover.vdis.enums;

import java.util.List;

/**
 * EDS_SURF_DMG: This class is auto-generated by vdis.EnumGenerator
 */
public final class EDS_SURF_DMG extends Value {

    public static final EDS_SURF_DMG
       NORMAL_APP = new EDS_SURF_DMG(0, "NORMAL_APP", "Normal Appearance", true),
       LIGHT_CHAR = new EDS_SURF_DMG(1, "LIGHT_CHAR", "Light Charring", true),
       HEAVY_CHAR = new EDS_SURF_DMG(2, "HEAVY_CHAR", "Heavy Charring", true),
       HOLES = new EDS_SURF_DMG(3, "HOLES", "One or More Holes", true);

    private EDS_SURF_DMG(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, EDS_SURF_DMG.class);
    }

    /** @see Value#values(Class) */
    public static List<EDS_SURF_DMG> values() {

        return values(EDS_SURF_DMG.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<EDS_SURF_DMG> values(boolean known) {

        return values(EDS_SURF_DMG.class, known);
    }

    /** @see Value#get(int, Class) */
    public static EDS_SURF_DMG get(int value) {

        return get(value, EDS_SURF_DMG.class);
    }
}

