package discover.vdis.enums;

import java.util.List;

/**
 * EDS_DMG_STATUS: This class is auto-generated by vdis.EnumGenerator
 */
public final class EDS_DMG_STATUS extends Value {

    public static final EDS_DMG_STATUS
       NO_DAMAGE = new EDS_DMG_STATUS(0, "NO_DAMAGE", "No Damage", true),
       MINOR_DAMAGE = new EDS_DMG_STATUS(1, "MINOR_DAMAGE", "Minor Damage", true),
       MEDIUM_DAMAGE = new EDS_DMG_STATUS(2, "MEDIUM_DAMAGE", "Medium Damage", true),
       MAJOR_DAMAGE = new EDS_DMG_STATUS(3, "MAJOR_DAMAGE", "Major Damage", true),
       DESTROYED = new EDS_DMG_STATUS(4, "DESTROYED", "Destroyed", true);

    private EDS_DMG_STATUS(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, EDS_DMG_STATUS.class);
    }

    /** @see Value#values(Class) */
    public static List<EDS_DMG_STATUS> values() {

        return values(EDS_DMG_STATUS.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<EDS_DMG_STATUS> values(boolean known) {

        return values(EDS_DMG_STATUS.class, known);
    }

    /** @see Value#get(int, Class) */
    public static EDS_DMG_STATUS get(int value) {

        return get(value, EDS_DMG_STATUS.class);
    }
}

