package discover.vdis.enums;

import java.util.List;

/**
 * ENT_ASSOC_STATUS: This class is auto-generated by vdis.EnumGenerator
 */
public final class ENT_ASSOC_STATUS extends Value {

    public static final ENT_ASSOC_STATUS
       EAVP_ENT_ASSOC_STATUS_NOT_SPECIFIED = new ENT_ASSOC_STATUS(0, "EAVP_ENT_ASSOC_STATUS_NOT_SPECIFIED", "Not Specified", true),
       EAVP_ENT_ASSOC_STATUS_PHYS_ASSOC_TARGET = new ENT_ASSOC_STATUS(1, "EAVP_ENT_ASSOC_STATUS_PHYS_ASSOC_TARGET", "Physical Association Target", true),
       EAVP_ENT_ASSOC_STATUS_NON_PHYSICAL_ASSOC = new ENT_ASSOC_STATUS(2, "EAVP_ENT_ASSOC_STATUS_NON_PHYSICAL_ASSOC", "Non Physical Association", true),
       EAVP_ENT_ASSOC_STATUS_ASSOCIATION_BROKEN = new ENT_ASSOC_STATUS(3, "EAVP_ENT_ASSOC_STATUS_ASSOCIATION_BROKEN", "Association Broken", true),
       EAVP_ENT_ASSOC_STATUS_PHYS_ASSOC_CARRIER = new ENT_ASSOC_STATUS(4, "EAVP_ENT_ASSOC_STATUS_PHYS_ASSOC_CARRIER", "Physical Association Carrier", true);

    private ENT_ASSOC_STATUS(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, ENT_ASSOC_STATUS.class);
    }

    /** @see Value#values(Class) */
    public static List<ENT_ASSOC_STATUS> values() {

        return values(ENT_ASSOC_STATUS.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<ENT_ASSOC_STATUS> values(boolean known) {

        return values(ENT_ASSOC_STATUS.class, known);
    }

    /** @see Value#get(int, Class) */
    public static ENT_ASSOC_STATUS get(int value) {

        return get(value, ENT_ASSOC_STATUS.class);
    }
}

