package discover.vdis.enums;

import java.util.List;

/**
 * ENT_KIND: This class is auto-generated by vdis.EnumGenerator
 */
public final class ENT_KIND extends Value {

    public static final ENT_KIND
       OTHER = new ENT_KIND(0, "OTHER", "Other", true),
       PLATFORMS = new ENT_KIND(1, "PLATFORMS", "Platforms", true),
       MUNITIONS = new ENT_KIND(2, "MUNITIONS", "Munitions", true),
       LIFEFORMS = new ENT_KIND(3, "LIFEFORMS", "Life Forms", true),
       ENVIRONMENTALS = new ENT_KIND(4, "ENVIRONMENTALS", "Environmentals", true),
       CULTURAL_FEATURES = new ENT_KIND(5, "CULTURAL_FEATURES", "Cultural Features", true),
       SUPPLIES = new ENT_KIND(6, "SUPPLIES", "Supplies", true),
       RADIOS = new ENT_KIND(7, "RADIOS", "Radios", true),
       EXPENDABLES = new ENT_KIND(8, "EXPENDABLES", "Expendables", true),
       SENSOR_EMITTERS = new ENT_KIND(9, "SENSOR_EMITTERS", "Sensor Emitters", true);

    private ENT_KIND(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, ENT_KIND.class);
    }

    /** @see Value#values(Class) */
    public static List<ENT_KIND> values() {

        return values(ENT_KIND.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<ENT_KIND> values(boolean known) {

        return values(ENT_KIND.class, known);
    }

    /** @see Value#get(int, Class) */
    public static ENT_KIND get(int value) {

        return get(value, ENT_KIND.class);
    }
}

