package discover.vdis.enums;

import java.util.List;

/**
 * ENTITY_MARKING: This class is auto-generated by vdis.EnumGenerator
 */
public final class ENTITY_MARKING extends Value {

    public static final ENTITY_MARKING
       UNUSED = new ENTITY_MARKING(0, "UNUSED", "Unused", true),
       ASCII = new ENTITY_MARKING(1, "ASCII", "ASCII", true),
       US_ARMY = new ENTITY_MARKING(2, "US_ARMY", "U.S. Army Marking", true),
       DIGIT_CHEVRON = new ENTITY_MARKING(3, "DIGIT_CHEVRON", "Digit Chevron", true);

    private ENTITY_MARKING(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, ENTITY_MARKING.class);
    }

    /** @see Value#values(Class) */
    public static List<ENTITY_MARKING> values() {

        return values(ENTITY_MARKING.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<ENTITY_MARKING> values(boolean known) {

        return values(ENTITY_MARKING.class, known);
    }

    /** @see Value#get(int, Class) */
    public static ENTITY_MARKING get(int value) {

        return get(value, ENTITY_MARKING.class);
    }
}

