package discover.vdis.enums;

import java.util.List;

/**
 * ENV_CAT_LAND: This class is auto-generated by vdis.EnumGenerator
 */
public final class ENV_CAT_LAND extends Value {

    public static final ENV_CAT_LAND
       OTH = new ENV_CAT_LAND(0, "OTH", "Other", true),
       RADAR = new ENV_CAT_LAND(1, "RADAR", "Radar collected noise", true);

    private ENV_CAT_LAND(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, ENV_CAT_LAND.class);
    }

    /** @see Value#values(Class) */
    public static List<ENV_CAT_LAND> values() {

        return values(ENV_CAT_LAND.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<ENV_CAT_LAND> values(boolean known) {

        return values(ENV_CAT_LAND.class, known);
    }

    /** @see Value#get(int, Class) */
    public static ENV_CAT_LAND get(int value) {

        return get(value, ENV_CAT_LAND.class);
    }
}

