package discover.vdis.enums;

import java.util.List;

/**
 * ENV_CAT_AIR: This class is auto-generated by vdis.EnumGenerator
 */
public final class ENV_CAT_AIR extends Value {

    public static final ENV_CAT_AIR
       OTH = new ENV_CAT_AIR(0, "OTH", "Other", true),
       SMOKE = new ENV_CAT_AIR(1, "SMOKE", "Smoke", true),
       FOG = new ENV_CAT_AIR(2, "FOG", "Fog", true),
       CLD = new ENV_CAT_AIR(3, "CLD", "Cloud", true),
       CLDRN = new ENV_CAT_AIR(4, "CLDRN", "Cloud With Rain Falling", true),
       CLDSN = new ENV_CAT_AIR(5, "CLDSN", "Cloud With Snow Falling", true),
       HAZE = new ENV_CAT_AIR(6, "HAZE", "Haze", true),
       DUST = new ENV_CAT_AIR(7, "DUST", "Dust/Sandstorm", true),
       CLDSL = new ENV_CAT_AIR(8, "CLDSL", "Cloud with sleet falling", true);

    private ENV_CAT_AIR(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, ENV_CAT_AIR.class);
    }

    /** @see Value#values(Class) */
    public static List<ENV_CAT_AIR> values() {

        return values(ENV_CAT_AIR.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<ENV_CAT_AIR> values(boolean known) {

        return values(ENV_CAT_AIR.class, known);
    }

    /** @see Value#get(int, Class) */
    public static ENV_CAT_AIR get(int value) {

        return get(value, ENV_CAT_AIR.class);
    }
}

