package discover.vdis.enums;

import java.util.List;

/**
 * ENV_CAT_SPACE: This class is auto-generated by vdis.EnumGenerator
 */
public final class ENV_CAT_SPACE extends Value {

    public static final ENV_CAT_SPACE
       OTH = new ENV_CAT_SPACE(0, "OTH", "Other", true);

    private ENV_CAT_SPACE(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, ENV_CAT_SPACE.class);
    }

    /** @see Value#values(Class) */
    public static List<ENV_CAT_SPACE> values() {

        return values(ENV_CAT_SPACE.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<ENV_CAT_SPACE> values(boolean known) {

        return values(ENV_CAT_SPACE.class, known);
    }

    /** @see Value#get(int, Class) */
    public static ENV_CAT_SPACE get(int value) {

        return get(value, ENV_CAT_SPACE.class);
    }
}

