package discover.vdis.enums;

import java.util.List;

/**
 * ENV_CAT_SUBSURFACE: This class is auto-generated by vdis.EnumGenerator
 */
public final class ENV_CAT_SUBSURFACE extends Value {

    public static final ENV_CAT_SUBSURFACE
       OTH = new ENV_CAT_SUBSURFACE(0, "OTH", "Other", true),
       SVP = new ENV_CAT_SUBSURFACE(1, "SVP", "Sound Velocity Profile", true),
       ICEB = new ENV_CAT_SUBSURFACE(2, "ICEB", "Ice Berg", true),
       CP = new ENV_CAT_SUBSURFACE(3, "CP", "Current Profile", true),
       BIO = new ENV_CAT_SUBSURFACE(4, "BIO", "Biologics", true),
       TRANS = new ENV_CAT_SUBSURFACE(5, "TRANS", "Transmissivity profile", true),
       ICEM = new ENV_CAT_SUBSURFACE(6, "ICEM", "Ice Merchant", true),
       KELP = new ENV_CAT_SUBSURFACE(7, "KELP", "Kelp Bed", true),
       KNUC = new ENV_CAT_SUBSURFACE(8, "KNUC", "Knuckle", true),
       DEB = new ENV_CAT_SUBSURFACE(9, "DEB", "Debris/Clutter", true);

    private ENV_CAT_SUBSURFACE(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, ENV_CAT_SUBSURFACE.class);
    }

    /** @see Value#values(Class) */
    public static List<ENV_CAT_SUBSURFACE> values() {

        return values(ENV_CAT_SUBSURFACE.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<ENV_CAT_SUBSURFACE> values(boolean known) {

        return values(ENV_CAT_SUBSURFACE.class, known);
    }

    /** @see Value#get(int, Class) */
    public static ENV_CAT_SUBSURFACE get(int value) {

        return get(value, ENV_CAT_SUBSURFACE.class);
    }
}

