package discover.vdis.enums;

import java.util.List;

/**
 * ENV_CAT_SURFACE: This class is auto-generated by vdis.EnumGenerator
 */
public final class ENV_CAT_SURFACE extends Value {

    public static final ENV_CAT_SURFACE
       OTH = new ENV_CAT_SURFACE(0, "OTH", "Other", true),
       SEA = new ENV_CAT_SURFACE(1, "SEA", "Sea State", true),
       OIL = new ENV_CAT_SURFACE(2, "OIL", "Oil Slick", true),
       ICE = new ENV_CAT_SURFACE(3, "ICE", "Ice", true),
       DEB = new ENV_CAT_SURFACE(4, "DEB", "Debris", true),
       SURNO = new ENV_CAT_SURFACE(5, "SURNO", "Surf Noise", true),
       ISLE = new ENV_CAT_SURFACE(6, "ISLE", "Island", true);

    private ENV_CAT_SURFACE(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, ENV_CAT_SURFACE.class);
    }

    /** @see Value#values(Class) */
    public static List<ENV_CAT_SURFACE> values() {

        return values(ENV_CAT_SURFACE.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<ENV_CAT_SURFACE> values(boolean known) {

        return values(ENV_CAT_SURFACE.class, known);
    }

    /** @see Value#get(int, Class) */
    public static ENV_CAT_SURFACE get(int value) {

        return get(value, ENV_CAT_SURFACE.class);
    }
}

