package discover.vdis.enums;

import java.util.List;

/**
 * FORCE_ID: This class is auto-generated by vdis.EnumGenerator
 */
public final class FORCE_ID extends Value {

    public static final FORCE_ID
       OTHER = new FORCE_ID(0, "OTHER", "Other", true),
       FRIENDLY = new FORCE_ID(1, "FRIENDLY", "Friendly", true),
       OPPOSING = new FORCE_ID(2, "OPPOSING", "Opposing", true),
       NEUTRAL = new FORCE_ID(3, "NEUTRAL", "Neutral", true),
       FRIENDLY_2 = new FORCE_ID(4, "FRIENDLY_2", "Friendly 2", true),
       OPPOSING_2 = new FORCE_ID(5, "OPPOSING_2", "Opposing 2", true),
       NEUTRAL_2 = new FORCE_ID(6, "NEUTRAL_2", "Neutral 2", true),
       FRIENDLY_3 = new FORCE_ID(7, "FRIENDLY_3", "Friendly 3", true),
       OPPOSING_3 = new FORCE_ID(8, "OPPOSING_3", "Opposing 3", true),
       NEUTRAL_3 = new FORCE_ID(9, "NEUTRAL_3", "Neutral 3", true),
       FRIENDLY_4 = new FORCE_ID(10, "FRIENDLY_4", "Friendly 4", true),
       OPPOSING_4 = new FORCE_ID(11, "OPPOSING_4", "Opposing 4", true),
       NEUTRAL_4 = new FORCE_ID(12, "NEUTRAL_4", "Neutral 4", true),
       FRIENDLY_5 = new FORCE_ID(13, "FRIENDLY_5", "Friendly 5", true),
       OPPOSING_5 = new FORCE_ID(14, "OPPOSING_5", "Opposing 5", true),
       NEUTRAL_5 = new FORCE_ID(15, "NEUTRAL_5", "Neutral 5", true),
       FRIENDLY_6 = new FORCE_ID(16, "FRIENDLY_6", "Friendly 6", true),
       OPPOSING_6 = new FORCE_ID(17, "OPPOSING_6", "Opposing 6", true),
       NEUTRAL_6 = new FORCE_ID(18, "NEUTRAL_6", "Neutral 6", true),
       FRIENDLY_7 = new FORCE_ID(19, "FRIENDLY_7", "Friendly 7", true),
       OPPOSING_7 = new FORCE_ID(20, "OPPOSING_7", "Opposing 7", true),
       NEUTRAL_7 = new FORCE_ID(21, "NEUTRAL_7", "Neutral 7", true),
       FRIENDLY_8 = new FORCE_ID(22, "FRIENDLY_8", "Friendly 8", true),
       OPPOSING_8 = new FORCE_ID(23, "OPPOSING_8", "Opposing 8", true),
       NEUTRAL_8 = new FORCE_ID(24, "NEUTRAL_8", "Neutral 8", true),
       FRIENDLY_9 = new FORCE_ID(25, "FRIENDLY_9", "Friendly 9", true),
       OPPOSING_9 = new FORCE_ID(26, "OPPOSING_9", "Opposing 9", true),
       NEUTRAL_9 = new FORCE_ID(27, "NEUTRAL_9", "Neutral 9", true),
       FRIENDLY_10 = new FORCE_ID(28, "FRIENDLY_10", "Friendly 10", true),
       OPPOSING_10 = new FORCE_ID(29, "OPPOSING_10", "Opposing 10", true),
       NEUTRAL_10 = new FORCE_ID(30, "NEUTRAL_10", "Neutral 10", true);

    private FORCE_ID(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, FORCE_ID.class);
    }

    /** @see Value#values(Class) */
    public static List<FORCE_ID> values() {

        return values(FORCE_ID.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<FORCE_ID> values(boolean known) {

        return values(FORCE_ID.class, known);
    }

    /** @see Value#get(int, Class) */
    public static FORCE_ID get(int value) {

        return get(value, FORCE_ID.class);
    }
}

