package discover.vdis.enums;

import java.util.List;

/**
 * FUEL_MEAS_UNITS: This class is auto-generated by vdis.EnumGenerator
 */
public final class FUEL_MEAS_UNITS extends Value {

    public static final FUEL_MEAS_UNITS
       ENG_FUEL_FMU_OTHER = new FUEL_MEAS_UNITS(0, "ENG_FUEL_FMU_OTHER", "Other", true),
       ENG_FUEL_FMU_LITER = new FUEL_MEAS_UNITS(1, "ENG_FUEL_FMU_LITER", "Liter", true),
       ENG_FUEL_FMU_KILOGRAM = new FUEL_MEAS_UNITS(2, "ENG_FUEL_FMU_KILOGRAM", "Kilogram", true);

    private FUEL_MEAS_UNITS(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, FUEL_MEAS_UNITS.class);
    }

    /** @see Value#values(Class) */
    public static List<FUEL_MEAS_UNITS> values() {

        return values(FUEL_MEAS_UNITS.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<FUEL_MEAS_UNITS> values(boolean known) {

        return values(FUEL_MEAS_UNITS.class, known);
    }

    /** @see Value#get(int, Class) */
    public static FUEL_MEAS_UNITS get(int value) {

        return get(value, FUEL_MEAS_UNITS.class);
    }
}

