package discover.vdis.enums;

import java.util.List;

/**
 * FUSE_BURST_DESC: This class is auto-generated by vdis.EnumGenerator
 */
public final class FUSE_BURST_DESC extends Value {

    public static final FUSE_BURST_DESC
       OTHER = new FUSE_BURST_DESC(0, "OTHER", "Other", true),
       INTELLIGENT_INFLUENCE = new FUSE_BURST_DESC(10, "INTELLIGENT_INFLUENCE", "Intelligent Influence", true),
       SENSOR = new FUSE_BURST_DESC(20, "SENSOR", "Sensor", true),
       SELF_DESTRUCT = new FUSE_BURST_DESC(30, "SELF_DESTRUCT", "Self-destruct", true),
       ULTRA_QUICK = new FUSE_BURST_DESC(40, "ULTRA_QUICK", "Ultra Quick", true),
       BODY = new FUSE_BURST_DESC(50, "BODY", "Body", true),
       DEEP_INTRUSION = new FUSE_BURST_DESC(60, "DEEP_INTRUSION", "Deep Intrusion", true),
       MULTIFUNCTION_ = new FUSE_BURST_DESC(100, "MULTIFUNCTION_", "Multifunction ", true),
       POINT_DETONATION_PD = new FUSE_BURST_DESC(200, "POINT_DETONATION_PD", "Point Detonation (PD)", true),
       BASE_DETONATION_BD = new FUSE_BURST_DESC(300, "BASE_DETONATION_BD", "Base Detonation (BD)", true),
       CONTACT = new FUSE_BURST_DESC(1000, "CONTACT", "Contact", true),
       CONTACT_INSTANT_IMPACT = new FUSE_BURST_DESC(1100, "CONTACT_INSTANT_IMPACT", "Contact, Instant (Impact)", true),
       CONTACT_DELAYED = new FUSE_BURST_DESC(1200, "CONTACT_DELAYED", "Contact, Delayed", true),
       CONTACT_DELAYED_10_MS = new FUSE_BURST_DESC(1201, "CONTACT_DELAYED_10_MS", "Contact, Delayed 10 ms", true),
       CONTACT_DELAYED_20_MS = new FUSE_BURST_DESC(1202, "CONTACT_DELAYED_20_MS", "Contact, Delayed 20 ms", true),
       CONTACT_DELAYED_50_MS = new FUSE_BURST_DESC(1205, "CONTACT_DELAYED_50_MS", "Contact, Delayed 50 ms", true),
       CONTACT_DELAYED_60_MS = new FUSE_BURST_DESC(1206, "CONTACT_DELAYED_60_MS", "Contact, Delayed 60 ms", true),
       CONTACT_DELAYED_100_MS = new FUSE_BURST_DESC(1210, "CONTACT_DELAYED_100_MS", "Contact, Delayed 100 ms", true),
       CONTACT_DELAYED_125_MS = new FUSE_BURST_DESC(1212, "CONTACT_DELAYED_125_MS", "Contact, Delayed 125 ms", true),
       CONTACT_DELAYED_250_MS = new FUSE_BURST_DESC(1225, "CONTACT_DELAYED_250_MS", "Contact, Delayed 250 ms", true),
       CONTACT_ELECTRONIC_OBLIQUE = new FUSE_BURST_DESC(1300, "CONTACT_ELECTRONIC_OBLIQUE", "Contact, Electronic (Oblique Contact)", true),
       CONTACT_GRAZE = new FUSE_BURST_DESC(1400, "CONTACT_GRAZE", "Contact, Graze", true),
       CONTACT_CRUSH = new FUSE_BURST_DESC(1500, "CONTACT_CRUSH", "Contact, Crush", true),
       CONTACT_HYDROSTATIC = new FUSE_BURST_DESC(1600, "CONTACT_HYDROSTATIC", "Contact, Hydrostatic", true),
       CONTACT_MECHANICAL = new FUSE_BURST_DESC(1700, "CONTACT_MECHANICAL", "Contact, Mechanical", true),
       CONTACT_CHEMICAL = new FUSE_BURST_DESC(1800, "CONTACT_CHEMICAL", "Contact, Chemical", true),
       CONTACT_PIEZOELECTRIC = new FUSE_BURST_DESC(1900, "CONTACT_PIEZOELECTRIC", "Contact, Piezoelectric", true),
       CONTACT_POINT_INITIATING = new FUSE_BURST_DESC(1910, "CONTACT_POINT_INITIATING", "Contact, Point Initiating", true),
       CONTACT_POINT_INITIATING_BASE_DETONATING = new FUSE_BURST_DESC(1920, "CONTACT_POINT_INITIATING_BASE_DETONATING", "Contact, Point Initiating, Base Detonating", true),
       CONTACT_BASE_DETONATING = new FUSE_BURST_DESC(1930, "CONTACT_BASE_DETONATING", "Contact, Base Detonating", true),
       CONTACT_BALLISTIC_CAP_AND_BASE = new FUSE_BURST_DESC(1940, "CONTACT_BALLISTIC_CAP_AND_BASE", "Contact, Ballistic Cap and Base", true),
       CONTACT_BASE = new FUSE_BURST_DESC(1950, "CONTACT_BASE", "Contact, Base", true),
       CONTACT_NOSE = new FUSE_BURST_DESC(1960, "CONTACT_NOSE", "Contact, Nose", true),
       CONTACT_FITTED_IN_STANDOFF_PROBE = new FUSE_BURST_DESC(1970, "CONTACT_FITTED_IN_STANDOFF_PROBE", "Contact, Fitted in Standoff Probe", true),
       CONTACT_NON_ALIGNED = new FUSE_BURST_DESC(1980, "CONTACT_NON_ALIGNED", "Contact, Non-aligned", true),
       TIMED = new FUSE_BURST_DESC(2000, "TIMED", "Timed", true),
       TIMED_PROGRAMMABLE = new FUSE_BURST_DESC(2100, "TIMED_PROGRAMMABLE", "Timed, Programmable", true),
       TIMED_BURNOUT = new FUSE_BURST_DESC(2200, "TIMED_BURNOUT", "Timed, Burnout", true),
       TIMED_PYROTECHNIC = new FUSE_BURST_DESC(2300, "TIMED_PYROTECHNIC", "Timed, Pyrotechnic", true),
       TIMED_ELECTRONIC = new FUSE_BURST_DESC(2400, "TIMED_ELECTRONIC", "Timed, Electronic", true),
       TIMED_BASE_DELAY = new FUSE_BURST_DESC(2500, "TIMED_BASE_DELAY", "Timed, Base Delay", true),
       TIMED_REINFORCED_NOSE_IMPACT_DELAY = new FUSE_BURST_DESC(2600, "TIMED_REINFORCED_NOSE_IMPACT_DELAY", "Timed, Reinforced Nose Impact Delay", true),
       TIMED_SHORT_DELAY_IMPACT = new FUSE_BURST_DESC(2700, "TIMED_SHORT_DELAY_IMPACT", "Timed, Short Delay Impact", true),
       TIMED_SHORT_DELAY_IMPACT_10_MS = new FUSE_BURST_DESC(2701, "TIMED_SHORT_DELAY_IMPACT_10_MS", "Timed, Short Delay Impact 10 ms", true),
       TIMED_SHORT_DELAY_IMPACT_20_MS = new FUSE_BURST_DESC(2702, "TIMED_SHORT_DELAY_IMPACT_20_MS", "Timed, Short Delay Impact 20 ms", true),
       TIMED_SHORT_DELAY_IMPACT_50_MS = new FUSE_BURST_DESC(2705, "TIMED_SHORT_DELAY_IMPACT_50_MS", "Timed, Short Delay Impact 50 ms", true),
       TIMED_SHORT_DELAY_IMPACT_60_MS = new FUSE_BURST_DESC(2706, "TIMED_SHORT_DELAY_IMPACT_60_MS", "Timed, Short Delay Impact 60 ms", true),
       TIMED_SHORT_DELAY_IMPACT_100_MS = new FUSE_BURST_DESC(2710, "TIMED_SHORT_DELAY_IMPACT_100_MS", "Timed, Short Delay Impact 100 ms", true),
       TIMED_SHORT_DELAY_IMPACT_125_MS = new FUSE_BURST_DESC(2712, "TIMED_SHORT_DELAY_IMPACT_125_MS", "Timed, Short Delay Impact 125 ms", true),
       TIMED_SHORT_DELAY_IMPACT_250_MS = new FUSE_BURST_DESC(2725, "TIMED_SHORT_DELAY_IMPACT_250_MS", "Timed, Short Delay Impact 250 ms", true),
       TIMED_NOSE_MOUNTED_VARIABLE_DELAY = new FUSE_BURST_DESC(2800, "TIMED_NOSE_MOUNTED_VARIABLE_DELAY", "Timed, Nose Mounted Variable Delay", true),
       TIMED_LONG_DELAY_SIDE = new FUSE_BURST_DESC(2900, "TIMED_LONG_DELAY_SIDE", "Timed, Long Delay Side", true),
       TIMED_SELECTABLE_DELAY = new FUSE_BURST_DESC(2910, "TIMED_SELECTABLE_DELAY", "Timed, Selectable Delay", true),
       TIMED_IMPACT = new FUSE_BURST_DESC(2920, "TIMED_IMPACT", "Timed, Impact", true),
       TIMED_SEQUENCE = new FUSE_BURST_DESC(2930, "TIMED_SEQUENCE", "Timed, Sequence", true),
       PROXIMITY = new FUSE_BURST_DESC(3000, "PROXIMITY", "Proximity", true),
       PROXIMITY_ACTIVE_LASER = new FUSE_BURST_DESC(3100, "PROXIMITY_ACTIVE_LASER", "Proximity, Active Laser", true),
       PROXIMITY_MAGNETIC = new FUSE_BURST_DESC(3200, "PROXIMITY_MAGNETIC", "Proximity, Magnetic (Magpolarity)", true),
       PROXIMITY_ACTIVE_RADAR_DOPPLER = new FUSE_BURST_DESC(3300, "PROXIMITY_ACTIVE_RADAR_DOPPLER", "Proximity, Active Radar (Doppler Radar)", true),
       PROXIMITY_RADIO_FREQUENCY = new FUSE_BURST_DESC(3400, "PROXIMITY_RADIO_FREQUENCY", "Proximity, Radio Frequency (RF)", true),
       PROXIMITY_PROGRAMMABLE = new FUSE_BURST_DESC(3500, "PROXIMITY_PROGRAMMABLE", "Proximity, Programmable", true),
       PROXIMITY_PROGRAMMABLE_PREFRAG = new FUSE_BURST_DESC(3600, "PROXIMITY_PROGRAMMABLE_PREFRAG", "Proximity, Programmable, Prefragmented", true),
       PROXIMITY_INFRARED = new FUSE_BURST_DESC(3700, "PROXIMITY_INFRARED", "Proximity, Infrared", true),
       COMMAND = new FUSE_BURST_DESC(4000, "COMMAND", "Command", true),
       COMMAND_ELECTRONIC_REMOTELY_SET = new FUSE_BURST_DESC(4100, "COMMAND_ELECTRONIC_REMOTELY_SET", "Command, Electronic, Remotely Set", true),
       ALTITUDE = new FUSE_BURST_DESC(5000, "ALTITUDE", "Altitude", true),
       ALTITUDE_RADIO_ALTIMETER = new FUSE_BURST_DESC(5100, "ALTITUDE_RADIO_ALTIMETER", "Altitude, Radio Altimeter", true),
       ALTITUDE_AIR_BURST = new FUSE_BURST_DESC(5200, "ALTITUDE_AIR_BURST", "Altitude, Air Burst", true),
       DEPTH = new FUSE_BURST_DESC(6000, "DEPTH", "Depth", true),
       ACOUSTIC = new FUSE_BURST_DESC(7000, "ACOUSTIC", "Acoustic", true),
       PRESSURE = new FUSE_BURST_DESC(8000, "PRESSURE", "Pressure", true),
       PRESSURE_DELAY = new FUSE_BURST_DESC(8010, "PRESSURE_DELAY", "Pressure, Delay", true),
       INERT = new FUSE_BURST_DESC(8100, "INERT", "Inert", true),
       DUMMY = new FUSE_BURST_DESC(8110, "DUMMY", "Dummy", true),
       PRACTICE = new FUSE_BURST_DESC(8120, "PRACTICE", "Practice", true),
       PLUG_REPRESENTING = new FUSE_BURST_DESC(8130, "PLUG_REPRESENTING", "Plug Representing", true),
       TRAINING = new FUSE_BURST_DESC(8150, "TRAINING", "Training", true),
       PYROTECHNIC = new FUSE_BURST_DESC(9000, "PYROTECHNIC", "Pyrotechnic", true),
       PYROTECHNIC_DELAY = new FUSE_BURST_DESC(9010, "PYROTECHNIC_DELAY", "Pyrotechnic, Delay", true),
       ELECTRO_OPTICAL = new FUSE_BURST_DESC(9100, "ELECTRO_OPTICAL", "Electro-optical", true),
       ELECTROMECHANICAL = new FUSE_BURST_DESC(9110, "ELECTROMECHANICAL", "Electromechanical", true),
       ELECTROMECHANICAL_NOSE = new FUSE_BURST_DESC(9120, "ELECTROMECHANICAL_NOSE", "Electromechanical, Nose", true),
       STRIKERLESS = new FUSE_BURST_DESC(9200, "STRIKERLESS", "Strikerless", true),
       STRIKERLESS_NOSE_IMPACT = new FUSE_BURST_DESC(9210, "STRIKERLESS_NOSE_IMPACT", "Strikerless, Nose Impact", true),
       STRIKERLESS_COMPRESSION_IGNITION = new FUSE_BURST_DESC(9220, "STRIKERLESS_COMPRESSION_IGNITION", "Strikerless, Compression-Ignition", true),
       COMPRESSION_IGNITION = new FUSE_BURST_DESC(9300, "COMPRESSION_IGNITION", "Compression-Ignition", true),
       COMPRESSION_IGNITION_STRIKERLESS_NOSE_IMPACT = new FUSE_BURST_DESC(9310, "COMPRESSION_IGNITION_STRIKERLESS_NOSE_IMPACT", "Compression-Ignition, Strikerless, Nose Impact", true),
       PERCUSSION = new FUSE_BURST_DESC(9400, "PERCUSSION", "Percussion", true),
       PERCUSSION_INSTANTANEOUS = new FUSE_BURST_DESC(9410, "PERCUSSION_INSTANTANEOUS", "Percussion, Instantaneous", true),
       ELECTRONIC = new FUSE_BURST_DESC(9500, "ELECTRONIC", "Electronic", true),
       ELECTRONIC_INTERNALLY_MOUNTED = new FUSE_BURST_DESC(9510, "ELECTRONIC_INTERNALLY_MOUNTED", "Electronic, Internally Mounted", true),
       ELECTRONIC_RANGE_SETTING = new FUSE_BURST_DESC(9520, "ELECTRONIC_RANGE_SETTING", "Electronic, Range Setting", true),
       ELECTRONIC_PROGRAMMED = new FUSE_BURST_DESC(9530, "ELECTRONIC_PROGRAMMED", "Electronic, Programmed", true),
       MECHANICAL = new FUSE_BURST_DESC(9600, "MECHANICAL", "Mechanical", true),
       MECHANICAL_NOSE = new FUSE_BURST_DESC(9610, "MECHANICAL_NOSE", "Mechanical, Nose", true),
       MECHANICAL_TAIL = new FUSE_BURST_DESC(9620, "MECHANICAL_TAIL", "Mechanical, Tail", true);

    private FUSE_BURST_DESC(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, FUSE_BURST_DESC.class);
    }

    /** @see Value#values(Class) */
    public static List<FUSE_BURST_DESC> values() {

        return values(FUSE_BURST_DESC.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<FUSE_BURST_DESC> values(boolean known) {

        return values(FUSE_BURST_DESC.class, known);
    }

    /** @see Value#get(int, Class) */
    public static FUSE_BURST_DESC get(int value) {

        return get(value, FUSE_BURST_DESC.class);
    }
}

