package discover.vdis.enums;

import java.util.List;

/**
 * GROUPED_ENTITY: This class is auto-generated by vdis.EnumGenerator
 */
public final class GROUPED_ENTITY extends Value {

    public static final GROUPED_ENTITY
       UNDEFINED = new GROUPED_ENTITY(0, "UNDEFINED", "Undefined", true),
       BASIC_GROUND_COMBAT_VEHICLE = new GROUPED_ENTITY(1, "BASIC_GROUND_COMBAT_VEHICLE", "Basic Ground Combat Vehicle", true),
       ENHANCED_GROUND_COMBAT_VEHICLE = new GROUPED_ENTITY(2, "ENHANCED_GROUND_COMBAT_VEHICLE", "Enhanced Ground Combat Vehicle", true),
       BASIC_GROUND_COMBAT_SOLDIER = new GROUPED_ENTITY(3, "BASIC_GROUND_COMBAT_SOLDIER", "Basic Ground Combat Soldier", true),
       ENHANCED_GROUND_COMBAT_SOLDIER = new GROUPED_ENTITY(4, "ENHANCED_GROUND_COMBAT_SOLDIER", "Enhanced Ground Combat Soldier", true),
       BASIC_ROTOR_WING_AIRCRAFT = new GROUPED_ENTITY(5, "BASIC_ROTOR_WING_AIRCRAFT", "Basic Rotor Wing Aircraft", true),
       ENHANCED_ROTOR_WING_AIRCRAFT = new GROUPED_ENTITY(6, "ENHANCED_ROTOR_WING_AIRCRAFT", "Enhanced Rotor Wing Aircraft", true),
       BASIC_FIXED_WING_AIRCRAFT = new GROUPED_ENTITY(7, "BASIC_FIXED_WING_AIRCRAFT", "Basic Fixed Wing Aircraft", true),
       ENHANCED_FIXED_WING_AIRCRAFT = new GROUPED_ENTITY(8, "ENHANCED_FIXED_WING_AIRCRAFT", "Enhanced Fixed Wing Aircraft", true),
       GROUND_LOGISTICS_VEHICLE = new GROUPED_ENTITY(9, "GROUND_LOGISTICS_VEHICLE", "Ground Logistics Vehicle", true);

    private GROUPED_ENTITY(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, GROUPED_ENTITY.class);
    }

    /** @see Value#values(Class) */
    public static List<GROUPED_ENTITY> values() {

        return values(GROUPED_ENTITY.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<GROUPED_ENTITY> values(boolean known) {

        return values(GROUPED_ENTITY.class, known);
    }

    /** @see Value#get(int, Class) */
    public static GROUPED_ENTITY get(int value) {

        return get(value, GROUPED_ENTITY.class);
    }
}

