package discover.vdis.enums;

import java.util.List;

/**
 * GRP_MEM_TYPE: This class is auto-generated by vdis.EnumGenerator
 */
public final class GRP_MEM_TYPE extends Value {

    public static final GRP_MEM_TYPE
       NOT_SPECIFIED = new GRP_MEM_TYPE(0, "NOT_SPECIFIED", "Not Specified", true),
       GROUP_LEADER = new GRP_MEM_TYPE(1, "GROUP_LEADER", "Group Leader", true),
       GROUP_MEMBER = new GRP_MEM_TYPE(2, "GROUP_MEMBER", "Group Member", true),
       FORMATION_LEADER = new GRP_MEM_TYPE(3, "FORMATION_LEADER", "Formation Leader", true),
       FORMATION_MEMBER = new GRP_MEM_TYPE(4, "FORMATION_MEMBER", "Formation Member", true),
       CONVOY_LEADER = new GRP_MEM_TYPE(5, "CONVOY_LEADER", "Convoy Leader", true),
       CONVOY_MEMBER = new GRP_MEM_TYPE(6, "CONVOY_MEMBER", "Convoy Member", true);

    private GRP_MEM_TYPE(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, GRP_MEM_TYPE.class);
    }

    /** @see Value#values(Class) */
    public static List<GRP_MEM_TYPE> values() {

        return values(GRP_MEM_TYPE.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<GRP_MEM_TYPE> values(boolean known) {

        return values(GRP_MEM_TYPE.class, known);
    }

    /** @see Value#get(int, Class) */
    public static GRP_MEM_TYPE get(int value) {

        return get(value, GRP_MEM_TYPE.class);
    }
}

