package discover.vdis.enums;

import java.util.List;

/**
 * HOIST_STATUS: This class is auto-generated by vdis.EnumGenerator
 */
public final class HOIST_STATUS extends Value {

    public static final HOIST_STATUS
       NOT_PRESENT = new HOIST_STATUS(0, "NOT_PRESENT", "Not Present", true),
       UNAVAILABLE = new HOIST_STATUS(1, "UNAVAILABLE", "Unavailable", true),
       AVAILABLE = new HOIST_STATUS(2, "AVAILABLE", "Available", true);

    private HOIST_STATUS(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, HOIST_STATUS.class);
    }

    /** @see Value#values(Class) */
    public static List<HOIST_STATUS> values() {

        return values(HOIST_STATUS.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<HOIST_STATUS> values(boolean known) {

        return values(HOIST_STATUS.class, known);
    }

    /** @see Value#get(int, Class) */
    public static HOIST_STATUS get(int value) {

        return get(value, HOIST_STATUS.class);
    }
}

