package discover.vdis.enums;

import java.util.List;

/**
 * HOOK_TYPE: This class is auto-generated by vdis.EnumGenerator
 */
public final class HOOK_TYPE extends Value {

    public static final HOOK_TYPE
       NOT_SPECIFIED = new HOOK_TYPE(0, "NOT_SPECIFIED", "Not Specified", true),
       SINGLE = new HOOK_TYPE(1, "SINGLE", "Single", true),
       FORWARD = new HOOK_TYPE(2, "FORWARD", "Forward", true),
       CENTER = new HOOK_TYPE(3, "CENTER", "Center", true),
       AFT = new HOOK_TYPE(4, "AFT", "Aft", true),
       TANDEM = new HOOK_TYPE(5, "TANDEM", "Tandem (Fore/Aft)", true),
       TANDEM_MISMANAGED_FORE_CENTER = new HOOK_TYPE(6, "TANDEM_MISMANAGED_FORE_CENTER", "Mismanaged Tandem (Fore/Center)", true),
       TANDEM_MISMANAGED_CENTER_AFT = new HOOK_TYPE(7, "TANDEM_MISMANAGED_CENTER_AFT", "Mismanaged Tandem (Center/Aft)", true),
       ALL = new HOOK_TYPE(8, "ALL", "All", true);

    private HOOK_TYPE(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, HOOK_TYPE.class);
    }

    /** @see Value#values(Class) */
    public static List<HOOK_TYPE> values() {

        return values(HOOK_TYPE.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<HOOK_TYPE> values(boolean known) {

        return values(HOOK_TYPE.class, known);
    }

    /** @see Value#get(int, Class) */
    public static HOOK_TYPE get(int value) {

        return get(value, HOOK_TYPE.class);
    }
}

