package discover.vdis.enums;

import java.util.List;

/**
 * IFF_SYSTEM_MODE: This class is auto-generated by vdis.EnumGenerator
 */
public final class IFF_SYSTEM_MODE extends Value {

    public static final IFF_SYSTEM_MODE
       IFF_SYS_MODE_NO_STATEMENT = new IFF_SYSTEM_MODE(0, "IFF_SYS_MODE_NO_STATEMENT", "No Statement", true),
       IFF_SYS_MODE_OFF = new IFF_SYSTEM_MODE(1, "IFF_SYS_MODE_OFF", "Off", true),
       IFF_SYS_MODE_STANDBY = new IFF_SYSTEM_MODE(2, "IFF_SYS_MODE_STANDBY", "Standby", true),
       IFF_SYS_MODE_NORMAL = new IFF_SYSTEM_MODE(3, "IFF_SYS_MODE_NORMAL", "Normal", true),
       IFF_SYS_MODE_EMERGENCY = new IFF_SYSTEM_MODE(4, "IFF_SYS_MODE_EMERGENCY", "Emergency", true);

    private IFF_SYSTEM_MODE(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, IFF_SYSTEM_MODE.class);
    }

    /** @see Value#values(Class) */
    public static List<IFF_SYSTEM_MODE> values() {

        return values(IFF_SYSTEM_MODE.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<IFF_SYSTEM_MODE> values(boolean known) {

        return values(IFF_SYSTEM_MODE.class, known);
    }

    /** @see Value#get(int, Class) */
    public static IFF_SYSTEM_MODE get(int value) {

        return get(value, IFF_SYSTEM_MODE.class);
    }
}

