package discover.vdis.enums;

import java.util.List;

/**
 * IFF_SYSTEM_NAME: This class is auto-generated by vdis.EnumGenerator
 */
public final class IFF_SYSTEM_NAME extends Value {

    public static final IFF_SYSTEM_NAME
       IFF_SYS_NAME_OTHER = new IFF_SYSTEM_NAME(0, "IFF_SYS_NAME_OTHER", "Not Used", true),
       IFF_SYS_NAME_MARK_X = new IFF_SYSTEM_NAME(1, "IFF_SYS_NAME_MARK_X", "Generic Mark X", true),
       IFF_SYS_NAME_MARK_XII = new IFF_SYSTEM_NAME(2, "IFF_SYS_NAME_MARK_XII", "Generic Mark XII", true),
       IFF_SYS_NAME_ATCRBS = new IFF_SYSTEM_NAME(3, "IFF_SYS_NAME_ATCRBS", "Generic ATCRBS", true),
       IFF_SYS_NAME_SOVIET = new IFF_SYSTEM_NAME(4, "IFF_SYS_NAME_SOVIET", "Generic Soviet", true),
       IFF_SYS_NAME_MODE_S = new IFF_SYSTEM_NAME(5, "IFF_SYS_NAME_MODE_S", "Generic Mode S", true),
       IFF_SYS_NAME_MARK_X_XII_ATCRBS = new IFF_SYSTEM_NAME(6, "IFF_SYS_NAME_MARK_X_XII_ATCRBS", "Generic Mark X/XII/ATCRBS", true),
       IFF_SYS_NAME_MARK_X_XII_ATCRBS_MODE_S = new IFF_SYSTEM_NAME(7, "IFF_SYS_NAME_MARK_X_XII_ATCRBS_MODE_S", "Generic Mark X/XII/ATCRBS/Mode S", true),
       IFF_SYS_NAME_ARI_5954 = new IFF_SYSTEM_NAME(8, "IFF_SYS_NAME_ARI_5954", "ARI 5954 (RRB)", true),
       IFF_SYS_NAME_ARI_5983 = new IFF_SYSTEM_NAME(9, "IFF_SYS_NAME_ARI_5983", "ARI 5983 (RRB)", true),
       IFF_SYS_NAME_RRB = new IFF_SYSTEM_NAME(10, "IFF_SYS_NAME_RRB", "Generic RRB ", true),
       IFF_SYS_NAME_MARK_XIIA = new IFF_SYSTEM_NAME(11, "IFF_SYS_NAME_MARK_XIIA", "Generic Mark XIIA   ", true),
       IFF_SYS_NAME_MODE_5 = new IFF_SYSTEM_NAME(12, "IFF_SYS_NAME_MODE_5", "Generic Mode 5", true),
       IFF_SYS_NAME_MARK_XIIA_CIT = new IFF_SYSTEM_NAME(13, "IFF_SYS_NAME_MARK_XIIA_CIT", "Generic Mark XIIA Combined Interrogator/Transponder (CIT) ", true),
       IFF_SYS_NAME_MARK_XII_CIT = new IFF_SYSTEM_NAME(14, "IFF_SYS_NAME_MARK_XII_CIT", "Generic Mark XII Combined Interrogator/Transponder (CIT) ", true),
       IFF_SYS_NAME_TCAS_I_ACAS_I_TRANSCEIVER = new IFF_SYSTEM_NAME(15, "IFF_SYS_NAME_TCAS_I_ACAS_I_TRANSCEIVER", "Generic TCAS I/ACAS I Transceiver", true),
       IFF_SYS_NAME_TCAS_II_ACAS_II_TRANSCEIVER = new IFF_SYSTEM_NAME(16, "IFF_SYS_NAME_TCAS_II_ACAS_II_TRANSCEIVER", "Generic TCAS II/ACAS II Transceiver", true),
       IFF_SYS_NAME_MARK_X_A = new IFF_SYSTEM_NAME(17, "IFF_SYS_NAME_MARK_X_A", "Generic Mark X (A)", true),
       IFF_SYS_NAME_MARK_X_SIF = new IFF_SYSTEM_NAME(18, "IFF_SYS_NAME_MARK_X_SIF", "Generic Mark X (SIF)", true);

    private IFF_SYSTEM_NAME(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, IFF_SYSTEM_NAME.class);
    }

    /** @see Value#values(Class) */
    public static List<IFF_SYSTEM_NAME> values() {

        return values(IFF_SYSTEM_NAME.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<IFF_SYSTEM_NAME> values(boolean known) {

        return values(IFF_SYSTEM_NAME.class, known);
    }

    /** @see Value#get(int, Class) */
    public static IFF_SYSTEM_NAME get(int value) {

        return get(value, IFF_SYSTEM_NAME.class);
    }
}

