package discover.vdis.enums;

import java.util.List;

/**
 * LAND_SMOKE: This class is auto-generated by vdis.EnumGenerator
 */
public final class LAND_SMOKE extends Value {

    public static final LAND_SMOKE
       NONE = new LAND_SMOKE(0, "NONE", "No Damage", true),
       RISING = new LAND_SMOKE(1, "RISING", "Rising Smoke", true),
       ENGINE = new LAND_SMOKE(2, "ENGINE", "Emitting Engine Smoke", true),
       ENGINE_RISING = new LAND_SMOKE(3, "ENGINE_RISING", "Emitting Engine Smoke and Rising Smoke", true);

    private LAND_SMOKE(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, LAND_SMOKE.class);
    }

    /** @see Value#values(Class) */
    public static List<LAND_SMOKE> values() {

        return values(LAND_SMOKE.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<LAND_SMOKE> values(boolean known) {

        return values(LAND_SMOKE.class, known);
    }

    /** @see Value#get(int, Class) */
    public static LAND_SMOKE get(int value) {

        return get(value, LAND_SMOKE.class);
    }
}

