package discover.vdis.enums;

import java.util.List;

/**
 * LASER_FUNCTION: This class is auto-generated by vdis.EnumGenerator
 */
public final class LASER_FUNCTION extends Value {

    public static final LASER_FUNCTION
       DESIGNATING = new LASER_FUNCTION(0, "DESIGNATING", "Designating", true),
       RANGING = new LASER_FUNCTION(1, "RANGING", "Ranging", true),
       IR_DESIGNATING = new LASER_FUNCTION(2, "IR_DESIGNATING", "IR Designating", true),
       BEAM_RIDING = new LASER_FUNCTION(3, "BEAM_RIDING", "Beam Riding", true),
       LASER_POINTING = new LASER_FUNCTION(4, "LASER_POINTING", "Laser Pointing", true),
       IR_MARKING = new LASER_FUNCTION(5, "IR_MARKING", "IR Marking", true),
       NVG_MARKING = new LASER_FUNCTION(6, "NVG_MARKING", "NVG Marking", true);

    private LASER_FUNCTION(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, LASER_FUNCTION.class);
    }

    /** @see Value#values(Class) */
    public static List<LASER_FUNCTION> values() {

        return values(LASER_FUNCTION.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<LASER_FUNCTION> values(boolean known) {

        return values(LASER_FUNCTION.class, known);
    }

    /** @see Value#get(int, Class) */
    public static LASER_FUNCTION get(int value) {

        return get(value, LASER_FUNCTION.class);
    }
}

