package discover.vdis.enums;

import java.util.List;

/**
 * LF_AGE_GROUP: This class is auto-generated by vdis.EnumGenerator
 */
public final class LF_AGE_GROUP extends Value {

    public static final LF_AGE_GROUP
       NOT_SPECIFIED = new LF_AGE_GROUP(0, "NOT_SPECIFIED", "Not Specified", true),
       NEWBORN = new LF_AGE_GROUP(1, "NEWBORN", "Newborn, 0-3 months)", true),
       INFANT = new LF_AGE_GROUP(2, "INFANT", "Infant, 3 months-1 year)", true),
       TODDLER = new LF_AGE_GROUP(3, "TODDLER", "Toddler, 1-3 years)", true),
       SMALL_CHILD = new LF_AGE_GROUP(4, "SMALL_CHILD", "Small Child, 3-6 years)", true),
       CHILD = new LF_AGE_GROUP(5, "CHILD", "Child, 6-10 years)", true),
       ADOLESCENT = new LF_AGE_GROUP(6, "ADOLESCENT", "Adolescent, 10-12 years)", true),
       TEENAGER = new LF_AGE_GROUP(7, "TEENAGER", "Teenager, 13-16 years)", true),
       EARLY_ADULTHOOD = new LF_AGE_GROUP(8, "EARLY_ADULTHOOD", "Early Adulthood, 17-25 years)", true),
       MIDDLE_ADULTHOOD = new LF_AGE_GROUP(9, "MIDDLE_ADULTHOOD", "Middle Adulthood, 26-40 years)", true),
       LATE_ADULTHOOD = new LF_AGE_GROUP(10, "LATE_ADULTHOOD", "Late Adulthood, 41-55 years)", true),
       SENIOR = new LF_AGE_GROUP(11, "SENIOR", "Senior, 55-70 years)", true),
       ELDERLY = new LF_AGE_GROUP(12, "ELDERLY", "Elderly, 71+ years)", true),
       CENTURION = new LF_AGE_GROUP(13, "CENTURION", "Centurion, 100+ years)", true);

    private LF_AGE_GROUP(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, LF_AGE_GROUP.class);
    }

    /** @see Value#values(Class) */
    public static List<LF_AGE_GROUP> values() {

        return values(LF_AGE_GROUP.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<LF_AGE_GROUP> values(boolean known) {

        return values(LF_AGE_GROUP.class, known);
    }

    /** @see Value#get(int, Class) */
    public static LF_AGE_GROUP get(int value) {

        return get(value, LF_AGE_GROUP.class);
    }
}

