package discover.vdis.enums;

import java.util.List;

/**
 * LF_COND_MTL: This class is auto-generated by vdis.EnumGenerator
 */
public final class LF_COND_MTL extends Value {

    public static final LF_COND_MTL
       LIFE_COND_MTL_NOT_SPECIFIED = new LF_COND_MTL(0, "LIFE_COND_MTL_NOT_SPECIFIED", "Not Specified", true),
       LIFE_COND_MTL_CLOTH = new LF_COND_MTL(1, "LIFE_COND_MTL_CLOTH", "Cloth", true),
       LIFE_COND_MTL_LEATHER = new LF_COND_MTL(2, "LIFE_COND_MTL_LEATHER", "Leather", true),
       LIFE_COND_MTL_RUBBER = new LF_COND_MTL(3, "LIFE_COND_MTL_RUBBER", "Rubber", true);

    private LF_COND_MTL(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, LF_COND_MTL.class);
    }

    /** @see Value#values(Class) */
    public static List<LF_COND_MTL> values() {

        return values(LF_COND_MTL.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<LF_COND_MTL> values(boolean known) {

        return values(LF_COND_MTL.class, known);
    }

    /** @see Value#get(int, Class) */
    public static LF_COND_MTL get(int value) {

        return get(value, LF_COND_MTL.class);
    }
}

