package discover.vdis.enums;

import java.util.List;

/**
 * LF_COND_CLEAN: This class is auto-generated by vdis.EnumGenerator
 */
public final class LF_COND_CLEAN extends Value {

    public static final LF_COND_CLEAN
       LIFE_COND_CLEAN_NOT_SPECIFIED = new LF_COND_CLEAN(0, "LIFE_COND_CLEAN_NOT_SPECIFIED", "Not Specified", true),
       LIFE_COND_CLEAN_SLIGHTLY_DIRTY = new LF_COND_CLEAN(1, "LIFE_COND_CLEAN_SLIGHTLY_DIRTY", "Slightly Dirty", true),
       LIFE_COND_CLEAN_MODERATELY_DIRTY = new LF_COND_CLEAN(2, "LIFE_COND_CLEAN_MODERATELY_DIRTY", "Moderately Dirty", true),
       LIFE_COND_CLEAN_VERY_DIRTY = new LF_COND_CLEAN(3, "LIFE_COND_CLEAN_VERY_DIRTY", "Very Dirty", true);

    private LF_COND_CLEAN(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, LF_COND_CLEAN.class);
    }

    /** @see Value#values(Class) */
    public static List<LF_COND_CLEAN> values() {

        return values(LF_COND_CLEAN.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<LF_COND_CLEAN> values(boolean known) {

        return values(LF_COND_CLEAN.class, known);
    }

    /** @see Value#get(int, Class) */
    public static LF_COND_CLEAN get(int value) {

        return get(value, LF_COND_CLEAN.class);
    }
}

