package discover.vdis.enums;

/**
 * This file is auto-generated (see vdis.EnumGenerator)
 */
public enum LF_CAT_LAND implements VdisEnum {

    OTH(0, "Other"),
    DIW(1, "Dismounted Infantry (with)"),
    DINV(2, "Dismounted Infantry (non-visible)"),
    CIVU(3, "Civilian (unarmed)"),
    CIVW(4, "Civilian (w/ weapons)"),
    ANI(5, "Animals"),
    MILITARY_GENERAL(6, "Military, General Regular Forces Military Personnel"),
    ARMY(7, "Army Regular Forces Military Personnel"),
    NAVY(8, "Navy Regular Forces Military Personnel"),
    MARINES(9, "Marines Regular Forces Military Personnel"),
    AIR_FORCE(10, "Air Force Regular Forces Military Personnel"),
    COAST_GUARD(11, "Coast Guard Regular Forces Military Personnel"),
    SPECIAL_FORCES(12, "Special Forces Regular Forces Military Personnel"),
    MERCHANT_MARINE(13, "Merchant Marine Regular Forces Military Personnel"),
    NATIONAL_GUARD(14, "National Guard Regular Forces Military Personnel"),
    RESERVED_15(15, "Reserved Regular Forces Military Personnel"),
    RESERVED_16(16, "Reserved Regular Forces Military Personnel"),
    RESERVED_17(17, "Reserved Regular Forces Military Personnel"),
    RESERVED_18(18, "Reserved Regular Forces Military Personnel"),
    RESERVED_19(19, "Reserved Regular Forces Military Personnel"),
    RESERVED_20(20, "Reserved Regular Forces Military Personnel"),
    RESERVED_21(21, "Reserved Regular Forces Military Personnel"),
    RESERVED_22(22, "Reserved Regular Forces Military Personnel"),
    RESERVED_23(23, "Reserved Regular Forces Military Personnel"),
    RESERVED_24(24, "Reserved Regular Forces Military Personnel"),
    PARAMILITARY(25, "Paramilitary Irregular Forces Military Personnel"),
    MILITIA(26, "Militia Irregular Forces Military Personnel"),
    GUERILLAS(27, "Guerillas Irregular Forces Military Personnel"),
    INSURGENTS(28, "Insurgents Irregular Forces Military Personnel"),
    TERRORIST_COMBATANTS(29, "Terrorist Combatants Irregular Forces Military Personnel"),
    REBELS(30, "Rebels Irregular Forces Military Personnel"),
    WARLORD_ARMY_PERSONNEL(31, "Warlord Army Personnel Irregular Forces Military Personnel"),
    RESERVED_32(32, "Reserved Irregular Forces Military Personnel"),
    RESERVED_33(33, "Reserved Irregular Forces Military Personnel"),
    RESERVED_34(34, "Reserved Irregular Forces Military Personnel"),
    RESERVED_35(35, "Reserved Irregular Forces Military Personnel"),
    RESERVED_36(36, "Reserved Irregular Forces Military Personnel"),
    RESERVED_37(37, "Reserved Irregular Forces Military Personnel"),
    RESERVED_38(38, "Reserved Irregular Forces Military Personnel"),
    RESERVED_39(39, "Reserved Irregular Forces Military Personnel"),
    GENERAL(40, "General Civilian Personnel"),
    MANAGEMENT(41, "Management Civilian Personnel"),
    BUSINESS(42, "Business Civilian Personnel"),
    FINANCIAL(43, "Financial Civilian Personnel"),
    COMPUTER(44, "Computer Civilian Personnel"),
    ARCHITECTURE(45, "Architecture Civilian Personnel"),
    ENGINEERING(46, "Engineering Civilian Personnel"),
    SCIENCE(47, "Science Civilian Personnel"),
    SOCIAL_SCIENCES(48, "Social Sciences Civilian Personnel"),
    LEGAL(49, "Legal Civilian Personnel"),
    EDUCATION(50, "Education Civilian Personnel"),
    ARTS_DESIGN(51, "Arts/Design Civilian Personnel"),
    ENTERTAINMENT(52, "Entertainment Civilian Personnel"),
    SPORTS(53, "Sports Civilian Personnel"),
    MEDIA(54, "Media Civilian Personnel"),
    HEALTHCARE(55, "Healthcare Civilian Personnel"),
    PROTECTIVE_SERVICE(56, "Protective Service Civilian Personnel"),
    FOOD_SERVICES(57, "Food Services Civilian Personnel"),
    CLEANING_MAINTENANCE(58, "Cleaning/Maintenance Civilian Personnel"),
    PERSONAL_CARE(59, "Personal Care Civilian Personnel"),
    SALES(60, "Sales Civilian Personnel"),
    OFFICE_SUPPORT(61, "Office Support Civilian Personnel"),
    AGRICULTURE(62, "Agriculture Civilian Personnel"),
    CONSTRUCTION(63, "Construction Civilian Personnel"),
    EXTRACTION(64, "Extraction Civilian Personnel"),
    INSTALL_MAINTENANCE(65, "Install/Maintenance Civilian Personnel"),
    PRODUCTION(66, "Production Civilian Personnel"),
    TRANSPORTATION(67, "Transportation Civilian Personnel"),
    MATERIAL_MOVING(68, "Material Moving Civilian Personnel"),
    RELIGION(69, "Religion Civilian Personnel"),
    GOVERNMENT(70, "Government Civilian Personnel"),
    NON_GOVERNMENT_ORG(71, "Non-Government Org Civilian Personnel"),
    SPACE_OPERATIONS(72, "Space Operations Civilian Personnel"),
    SPECIAL_STATUS(73, "Special Status Civilian Personnel"),
    RESERVED_74(74, "Reserved Civilian Personnel"),
    RESERVED_75(75, "Reserved Civilian Personnel"),
    RESERVED_76(76, "Reserved Civilian Personnel"),
    RESERVED_77(77, "Reserved Civilian Personnel"),
    RESERVED_78(78, "Reserved Civilian Personnel"),
    RESERVED_79(79, "Reserved Civilian Personnel"),
    ALLIGATOR_CAPTIVE(80, "Alligator (captive) Domesticated Animals"),
    ALPACA(81, "Alpaca Domesticated Animals"),
    BUFFALO(82, "Buffalo Domesticated Animals"),
    CAMEL(83, "Camel Domesticated Animals"),
    CARIBOU(84, "Caribou Domesticated Animals"),
    CAT(85, "Cat Domesticated Animals"),
    CATTLE(86, "Cattle Domesticated Animals"),
    CHICKEN(87, "Chicken Domesticated Animals"),
    CHINCHILLA_CAPTIVE_BRED(88, "Chinchilla (captive-bred) Domesticated Animals"),
    CRICKET_CAPT_BRED(89, "Cricket (capt-bred) Domesticated Animals"),
    DEER(90, "Deer Domesticated Animals"),
    DOG(91, "Dog Domesticated Animals"),
    DONKEY(92, "Donkey Domesticated Animals"),
    DUCK(93, "Duck Domesticated Animals"),
    ELEPHANT_CAPTIVE_BRED(94, "Elephant (captive-bred) Domesticated Animals"),
    ERMINE_CAPTIVE_BRED(95, "Ermine (captive-bred) Domesticated Animals"),
    FERRET(96, "Ferret Domesticated Animals"),
    FOX_CAPTIVE_BRED(97, "Fox (captive-bred) Domesticated Animals"),
    GEESE(98, "Geese Domesticated Animals"),
    GERBIL(99, "Gerbil Domesticated Animals"),
    GOAT(100, "Goat Domesticated Animals"),
    GUINEA_PIG(101, "Guinea pig Domesticated Animals"),
    HAMSTER(102, "Hamster Domesticated Animals"),
    HORSE(103, "Horse Domesticated Animals"),
    KANGAROO(104, "Kangaroo Domesticated Animals"),
    LLAMA(105, "Llama Domesticated Animals"),
    MINK_CAPTIVE_BRED(106, "Mink (captive-bred) Domesticated Animals"),
    MOUSE(107, "Mouse Domesticated Animals"),
    NIGHTCRAWLER(108, "Nightcrawler Domesticated Animals"),
    OSTRICH_CAPTIVE_BRED(109, "Ostrich (captive-bred) Domesticated Animals"),
    OTTER_CAPTIVE_BRED(110, "Otter (captive-bred) Domesticated Animals"),
    OXEN(111, "Oxen Domesticated Animals"),
    PIG(112, "Pig Domesticated Animals"),
    PIGEON(113, "Pigeon Domesticated Animals"),
    POSSUM(114, "Possum Domesticated Animals"),
    PRIMATE(115, "Primate Domesticated Animals"),
    RABBIT(116, "Rabbit Domesticated Animals"),
    RAT(117, "Rat Domesticated Animals"),
    SHEEP(118, "Sheep Domesticated Animals"),
    SILKWORM(119, "Silkworm Domesticated Animals"),
    SNAIL(120, "Snail Domesticated Animals"),
    SWAN_CAPTIVE_BRED(121, "Swan (captive-bred) Domesticated Animals"),
    TURKEYS(122, "Turkeys Domesticated Animals"),
    WORM_CAPTIVE_BRED(123, "Worm (captive-bred) Domesticated Animals"),
    YAK(124, "Yak Domesticated Animals"),
    RESERVED_125(125, "Reserved Domesticated Animals"),
    RESERVED_126(126, "Reserved Domesticated Animals"),
    RESERVED_127(127, "Reserved Domesticated Animals"),
    RESERVED_128(128, "Reserved Domesticated Animals"),
    RESERVED_129(129, "Reserved Domesticated Animals"),
    RESERVED_130(130, "Reserved Domesticated Animals"),
    RESERVED_131(131, "Reserved Domesticated Animals"),
    RESERVED_132(132, "Reserved Domesticated Animals"),
    RESERVED_133(133, "Reserved Domesticated Animals"),
    RESERVED_134(134, "Reserved Domesticated Animals"),
    RESERVED_135(135, "Reserved Domesticated Animals"),
    RESERVED_136(136, "Reserved Domesticated Animals"),
    RESERVED_137(137, "Reserved Domesticated Animals"),
    RESERVED_138(138, "Reserved Domesticated Animals"),
    RESERVED_139(139, "Reserved Domesticated Animals"),
    GENERAL_140(140, "General Mammals Wild"),
    AARDVARKS(141, "Aardvarks Mammals Wild"),
    ARMADILLOS_AND_RELATED(142, "Armadillos and related Mammals Wild"),
    BANDICOOTS_AND_RELATED(143, "Bandicoots and related Mammals Wild"),
    ELEPHANTS_AND_RELATED(144, "Elephants and related Mammals Wild"),
    EVEN_TOED_UNGULATES(145, "Even-toed ungulates Mammals Wild"),
    HYRAXES(146, "Hyraxes Mammals Wild"),
    INSECT_EATERS(147, "Insect-eaters Mammals Wild"),
    RABBITS_AND_RELATED(148, "Rabbits and related Mammals Wild"),
    KANGAROOS_AND_RELATED(149, "Kangaroos and related Mammals Wild"),
    MEAT_EATERS(150, "Meat-eaters Mammals Wild"),
    MOLES(151, "Moles Mammals Wild"),
    ODD_TOED_UNGULATES(152, "Odd-toed ungulates Mammals Wild"),
    OPOSSUMS(153, "Opossums Mammals Wild"),
    PANGOLINS_AND_RELATED(154, "Pangolins and related Mammals Wild"),
    PLATYPUS(155, "Platypus Mammals Wild"),
    PRIMATES(156, "Primates Mammals Wild"),
    RODENTS(157, "Rodents Mammals Wild"),
    SPINY_ANTEATERS(158, "Spiny anteaters Mammals Wild"),
    RESERVED_159(159, "Reserved Mammals Wild"),
    RESERVED_160(160, "Reserved Mammals Wild"),
    RESERVED_161(161, "Reserved Mammals Wild"),
    RESERVED_162(162, "Reserved Mammals Wild"),
    RESERVED_163(163, "Reserved Mammals Wild"),
    RESERVED_164(164, "Reserved Mammals Wild"),
    RESERVED_165(165, "Reserved Mammals Wild"),
    OTHER(166, "Other Birds Wild"),
    PENGUINS(167, "Penguins Birds Wild"),
    OSTRICHES(168, "Ostriches Birds Wild"),
    RESERVED_169(169, "Reserved Birds Wild"),
    SNAKES(170, "Snakes Reptiles Wild"),
    ALLIGATORS_CROCODILES(171, "Alligators/Crocodiles Reptiles Wild"),
    TUATARAS(172, "Tuataras Reptiles Wild"),
    LIZARDS(173, "Lizards Reptiles Wild"),
    WORM_LIZARDS(174, "Worm Lizards Reptiles Wild"),
    TURTLES(175, "Turtles Reptiles Wild"),
    RESERVED_176(176, "Reserved Reptiles Wild"),
    RESERVED_177(177, "Reserved Reptiles Wild"),
    RESERVED_178(178, "Reserved Reptiles Wild"),
    RESERVED_179(179, "Reserved Reptiles Wild"),
    GENERAL_180(180, "General Insects Wild"),
    BEETLES(181, "Beetles Insects Wild"),
    ANTS(182, "Ants Insects Wild"),
    TRUE_BUGS(183, "True Bugs Insects Wild"),
    GRASSHOPPER(184, "Grasshopper Insects Wild"),
    CRICKETS(185, "Crickets Insects Wild"),
    COCKROACHES(186, "Cockroaches Insects Wild"),
    MANTIDS(187, "Mantids Insects Wild"),
    CICADAS_APHIDS(188, "Cicadas/Aphids Insects Wild"),
    SCALE_INSECTS(189, "Scale insects Insects Wild"),
    RESERVED_190(190, "Reserved Insects Wild"),
    RESERVED_191(191, "Reserved Insects Wild"),
    RESERVED_192(192, "Reserved Insects Wild"),
    GENERAL_193(193, "General Amphibians Wild"),
    RESERVED_194(194, "Reserved Amphibians Wild"),
    RESERVED_195(195, "Reserved Amphibians Wild"),
    SPIDERS_AND_RELATED(196, "Spiders and related Other Animals Wild"),
    RESERVED_197(197, "Reserved Other Animals Wild"),
    RESERVED_198(198, "Reserved Other Animals Wild"),
    RESERVED_199(199, "Reserved Other Animals Wild"),
    GRAINS(200, "Grains Domesticated Plants"),
    FRUIT_TREES(201, "Fruit Trees Domesticated Plants"),
    VEGETABLES(202, "Vegetables Domesticated Plants"),
    FLOWERS(203, "Flowers Domesticated Plants"),
    RESERVED_204(204, "Reserved Domesticated Plants"),
    RESERVED_205(205, "Reserved Domesticated Plants"),
    RESERVED_206(206, "Reserved Domesticated Plants"),
    RESERVED_207(207, "Reserved Domesticated Plants"),
    RESERVED_208(208, "Reserved Domesticated Plants"),
    RESERVED_209(209, "Reserved Domesticated Plants"),
    RESERVED_210(210, "Reserved Domesticated Plants"),
    RESERVED_211(211, "Reserved Domesticated Plants"),
    RESERVED_212(212, "Reserved Domesticated Plants"),
    RESERVED_213(213, "Reserved Domesticated Plants"),
    RESERVED_214(214, "Reserved Domesticated Plants"),
    RESERVED_215(215, "Reserved Domesticated Plants"),
    RESERVED_216(216, "Reserved Domesticated Plants"),
    RESERVED_217(217, "Reserved Domesticated Plants"),
    RESERVED_218(218, "Reserved Domesticated Plants"),
    RESERVED_219(219, "Reserved Domesticated Plants"),
    RESERVED_220(220, "Reserved Domesticated Plants"),
    RESERVED_221(221, "Reserved Domesticated Plants"),
    RESERVED_222(222, "Reserved Domesticated Plants"),
    RESERVED_223(223, "Reserved Domesticated Plants"),
    RESERVED_224(224, "Reserved Domesticated Plants"),
    RESERVED_225(225, "Reserved Domesticated Plants"),
    RESERVED_226(226, "Reserved Domesticated Plants"),
    RESERVED_227(227, "Reserved Domesticated Plants"),
    RESERVED_228(228, "Reserved Domesticated Plants"),
    RESERVED_229(229, "Reserved Domesticated Plants"),
    SHRUBS_BUSHES(230, "Shrubs/Bushes Wild Plants"),
    WILD_FLOWERS(231, "Wild Flowers Wild Plants"),
    WILD_GRASSES(232, "Wild Grasses Wild Plants"),
    MOSSES(233, "Mosses Wild Plants"),
    FERNS(234, "Ferns Wild Plants"),
    LICHENS(235, "Lichens Wild Plants"),
    OTHER_FLOWERING_DICOT_PLANTS(236, "Other Flowering Dicot Plants Wild Plants"),
    OTHER_FLOWERING_MONOCOT_PLANTS(237, "Other Flowering Monocot Plants Wild Plants"),
    RESERVED_238(238, "Reserved Wild Plants"),
    RESERVED_239(239, "Reserved Wild Plants"),
    DICOTS_BROADLEAF_HARDWOODS(240, "Dicots (broadleaf/hardwoods) Trees Plants"),
    MONOCOTS(241, "Monocots Trees Plants"),
    CONIFERS_SOFTWOODS(242, "Conifers (Softwoods) Trees Plants"),
    GINKGOS(243, "Ginkgos Trees Plants"),
    CYCADS(244, "Cycads Trees Plants"),
    TREE_FERNS(245, "Tree Ferns Trees Plants"),
    RESERVED_246(246, "Reserved Trees Plants"),
    RESERVED_247(247, "Reserved Trees Plants"),
    RESERVED_248(248, "Reserved Trees Plants"),
    RESERVED_249(249, "Reserved Trees Plants"),
    OTHER_250(250, "Other Microbes"),
    BACTERIA(251, "Bacteria Microbes"),
    VIRUSES(252, "Viruses Microbes"),
    FUNGI(253, "Fungi Microbes"),
    ALGAE(254, "Algae Microbes"),
    RESERVED_255(255, "Reserved Microbes");

    private final int value;
    private final String description;

    private LF_CAT_LAND(int value, String description) {

        this.value = value;
        this.description = description;
    }

    @Override
    public int getValue() {

        return value;
    }

    @Override
    public String getDescription() {

        return description;
    }
}

