package discover.vdis.enums;

import java.util.List;

/**
 * LF_COMPLIANCE: This class is auto-generated by vdis.EnumGenerator
 */
public final class LF_COMPLIANCE extends Value {

    public static final LF_COMPLIANCE
       OTHER = new LF_COMPLIANCE(0, "OTHER", "Other", true),
       DETAINED = new LF_COMPLIANCE(1, "DETAINED", "Detained", true),
       SURRENDER = new LF_COMPLIANCE(2, "SURRENDER", "Surrender", true),
       USING_FISTS = new LF_COMPLIANCE(3, "USING_FISTS", "Using Fists", true),
       VERBAL_ABUSE_LEVEL_1 = new LF_COMPLIANCE(4, "VERBAL_ABUSE_LEVEL_1", "Verbal Abuse Level 1", true),
       VERBAL_ABUSE_LEVEL_2 = new LF_COMPLIANCE(5, "VERBAL_ABUSE_LEVEL_2", "Verbal Abuse Level 2", true),
       VERBAL_ABUSE_LEVEL_3 = new LF_COMPLIANCE(6, "VERBAL_ABUSE_LEVEL_3", "Verbal Abuse Level 3", true),
       PASSIVE_RESISTANCE_LEVEL_1 = new LF_COMPLIANCE(7, "PASSIVE_RESISTANCE_LEVEL_1", "Passive Resistance Level 1", true),
       PASSIVE_RESISTANCE_LEVEL_2 = new LF_COMPLIANCE(8, "PASSIVE_RESISTANCE_LEVEL_2", "Passive Resistance Level 2", true),
       PASSIVE_RESISTANCE_LEVEL_3 = new LF_COMPLIANCE(9, "PASSIVE_RESISTANCE_LEVEL_3", "Passive Resistance Level 3", true),
       USING_NON_LETHAL_WEAPON_1 = new LF_COMPLIANCE(10, "USING_NON_LETHAL_WEAPON_1", "Using Non-lethal Weapon 1", true),
       USING_NON_LETHAL_WEAPON_2 = new LF_COMPLIANCE(11, "USING_NON_LETHAL_WEAPON_2", "Using Non-lethal Weapon 2", true),
       USING_NON_LETHAL_WEAPON_3 = new LF_COMPLIANCE(12, "USING_NON_LETHAL_WEAPON_3", "Using Non-lethal Weapon 3", true),
       USING_NON_LETHAL_WEAPON_4 = new LF_COMPLIANCE(13, "USING_NON_LETHAL_WEAPON_4", "Using Non-lethal Weapon 4", true),
       USING_NON_LETHAL_WEAPON_5 = new LF_COMPLIANCE(14, "USING_NON_LETHAL_WEAPON_5", "Using Non-lethal Weapon 5", true),
       USING_NON_LETHAL_WEAPON_6 = new LF_COMPLIANCE(15, "USING_NON_LETHAL_WEAPON_6", "Using Non-lethal Weapon 6", true);

    private LF_COMPLIANCE(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, LF_COMPLIANCE.class);
    }

    /** @see Value#values(Class) */
    public static List<LF_COMPLIANCE> values() {

        return values(LF_COMPLIANCE.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<LF_COMPLIANCE> values(boolean known) {

        return values(LF_COMPLIANCE.class, known);
    }

    /** @see Value#get(int, Class) */
    public static LF_COMPLIANCE get(int value) {

        return get(value, LF_COMPLIANCE.class);
    }
}

