package discover.vdis.enums;

import java.util.List;

/**
 * LF_CLOTH_TYPE: This class is auto-generated by vdis.EnumGenerator
 */
public final class LF_CLOTH_TYPE extends Value {

    public static final LF_CLOTH_TYPE
       UNIFORM_COLOR = new LF_CLOTH_TYPE(0, "UNIFORM_COLOR", "Uniform Color", true),
       CAMOUFLAGE = new LF_CLOTH_TYPE(1, "CAMOUFLAGE", "Camouflage", true);

    private LF_CLOTH_TYPE(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, LF_CLOTH_TYPE.class);
    }

    /** @see Value#values(Class) */
    public static List<LF_CLOTH_TYPE> values() {

        return values(LF_CLOTH_TYPE.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<LF_CLOTH_TYPE> values(boolean known) {

        return values(LF_CLOTH_TYPE.class, known);
    }

    /** @see Value#get(int, Class) */
    public static LF_CLOTH_TYPE get(int value) {

        return get(value, LF_CLOTH_TYPE.class);
    }
}

