package discover.vdis.enums;

import java.util.List;

/**
 * LF_CAMOUFLAGE_TYPE: This class is auto-generated by vdis.EnumGenerator
 */
public final class LF_CAMOUFLAGE_TYPE extends Value {

    public static final LF_CAMOUFLAGE_TYPE
       DESERT = new LF_CAMOUFLAGE_TYPE(0, "DESERT", "Desert Camouflage", true),
       WINTER = new LF_CAMOUFLAGE_TYPE(1, "WINTER", "Winter Camouflage", true),
       FOREST = new LF_CAMOUFLAGE_TYPE(2, "FOREST", "Forest Camouflage", true),
       NONE = new LF_CAMOUFLAGE_TYPE(3, "NONE", "No Camouflage", true);

    private LF_CAMOUFLAGE_TYPE(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, LF_CAMOUFLAGE_TYPE.class);
    }

    /** @see Value#values(Class) */
    public static List<LF_CAMOUFLAGE_TYPE> values() {

        return values(LF_CAMOUFLAGE_TYPE.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<LF_CAMOUFLAGE_TYPE> values(boolean known) {

        return values(LF_CAMOUFLAGE_TYPE.class, known);
    }

    /** @see Value#get(int, Class) */
    public static LF_CAMOUFLAGE_TYPE get(int value) {

        return get(value, LF_CAMOUFLAGE_TYPE.class);
    }
}

