package discover.vdis.enums;

import java.util.List;

/**
 * LF_DECAL_SCHEME: This class is auto-generated by vdis.EnumGenerator
 */
public final class LF_DECAL_SCHEME extends Value {

    public static final LF_DECAL_SCHEME
       NONE = new LF_DECAL_SCHEME(0, "NONE", "None", true),
       BOSTON_RED_SOX = new LF_DECAL_SCHEME(1, "BOSTON_RED_SOX", "Boston Red Sox", true),
       NEW_ENGLAND_PATRIOTS = new LF_DECAL_SCHEME(2, "NEW_ENGLAND_PATRIOTS", "New England Patriots", true),
       ORLANDO_MAGIC = new LF_DECAL_SCHEME(3, "ORLANDO_MAGIC", "Orlando Magic", true),
       NIKE = new LF_DECAL_SCHEME(4, "NIKE", "Nike", true),
       DISNEY_WORLD = new LF_DECAL_SCHEME(5, "DISNEY_WORLD", "Disney World", true),
       POLICE = new LF_DECAL_SCHEME(6, "POLICE", "Police", true),
       FBI = new LF_DECAL_SCHEME(7, "FBI", "FBI", true),
       US_MARSHAL = new LF_DECAL_SCHEME(8, "US_MARSHAL", "US Marshal", true);

    private LF_DECAL_SCHEME(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, LF_DECAL_SCHEME.class);
    }

    /** @see Value#values(Class) */
    public static List<LF_DECAL_SCHEME> values() {

        return values(LF_DECAL_SCHEME.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<LF_DECAL_SCHEME> values(boolean known) {

        return values(LF_DECAL_SCHEME.class, known);
    }

    /** @see Value#get(int, Class) */
    public static LF_DECAL_SCHEME get(int value) {

        return get(value, LF_DECAL_SCHEME.class);
    }
}

