package discover.vdis.enums;

import java.util.List;

/**
 * LF_ETHNICITY: This class is auto-generated by vdis.EnumGenerator
 */
public final class LF_ETHNICITY extends Value {

    public static final LF_ETHNICITY
       NOT_SPECIFIED = new LF_ETHNICITY(0, "NOT_SPECIFIED", "Not Specified", true),
       ASIAN = new LF_ETHNICITY(1, "ASIAN", "Asian", true),
       PACIFIC_ISLANDER = new LF_ETHNICITY(2, "PACIFIC_ISLANDER", "Pacific Islander", true),
       BLACK = new LF_ETHNICITY(3, "BLACK", "Black", true),
       EAST_ASIAN = new LF_ETHNICITY(4, "EAST_ASIAN", "East Asian", true),
       HISPANIC = new LF_ETHNICITY(5, "HISPANIC", "Hispanic", true),
       WHITE = new LF_ETHNICITY(6, "WHITE", "White", true),
       ARAB = new LF_ETHNICITY(7, "ARAB", "Arab", true),
       HOMOGENOUS_CTRY = new LF_ETHNICITY(8, "HOMOGENOUS_CTRY", "Homogenous Country Code", true),
       INDIGENOUS_CTRY = new LF_ETHNICITY(9, "INDIGENOUS_CTRY", "Indigenous Country Code", true);

    private LF_ETHNICITY(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, LF_ETHNICITY.class);
    }

    /** @see Value#values(Class) */
    public static List<LF_ETHNICITY> values() {

        return values(LF_ETHNICITY.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<LF_ETHNICITY> values(boolean known) {

        return values(LF_ETHNICITY.class, known);
    }

    /** @see Value#get(int, Class) */
    public static LF_ETHNICITY get(int value) {

        return get(value, LF_ETHNICITY.class);
    }
}

