package discover.vdis.enums;

import java.util.List;

/**
 * LF_EQ_CHUTE: This class is auto-generated by vdis.EnumGenerator
 */
public final class LF_EQ_CHUTE extends Value {

    public static final LF_EQ_CHUTE
       LF_EQUIP_CHUTE_DOES_NOT_HAVE = new LF_EQ_CHUTE(0, "LF_EQUIP_CHUTE_DOES_NOT_HAVE", "Does not have", true),
       LF_EQUIP_CHUTE_NOT_DEPLOYED = new LF_EQ_CHUTE(1, "LF_EQUIP_CHUTE_NOT_DEPLOYED", "Not Deployed", true),
       LF_EQUIP_CHUTE_DEPLOYED = new LF_EQ_CHUTE(2, "LF_EQUIP_CHUTE_DEPLOYED", "Deployed", true);

    private LF_EQ_CHUTE(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, LF_EQ_CHUTE.class);
    }

    /** @see Value#values(Class) */
    public static List<LF_EQ_CHUTE> values() {

        return values(LF_EQ_CHUTE.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<LF_EQ_CHUTE> values(boolean known) {

        return values(LF_EQ_CHUTE.class, known);
    }

    /** @see Value#get(int, Class) */
    public static LF_EQ_CHUTE get(int value) {

        return get(value, LF_EQ_CHUTE.class);
    }
}

