package discover.vdis.enums;

import java.util.List;

/**
 * LF_EQ_LASER: This class is auto-generated by vdis.EnumGenerator
 */
public final class LF_EQ_LASER extends Value {

    public static final LF_EQ_LASER
       NONE = new LF_EQ_LASER(0, "NONE", "None", true),
       LASER_POINTER = new LF_EQ_LASER(1, "LASER_POINTER", "Laser Pointer", true),
       LASER_DESIGNATOR = new LF_EQ_LASER(2, "LASER_DESIGNATOR", "Laser Designator", true),
       LASER_RANGE_FINDER = new LF_EQ_LASER(3, "LASER_RANGE_FINDER", "Laser Range Finder", true);

    private LF_EQ_LASER(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, LF_EQ_LASER.class);
    }

    /** @see Value#values(Class) */
    public static List<LF_EQ_LASER> values() {

        return values(LF_EQ_LASER.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<LF_EQ_LASER> values(boolean known) {

        return values(LF_EQ_LASER.class, known);
    }

    /** @see Value#get(int, Class) */
    public static LF_EQ_LASER get(int value) {

        return get(value, LF_EQ_LASER.class);
    }
}

