package discover.vdis.enums;

import java.util.List;

/**
 * LF_GENDER: This class is auto-generated by vdis.EnumGenerator
 */
public final class LF_GENDER extends Value {

    public static final LF_GENDER
       MALE = new LF_GENDER(0, "MALE", "Male", true),
       FEMALE = new LF_GENDER(1, "FEMALE", "Female", true);

    private LF_GENDER(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, LF_GENDER.class);
    }

    /** @see Value#values(Class) */
    public static List<LF_GENDER> values() {

        return values(LF_GENDER.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<LF_GENDER> values(boolean known) {

        return values(LF_GENDER.class, known);
    }

    /** @see Value#get(int, Class) */
    public static LF_GENDER get(int value) {

        return get(value, LF_GENDER.class);
    }
}

