package discover.vdis.enums;

import java.util.List;

/**
 * LF_HEALTH: This class is auto-generated by vdis.EnumGenerator
 */
public final class LF_HEALTH extends Value {

    public static final LF_HEALTH
       NO_INJURY = new LF_HEALTH(0, "NO_INJURY", "No Injury", true),
       SLIGHT_INJURY = new LF_HEALTH(1, "SLIGHT_INJURY", "Slight Injury", true),
       MODERATE_INJURY = new LF_HEALTH(2, "MODERATE_INJURY", "Moderate Injury", true),
       FATAL_INJURY = new LF_HEALTH(3, "FATAL_INJURY", "Fatal Injury", true);

    private LF_HEALTH(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, LF_HEALTH.class);
    }

    /** @see Value#values(Class) */
    public static List<LF_HEALTH> values() {

        return values(LF_HEALTH.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<LF_HEALTH> values(boolean known) {

        return values(LF_HEALTH.class, known);
    }

    /** @see Value#get(int, Class) */
    public static LF_HEALTH get(int value) {

        return get(value, LF_HEALTH.class);
    }
}

