package discover.vdis.enums;

import java.util.List;

/**
 * LF_POSTURE: This class is auto-generated by vdis.EnumGenerator
 */
public final class LF_POSTURE extends Value {

    public static final LF_POSTURE
       OTHER = new LF_POSTURE(0, "OTHER", "Other", true),
       UPRIGHT_STANDING_STILL = new LF_POSTURE(1, "UPRIGHT_STANDING_STILL", "Upright Standing Still", true),
       UPRIGHT_WALKING = new LF_POSTURE(2, "UPRIGHT_WALKING", "Upright Walking", true),
       UPRIGHT_RUNNING = new LF_POSTURE(3, "UPRIGHT_RUNNING", "Upright Running", true),
       KNEELING = new LF_POSTURE(4, "KNEELING", "Kneeling", true),
       PRONE = new LF_POSTURE(5, "PRONE", "Prone", true),
       CRAWLING = new LF_POSTURE(6, "CRAWLING", "Crawling", true),
       SWIMMING = new LF_POSTURE(7, "SWIMMING", "Swimming", true),
       PARACHUTING = new LF_POSTURE(8, "PARACHUTING", "Parachuting", true),
       JUMPING = new LF_POSTURE(9, "JUMPING", "Jumping", true),
       SITTING = new LF_POSTURE(10, "SITTING", "Sitting", true),
       SQUATTING = new LF_POSTURE(11, "SQUATTING", "Squatting", true),
       CROUCHING = new LF_POSTURE(12, "CROUCHING", "Crouching", true),
       WADING = new LF_POSTURE(13, "WADING", "Wading", true),
       SURRENDER = new LF_POSTURE(14, "SURRENDER", "Surrender", true),
       DETAINED = new LF_POSTURE(15, "DETAINED", "Detained", true);

    private LF_POSTURE(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, LF_POSTURE.class);
    }

    /** @see Value#values(Class) */
    public static List<LF_POSTURE> values() {

        return values(LF_POSTURE.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<LF_POSTURE> values(boolean known) {

        return values(LF_POSTURE.class, known);
    }

    /** @see Value#get(int, Class) */
    public static LF_POSTURE get(int value) {

        return get(value, LF_POSTURE.class);
    }
}

