package discover.vdis.enums;

import java.util.List;

/**
 * LF_PRIM_COND_HEAD: This class is auto-generated by vdis.EnumGenerator
 */
public final class LF_PRIM_COND_HEAD extends Value {

    public static final LF_PRIM_COND_HEAD
       LIFE_PRIM_COND_HEAD_NOT_SPECIFIED = new LF_PRIM_COND_HEAD(0, "LIFE_PRIM_COND_HEAD_NOT_SPECIFIED", "Not Specified", true),
       LIFE_PRIM_COND_HEAD_BALD = new LF_PRIM_COND_HEAD(1, "LIFE_PRIM_COND_HEAD_BALD", "Bald", true),
       LIFE_PRIM_COND_HEAD_SHORT = new LF_PRIM_COND_HEAD(2, "LIFE_PRIM_COND_HEAD_SHORT", "Short", true),
       LIFE_PRIM_COND_HEAD_LONG = new LF_PRIM_COND_HEAD(3, "LIFE_PRIM_COND_HEAD_LONG", "Long", true);

    private LF_PRIM_COND_HEAD(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, LF_PRIM_COND_HEAD.class);
    }

    /** @see Value#values(Class) */
    public static List<LF_PRIM_COND_HEAD> values() {

        return values(LF_PRIM_COND_HEAD.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<LF_PRIM_COND_HEAD> values(boolean known) {

        return values(LF_PRIM_COND_HEAD.class, known);
    }

    /** @see Value#get(int, Class) */
    public static LF_PRIM_COND_HEAD get(int value) {

        return get(value, LF_PRIM_COND_HEAD.class);
    }
}

