package discover.vdis.enums;

import java.util.List;

/**
 * LF_SEC_COND_FACIAL: This class is auto-generated by vdis.EnumGenerator
 */
public final class LF_SEC_COND_FACIAL extends Value {

    public static final LF_SEC_COND_FACIAL
       LIFE_SEC_COND_FACIAL_NOT_SPECIFIED = new LF_SEC_COND_FACIAL(0, "LIFE_SEC_COND_FACIAL_NOT_SPECIFIED", "Not Specified", true),
       LIFE_SEC_COND_FACIAL_CLEAN_SHAVEN = new LF_SEC_COND_FACIAL(1, "LIFE_SEC_COND_FACIAL_CLEAN_SHAVEN", "Clean Shaven", true),
       LIFE_SEC_COND_FACIAL_SHORT_BEARD = new LF_SEC_COND_FACIAL(2, "LIFE_SEC_COND_FACIAL_SHORT_BEARD", "Short Beard", true),
       LIFE_SEC_COND_FACIAL_LONG_BEARD = new LF_SEC_COND_FACIAL(3, "LIFE_SEC_COND_FACIAL_LONG_BEARD", "Long Beard", true);

    private LF_SEC_COND_FACIAL(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, LF_SEC_COND_FACIAL.class);
    }

    /** @see Value#values(Class) */
    public static List<LF_SEC_COND_FACIAL> values() {

        return values(LF_SEC_COND_FACIAL.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<LF_SEC_COND_FACIAL> values(boolean known) {

        return values(LF_SEC_COND_FACIAL.class, known);
    }

    /** @see Value#get(int, Class) */
    public static LF_SEC_COND_FACIAL get(int value) {

        return get(value, LF_SEC_COND_FACIAL.class);
    }
}

