package discover.vdis.enums;

import java.util.List;

/**
 * MAJOR_MODULATION: This class is auto-generated by vdis.EnumGenerator
 */
public final class MAJOR_MODULATION extends Value {

    public static final MAJOR_MODULATION
       MAJ_MOD_OTHER = new MAJOR_MODULATION(0, "MAJ_MOD_OTHER", "Other", true),
       MAJ_MOD_AMPLITUDE = new MAJOR_MODULATION(1, "MAJ_MOD_AMPLITUDE", "Amplitude", true),
       MAJ_MOD_AMPLITUDE_AND_ANGLE = new MAJOR_MODULATION(2, "MAJ_MOD_AMPLITUDE_AND_ANGLE", "Amplitude And Angle", true),
       MAJ_MOD_ANGLE = new MAJOR_MODULATION(3, "MAJ_MOD_ANGLE", "Angle", true),
       MAJ_MOD_COMBINATION = new MAJOR_MODULATION(4, "MAJ_MOD_COMBINATION", "Combination", true),
       MAJ_MOD_PULSE = new MAJOR_MODULATION(5, "MAJ_MOD_PULSE", "Pulse", true),
       MAJ_MOD_UNMODULATED = new MAJOR_MODULATION(6, "MAJ_MOD_UNMODULATED", "Unmodulated", true),
       MAJ_MOD_CPSM = new MAJOR_MODULATION(7, "MAJ_MOD_CPSM", "Carrier Phase Shift Modulation (CPSM)", true);

    private MAJOR_MODULATION(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, MAJOR_MODULATION.class);
    }

    /** @see Value#values(Class) */
    public static List<MAJOR_MODULATION> values() {

        return values(MAJOR_MODULATION.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<MAJOR_MODULATION> values(boolean known) {

        return values(MAJOR_MODULATION.class, known);
    }

    /** @see Value#get(int, Class) */
    public static MAJOR_MODULATION get(int value) {

        return get(value, MAJOR_MODULATION.class);
    }
}

