package discover.vdis.enums;

import java.util.List;

/**
 * MESSAGE_FORMAT_ENUM: This class is auto-generated by vdis.EnumGenerator
 */
public final class MESSAGE_FORMAT_ENUM extends Value {

    public static final MESSAGE_FORMAT_ENUM
       MESSAGE_FORMAT_47001C_LINK_16 = new MESSAGE_FORMAT_ENUM(0, "MESSAGE_FORMAT_47001C_LINK_16", "Link 16 (J-series) message", true),
       MESSAGE_FORMAT_47001C_BINARY = new MESSAGE_FORMAT_ENUM(1, "MESSAGE_FORMAT_47001C_BINARY", "Binary File", true),
       MESSAGE_FORMAT_47001C_VMF = new MESSAGE_FORMAT_ENUM(2, "MESSAGE_FORMAT_47001C_VMF", "Variable Message Format (VMF) (K-series) message", true),
       MESSAGE_FORMAT_47001C_NITFS = new MESSAGE_FORMAT_ENUM(3, "MESSAGE_FORMAT_47001C_NITFS", "National Imagery Transmission Format System (NITFS)", true),
       MESSAGE_FORMAT_47001C_FWD_MSG = new MESSAGE_FORMAT_ENUM(4, "MESSAGE_FORMAT_47001C_FWD_MSG", "Forwarded Message (FWD MSG)", true),
       MESSAGE_FORMAT_47001C_USMTF = new MESSAGE_FORMAT_ENUM(5, "MESSAGE_FORMAT_47001C_USMTF", "United States Message Text Format (USMTF)", true),
       MESSAGE_FORMAT_47001C_DOI_103 = new MESSAGE_FORMAT_ENUM(6, "MESSAGE_FORMAT_47001C_DOI_103", "DOI-103", true),
       MESSAGE_FORMAT_47001C_XML_MTF = new MESSAGE_FORMAT_ENUM(7, "MESSAGE_FORMAT_47001C_XML_MTF", "eXtensible Markup Language (XML) - Message Text Format (MTF)", true),
       MESSAGE_FORMAT_47001C_XML_VMF = new MESSAGE_FORMAT_ENUM(8, "MESSAGE_FORMAT_47001C_XML_VMF", "eXtensible Markup Language (XML) - Variable Message Format (VMF)", true),
       MESSAGE_FORMAT_AFAPD = new MESSAGE_FORMAT_ENUM(16, "MESSAGE_FORMAT_AFAPD", "AFAPD", true);

    private MESSAGE_FORMAT_ENUM(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, MESSAGE_FORMAT_ENUM.class);
    }

    /** @see Value#values(Class) */
    public static List<MESSAGE_FORMAT_ENUM> values() {

        return values(MESSAGE_FORMAT_ENUM.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<MESSAGE_FORMAT_ENUM> values(boolean known) {

        return values(MESSAGE_FORMAT_ENUM.class, known);
    }

    /** @see Value#get(int, Class) */
    public static MESSAGE_FORMAT_ENUM get(int value) {

        return get(value, MESSAGE_FORMAT_ENUM.class);
    }
}

