package discover.vdis.enums;

import java.util.List;

/**
 * MUN_CAT: This class is auto-generated by vdis.EnumGenerator
 */
public final class MUN_CAT extends Value {

    public static final MUN_CAT
       OTH = new MUN_CAT(0, "OTH", "Other", true),
       GUID = new MUN_CAT(1, "GUID", "Guided", true),
       BALL = new MUN_CAT(2, "BALL", "Ballistic", true),
       FIX = new MUN_CAT(3, "FIX", "Fixed", true);

    private MUN_CAT(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, MUN_CAT.class);
    }

    /** @see Value#values(Class) */
    public static List<MUN_CAT> values() {

        return values(MUN_CAT.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<MUN_CAT> values(boolean known) {

        return values(MUN_CAT.class, known);
    }

    /** @see Value#get(int, Class) */
    public static MUN_CAT get(int value) {

        return get(value, MUN_CAT.class);
    }
}

