package discover.vdis.enums;

import java.util.List;

/**
 * MUNITION_STATUS: This class is auto-generated by vdis.EnumGenerator
 */
public final class MUNITION_STATUS extends Value {

    public static final MUNITION_STATUS
       MUNREC_MUNITION_STATUS_OTHER = new MUNITION_STATUS(0, "MUNREC_MUNITION_STATUS_OTHER", "Other", true),
       MUNREC_MUNITION_STATUS_READY = new MUNITION_STATUS(1, "MUNREC_MUNITION_STATUS_READY", "Ready", true),
       MUNREC_MUNITION_STATUS_INVENTORY = new MUNITION_STATUS(2, "MUNREC_MUNITION_STATUS_INVENTORY", "Inventory", true);

    private MUNITION_STATUS(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, MUNITION_STATUS.class);
    }

    /** @see Value#values(Class) */
    public static List<MUNITION_STATUS> values() {

        return values(MUNITION_STATUS.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<MUNITION_STATUS> values(boolean known) {

        return values(MUNITION_STATUS.class, known);
    }

    /** @see Value#get(int, Class) */
    public static MUNITION_STATUS get(int value) {

        return get(value, MUNITION_STATUS.class);
    }
}

