package discover.vdis.enums;

import java.util.List;

/**
 * OBJECT_DAMAGE: This class is auto-generated by vdis.EnumGenerator
 */
public final class OBJECT_DAMAGE extends Value {

    public static final OBJECT_DAMAGE
       NO_DAMAGE = new OBJECT_DAMAGE(0, "NO_DAMAGE", "No Damage", true),
       DAMAGED = new OBJECT_DAMAGE(1, "DAMAGED", "Damaged", true),
       DESTROYED = new OBJECT_DAMAGE(2, "DESTROYED", "Destroyed", true);

    private OBJECT_DAMAGE(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, OBJECT_DAMAGE.class);
    }

    /** @see Value#values(Class) */
    public static List<OBJECT_DAMAGE> values() {

        return values(OBJECT_DAMAGE.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<OBJECT_DAMAGE> values(boolean known) {

        return values(OBJECT_DAMAGE.class, known);
    }

    /** @see Value#get(int, Class) */
    public static OBJECT_DAMAGE get(int value) {

        return get(value, OBJECT_DAMAGE.class);
    }
}

