package discover.vdis.enums;

import java.util.List;

/**
 * OBJECT_KIND: This class is auto-generated by vdis.EnumGenerator
 */
public final class OBJECT_KIND extends Value {

    public static final OBJECT_KIND
       OTHER = new OBJECT_KIND(0, "OTHER", "Other", true),
       OBSTACLE = new OBJECT_KIND(1, "OBSTACLE", "Obstacle", true),
       PREPARED_POSITION = new OBJECT_KIND(2, "PREPARED_POSITION", "Prepared Position", true),
       CULTURAL_FEATURE = new OBJECT_KIND(3, "CULTURAL_FEATURE", "Cultural Feature", true),
       PASSAGEWAY = new OBJECT_KIND(4, "PASSAGEWAY", "Passageway", true),
       TACTICAL_SMOKE = new OBJECT_KIND(5, "TACTICAL_SMOKE", "Tactical Smoke", true),
       OBSTACLE_MARKER = new OBJECT_KIND(6, "OBSTACLE_MARKER", "Obstacle Marker", true),
       OBSTACLE_BREACH = new OBJECT_KIND(7, "OBSTACLE_BREACH", "Obstacle Breach", true),
       ENV_OBJECT = new OBJECT_KIND(8, "ENV_OBJECT", "Environmental Object", true);

    private OBJECT_KIND(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, OBJECT_KIND.class);
    }

    /** @see Value#values(Class) */
    public static List<OBJECT_KIND> values() {

        return values(OBJECT_KIND.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<OBJECT_KIND> values(boolean known) {

        return values(OBJECT_KIND.class, known);
    }

    /** @see Value#get(int, Class) */
    public static OBJECT_KIND get(int value) {

        return get(value, OBJECT_KIND.class);
    }
}

