package discover.vdis.enums;

import java.util.List;

/**
 * OBJECT_GEOMETRY: This class is auto-generated by vdis.EnumGenerator
 */
public final class OBJECT_GEOMETRY extends Value {

    public static final OBJECT_GEOMETRY
       UNKNOWN = new OBJECT_GEOMETRY(0, "UNKNOWN", "Unknown", true),
       POINT = new OBJECT_GEOMETRY(1, "POINT", "Point", true),
       LINEAR = new OBJECT_GEOMETRY(2, "LINEAR", "Linear", true),
       AREAL = new OBJECT_GEOMETRY(3, "AREAL", "Areal", true);

    private OBJECT_GEOMETRY(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, OBJECT_GEOMETRY.class);
    }

    /** @see Value#values(Class) */
    public static List<OBJECT_GEOMETRY> values() {

        return values(OBJECT_GEOMETRY.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<OBJECT_GEOMETRY> values(boolean known) {

        return values(OBJECT_GEOMETRY.class, known);
    }

    /** @see Value#get(int, Class) */
    public static OBJECT_GEOMETRY get(int value) {

        return get(value, OBJECT_GEOMETRY.class);
    }
}

