package discover.vdis.enums;

import java.util.List;

/**
 * OFFSET_TYPE: This class is auto-generated by vdis.EnumGenerator
 */
public final class OFFSET_TYPE extends Value {

    public static final OFFSET_TYPE
       OFFVP_OFFSET_TYPE_CARRIER_ORIGIN = new OFFSET_TYPE(0, "OFFVP_OFFSET_TYPE_CARRIER_ORIGIN", "Carrier Origin", true),
       OFFVP_OFFSET_TYPE_STATION_LOC = new OFFSET_TYPE(1, "OFFVP_OFFSET_TYPE_STATION_LOC", "Station Location", true),
       OFFVP_OFFSET_TYPE_POS_MOD_BY_CARRIER = new OFFSET_TYPE(2, "OFFVP_OFFSET_TYPE_POS_MOD_BY_CARRIER", "Position Modified by Carrier", true),
       OFFVP_OFFSET_TYPE_ORIENT_SET_BY_CARRIER = new OFFSET_TYPE(3, "OFFVP_OFFSET_TYPE_ORIENT_SET_BY_CARRIER", "Orientation Modified by Carrier", true),
       OFFVP_OFFSET_TYPE_CENTER_OF_GRAVITY = new OFFSET_TYPE(100, "OFFVP_OFFSET_TYPE_CENTER_OF_GRAVITY", "Center of Gravity", true);

    private OFFSET_TYPE(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, OFFSET_TYPE.class);
    }

    /** @see Value#values(Class) */
    public static List<OFFSET_TYPE> values() {

        return values(OFFSET_TYPE.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<OFFSET_TYPE> values(boolean known) {

        return values(OFFSET_TYPE.class, known);
    }

    /** @see Value#get(int, Class) */
    public static OFFSET_TYPE get(int value) {

        return get(value, OFFSET_TYPE.class);
    }
}

