package discover.vdis.enums;

import java.util.List;

/**
 * ON_OFF: This class is auto-generated by vdis.EnumGenerator
 */
public final class ON_OFF extends Value {

    public static final ON_OFF
       OFF = new ON_OFF(0, "OFF", "Off", true),
       ON = new ON_OFF(1, "ON", "ON", true);

    private ON_OFF(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, ON_OFF.class);
    }

    /** @see Value#values(Class) */
    public static List<ON_OFF> values() {

        return values(ON_OFF.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<ON_OFF> values(boolean known) {

        return values(ON_OFF.class, known);
    }

    /** @see Value#get(int, Class) */
    public static ON_OFF get(int value) {

        return get(value, ON_OFF.class);
    }
}

