package discover.vdis.enums;

import java.util.List;

/**
 * PDU_STATUS_DTI: This class is auto-generated by vdis.EnumGenerator
 */
public final class PDU_STATUS_DTI extends Value {

    public static final PDU_STATUS_DTI
       MUNITION = new PDU_STATUS_DTI(0, "MUNITION", "Munition", true),
       EXPENDABLE = new PDU_STATUS_DTI(1, "EXPENDABLE", "Expendable", true),
       NON_MUNITION_EXPLOSION = new PDU_STATUS_DTI(2, "NON_MUNITION_EXPLOSION", "Non-Munition Explosion", true);

    private PDU_STATUS_DTI(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, PDU_STATUS_DTI.class);
    }

    /** @see Value#values(Class) */
    public static List<PDU_STATUS_DTI> values() {

        return values(PDU_STATUS_DTI.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<PDU_STATUS_DTI> values(boolean known) {

        return values(PDU_STATUS_DTI.class, known);
    }

    /** @see Value#get(int, Class) */
    public static PDU_STATUS_DTI get(int value) {

        return get(value, PDU_STATUS_DTI.class);
    }
}

