package discover.vdis.enums;

import java.util.List;

/**
 * PDU_STATUS_IAI: This class is auto-generated by vdis.EnumGenerator
 */
public final class PDU_STATUS_IAI extends Value {

    public static final PDU_STATUS_IAI
       NO_STATEMENT = new PDU_STATUS_IAI(0, "NO_STATEMENT", "No Statement", true),
       NOT_ATTACHED = new PDU_STATUS_IAI(1, "NOT_ATTACHED", "Not Attached", true),
       ATTACHED = new PDU_STATUS_IAI(2, "ATTACHED", "Attached", true);

    private PDU_STATUS_IAI(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, PDU_STATUS_IAI.class);
    }

    /** @see Value#values(Class) */
    public static List<PDU_STATUS_IAI> values() {

        return values(PDU_STATUS_IAI.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<PDU_STATUS_IAI> values(boolean known) {

        return values(PDU_STATUS_IAI.class, known);
    }

    /** @see Value#get(int, Class) */
    public static PDU_STATUS_IAI get(int value) {

        return get(value, PDU_STATUS_IAI.class);
    }
}

