package discover.vdis.enums;

import java.util.List;

/**
 * PDU_STATUS_CEI: This class is auto-generated by vdis.EnumGenerator
 */
public final class PDU_STATUS_CEI extends Value {

    public static final PDU_STATUS_CEI
       NOT_COUPLED = new PDU_STATUS_CEI(0, "NOT_COUPLED", "Not Coupled", true),
       COUPLED = new PDU_STATUS_CEI(1, "COUPLED", "Coupled", true);

    private PDU_STATUS_CEI(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, PDU_STATUS_CEI.class);
    }

    /** @see Value#values(Class) */
    public static List<PDU_STATUS_CEI> values() {

        return values(PDU_STATUS_CEI.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<PDU_STATUS_CEI> values(boolean known) {

        return values(PDU_STATUS_CEI.class, known);
    }

    /** @see Value#get(int, Class) */
    public static PDU_STATUS_CEI get(int value) {

        return get(value, PDU_STATUS_CEI.class);
    }
}

