package discover.vdis.enums;

import java.util.List;

/**
 * PDU_STATUS_DMI: This class is auto-generated by vdis.EnumGenerator
 */
public final class PDU_STATUS_DMI extends Value {

    public static final PDU_STATUS_DMI
       GUISE_MODE = new PDU_STATUS_DMI(0, "GUISE_MODE", "Guise Mode", true),
       DISGUISE_MODE = new PDU_STATUS_DMI(1, "DISGUISE_MODE", "Disguise Mode", true);

    private PDU_STATUS_DMI(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, PDU_STATUS_DMI.class);
    }

    /** @see Value#values(Class) */
    public static List<PDU_STATUS_DMI> values() {

        return values(PDU_STATUS_DMI.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<PDU_STATUS_DMI> values(boolean known) {

        return values(PDU_STATUS_DMI.class, known);
    }

    /** @see Value#get(int, Class) */
    public static PDU_STATUS_DMI get(int value) {

        return get(value, PDU_STATUS_DMI.class);
    }
}

