package discover.vdis.enums;

import java.util.List;

/**
 * PDU_STATUS_FTI: This class is auto-generated by vdis.EnumGenerator
 */
public final class PDU_STATUS_FTI extends Value {

    public static final PDU_STATUS_FTI
       MUNITION = new PDU_STATUS_FTI(0, "MUNITION", "Munition", true),
       EXPENDABLE = new PDU_STATUS_FTI(1, "EXPENDABLE", "Expendable", true);

    private PDU_STATUS_FTI(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, PDU_STATUS_FTI.class);
    }

    /** @see Value#values(Class) */
    public static List<PDU_STATUS_FTI> values() {

        return values(PDU_STATUS_FTI.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<PDU_STATUS_FTI> values(boolean known) {

        return values(PDU_STATUS_FTI.class, known);
    }

    /** @see Value#get(int, Class) */
    public static PDU_STATUS_FTI get(int value) {

        return get(value, PDU_STATUS_FTI.class);
    }
}

