package discover.vdis.enums;

import java.util.List;

/**
 * PDU_STATUS_TEI: This class is auto-generated by vdis.EnumGenerator
 */
public final class PDU_STATUS_TEI extends Value {

    public static final PDU_STATUS_TEI
       NO_DIFF = new PDU_STATUS_TEI(0, "NO_DIFF", "No Difference", true),
       DIFF = new PDU_STATUS_TEI(1, "DIFF", "Difference", true);

    private PDU_STATUS_TEI(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, PDU_STATUS_TEI.class);
    }

    /** @see Value#values(Class) */
    public static List<PDU_STATUS_TEI> values() {

        return values(PDU_STATUS_TEI.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<PDU_STATUS_TEI> values(boolean known) {

        return values(PDU_STATUS_TEI.class, known);
    }

    /** @see Value#get(int, Class) */
    public static PDU_STATUS_TEI get(int value) {

        return get(value, PDU_STATUS_TEI.class);
    }
}

