package discover.vdis.enums;

import java.util.List;

/**
 * PDU_STATUS_RAI: This class is auto-generated by vdis.EnumGenerator
 */
public final class PDU_STATUS_RAI extends Value {

    public static final PDU_STATUS_RAI
       NO_STATEMENT = new PDU_STATUS_RAI(0, "NO_STATEMENT", "No Statement", true),
       NOT_ATTACHED = new PDU_STATUS_RAI(1, "NOT_ATTACHED", "Not Attached", true),
       ATTACHED = new PDU_STATUS_RAI(2, "ATTACHED", "Attached", true);

    private PDU_STATUS_RAI(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, PDU_STATUS_RAI.class);
    }

    /** @see Value#values(Class) */
    public static List<PDU_STATUS_RAI> values() {

        return values(PDU_STATUS_RAI.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<PDU_STATUS_RAI> values(boolean known) {

        return values(PDU_STATUS_RAI.class, known);
    }

    /** @see Value#get(int, Class) */
    public static PDU_STATUS_RAI get(int value) {

        return get(value, PDU_STATUS_RAI.class);
    }
}

