package discover.vdis.enums;

import java.util.List;

/**
 * PDU_STATUS_LVCI: This class is auto-generated by vdis.EnumGenerator
 */
public final class PDU_STATUS_LVCI extends Value {

    public static final PDU_STATUS_LVCI
       NO_STATEMENT = new PDU_STATUS_LVCI(0, "NO_STATEMENT", "No Statement", true),
       LIVE = new PDU_STATUS_LVCI(1, "LIVE", "Live", true),
       VIRTUAL = new PDU_STATUS_LVCI(2, "VIRTUAL", "Virtual", true),
       CONSTRUCTIVE = new PDU_STATUS_LVCI(3, "CONSTRUCTIVE", "Constructive", true);

    private PDU_STATUS_LVCI(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, PDU_STATUS_LVCI.class);
    }

    /** @see Value#values(Class) */
    public static List<PDU_STATUS_LVCI> values() {

        return values(PDU_STATUS_LVCI.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<PDU_STATUS_LVCI> values(boolean known) {

        return values(PDU_STATUS_LVCI.class, known);
    }

    /** @see Value#get(int, Class) */
    public static PDU_STATUS_LVCI get(int value) {

        return get(value, PDU_STATUS_LVCI.class);
    }
}

