package discover.vdis.enums;

import java.util.List;

/**
 * PHYS_ASSOC_TYPE: This class is auto-generated by vdis.EnumGenerator
 */
public final class PHYS_ASSOC_TYPE extends Value {

    public static final PHYS_ASSOC_TYPE
       EAVP_PHYS_ASSOC_TYPE_NOT_SPECIFIED = new PHYS_ASSOC_TYPE(0, "EAVP_PHYS_ASSOC_TYPE_NOT_SPECIFIED", "Not Specified", true),
       EAVP_PHYS_ASSOC_TYPE_TOWED_IN_AIR = new PHYS_ASSOC_TYPE(1, "EAVP_PHYS_ASSOC_TYPE_TOWED_IN_AIR", "Towed in Air (Single Hook, Not Specified)", true),
       EAVP_PHYS_ASSOC_TYPE_TOWED_ON_LAND = new PHYS_ASSOC_TYPE(2, "EAVP_PHYS_ASSOC_TYPE_TOWED_ON_LAND", "Towed on Land", true),
       EAVP_PHYS_ASSOC_TYPE_TOWED_ON_WATER_SURFACE = new PHYS_ASSOC_TYPE(3, "EAVP_PHYS_ASSOC_TYPE_TOWED_ON_WATER_SURFACE", "Towed on Water Surface", true),
       EAVP_PHYS_ASSOC_TYPE_TOWED_UNDERWATER = new PHYS_ASSOC_TYPE(4, "EAVP_PHYS_ASSOC_TYPE_TOWED_UNDERWATER", "Towed Underwater", true),
       EAVP_PHYS_ASSOC_TYPE_MOUNTED_ATTACHED = new PHYS_ASSOC_TYPE(5, "EAVP_PHYS_ASSOC_TYPE_MOUNTED_ATTACHED", "Mounted Attached", true),
       EAVP_PHYS_ASSOC_TYPE_MOUNTED_UNATTACH_UNSUPP = new PHYS_ASSOC_TYPE(6, "EAVP_PHYS_ASSOC_TYPE_MOUNTED_UNATTACH_UNSUPP", "Mounted Unattached and Unsupported", true),
       EAVP_PHYS_ASSOC_TYPE_MOUNTED_UNATTACH_SUPP = new PHYS_ASSOC_TYPE(7, "EAVP_PHYS_ASSOC_TYPE_MOUNTED_UNATTACH_SUPP", "Mounted Unattached and Supported", true),
       EAVP_PHYS_ASSOC_TYPE_TOWED_IN_AIR_CENTER_HOOK = new PHYS_ASSOC_TYPE(8, "EAVP_PHYS_ASSOC_TYPE_TOWED_IN_AIR_CENTER_HOOK", "Towed in Air (Center Hook)", true),
       EAVP_PHYS_ASSOC_TYPE_TOWED_IN_AIR_FWD_HOOK = new PHYS_ASSOC_TYPE(9, "EAVP_PHYS_ASSOC_TYPE_TOWED_IN_AIR_FWD_HOOK", "Towed in Air (Forward Hook)", true),
       EAVP_PHYS_ASSOC_TYPE_TOWED_IN_AIR_AFT_HOOK = new PHYS_ASSOC_TYPE(10, "EAVP_PHYS_ASSOC_TYPE_TOWED_IN_AIR_AFT_HOOK", "Towed in Air (Aft Hook)", true),
       EAVP_PHYS_ASSOC_TYPE_TOWED_IN_AIR_TANDEM_HOOK = new PHYS_ASSOC_TYPE(11, "EAVP_PHYS_ASSOC_TYPE_TOWED_IN_AIR_TANDEM_HOOK", "Towed in Air (Tandem Hook - Fore and Aft)", true),
       EAVP_PHYS_ASSOC_TYPE_TOWED_IN_AIR_MISMAN_TANDEM_FORE_CENTER = new PHYS_ASSOC_TYPE(12, "EAVP_PHYS_ASSOC_TYPE_TOWED_IN_AIR_MISMAN_TANDEM_FORE_CENTER", "Towed in Air (Mismanaged Tandem - Fore and Center)", true),
       EAVP_PHYS_ASSOC_TYPE_TOWED_IN_AIR_MISMAN_TANDEM_CENTER_AFT = new PHYS_ASSOC_TYPE(13, "EAVP_PHYS_ASSOC_TYPE_TOWED_IN_AIR_MISMAN_TANDEM_CENTER_AFT", "Towed in Air (Mismanaged Tandem - Center and Aft)", true),
       EAVP_PHYS_ASSOC_TYPE_TOWED_IN_AIR_ALL_HOOKS = new PHYS_ASSOC_TYPE(14, "EAVP_PHYS_ASSOC_TYPE_TOWED_IN_AIR_ALL_HOOKS", "Towed in Air (All Hooks)", true),
       EAVP_PHYS_ASSOC_TYPE_HOISTED = new PHYS_ASSOC_TYPE(15, "EAVP_PHYS_ASSOC_TYPE_HOISTED", "Hoisted", true),
       EAVP_PHYS_ASSOC_TYPE_RESTRAINED_TO_A_LIFEFORM = new PHYS_ASSOC_TYPE(30, "EAVP_PHYS_ASSOC_TYPE_RESTRAINED_TO_A_LIFEFORM", "Restrained to a Lifeform", true),
       EAVP_PHYS_ASSOC_TYPE_RESTRAINED_TO_A_PLATFORM = new PHYS_ASSOC_TYPE(31, "EAVP_PHYS_ASSOC_TYPE_RESTRAINED_TO_A_PLATFORM", "Restrained to a Platform", true),
       EAVP_PHYS_ASSOC_TYPE_RESTRAINED_TO_AN_OBJECT = new PHYS_ASSOC_TYPE(32, "EAVP_PHYS_ASSOC_TYPE_RESTRAINED_TO_AN_OBJECT", "Restrained to an Object", true),
       EAVP_PHYS_ASSOC_TYPE_REFUELING_OPERATION = new PHYS_ASSOC_TYPE(61, "EAVP_PHYS_ASSOC_TYPE_REFUELING_OPERATION", "Refueling Operation", true),
       EAVP_PHYS_ASSOC_TYPE_SAR_BASKET = new PHYS_ASSOC_TYPE(62, "EAVP_PHYS_ASSOC_TYPE_SAR_BASKET", "Search and Rescue Basket", true),
       EAVP_PHYS_ASSOC_TYPE_SAR_RESCUE_COLLAR = new PHYS_ASSOC_TYPE(63, "EAVP_PHYS_ASSOC_TYPE_SAR_RESCUE_COLLAR", "Search and Rescue Rescue Collar", true),
       EAVP_PHYS_ASSOC_TYPE_ENGAGEMENT = new PHYS_ASSOC_TYPE(64, "EAVP_PHYS_ASSOC_TYPE_ENGAGEMENT", "Engagement/Object 2 is Being Engaged", true),
       EAVP_PHYS_ASSOC_TYPE_RETURN_TO_BASE = new PHYS_ASSOC_TYPE(65, "EAVP_PHYS_ASSOC_TYPE_RETURN_TO_BASE", "Return To Base/Object 2 is the Destination Object", true),
       EAVP_PHYS_ASSOC_TYPE_LINE_BETWEEN_COMM_TOWERS = new PHYS_ASSOC_TYPE(90, "EAVP_PHYS_ASSOC_TYPE_LINE_BETWEEN_COMM_TOWERS", "Line between Communication Towers", true),
       EAVP_PHYS_ASSOC_TYPE_LINE_BETWEEN_POWER_TOWERS = new PHYS_ASSOC_TYPE(91, "EAVP_PHYS_ASSOC_TYPE_LINE_BETWEEN_POWER_TOWERS", "Line Between Power Towers", true),
       EAVP_PHYS_ASSOC_TYPE_INDOORS = new PHYS_ASSOC_TYPE(92, "EAVP_PHYS_ASSOC_TYPE_INDOORS", "Indoors", true),
       EAVP_PHYS_ASSOC_TYPE_ROOF = new PHYS_ASSOC_TYPE(93, "EAVP_PHYS_ASSOC_TYPE_ROOF", "Roof", true);

    private PHYS_ASSOC_TYPE(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, PHYS_ASSOC_TYPE.class);
    }

    /** @see Value#values(Class) */
    public static List<PHYS_ASSOC_TYPE> values() {

        return values(PHYS_ASSOC_TYPE.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<PHYS_ASSOC_TYPE> values(boolean known) {

        return values(PHYS_ASSOC_TYPE.class, known);
    }

    /** @see Value#get(int, Class) */
    public static PHYS_ASSOC_TYPE get(int value) {

        return get(value, PHYS_ASSOC_TYPE.class);
    }
}

