package discover.vdis.enums;

import java.util.List;

/**
 * PHYS_CONN_TYPE: This class is auto-generated by vdis.EnumGenerator
 */
public final class PHYS_CONN_TYPE extends Value {

    public static final PHYS_CONN_TYPE
       EAVP_PHYS_CONN_TYPE_NOT_SPECIFIED = new PHYS_CONN_TYPE(0, "EAVP_PHYS_CONN_TYPE_NOT_SPECIFIED", "Not Specified", true),
       EAVP_PHYS_CONN_TYPE_ATTACHED_TO_SURFACE = new PHYS_CONN_TYPE(1, "EAVP_PHYS_CONN_TYPE_ATTACHED_TO_SURFACE", "Attached Directly to Surface", true),
       EAVP_PHYS_CONN_TYPE_CABLE_WIRE = new PHYS_CONN_TYPE(2, "EAVP_PHYS_CONN_TYPE_CABLE_WIRE", "Cable Wire", true),
       EAVP_PHYS_CONN_TYPE_ROPE = new PHYS_CONN_TYPE(3, "EAVP_PHYS_CONN_TYPE_ROPE", "Rope", true),
       EAVP_PHYS_CONN_TYPE_CHAIN = new PHYS_CONN_TYPE(4, "EAVP_PHYS_CONN_TYPE_CHAIN", "Chain", true),
       EAVP_PHYS_CONN_TYPE_POWER_LINE = new PHYS_CONN_TYPE(5, "EAVP_PHYS_CONN_TYPE_POWER_LINE", "Power Line", true),
       EAVP_PHYS_CONN_TYPE_TELEPHONE_LINE = new PHYS_CONN_TYPE(6, "EAVP_PHYS_CONN_TYPE_TELEPHONE_LINE", "Telephone Line", true),
       EAVP_PHYS_CONN_TYPE_CABLE_LINE = new PHYS_CONN_TYPE(7, "EAVP_PHYS_CONN_TYPE_CABLE_LINE", "Cable Line", true),
       EAVP_PHYS_CONN_TYPE_REFUELING_DROGUE = new PHYS_CONN_TYPE(8, "EAVP_PHYS_CONN_TYPE_REFUELING_DROGUE", "Refueling Drogue", true),
       EAVP_PHYS_CONN_TYPE_REFUELING_BOOM = new PHYS_CONN_TYPE(9, "EAVP_PHYS_CONN_TYPE_REFUELING_BOOM", "Refueling Boom", true),
       EAVP_PHYS_CONN_TYPE_HANDCUFFS = new PHYS_CONN_TYPE(10, "EAVP_PHYS_CONN_TYPE_HANDCUFFS", "Handcuffs", true),
       EAVP_PHYS_CONN_TYPE_IN_CONTACT_WITH = new PHYS_CONN_TYPE(11, "EAVP_PHYS_CONN_TYPE_IN_CONTACT_WITH", "In Contact With", true),
       EAVP_PHYS_CONN_TYPE_FAST_ROPE = new PHYS_CONN_TYPE(12, "EAVP_PHYS_CONN_TYPE_FAST_ROPE", "Fast Rope", true);

    private PHYS_CONN_TYPE(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, PHYS_CONN_TYPE.class);
    }

    /** @see Value#values(Class) */
    public static List<PHYS_CONN_TYPE> values() {

        return values(PHYS_CONN_TYPE.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<PHYS_CONN_TYPE> values(boolean known) {

        return values(PHYS_CONN_TYPE.class, known);
    }

    /** @see Value#get(int, Class) */
    public static PHYS_CONN_TYPE get(int value) {

        return get(value, PHYS_CONN_TYPE.class);
    }
}

