package discover.vdis.enums;

import java.util.List;

/**
 * PL_COND_CLEAN: This class is auto-generated by vdis.EnumGenerator
 */
public final class PL_COND_CLEAN extends Value {

    public static final PL_COND_CLEAN
       PLAT_COND_CLEAN_NOT_SPECIFIED = new PL_COND_CLEAN(0, "PLAT_COND_CLEAN_NOT_SPECIFIED", "Not Specified", true),
       PLAT_COND_CLEAN_SLIGHTLY_DIRTY = new PL_COND_CLEAN(1, "PLAT_COND_CLEAN_SLIGHTLY_DIRTY", "Slightly Dirty", true),
       PLAT_COND_CLEAN_MODERATELY_DIRTY = new PL_COND_CLEAN(2, "PLAT_COND_CLEAN_MODERATELY_DIRTY", "Moderately Dirty", true),
       PLAT_COND_CLEAN_VERY_DIRTY = new PL_COND_CLEAN(3, "PLAT_COND_CLEAN_VERY_DIRTY", "Very Dirty", true);

    private PL_COND_CLEAN(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, PL_COND_CLEAN.class);
    }

    /** @see Value#values(Class) */
    public static List<PL_COND_CLEAN> values() {

        return values(PL_COND_CLEAN.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<PL_COND_CLEAN> values(boolean known) {

        return values(PL_COND_CLEAN.class, known);
    }

    /** @see Value#get(int, Class) */
    public static PL_COND_CLEAN get(int value) {

        return get(value, PL_COND_CLEAN.class);
    }
}

