package discover.vdis.enums;

import java.util.List;

/**
 * PL_COND_RUST: This class is auto-generated by vdis.EnumGenerator
 */
public final class PL_COND_RUST extends Value {

    public static final PL_COND_RUST
       PLAT_COND_RUST_NOT_SPECIFIED = new PL_COND_RUST(0, "PLAT_COND_RUST_NOT_SPECIFIED", "Not Specified", true),
       PLAT_COND_RUST_SLIGHT = new PL_COND_RUST(1, "PLAT_COND_RUST_SLIGHT", "Slight", true),
       PLAT_COND_RUST_MODERATE = new PL_COND_RUST(2, "PLAT_COND_RUST_MODERATE", "Moderate", true),
       PLAT_COND_RUST_HEAVY = new PL_COND_RUST(3, "PLAT_COND_RUST_HEAVY", "Heavy", true);

    private PL_COND_RUST(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, PL_COND_RUST.class);
    }

    /** @see Value#values(Class) */
    public static List<PL_COND_RUST> values() {

        return values(PL_COND_RUST.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<PL_COND_RUST> values(boolean known) {

        return values(PL_COND_RUST.class, known);
    }

    /** @see Value#get(int, Class) */
    public static PL_COND_RUST get(int value) {

        return get(value, PL_COND_RUST.class);
    }
}

