package discover.vdis.enums;

import java.util.List;

/**
 * PL_COND_MTL: This class is auto-generated by vdis.EnumGenerator
 */
public final class PL_COND_MTL extends Value {

    public static final PL_COND_MTL
       PLAT_COND_MTL_NOT_SPECIFIED = new PL_COND_MTL(0, "PLAT_COND_MTL_NOT_SPECIFIED", "Not Specified", true),
       PLAT_COND_MTL_METALLIC = new PL_COND_MTL(1, "PLAT_COND_MTL_METALLIC", "Metallic (shiny)", true),
       PLAT_COND_MTL_PLASTIC = new PL_COND_MTL(2, "PLAT_COND_MTL_PLASTIC", "Plastic (matte)", true),
       PLAT_COND_MTL_ROUGH = new PL_COND_MTL(3, "PLAT_COND_MTL_ROUGH", "Rough (coarse)", true);

    private PL_COND_MTL(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, PL_COND_MTL.class);
    }

    /** @see Value#values(Class) */
    public static List<PL_COND_MTL> values() {

        return values(PL_COND_MTL.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<PL_COND_MTL> values(boolean known) {

        return values(PL_COND_MTL.class, known);
    }

    /** @see Value#get(int, Class) */
    public static PL_COND_MTL get(int value) {

        return get(value, PL_COND_MTL.class);
    }
}

