package discover.vdis.enums;

import java.util.List;

/**
 * PLAT_CAT_AIR: This class is auto-generated by vdis.EnumGenerator
 */
public final class PLAT_CAT_AIR extends Value {

    public static final PLAT_CAT_AIR
       OTH = new PLAT_CAT_AIR(0, "OTH", "Other", true),
       FAD = new PLAT_CAT_AIR(1, "FAD", "Fighter/Air Defense", true),
       ATK = new PLAT_CAT_AIR(2, "ATK", "Attack/Strike", true),
       BOMB = new PLAT_CAT_AIR(3, "BOMB", "Bomber", true),
       CARGO = new PLAT_CAT_AIR(4, "CARGO", "Cargo/Tanker", true),
       ASW = new PLAT_CAT_AIR(5, "ASW", "ASW/Patrol/Observation", true),
       EW = new PLAT_CAT_AIR(6, "EW", "Electronic Warfare (EW)", true),
       RECON = new PLAT_CAT_AIR(7, "RECON", "Reconnaissance", true),
       SURV = new PLAT_CAT_AIR(8, "SURV", "Surveillance/C2 (Airborne Early Warning)", true),
       AH = new PLAT_CAT_AIR(20, "AH", "Attack Helicopter", true),
       UH = new PLAT_CAT_AIR(21, "UH", "Utility Helicopter", true),
       ASUB = new PLAT_CAT_AIR(22, "ASUB", "Antisubmarine Warfare/Patrol Helicopter", true),
       CARH = new PLAT_CAT_AIR(23, "CARH", "Cargo Helicopter", true),
       OBSH = new PLAT_CAT_AIR(24, "OBSH", "Observation Helicopter", true),
       SOPSH = new PLAT_CAT_AIR(25, "SOPSH", "Special Operations Helicopter", true),
       TRAIN = new PLAT_CAT_AIR(40, "TRAIN", "Trainer", true),
       UAV = new PLAT_CAT_AIR(50, "UAV", "Unmanned", true),
       CIV = new PLAT_CAT_AIR(57, "CIV", "Non-Combatant Commercial Aircraft", true);

    private PLAT_CAT_AIR(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, PLAT_CAT_AIR.class);
    }

    /** @see Value#values(Class) */
    public static List<PLAT_CAT_AIR> values() {

        return values(PLAT_CAT_AIR.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<PLAT_CAT_AIR> values(boolean known) {

        return values(PLAT_CAT_AIR.class, known);
    }

    /** @see Value#get(int, Class) */
    public static PLAT_CAT_AIR get(int value) {

        return get(value, PLAT_CAT_AIR.class);
    }
}

