package discover.vdis.enums;

import java.util.List;

/**
 * PLAT_CAT_SURFACE: This class is auto-generated by vdis.EnumGenerator
 */
public final class PLAT_CAT_SURFACE extends Value {

    public static final PLAT_CAT_SURFACE
       OTH = new PLAT_CAT_SURFACE(0, "OTH", "Other", true),
       CAR = new PLAT_CAT_SURFACE(1, "CAR", "Carrier", true),
       COM = new PLAT_CAT_SURFACE(2, "COM", "Command Ship/Cruiser", true),
       GMC = new PLAT_CAT_SURFACE(3, "GMC", "Guided Missile Cruiser", true),
       DDG = new PLAT_CAT_SURFACE(4, "DDG", "Guided Missile Destroyer (DDG)", true),
       DD = new PLAT_CAT_SURFACE(5, "DD", "Destroyer (DD)", true),
       FFG = new PLAT_CAT_SURFACE(6, "FFG", "Guided Missile Frigate (FFG)", true),
       LPC = new PLAT_CAT_SURFACE(7, "LPC", "Light/Patrol Craft", true),
       MCS = new PLAT_CAT_SURFACE(8, "MCS", "Mine Countermeasure Ship/Craft", true),
       DLS = new PLAT_CAT_SURFACE(9, "DLS", "Dock Landing Ship", true),
       TLS = new PLAT_CAT_SURFACE(10, "TLS", "Tank Landing Ship", true),
       LAND = new PLAT_CAT_SURFACE(11, "LAND", "Landing Craft", true),
       LCAR = new PLAT_CAT_SURFACE(12, "LCAR", "Light Carrier", true),
       CHCAR = new PLAT_CAT_SURFACE(13, "CHCAR", "Cruiser/Helicopter Carrier", true),
       HYD = new PLAT_CAT_SURFACE(14, "HYD", "Hydrofoil", true),
       ACSEF = new PLAT_CAT_SURFACE(15, "ACSEF", "Air Cushion/Surface Effect", true),
       AUX = new PLAT_CAT_SURFACE(16, "AUX", "Auxiliary", true),
       AUXMM = new PLAT_CAT_SURFACE(17, "AUXMM", "Auxiliary, Merchant Marine", true),
       UTIL = new PLAT_CAT_SURFACE(18, "UTIL", "Utility", true),
       FRG = new PLAT_CAT_SURFACE(50, "FRG", "Frigate (including Corvette)", true),
       BAT = new PLAT_CAT_SURFACE(51, "BAT", "Battleship", true),
       HC = new PLAT_CAT_SURFACE(52, "HC", "Heavy Cruiser", true),
       DT = new PLAT_CAT_SURFACE(53, "DT", "Destroyer Tender", true),
       AAS = new PLAT_CAT_SURFACE(54, "AAS", "Amphibious Assault Ship", true),
       ACS = new PLAT_CAT_SURFACE(55, "ACS", "Amphibious Cargo Ship", true),
       ATD = new PLAT_CAT_SURFACE(56, "ATD", "Amphibious Transport Dock", true),
       AMMO = new PLAT_CAT_SURFACE(57, "AMMO", "Ammunition Ship", true),
       CSS = new PLAT_CAT_SURFACE(58, "CSS", "Combat Stores Ship", true),
       SURTASS = new PLAT_CAT_SURFACE(59, "SURTASS", "Surveillance Towed Array Sonar System (SURTASS)", true),
       FCSS = new PLAT_CAT_SURFACE(60, "FCSS", "Fast Combat Support Ship", true),
       CIV = new PLAT_CAT_SURFACE(61, "CIV", "Non-Combatant Ship", true),
       CGC = new PLAT_CAT_SURFACE(62, "CGC", "Coast Guard Cutters", true),
       CGB = new PLAT_CAT_SURFACE(63, "CGB", "Coast Guard Boats", true);

    private PLAT_CAT_SURFACE(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, PLAT_CAT_SURFACE.class);
    }

    /** @see Value#values(Class) */
    public static List<PLAT_CAT_SURFACE> values() {

        return values(PLAT_CAT_SURFACE.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<PLAT_CAT_SURFACE> values(boolean known) {

        return values(PLAT_CAT_SURFACE.class, known);
    }

    /** @see Value#get(int, Class) */
    public static PLAT_CAT_SURFACE get(int value) {

        return get(value, PLAT_CAT_SURFACE.class);
    }
}

