package discover.vdis.enums;

import java.util.List;

/**
 * PLAT_CAT_SUBSURFACE: This class is auto-generated by vdis.EnumGenerator
 */
public final class PLAT_CAT_SUBSURFACE extends Value {

    public static final PLAT_CAT_SUBSURFACE
       OTH = new PLAT_CAT_SUBSURFACE(0, "OTH", "Other", true),
       SSBN = new PLAT_CAT_SUBSURFACE(1, "SSBN", "SSBN (Nuclear Ballistic Missile)", true),
       SSGN = new PLAT_CAT_SUBSURFACE(2, "SSGN", "SSGN (Nuclear Guided Missile)", true),
       SSN = new PLAT_CAT_SUBSURFACE(3, "SSN", "SSN (Nuclear Attack - Torpedo)", true),
       SSG = new PLAT_CAT_SUBSURFACE(4, "SSG", "SSG (Conventional Guided Missile)", true),
       SS = new PLAT_CAT_SUBSURFACE(5, "SS", "SS (Conventional Attack - Torpedo, Patrol)", true),
       SSAN = new PLAT_CAT_SUBSURFACE(6, "SSAN", "SSAN (Nuclear Auxiliary)", true),
       SSA = new PLAT_CAT_SUBSURFACE(7, "SSA", "SSA (Conventional Auxiliary)", true);

    private PLAT_CAT_SUBSURFACE(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, PLAT_CAT_SUBSURFACE.class);
    }

    /** @see Value#values(Class) */
    public static List<PLAT_CAT_SUBSURFACE> values() {

        return values(PLAT_CAT_SUBSURFACE.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<PLAT_CAT_SUBSURFACE> values(boolean known) {

        return values(PLAT_CAT_SUBSURFACE.class, known);
    }

    /** @see Value#get(int, Class) */
    public static PLAT_CAT_SUBSURFACE get(int value) {

        return get(value, PLAT_CAT_SUBSURFACE.class);
    }
}

