package discover.vdis.enums;

import java.util.List;

/**
 * PLAT_CAT_LAND: This class is auto-generated by vdis.EnumGenerator
 */
public final class PLAT_CAT_LAND extends Value {

    public static final PLAT_CAT_LAND
       OTH = new PLAT_CAT_LAND(0, "OTH", "Other", true),
       TANK = new PLAT_CAT_LAND(1, "TANK", "Tank", true),
       AFV = new PLAT_CAT_LAND(2, "AFV", "Armored Fighting Vehicle", true),
       AUV = new PLAT_CAT_LAND(3, "AUV", "Armored Utility Vehicle", true),
       SPA = new PLAT_CAT_LAND(4, "SPA", "Self-propelled Artillery", true),
       TOW = new PLAT_CAT_LAND(5, "TOW", "Towed Artillery", true),
       SWUV = new PLAT_CAT_LAND(6, "SWUV", "Small Wheeled Utility Vehicle", true),
       LWUV = new PLAT_CAT_LAND(7, "LWUV", "Large Wheeled Utility Vehicle", true),
       STUV = new PLAT_CAT_LAND(8, "STUV", "Small Tracked Utility Vehicle", true),
       LTUV = new PLAT_CAT_LAND(9, "LTUV", "Large Tracked Utility Vehicle", true),
       MORT = new PLAT_CAT_LAND(10, "MORT", "Mortar", true),
       PLOW = new PLAT_CAT_LAND(11, "PLOW", "Mine plow", true),
       RAKE = new PLAT_CAT_LAND(12, "RAKE", "Mine rake", true),
       ROLL = new PLAT_CAT_LAND(13, "ROLL", "Mine roller", true),
       CARGO = new PLAT_CAT_LAND(14, "CARGO", "Cargo trailer", true),
       FUEL = new PLAT_CAT_LAND(15, "FUEL", "Fuel trailer", true),
       GEN = new PLAT_CAT_LAND(16, "GEN", "Generator trailer", true),
       WATER = new PLAT_CAT_LAND(17, "WATER", "Water trailer", true),
       ENG = new PLAT_CAT_LAND(18, "ENG", "Engineer equipment", true),
       HET = new PLAT_CAT_LAND(19, "HET", "Heavy equipment transport trailer", true),
       MET = new PLAT_CAT_LAND(20, "MET", "Maintenance equipment trailer", true),
       LIMB = new PLAT_CAT_LAND(21, "LIMB", "Limber", true),
       CDEC = new PLAT_CAT_LAND(22, "CDEC", "Chemical decontamination trailer", true),
       WARN = new PLAT_CAT_LAND(23, "WARN", "Warning System", true),
       TREN = new PLAT_CAT_LAND(24, "TREN", "Train - Engine", true),
       TRCAR = new PLAT_CAT_LAND(25, "TRCAR", "Train - Car", true),
       TRCAB = new PLAT_CAT_LAND(26, "TRCAB", "Train - Caboose", true),
       CIV = new PLAT_CAT_LAND(27, "CIV", "Civilian Vehicle", true),
       ADUE = new PLAT_CAT_LAND(28, "ADUE", "Air Defense / Missile Defense Unit Equipment", true),
       C3I = new PLAT_CAT_LAND(29, "C3I", "Command, Control, Communications, and Intelligence (C3I) System", true),
       OPS = new PLAT_CAT_LAND(30, "OPS", "Operations Facility", true),
       INT = new PLAT_CAT_LAND(31, "INT", "Intelligence Facility", true),
       SURV = new PLAT_CAT_LAND(32, "SURV", "Surveillance Facility", true),
       COMU = new PLAT_CAT_LAND(33, "COMU", "Communications Facility", true),
       COM = new PLAT_CAT_LAND(34, "COM", "Command Facility", true),
       C4I = new PLAT_CAT_LAND(35, "C4I", "C4I Facility", true),
       CTRL = new PLAT_CAT_LAND(36, "CTRL", "Control Facility", true),
       FIRE = new PLAT_CAT_LAND(37, "FIRE", "Fire Control Facility", true),
       MDEF = new PLAT_CAT_LAND(38, "MDEF", "Missile Defense Facility", true),
       FCOM = new PLAT_CAT_LAND(39, "FCOM", "Field Command Post", true),
       OBS = new PLAT_CAT_LAND(40, "OBS", "Observation Post", true),
       GWV = new PLAT_CAT_LAND(41, "GWV", "General Wheeled Vehicles", true),
       MOTORCYCLE = new PLAT_CAT_LAND(80, "MOTORCYCLE", "null", true),
       CAR_SEDAN = new PLAT_CAT_LAND(81, "CAR_SEDAN", "null", true),
       BUS = new PLAT_CAT_LAND(82, "BUS", "null", true),
       SINGLE_UNIT_CARGO_TRUCK = new PLAT_CAT_LAND(83, "SINGLE_UNIT_CARGO_TRUCK", "null", true),
       SINGLE_UNIT_UTILITY_EMERGENCY_TRUCK = new PLAT_CAT_LAND(84, "SINGLE_UNIT_UTILITY_EMERGENCY_TRUCK", "null", true),
       MULTIPLE_UNIT_CARGO_TRUCK = new PLAT_CAT_LAND(85, "MULTIPLE_UNIT_CARGO_TRUCK", "null", true),
       MULTIPLE_UNIT_UTILITY_EMERGENCY_TRUCK = new PLAT_CAT_LAND(86, "MULTIPLE_UNIT_UTILITY_EMERGENCY_TRUCK", "null", true),
       CONSTRUCTION_SPECIALTY_VEHICLE = new PLAT_CAT_LAND(87, "CONSTRUCTION_SPECIALTY_VEHICLE", "null", true),
       FARM_SPECIALTY_VEHICLE = new PLAT_CAT_LAND(88, "FARM_SPECIALTY_VEHICLE", "null", true),
       TRAILER = new PLAT_CAT_LAND(89, "TRAILER", "null", true),
       CAR_COUPE = new PLAT_CAT_LAND(90, "CAR_COUPE", "null", true),
       CAR_3_DOOR_HATCHBACK = new PLAT_CAT_LAND(91, "CAR_3_DOOR_HATCHBACK", "null", true),
       CAR_5_DOOR_HATCHBACK = new PLAT_CAT_LAND(92, "CAR_5_DOOR_HATCHBACK", "null", true),
       RECREATIONAL = new PLAT_CAT_LAND(93, "RECREATIONAL", "null", true),
       NON_MOTORIZED = new PLAT_CAT_LAND(94, "NON_MOTORIZED", "null", true),
       TRAINS = new PLAT_CAT_LAND(95, "TRAINS", "null", true),
       UTILITY_EMERGENCY_CAR = new PLAT_CAT_LAND(96, "UTILITY_EMERGENCY_CAR", "null", true);

    private PLAT_CAT_LAND(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, PLAT_CAT_LAND.class);
    }

    /** @see Value#values(Class) */
    public static List<PLAT_CAT_LAND> values() {

        return values(PLAT_CAT_LAND.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<PLAT_CAT_LAND> values(boolean known) {

        return values(PLAT_CAT_LAND.class, known);
    }

    /** @see Value#get(int, Class) */
    public static PLAT_CAT_LAND get(int value) {

        return get(value, PLAT_CAT_LAND.class);
    }
}

