package discover.vdis.enums;

import java.util.List;

/**
 * PLAT_CAT_SPACE: This class is auto-generated by vdis.EnumGenerator
 */
public final class PLAT_CAT_SPACE extends Value {

    public static final PLAT_CAT_SPACE
       OTH = new PLAT_CAT_SPACE(0, "OTH", "Other", true),
       MAN = new PLAT_CAT_SPACE(1, "MAN", "Manned", true),
       UNMAN = new PLAT_CAT_SPACE(2, "UNMAN", "Unmanned", true),
       BOOS = new PLAT_CAT_SPACE(3, "BOOS", "Booster", true);

    private PLAT_CAT_SPACE(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, PLAT_CAT_SPACE.class);
    }

    /** @see Value#values(Class) */
    public static List<PLAT_CAT_SPACE> values() {

        return values(PLAT_CAT_SPACE.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<PLAT_CAT_SPACE> values(boolean known) {

        return values(PLAT_CAT_SPACE.class, known);
    }

    /** @see Value#get(int, Class) */
    public static PLAT_CAT_SPACE get(int value) {

        return get(value, PLAT_CAT_SPACE.class);
    }
}

