package discover.vdis.enums;

import java.util.List;

/**
 * POSITION: This class is auto-generated by vdis.EnumGenerator
 */
public final class POSITION extends Value {

    public static final POSITION
       OTHER = new POSITION(0, "OTHER", "Other", true),
       ON_TOP_OF = new POSITION(1, "ON_TOP_OF", "On Top Of", true),
       INSIDE_OF = new POSITION(2, "INSIDE_OF", "Inside Of", true);

    private POSITION(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, POSITION.class);
    }

    /** @see Value#values(Class) */
    public static List<POSITION> values() {

        return values(POSITION.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<POSITION> values(boolean known) {

        return values(POSITION.class, known);
    }

    /** @see Value#get(int, Class) */
    public static POSITION get(int value) {

        return get(value, POSITION.class);
    }
}

