package discover.vdis.enums;

import java.util.List;

/**
 * PRECEDENCE_ENUM: This class is auto-generated by vdis.EnumGenerator
 */
public final class PRECEDENCE_ENUM extends Value {

    public static final PRECEDENCE_ENUM
       PRECEDENCE_UNDEFINED = new PRECEDENCE_ENUM(0, "PRECEDENCE_UNDEFINED", "Undefined", true),
       PRECEDENCE_EMERGENCY = new PRECEDENCE_ENUM(2, "PRECEDENCE_EMERGENCY", "Emergency", true),
       PRECEDENCE_FLASH = new PRECEDENCE_ENUM(4, "PRECEDENCE_FLASH", "Flash", true),
       PRECEDENCE_IMMEDIATE = new PRECEDENCE_ENUM(5, "PRECEDENCE_IMMEDIATE", "Immediate", true),
       PRECEDENCE_PRIORITY = new PRECEDENCE_ENUM(6, "PRECEDENCE_PRIORITY", "Priority", true),
       PRECEDENCE_ROUTINE = new PRECEDENCE_ENUM(7, "PRECEDENCE_ROUTINE", "Routine", true);

    private PRECEDENCE_ENUM(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, PRECEDENCE_ENUM.class);
    }

    /** @see Value#values(Class) */
    public static List<PRECEDENCE_ENUM> values() {

        return values(PRECEDENCE_ENUM.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<PRECEDENCE_ENUM> values(boolean known) {

        return values(PRECEDENCE_ENUM.class, known);
    }

    /** @see Value#get(int, Class) */
    public static PRECEDENCE_ENUM get(int value) {

        return get(value, PRECEDENCE_ENUM.class);
    }
}

