package discover.vdis.enums;

import java.util.List;

/**
 * PRESENT_DOMAIN: This class is auto-generated by vdis.EnumGenerator
 */
public final class PRESENT_DOMAIN extends Value {

    public static final PRESENT_DOMAIN
       PRESENT_DOM_ENUM_UNCHANGED = new PRESENT_DOMAIN(0, "PRESENT_DOM_ENUM_UNCHANGED", "Unchanged", true),
       PRESENT_DOM_ENUM_LAND = new PRESENT_DOMAIN(1, "PRESENT_DOM_ENUM_LAND", "Land", true),
       PRESENT_DOM_ENUM_AIR = new PRESENT_DOMAIN(2, "PRESENT_DOM_ENUM_AIR", "Air", true),
       PRESENT_DOM_ENUM_SURFACE = new PRESENT_DOMAIN(3, "PRESENT_DOM_ENUM_SURFACE", "Surface", true),
       PRESENT_DOM_ENUM_SUBSURFACE = new PRESENT_DOMAIN(4, "PRESENT_DOM_ENUM_SUBSURFACE", "Subsurface", true),
       PRESENT_DOM_ENUM_SPACE = new PRESENT_DOMAIN(5, "PRESENT_DOM_ENUM_SPACE", "Space", true),
       PRESENT_DOM_ENUM_SUBTERRANEAN_LAND = new PRESENT_DOMAIN(6, "PRESENT_DOM_ENUM_SUBTERRANEAN_LAND", "Subterranean Land", true),
       PRESENT_DOM_ENUM_SUBTERRANEAN_AIR = new PRESENT_DOMAIN(7, "PRESENT_DOM_ENUM_SUBTERRANEAN_AIR", "Subterranean Air", true),
       PRESENT_DOM_ENUM_SUBTERRANEAN_SURFACE = new PRESENT_DOMAIN(8, "PRESENT_DOM_ENUM_SUBTERRANEAN_SURFACE", "Subterranean Surface", true),
       PRESENT_DOM_ENUM_SUBTERRANEAN_SUBSURFACE = new PRESENT_DOMAIN(9, "PRESENT_DOM_ENUM_SUBTERRANEAN_SUBSURFACE", "Subterranean Subsurface", true),
       PRESENT_DOM_ENUM_SUBSURFACE_TERRAIN = new PRESENT_DOMAIN(10, "PRESENT_DOM_ENUM_SUBSURFACE_TERRAIN", "Subsurface Terrain", true),
       PRESENT_DOM_ENUM_SUBSURFACE_CAVES = new PRESENT_DOMAIN(11, "PRESENT_DOM_ENUM_SUBSURFACE_CAVES", "Subsurface Caves", true),
       PRESENT_DOM_ENUM_INTERIOR_OTHER_ENTITY = new PRESENT_DOMAIN(12, "PRESENT_DOM_ENUM_INTERIOR_OTHER_ENTITY", "Interior Other Entity/Object", true),
       PRESENT_DOM_ENUM_EXTERIOR_OTHER_ENTITY = new PRESENT_DOMAIN(13, "PRESENT_DOM_ENUM_EXTERIOR_OTHER_ENTITY", "Exterior Other Entity/Object", true),
       PRESENT_DOM_ENUM_ADMIN_INACTIVE = new PRESENT_DOMAIN(14, "PRESENT_DOM_ENUM_ADMIN_INACTIVE", "Administratively Inactive", true);

    private PRESENT_DOMAIN(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, PRESENT_DOMAIN.class);
    }

    /** @see Value#values(Class) */
    public static List<PRESENT_DOMAIN> values() {

        return values(PRESENT_DOMAIN.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<PRESENT_DOMAIN> values(boolean known) {

        return values(PRESENT_DOMAIN.class, known);
    }

    /** @see Value#get(int, Class) */
    public static PRESENT_DOMAIN get(int value) {

        return get(value, PRESENT_DOMAIN.class);
    }
}

