package discover.vdis.enums;

import java.util.List;

/**
 * PRESENCE: This class is auto-generated by vdis.EnumGenerator
 */
public final class PRESENCE extends Value {

    public static final PRESENCE
       NOT_PRESENT = new PRESENCE(0, "NOT_PRESENT", "Not Present", true),
       PRESENT = new PRESENCE(1, "PRESENT", "Present", true);

    private PRESENCE(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, PRESENCE.class);
    }

    /** @see Value#values(Class) */
    public static List<PRESENCE> values() {

        return values(PRESENCE.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<PRESENCE> values(boolean known) {

        return values(PRESENCE.class, known);
    }

    /** @see Value#get(int, Class) */
    public static PRESENCE get(int value) {

        return get(value, PRESENCE.class);
    }
}

