package discover.vdis.enums;

import java.util.List;

/**
 * PROTOCOL_VERSION: This class is auto-generated by vdis.EnumGenerator
 */
public final class PROTOCOL_VERSION extends Value {

    public static final PROTOCOL_VERSION
       PTCL_VER_OTHER = new PROTOCOL_VERSION(0, "PTCL_VER_OTHER", "Other", true),
       PTCL_VER_DIS_1_0_MAY_1992 = new PROTOCOL_VERSION(1, "PTCL_VER_DIS_1_0_MAY_1992", "DIS PDU version 1.0 (May 92)", true),
       PTCL_VER_IEEE_1278_1993 = new PROTOCOL_VERSION(2, "PTCL_VER_IEEE_1278_1993", "IEEE 1278-1993", true),
       PTCL_VER_DIS_2_0_THIRD_DRAFT = new PROTOCOL_VERSION(3, "PTCL_VER_DIS_2_0_THIRD_DRAFT", "DIS PDU version 2.0 - third draft (May 93)", true),
       PTCL_VER_DIS_2_0_FOURTH_DRAFT = new PROTOCOL_VERSION(4, "PTCL_VER_DIS_2_0_FOURTH_DRAFT", "DIS PDU version 2.0 - fourth draft (revised) March 16, 1994", true),
       PTCL_VER_IEEE_1278_1_1995 = new PROTOCOL_VERSION(5, "PTCL_VER_IEEE_1278_1_1995", "IEEE 1278.1-1995", true),
       PTCL_VER_IEEE_1278_1A_1998 = new PROTOCOL_VERSION(6, "PTCL_VER_IEEE_1278_1A_1998", "IEEE 1278.1A-1998", true),
       PTCL_VER_IEEE_1278_1_2012 = new PROTOCOL_VERSION(7, "PTCL_VER_IEEE_1278_1_2012", "IEEE 1278.1-2012", true);

    private PROTOCOL_VERSION(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, PROTOCOL_VERSION.class);
    }

    /** @see Value#values(Class) */
    public static List<PROTOCOL_VERSION> values() {

        return values(PROTOCOL_VERSION.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<PROTOCOL_VERSION> values(boolean known) {

        return values(PROTOCOL_VERSION.class, known);
    }

    /** @see Value#get(int, Class) */
    public static PROTOCOL_VERSION get(int value) {

        return get(value, PROTOCOL_VERSION.class);
    }
}

