package discover.vdis.enums;

import java.util.List;

/**
 * PULSE: This class is auto-generated by vdis.EnumGenerator
 */
public final class PULSE extends Value {

    public static final PULSE
       OTHER = new PULSE(0, "OTHER", "Other", true),
       PULSE = new PULSE(1, "PULSE", "Pulse", true),
       X_BAND_TACAN_PULSE = new PULSE(2, "X_BAND_TACAN_PULSE", "X Band TACAN Pulse", true),
       Y_BAND_TACAN_PULSE = new PULSE(3, "Y_BAND_TACAN_PULSE", "Y Band TACAN Pulse", true);

    private PULSE(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, PULSE.class);
    }

    /** @see Value#values(Class) */
    public static List<PULSE> values() {

        return values(PULSE.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<PULSE> values(boolean known) {

        return values(PULSE.class, known);
    }

    /** @see Value#get(int, Class) */
    public static PULSE get(int value) {

        return get(value, PULSE.class);
    }
}

