package discover.vdis.enums;

import java.util.List;

/**
 * RADIO_SYSTEM: This class is auto-generated by vdis.EnumGenerator
 */
public final class RADIO_SYSTEM extends Value {

    public static final RADIO_SYSTEM
       RADIO_OTHER = new RADIO_SYSTEM(0, "RADIO_OTHER", "Other", true),
       RADIO_GENERIC = new RADIO_SYSTEM(1, "RADIO_GENERIC", "Generic", true),
       RADIO_HQ = new RADIO_SYSTEM(2, "RADIO_HQ", "HQ", true),
       RADIO_HQII = new RADIO_SYSTEM(3, "RADIO_HQII", "HQII", true),
       RADIO_HQIIA = new RADIO_SYSTEM(4, "RADIO_HQIIA", "HQIIA", true),
       RADIO_SINCGARS = new RADIO_SYSTEM(5, "RADIO_SINCGARS", "SINCGARS", true),
       RADIO_CCTT_SINCGARS = new RADIO_SYSTEM(6, "RADIO_CCTT_SINCGARS", "CCTT SINCGARS", true),
       RADIO_EPLRS = new RADIO_SYSTEM(7, "RADIO_EPLRS", "EPLRS (Enhanced Position Location Reporting System)", true),
       RADIO_JTIDS_MIDS_ = new RADIO_SYSTEM(8, "RADIO_JTIDS_MIDS_", "JTIDS/MIDS ", true),
       RADIO_LINK_11 = new RADIO_SYSTEM(9, "RADIO_LINK_11", "Link 11", true),
       RADIO_LINK_11B = new RADIO_SYSTEM(10, "RADIO_LINK_11B", "Link 11B", true),
       RADIO_L_BAND_SATCOM = new RADIO_SYSTEM(11, "RADIO_L_BAND_SATCOM", "L-Band SATCOM", true),
       RADIO_ENHANCED_SINCGARS_7_3 = new RADIO_SYSTEM(12, "RADIO_ENHANCED_SINCGARS_7_3", "Enhanced SINCGARS 7.3", true),
       RADIO_NAVIGATION_AID = new RADIO_SYSTEM(13, "RADIO_NAVIGATION_AID", "Navigation Aid", true);

    private RADIO_SYSTEM(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, RADIO_SYSTEM.class);
    }

    /** @see Value#values(Class) */
    public static List<RADIO_SYSTEM> values() {

        return values(RADIO_SYSTEM.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<RADIO_SYSTEM> values(boolean known) {

        return values(RADIO_SYSTEM.class, known);
    }

    /** @see Value#get(int, Class) */
    public static RADIO_SYSTEM get(int value) {

        return get(value, RADIO_SYSTEM.class);
    }
}

