package discover.vdis.enums;

import java.util.List;

/**
 * RADIO_TYPE_CAT: This class is auto-generated by vdis.EnumGenerator
 */
public final class RADIO_TYPE_CAT extends Value {

    public static final RADIO_TYPE_CAT
       RT_CAT_OTHER = new RADIO_TYPE_CAT(0, "RT_CAT_OTHER", "Other", true),
       RT_CAT_VOICE_TRANS_REC = new RADIO_TYPE_CAT(1, "RT_CAT_VOICE_TRANS_REC", "Voice Transmission/Reception", true),
       RT_CAT_DATA_LINK_TRANS_REC = new RADIO_TYPE_CAT(2, "RT_CAT_DATA_LINK_TRANS_REC", "Data Link Transmission/Reception", true),
       RT_CAT_VOICE_AND_DATA_LINK_TRANS_REC = new RADIO_TYPE_CAT(3, "RT_CAT_VOICE_AND_DATA_LINK_TRANS_REC", "Voice and Data Link Transmission/Reception", true),
       RT_CAT_ILS_GLIDESLOPE_TRANS = new RADIO_TYPE_CAT(4, "RT_CAT_ILS_GLIDESLOPE_TRANS", "Instrumented Landing System (ILS) Glideslope Transmitter", true),
       RT_CAT_ILS_LOCALIZER_TRANS = new RADIO_TYPE_CAT(5, "RT_CAT_ILS_LOCALIZER_TRANS", "Instrumented Landing System (ILS) Localizer Transmitter", true),
       RT_CAT_ILS_OUTER_MARKER_BEACON = new RADIO_TYPE_CAT(6, "RT_CAT_ILS_OUTER_MARKER_BEACON", "Instrumented Landing System (ILS) Outer Marker Beacon", true),
       RT_CAT_ILS_MIDDLE_MARKER_BEACON = new RADIO_TYPE_CAT(7, "RT_CAT_ILS_MIDDLE_MARKER_BEACON", "Instrumented Landing System (ILS) Middle Marker Beacon", true),
       RT_CAT_ILS_INNER_MARKER_BEACON = new RADIO_TYPE_CAT(8, "RT_CAT_ILS_INNER_MARKER_BEACON", "Instrumented Landing System (ILS) Inner Marker Beacon", true),
       RT_CAT_ILS_REC_PLATFORM_RADIO = new RADIO_TYPE_CAT(9, "RT_CAT_ILS_REC_PLATFORM_RADIO", "Instrumented Landing System (ILS) Receiver (Platform Radio)", true),
       RT_CAT_TACAN_TRANS_GFE = new RADIO_TYPE_CAT(10, "RT_CAT_TACAN_TRANS_GFE", "Tactical Air Navigation (TACAN) Transmitter (Ground Fixed Equipment)", true),
       RT_CAT_TACAN_REC_MPE = new RADIO_TYPE_CAT(11, "RT_CAT_TACAN_REC_MPE", "Tactical Air Navigation (TACAN) Receiver (Moving Platform Equipment)", true),
       RT_CAT_TACAN_TRANS_REC_MPE = new RADIO_TYPE_CAT(12, "RT_CAT_TACAN_TRANS_REC_MPE", "Tactical Air Navigation (TACAN) Transmitter/Receiver (Moving Platform Equipment)", true),
       RT_CAT_VOR_TRANS_GFE = new RADIO_TYPE_CAT(13, "RT_CAT_VOR_TRANS_GFE", "Variable Omni-Ranging (VOR) Transmitter (Ground Fixed Equipment)", true),
       RT_CAT_VOR_WITH_DME_TRANS_GFE = new RADIO_TYPE_CAT(14, "RT_CAT_VOR_WITH_DME_TRANS_GFE", "Variable Omni-Ranging (VOR) with Distance Measuring Equipment (DME) Transmitter (Ground Fixed Equipment)", true),
       RT_CAT_COMBINED_VOR_ILS_REC_MPE = new RADIO_TYPE_CAT(15, "RT_CAT_COMBINED_VOR_ILS_REC_MPE", "Combined VOR/ILS Receiver (Moving Platform Equipment)", true),
       RT_CAT_COMBINED_VOR_TACAN_TRANS = new RADIO_TYPE_CAT(16, "RT_CAT_COMBINED_VOR_TACAN_TRANS", "Combined VOR/TACAN (VORTAC) Transmitter", true),
       RT_CAT_NDB_TRANS = new RADIO_TYPE_CAT(17, "RT_CAT_NDB_TRANS", "Non-Directional Beacon (NDB) Transmitter", true),
       RT_CAT_NDB_REC = new RADIO_TYPE_CAT(18, "RT_CAT_NDB_REC", "Non-Directional Beacon (NDB) Receiver", true),
       RT_CAT_NDB_WITH_DME_TRANS = new RADIO_TYPE_CAT(19, "RT_CAT_NDB_WITH_DME_TRANS", "Non-Directional Beacon (NDB) with Distance Measuring Equipment (DME) Transmitter", true),
       RT_CAT_DME = new RADIO_TYPE_CAT(20, "RT_CAT_DME", "Distance Measuring Equipment (DME)", true),
       RT_CAT_LINK_11_TERMINAL = new RADIO_TYPE_CAT(22, "RT_CAT_LINK_11_TERMINAL", "Link 11 Terminal", true),
       RT_CAT_LINK_11B_TERMINAL = new RADIO_TYPE_CAT(23, "RT_CAT_LINK_11B_TERMINAL", "Link 11B Terminal", true),
       RT_CAT_EPLRS_SADL_TERMINAL = new RADIO_TYPE_CAT(24, "RT_CAT_EPLRS_SADL_TERMINAL", "EPLRS/SADL Terminal", true),
       RT_CAT_IFDL = new RADIO_TYPE_CAT(25, "RT_CAT_IFDL", "F-22 Intra-Flight Data Link (IFDL)", true),
       RT_CAT_F35_MADL = new RADIO_TYPE_CAT(26, "RT_CAT_F35_MADL", "F-35 Multifunction Advanced Data Link (MADL)", true),
       RT_CAT_SINCGARS_TERMINAL = new RADIO_TYPE_CAT(27, "RT_CAT_SINCGARS_TERMINAL", "SINCGARS Terminal", true),
       RT_CAT_L_BAND_SATCOM_TERMINAL = new RADIO_TYPE_CAT(28, "RT_CAT_L_BAND_SATCOM_TERMINAL", "L-Band SATCOM Terminal", true),
       RT_CAT_IBS_IS_TERMINAL = new RADIO_TYPE_CAT(29, "RT_CAT_IBS_IS_TERMINAL", "IBS-I/S Terminal", true),
       RT_CAT_GPS = new RADIO_TYPE_CAT(30, "RT_CAT_GPS", "GPS", true);

    private RADIO_TYPE_CAT(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, RADIO_TYPE_CAT.class);
    }

    /** @see Value#values(Class) */
    public static List<RADIO_TYPE_CAT> values() {

        return values(RADIO_TYPE_CAT.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<RADIO_TYPE_CAT> values(boolean known) {

        return values(RADIO_TYPE_CAT.class, known);
    }

    /** @see Value#get(int, Class) */
    public static RADIO_TYPE_CAT get(int value) {

        return get(value, RADIO_TYPE_CAT.class);
    }
}

