package discover.vdis.enums;

import java.util.List;

/**
 * RECEIVER: This class is auto-generated by vdis.EnumGenerator
 */
public final class RECEIVER extends Value {

    public static final RECEIVER
       OFF = new RECEIVER(0, "OFF", "Off", true),
       ON_BUT_NOT_RECEIVING = new RECEIVER(1, "ON_BUT_NOT_RECEIVING", "On But Not Receiving", true),
       ON_AND_RECEIVING = new RECEIVER(2, "ON_AND_RECEIVING", "On And Receiving", true);

    private RECEIVER(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, RECEIVER.class);
    }

    /** @see Value#values(Class) */
    public static List<RECEIVER> values() {

        return values(RECEIVER.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<RECEIVER> values(boolean known) {

        return values(RECEIVER.class, known);
    }

    /** @see Value#get(int, Class) */
    public static RECEIVER get(int value) {

        return get(value, RECEIVER.class);
    }
}

