package discover.vdis.enums;

import java.util.List;

/**
 * RECORD_TYPE: This class is auto-generated by vdis.EnumGenerator
 */
public final class RECORD_TYPE extends Value {

    public static final RECORD_TYPE
       RECORD_ENTITY_DESTINATION_RECORD = new RECORD_TYPE(1, "RECORD_ENTITY_DESTINATION_RECORD", "Entity Destination Record", true),
       RECORD_GROUP_DESTINATION_RECORD = new RECORD_TYPE(2, "RECORD_GROUP_DESTINATION_RECORD", "Group Destination Record", true),
       RECORD_GROUP_ASSIGNMENT_RECORD = new RECORD_TYPE(3, "RECORD_GROUP_ASSIGNMENT_RECORD", "Group Assignment Record", true);

    private RECORD_TYPE(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, RECORD_TYPE.class);
    }

    /** @see Value#values(Class) */
    public static List<RECORD_TYPE> values() {

        return values(RECORD_TYPE.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<RECORD_TYPE> values(boolean known) {

        return values(RECORD_TYPE.class, known);
    }

    /** @see Value#get(int, Class) */
    public static RECORD_TYPE get(int value) {

        return get(value, RECORD_TYPE.class);
    }
}

