package discover.vdis.enums;

import java.util.List;

/**
 * REFERENCE_SYSTEM: This class is auto-generated by vdis.EnumGenerator
 */
public final class REFERENCE_SYSTEM extends Value {

    public static final REFERENCE_SYSTEM
       REF_UNDEFINED_COORDINATES = new REFERENCE_SYSTEM(0, "REF_UNDEFINED_COORDINATES", "Undefined Coordinates", true),
       REF_WORLD_COORDINATES = new REFERENCE_SYSTEM(1, "REF_WORLD_COORDINATES", "World Coordinates", true),
       REF_ENTITY_COORDINATES = new REFERENCE_SYSTEM(2, "REF_ENTITY_COORDINATES", "Entity Coordinates", true);

    private REFERENCE_SYSTEM(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, REFERENCE_SYSTEM.class);
    }

    /** @see Value#values(Class) */
    public static List<REFERENCE_SYSTEM> values() {

        return values(REFERENCE_SYSTEM.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<REFERENCE_SYSTEM> values(boolean known) {

        return values(REFERENCE_SYSTEM.class, known);
    }

    /** @see Value#get(int, Class) */
    public static REFERENCE_SYSTEM get(int value) {

        return get(value, REFERENCE_SYSTEM.class);
    }
}

