package discover.vdis.enums;

import java.util.List;

/**
 * REST_STATUS: This class is auto-generated by vdis.EnumGenerator
 */
public final class REST_STATUS extends Value {

    public static final REST_STATUS
       REST_NOT_RESTED = new REST_STATUS(0, "REST_NOT_RESTED", "Not Rested (Has Not Slept In The Last Three Days)", true),
       REST_HAS_SLEPT_AN_AVERAGE_OF_1_HOUR = new REST_STATUS(1, "REST_HAS_SLEPT_AN_AVERAGE_OF_1_HOUR", "Has Slept An Average Of 1 Hour Per Day In The Last Three Days", true),
       REST_HAS_SLEPT_AN_AVERAGE_OF_2_HOURS = new REST_STATUS(2, "REST_HAS_SLEPT_AN_AVERAGE_OF_2_HOURS", "Has Slept An Average Of 2 Hours Per Day In The Last Three Days", true),
       REST_HAS_SLEPT_AN_AVERAGE_OF_3_HOURS = new REST_STATUS(3, "REST_HAS_SLEPT_AN_AVERAGE_OF_3_HOURS", "Has Slept An Average Of 3 Hours Per Day In The Last Three Days", true),
       REST_HAS_SLEPT_AN_AVERAGE_OF_4_HOURS = new REST_STATUS(4, "REST_HAS_SLEPT_AN_AVERAGE_OF_4_HOURS", "Has Slept An Average Of 4 Hours Per Day In The Last Three Days", true),
       REST_HAS_SLEPT_AN_AVERAGE_OF_5_HOURS = new REST_STATUS(5, "REST_HAS_SLEPT_AN_AVERAGE_OF_5_HOURS", "Has Slept An Average Of 5 Hours Per Day In The Last Three Days", true),
       REST_HAS_SLEPT_AN_AVERAGE_OF_6_HOURS = new REST_STATUS(6, "REST_HAS_SLEPT_AN_AVERAGE_OF_6_HOURS", "Has Slept An Average Of 6 Hours Per Day In The Last Three Days", true),
       REST_HAS_SLEPT_AN_AVERAGE_OF_7_HOURS = new REST_STATUS(7, "REST_HAS_SLEPT_AN_AVERAGE_OF_7_HOURS", "Has Slept An Average Of 7 Hours Per Day In The Last Three Days", true),
       REST_FULLY_RESTED = new REST_STATUS(8, "REST_FULLY_RESTED", "Fully Rested (Has Slept An Average Of 8 Hours Per Day In The Last Three Days)", true);

    private REST_STATUS(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, REST_STATUS.class);
    }

    /** @see Value#values(Class) */
    public static List<REST_STATUS> values() {

        return values(REST_STATUS.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<REST_STATUS> values(boolean known) {

        return values(REST_STATUS.class, known);
    }

    /** @see Value#get(int, Class) */
    public static REST_STATUS get(int value) {

        return get(value, REST_STATUS.class);
    }
}

