package discover.vdis.enums;

import java.util.List;

/**
 * RQR_EVENT_TYPE: This class is auto-generated by vdis.EnumGenerator
 */
public final class RQR_EVENT_TYPE extends Value {

    public static final RQR_EVENT_TYPE
       OTHER = new RQR_EVENT_TYPE(0, "OTHER", "Other", true),
       INTERNAL_ES_DATA = new RQR_EVENT_TYPE(1, "INTERNAL_ES_DATA", "Internal Entity State Data", true);

    private RQR_EVENT_TYPE(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, RQR_EVENT_TYPE.class);
    }

    /** @see Value#values(Class) */
    public static List<RQR_EVENT_TYPE> values() {

        return values(RQR_EVENT_TYPE.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<RQR_EVENT_TYPE> values(boolean known) {

        return values(RQR_EVENT_TYPE.class, known);
    }

    /** @see Value#get(int, Class) */
    public static RQR_EVENT_TYPE get(int value) {

        return get(value, RQR_EVENT_TYPE.class);
    }
}

