package discover.vdis.enums;

import java.util.List;

/**
 * SE_CAT: This class is auto-generated by vdis.EnumGenerator
 */
public final class SE_CAT extends Value {

    public static final SE_CAT
       OTH = new SE_CAT(0, "OTH", "Other", true),
       MSPEC = new SE_CAT(1, "MSPEC", "Multi-spectral", true),
       RFA = new SE_CAT(2, "RFA", "RF Active", true),
       RFP = new SE_CAT(3, "RFP", "RF Passive (intercept and DF)", true),
       OPT = new SE_CAT(4, "OPT", "Optical (direct viewing with or without optics)", true),
       EO = new SE_CAT(5, "EO", "Electro-Optical", true),
       SEIS = new SE_CAT(6, "SEIS", "Seismic", true),
       CHEMPD = new SE_CAT(7, "CHEMPD", "Chemical, point detector", true),
       CHEMS = new SE_CAT(8, "CHEMS", "Chemical, standoff", true),
       THERM = new SE_CAT(9, "THERM", "Thermal (temperature sensing)", true),
       ACUA = new SE_CAT(10, "ACUA", "Acoustic, Active", true),
       ACUP = new SE_CAT(11, "ACUP", "Acoustic, Passive", true),
       CP = new SE_CAT(12, "CP", "Contact/Pressure (physical, hydrostatic, barometric)", true),
       EMRAD = new SE_CAT(13, "EMRAD", "Electro-Magnetic Radiation (gamma radiation)", true),
       PRAD = new SE_CAT(14, "PRAD", "Particle Radiation (Neutrons, alpha, beta particles)", true),
       MAG = new SE_CAT(15, "MAG", "Magnetic", true),
       GRAV = new SE_CAT(16, "GRAV", "Gravitational", true);

    private SE_CAT(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, SE_CAT.class);
    }

    /** @see Value#values(Class) */
    public static List<SE_CAT> values() {

        return values(SE_CAT.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<SE_CAT> values(boolean known) {

        return values(SE_CAT.class, known);
    }

    /** @see Value#get(int, Class) */
    public static SE_CAT get(int value) {

        return get(value, SE_CAT.class);
    }
}

