package discover.vdis.enums;

import java.util.List;

/**
 * SEVERITY: This class is auto-generated by vdis.EnumGenerator
 */
public final class SEVERITY extends Value {

    public static final SEVERITY
       NONE = new SEVERITY(0, "NONE", "None", true),
       SLIGHT = new SEVERITY(1, "SLIGHT", "Slight", true),
       MODERATE = new SEVERITY(2, "MODERATE", "Moderate", true),
       HEAVY = new SEVERITY(3, "HEAVY", "Heavy", true);

    private SEVERITY(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, SEVERITY.class);
    }

    /** @see Value#values(Class) */
    public static List<SEVERITY> values() {

        return values(SEVERITY.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<SEVERITY> values(boolean known) {

        return values(SEVERITY.class, known);
    }

    /** @see Value#get(int, Class) */
    public static SEVERITY get(int value) {

        return get(value, SEVERITY.class);
    }
}

