package discover.vdis.enums;

import java.util.List;

/**
 * SF_REASON_CODES: This class is auto-generated by vdis.EnumGenerator
 */
public final class SF_REASON_CODES extends Value {

    public static final SF_REASON_CODES
       SF_REASON_OTHER = new SF_REASON_CODES(0, "SF_REASON_OTHER", "Other", true),
       SF_REASON_RECESS = new SF_REASON_CODES(1, "SF_REASON_RECESS", "Recess", true),
       SF_REASON_TERMINATION = new SF_REASON_CODES(2, "SF_REASON_TERMINATION", "Termination", true),
       SF_REASON_SYSTEM_FAILURE = new SF_REASON_CODES(3, "SF_REASON_SYSTEM_FAILURE", "System Failure", true),
       SF_REASON_SECURITY_VIOLATION = new SF_REASON_CODES(4, "SF_REASON_SECURITY_VIOLATION", "Security Violation", true),
       SF_REASON_ENTITY_RECONSTITUTION = new SF_REASON_CODES(5, "SF_REASON_ENTITY_RECONSTITUTION", "Entity Reconstitution", true),
       SF_REASON_STOP_FOR_RESET = new SF_REASON_CODES(6, "SF_REASON_STOP_FOR_RESET", "Stop For Reset", true),
       SF_REASON_STOP_FOR_RESTART = new SF_REASON_CODES(7, "SF_REASON_STOP_FOR_RESTART", "Stop For Restart", true),
       SF_REASON_ABORT_TRAINING_RETURN_TAC_OPS = new SF_REASON_CODES(8, "SF_REASON_ABORT_TRAINING_RETURN_TAC_OPS", "Abort Training Return to Tactical Operations", true);

    private SF_REASON_CODES(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, SF_REASON_CODES.class);
    }

    /** @see Value#values(Class) */
    public static List<SF_REASON_CODES> values() {

        return values(SF_REASON_CODES.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<SF_REASON_CODES> values(boolean known) {

        return values(SF_REASON_CODES.class, known);
    }

    /** @see Value#get(int, Class) */
    public static SF_REASON_CODES get(int value) {

        return get(value, SF_REASON_CODES.class);
    }
}

