package discover.vdis.enums;

import java.util.List;

/**
 * SLING_DAMAGE: This class is auto-generated by vdis.EnumGenerator
 */
public final class SLING_DAMAGE extends Value {

    public static final SLING_DAMAGE
       NONE = new SLING_DAMAGE(0, "NONE", "None", true),
       SLING_DAMAGED = new SLING_DAMAGE(1, "SLING_DAMAGED", "Sling Damaged", true),
       LINE_DAMAGED = new SLING_DAMAGE(2, "LINE_DAMAGED", "Line Damaged", true),
       SLING_OR_LINE_DAMAGED = new SLING_DAMAGE(3, "SLING_OR_LINE_DAMAGED", "Sling or Line Destroyed", true);

    private SLING_DAMAGE(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, SLING_DAMAGE.class);
    }

    /** @see Value#values(Class) */
    public static List<SLING_DAMAGE> values() {

        return values(SLING_DAMAGE.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<SLING_DAMAGE> values(boolean known) {

        return values(SLING_DAMAGE.class, known);
    }

    /** @see Value#get(int, Class) */
    public static SLING_DAMAGE get(int value) {

        return get(value, SLING_DAMAGE.class);
    }
}

