package discover.vdis.enums;

import java.util.List;

/**
 * SPEED_BUMP_MTL: This class is auto-generated by vdis.EnumGenerator
 */
public final class SPEED_BUMP_MTL extends Value {

    public static final SPEED_BUMP_MTL
       MTL_SPEED_BUMP_NOT_SPECIFIED = new SPEED_BUMP_MTL(0, "MTL_SPEED_BUMP_NOT_SPECIFIED", "Not specified", true),
       MTL_SPEED_BUMP_PLASTIC = new SPEED_BUMP_MTL(1, "MTL_SPEED_BUMP_PLASTIC", "Plastic", true),
       MTL_SPEED_BUMP_RUBBER = new SPEED_BUMP_MTL(2, "MTL_SPEED_BUMP_RUBBER", "Rubber", true),
       MTL_SPEED_BUMP_ROAD = new SPEED_BUMP_MTL(3, "MTL_SPEED_BUMP_ROAD", "Road", true);

    private SPEED_BUMP_MTL(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, SPEED_BUMP_MTL.class);
    }

    /** @see Value#values(Class) */
    public static List<SPEED_BUMP_MTL> values() {

        return values(SPEED_BUMP_MTL.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<SPEED_BUMP_MTL> values(boolean known) {

        return values(SPEED_BUMP_MTL.class, known);
    }

    /** @see Value#get(int, Class) */
    public static SPEED_BUMP_MTL get(int value) {

        return get(value, SPEED_BUMP_MTL.class);
    }
}

