package discover.vdis.enums;

import java.util.List;

/**
 * START_OF_MESSAGE: This class is auto-generated by vdis.EnumGenerator
 */
public final class START_OF_MESSAGE extends Value {

    public static final START_OF_MESSAGE
       START_NOT_START_OF_MESSAGE = new START_OF_MESSAGE(0, "START_NOT_START_OF_MESSAGE", "Not Start Of Message", true),
       START_START_OF_MESSAGE = new START_OF_MESSAGE(1, "START_START_OF_MESSAGE", "Start Of Message", true);

    private START_OF_MESSAGE(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, START_OF_MESSAGE.class);
    }

    /** @see Value#values(Class) */
    public static List<START_OF_MESSAGE> values() {

        return values(START_OF_MESSAGE.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<START_OF_MESSAGE> values(boolean known) {

        return values(START_OF_MESSAGE.class, known);
    }

    /** @see Value#get(int, Class) */
    public static START_OF_MESSAGE get(int value) {

        return get(value, START_OF_MESSAGE.class);
    }
}

