package discover.vdis.enums;

import java.util.List;

/**
 * STATION_NAME: This class is auto-generated by vdis.EnumGenerator
 */
public final class STATION_NAME extends Value {

    public static final STATION_NAME
       STATION_OTHER = new STATION_NAME(0, "STATION_OTHER", "Other", true),
       STATION_AIRCRAFT_WINGSTATION = new STATION_NAME(1, "STATION_AIRCRAFT_WINGSTATION", "Aircraft Wingstation", true),
       STATION_SHIPS_FORWARD_GUNMOUNT_STARBOARD = new STATION_NAME(2, "STATION_SHIPS_FORWARD_GUNMOUNT_STARBOARD", "Ships Forward Gunmount (Starboard)", true),
       STATION_SHIPS_FORWARD_GUNMOUNT_PORT = new STATION_NAME(3, "STATION_SHIPS_FORWARD_GUNMOUNT_PORT", "Ships Forward Gunmount (Port)", true),
       STATION_SHIPS_FORWARD_GUNMOUNT_CENTERLINE = new STATION_NAME(4, "STATION_SHIPS_FORWARD_GUNMOUNT_CENTERLINE", "Ships Forward Gunmount (Centerline)", true),
       STATION_SHIPS_AFT_GUNMOUNT_STARBOARD = new STATION_NAME(5, "STATION_SHIPS_AFT_GUNMOUNT_STARBOARD", "Ships Aft Gunmount (Starboard)", true),
       STATION_SHIPS_AFT_GUNMOUNT_PORT = new STATION_NAME(6, "STATION_SHIPS_AFT_GUNMOUNT_PORT", "Ships Aft Gunmount (Port)", true),
       STATION_SHIPS_AFT_GUNMOUNT_CENTERLINE = new STATION_NAME(7, "STATION_SHIPS_AFT_GUNMOUNT_CENTERLINE", "Ships Aft Gunmount (Centerline)", true),
       STATION_FORWARD_TORPEDO_TUBE = new STATION_NAME(8, "STATION_FORWARD_TORPEDO_TUBE", "Forward Torpedo Tube", true),
       STATION_AFT_TORPEDO_TUBE = new STATION_NAME(9, "STATION_AFT_TORPEDO_TUBE", "Aft Torpedo Tube", true),
       STATION_BOMB_BAY = new STATION_NAME(10, "STATION_BOMB_BAY", "Bomb Bay", true),
       STATION_CARGO_BAY = new STATION_NAME(11, "STATION_CARGO_BAY", "Cargo Bay", true),
       STATION_TRUCK_BED = new STATION_NAME(12, "STATION_TRUCK_BED", "Truck Bed", true),
       STATION_TRAILER_BED = new STATION_NAME(13, "STATION_TRAILER_BED", "Trailer Bed", true),
       STATION_WELL_DECK = new STATION_NAME(14, "STATION_WELL_DECK", "Well Deck", true),
       STATION_ON_STATION_RNG_BRG = new STATION_NAME(15, "STATION_ON_STATION_RNG_BRG", "On Station - (Rng/Brg)", true),
       STATION_ON_STATION_XYZ = new STATION_NAME(16, "STATION_ON_STATION_XYZ", "On Station - (X,Y,Z)", true);

    private STATION_NAME(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, STATION_NAME.class);
    }

    /** @see Value#values(Class) */
    public static List<STATION_NAME> values() {

        return values(STATION_NAME.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<STATION_NAME> values(boolean known) {

        return values(STATION_NAME.class, known);
    }

    /** @see Value#get(int, Class) */
    public static STATION_NAME get(int value) {

        return get(value, STATION_NAME.class);
    }
}

