package discover.vdis.enums;

import java.util.List;

/**
 * STEALTHSTATE_SENSOR_MODE: This class is auto-generated by vdis.EnumGenerator
 */
public final class STEALTHSTATE_SENSOR_MODE extends Value {

    public static final STEALTHSTATE_SENSOR_MODE
       OTHER = new STEALTHSTATE_SENSOR_MODE(0, "OTHER", "Other", true),
       OTW = new STEALTHSTATE_SENSOR_MODE(1, "OTW", "Out the Window (OTW)", true),
       IR = new STEALTHSTATE_SENSOR_MODE(2, "IR", "Infrared (IR)", true),
       NVG = new STEALTHSTATE_SENSOR_MODE(3, "NVG", "Night Vision Goggles (NVG)", true);

    private STEALTHSTATE_SENSOR_MODE(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, STEALTHSTATE_SENSOR_MODE.class);
    }

    /** @see Value#values(Class) */
    public static List<STEALTHSTATE_SENSOR_MODE> values() {

        return values(STEALTHSTATE_SENSOR_MODE.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<STEALTHSTATE_SENSOR_MODE> values(boolean known) {

        return values(STEALTHSTATE_SENSOR_MODE.class, known);
    }

    /** @see Value#get(int, Class) */
    public static STEALTHSTATE_SENSOR_MODE get(int value) {

        return get(value, STEALTHSTATE_SENSOR_MODE.class);
    }
}

