package discover.vdis.enums;

import java.util.List;

/**
 * STEALTH_ATTACH_MODE: This class is auto-generated by vdis.EnumGenerator
 */
public final class STEALTH_ATTACH_MODE extends Value {

    public static final STEALTH_ATTACH_MODE
       STEALTH_ATTATCH_MODE_FREE = new STEALTH_ATTACH_MODE(0, "STEALTH_ATTATCH_MODE_FREE", "Free", true),
       STEALTH_ATTATCH_MODE_HUG = new STEALTH_ATTACH_MODE(1, "STEALTH_ATTATCH_MODE_HUG", "Hug", true),
       STEALTH_ATTATCH_MODE_TETHER = new STEALTH_ATTACH_MODE(2, "STEALTH_ATTATCH_MODE_TETHER", "Tether", true),
       STEALTH_ATTATCH_MODE_COMPASS = new STEALTH_ATTACH_MODE(3, "STEALTH_ATTATCH_MODE_COMPASS", "Compass", true),
       STEALTH_ATTATCH_MODE_ORBIT = new STEALTH_ATTACH_MODE(4, "STEALTH_ATTATCH_MODE_ORBIT", "Orbit", true),
       STEALTH_ATTATCH_MODE_MIMIC = new STEALTH_ATTACH_MODE(5, "STEALTH_ATTATCH_MODE_MIMIC", "Mimic", true),
       STEALTH_ATTATCH_MODE_NO = new STEALTH_ATTACH_MODE(6, "STEALTH_ATTATCH_MODE_NO", "No", true),
       STEALTH_ATTATCH_MODE_GUNSIGHT = new STEALTH_ATTACH_MODE(7, "STEALTH_ATTATCH_MODE_GUNSIGHT", "Gunsight", true);

    private STEALTH_ATTACH_MODE(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, STEALTH_ATTACH_MODE.class);
    }

    /** @see Value#values(Class) */
    public static List<STEALTH_ATTACH_MODE> values() {

        return values(STEALTH_ATTACH_MODE.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<STEALTH_ATTACH_MODE> values(boolean known) {

        return values(STEALTH_ATTACH_MODE.class, known);
    }

    /** @see Value#get(int, Class) */
    public static STEALTH_ATTACH_MODE get(int value) {

        return get(value, STEALTH_ATTACH_MODE.class);
    }
}

