package discover.vdis.enums;

import java.util.List;

/**
 * STEALTH_ATTACH_COMMAND: This class is auto-generated by vdis.EnumGenerator
 */
public final class STEALTH_ATTACH_COMMAND extends Value {

    public static final STEALTH_ATTACH_COMMAND
       STEALTH_ATTACH_COM_SPECIFIC = new STEALTH_ATTACH_COMMAND(0, "STEALTH_ATTACH_COM_SPECIFIC", "Specific", true),
       STEALTH_ATTACH_COM_ANY = new STEALTH_ATTACH_COMMAND(1, "STEALTH_ATTACH_COM_ANY", "Any", true),
       STEALTH_ATTACH_COM_DETACH = new STEALTH_ATTACH_COMMAND(2, "STEALTH_ATTACH_COM_DETACH", "Detach", true);

    private STEALTH_ATTACH_COMMAND(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, STEALTH_ATTACH_COMMAND.class);
    }

    /** @see Value#values(Class) */
    public static List<STEALTH_ATTACH_COMMAND> values() {

        return values(STEALTH_ATTACH_COMMAND.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<STEALTH_ATTACH_COMMAND> values(boolean known) {

        return values(STEALTH_ATTACH_COMMAND.class, known);
    }

    /** @see Value#get(int, Class) */
    public static STEALTH_ATTACH_COMMAND get(int value) {

        return get(value, STEALTH_ATTACH_COMMAND.class);
    }
}

