package discover.vdis.enums;

import java.util.List;

/**
 * TDL_TYPE: This class is auto-generated by vdis.EnumGenerator
 */
public final class TDL_TYPE extends Value {

    public static final TDL_TYPE
       TDL_OTHER = new TDL_TYPE(0, "TDL_OTHER", "Other", true),
       TDL_PADIL = new TDL_TYPE(1, "TDL_PADIL", "Padil", true),
       TDL_NATO_LINK_1 = new TDL_TYPE(2, "TDL_NATO_LINK_1", "NATO Link-1", true),
       TDL_ATDL_1 = new TDL_TYPE(3, "TDL_ATDL_1", "ATDL-1", true),
       TDL_LINK_11B_TADIL_B = new TDL_TYPE(4, "TDL_LINK_11B_TADIL_B", "Link 11B (TADIL B)", true),
       TDL_SITUATIONAL_AWARENESS_DATA_LINK_SADL = new TDL_TYPE(5, "TDL_SITUATIONAL_AWARENESS_DATA_LINK_SADL", "Situational Awareness Data Link (SADL)", true),
       TDL_LINK_16_LEGACY_FORMAT__JTIDS_TADIL_J = new TDL_TYPE(6, "TDL_LINK_16_LEGACY_FORMAT__JTIDS_TADIL_J", "Link 16 Legacy Format  (JTIDS/TADIL-J)", true),
       TDL_LINK_16_LEGACY_FORMAT_JTIDS_FDL_TADIL_J = new TDL_TYPE(7, "TDL_LINK_16_LEGACY_FORMAT_JTIDS_FDL_TADIL_J", "Link 16 Legacy Format (JTIDS/FDL/TADIL-J)", true),
       TDL_LINK_11A_TADIL_A = new TDL_TYPE(8, "TDL_LINK_11A_TADIL_A", "Link 11A (TADIL A)", true),
       TDL_IJMS = new TDL_TYPE(9, "TDL_IJMS", "IJMS", true),
       TDL_LINK_4A_TADIL_C = new TDL_TYPE(10, "TDL_LINK_4A_TADIL_C", "Link 4A (TADIL C)", true),
       TDL_LINK_4C = new TDL_TYPE(11, "TDL_LINK_4C", "Link 4C", true),
       TDL_TIBS = new TDL_TYPE(12, "TDL_TIBS", "TIBS", true),
       TDL_ATL = new TDL_TYPE(13, "TDL_ATL", "ATL", true),
       TDL_CONSTANT_SOURCE = new TDL_TYPE(14, "TDL_CONSTANT_SOURCE", "Constant Source", true),
       TDL_ABBREVIATED_COMMAND_AND_CONTROL = new TDL_TYPE(15, "TDL_ABBREVIATED_COMMAND_AND_CONTROL", "Abbreviated Command and Control", true),
       TDL_MILSTAR = new TDL_TYPE(16, "TDL_MILSTAR", "MILSTAR", true),
       TDL_ATHS = new TDL_TYPE(17, "TDL_ATHS", "ATHS", true),
       TDL_OTHGOLD = new TDL_TYPE(18, "TDL_OTHGOLD", "OTHGOLD", true),
       TDL_TACELINT = new TDL_TYPE(19, "TDL_TACELINT", "TACELINT", true),
       TDL_WEAPONS_DATA_LINK_AWW_13 = new TDL_TYPE(20, "TDL_WEAPONS_DATA_LINK_AWW_13", "Weapons Data Link (AWW-13)", true),
       TDL_ABBR_COMMAND_AND_CONTROL = new TDL_TYPE(21, "TDL_ABBR_COMMAND_AND_CONTROL", "Abbreviated Command and Control", true),
       TDL_ENHANCED_POSITION_LOCATION_REPORTING_SYS_EPLRS = new TDL_TYPE(22, "TDL_ENHANCED_POSITION_LOCATION_REPORTING_SYS_EPLRS", "Enhanced Position Location Reporting System (EPLRS)", true),
       TDL_POSITION_LOCATION_REPORTING_SYS_PLRS = new TDL_TYPE(23, "TDL_POSITION_LOCATION_REPORTING_SYS_PLRS", "Position Location Reporting System (PLRS)", true),
       TDL_SINCGARS = new TDL_TYPE(24, "TDL_SINCGARS", "SINCGARS", true),
       TDL_HAVE_QUICK_I = new TDL_TYPE(25, "TDL_HAVE_QUICK_I", "Have Quick I", true),
       TDL_HAVE_QUICK_II = new TDL_TYPE(26, "TDL_HAVE_QUICK_II", "Have Quick II", true),
       TDL_HAVE_QUICK_IIA_SATURN = new TDL_TYPE(27, "TDL_HAVE_QUICK_IIA_SATURN", "Have Quick IIa (SATURN)", true),
       TDL_INTRA_FLIGHT_DATA_LINK_1 = new TDL_TYPE(28, "TDL_INTRA_FLIGHT_DATA_LINK_1", "Intra-Flight Data Link 1", true),
       TDL_INTRA_FLIGHT_DATA_LINK_2 = new TDL_TYPE(29, "TDL_INTRA_FLIGHT_DATA_LINK_2", "Intra-Flight Data Link 2", true),
       TDL_IMPROVED_DATA_MODEM_IDM = new TDL_TYPE(30, "TDL_IMPROVED_DATA_MODEM_IDM", "Improved Data Modem (IDM)", true),
       TDL_AIR_FORCE_APPLICATION_PROGRAM_DEVELOPMENT_AFAPD = new TDL_TYPE(31, "TDL_AIR_FORCE_APPLICATION_PROGRAM_DEVELOPMENT_AFAPD", "Air Force Application Program Development (AFAPD)", true),
       TDL_COOPERATIVE_ENGAGEMENT_CAPABILITY_CEC = new TDL_TYPE(32, "TDL_COOPERATIVE_ENGAGEMENT_CAPABILITY_CEC", "Cooperative Engagement Capability (CEC)", true),
       TDL_FORWARD_AREA_AIR_DEFENSE_FAAD_DATA_LINK_FDL = new TDL_TYPE(33, "TDL_FORWARD_AREA_AIR_DEFENSE_FAAD_DATA_LINK_FDL", "Forward Area Air Defense (FAAD) Data Link (FDL)", true),
       TDL_GROUND_BASED_DATA_LINK_GBDL = new TDL_TYPE(34, "TDL_GROUND_BASED_DATA_LINK_GBDL", "Ground Based Data Link (GBDL)", true),
       TDL_INTRA_VEHICULAR_INFO_SYS_IVIS = new TDL_TYPE(35, "TDL_INTRA_VEHICULAR_INFO_SYS_IVIS", "Intra Vehicular Info System (IVIS)", true),
       TDL_MARINE_TACTICAL_SYS_MTS = new TDL_TYPE(36, "TDL_MARINE_TACTICAL_SYS_MTS", "Marine Tactical System (MTS)", true),
       TDL_TACTICAL_FIRE_DIRECTION_SYS_TACFIRE = new TDL_TYPE(37, "TDL_TACTICAL_FIRE_DIRECTION_SYS_TACFIRE", "Tactical Fire Direction System (TACFIRE)", true),
       TDL_INTEGRATED_BROADCAST_SERVICE_IBS = new TDL_TYPE(38, "TDL_INTEGRATED_BROADCAST_SERVICE_IBS", "Integrated Broadcast Service (IBS)", true),
       TDL_AIRBORNE_INFORMATION_TRANSFER_ABIT = new TDL_TYPE(39, "TDL_AIRBORNE_INFORMATION_TRANSFER_ABIT", "Airborne Information Transfer (ABIT)", true),
       TDL_ADVANCED_TACTICAL_AIRBORNE_RECON_SYS_ATARS_DATA_LINK = new TDL_TYPE(40, "TDL_ADVANCED_TACTICAL_AIRBORNE_RECON_SYS_ATARS_DATA_LINK", "Advanced Tactical Airborne Reconnaissance System (ATARS) Data Link", true),
       TDL_BATTLE_GROUP_PASSIVE_HORIZON_EXTENSION_SYS_BGPHES_DATA_LINK = new TDL_TYPE(41, "TDL_BATTLE_GROUP_PASSIVE_HORIZON_EXTENSION_SYS_BGPHES_DATA_LINK", "Battle Group Passive Horizon Extension System (BGPHES) Data Link", true),
       TDL_COMMON_HIGH_BANDWIDTH_DATA_LINK_CHBDL = new TDL_TYPE(42, "TDL_COMMON_HIGH_BANDWIDTH_DATA_LINK_CHBDL", "Common High Bandwidth Data Link (CHBDL)", true),
       TDL_GUARDRAIL_INTEROPERABLE_DATA_LINK_IDL = new TDL_TYPE(43, "TDL_GUARDRAIL_INTEROPERABLE_DATA_LINK_IDL", "Guardrail Interoperable Data Link (IDL)", true),
       TDL_GUARDRAIL_COMMON_SENSOR_SYS_ONE_CSS1_DATA_LINK = new TDL_TYPE(44, "TDL_GUARDRAIL_COMMON_SENSOR_SYS_ONE_CSS1_DATA_LINK", "Guardrail Common Sensor System One (CSS1) Data Link", true),
       TDL_GUARDRAIL_COMMON_SENSOR_SYS_TWO_CSS2_DATA_LINK = new TDL_TYPE(45, "TDL_GUARDRAIL_COMMON_SENSOR_SYS_TWO_CSS2_DATA_LINK", "Guardrail Common Sensor System Two (CSS2) Data Link", true),
       TDL_GUARDRAIL_CSS2_MULTI_ROLE_DATA_LINK_MRDL = new TDL_TYPE(46, "TDL_GUARDRAIL_CSS2_MULTI_ROLE_DATA_LINK_MRDL", "Guardrail CSS2 Multi-Role Data Link (MRDL)", true),
       TDL_GUARDRAIL_CSS2_DIRECT_AIR_TO_SATELLITE_RELAY_DASR_DATA_LINK = new TDL_TYPE(47, "TDL_GUARDRAIL_CSS2_DIRECT_AIR_TO_SATELLITE_RELAY_DASR_DATA_LINK", "Guardrail CSS2 Direct Air To Satellite Relay (DASR) Data Link", true),
       TDL_LINE_OF_SIGHT_LOS_DATA_LINK_IMP_LOS_TETHER = new TDL_TYPE(48, "TDL_LINE_OF_SIGHT_LOS_DATA_LINK_IMP_LOS_TETHER", "Line of Sight (LOS) Data Link Implementation (LOS TETHER)", true),
       TDL_LIGHTWEIGHT_CDL_LWCDL = new TDL_TYPE(49, "TDL_LIGHTWEIGHT_CDL_LWCDL", "Lightweight CDL (LWCDL)", true),
       TDL_L_52M_SR_71 = new TDL_TYPE(50, "TDL_L_52M_SR_71", "L-52M (SR-71)", true),
       TDL_RIVET_REACH_RIVET_OWL_DATA_LINK = new TDL_TYPE(51, "TDL_RIVET_REACH_RIVET_OWL_DATA_LINK", "Rivet Reach/Rivet Owl Data Link", true),
       TDL_SENIOR_SPAN = new TDL_TYPE(52, "TDL_SENIOR_SPAN", "Senior Span", true),
       TDL_SENIOR_SPUR = new TDL_TYPE(53, "TDL_SENIOR_SPUR", "Senior Spur", true),
       TDL_SENIOR_STRETCH = new TDL_TYPE(54, "TDL_SENIOR_STRETCH", "Senior Stretch", true),
       TDL_SENIOR_YEAR_INTEROPERABLE_DATA_LINK_IDL = new TDL_TYPE(55, "TDL_SENIOR_YEAR_INTEROPERABLE_DATA_LINK_IDL", "Senior Year Interoperable Data Link (IDL)", true),
       TDL_SPACE_CDL = new TDL_TYPE(56, "TDL_SPACE_CDL", "Space CDL", true),
       TDL_TR_1_MODE_MIST_AIRBORNE_DATA_LINK = new TDL_TYPE(57, "TDL_TR_1_MODE_MIST_AIRBORNE_DATA_LINK", "TR-1 Mode Mist Airborne Data Link", true),
       TDL_KU_BAND_SATCOM_DATA_LINK_IMP_UAV = new TDL_TYPE(58, "TDL_KU_BAND_SATCOM_DATA_LINK_IMP_UAV", "Ku-Band Satcom Data Link Implementation (UAV)", true),
       TDL_MISSION_EQUIPMENT_CONTROL_DATA_LINK_MECDL = new TDL_TYPE(59, "TDL_MISSION_EQUIPMENT_CONTROL_DATA_LINK_MECDL", "Mission Equipment Control Data Link (MECDL)", true),
       TDL_RADAR_DATA_TRANSMITTING_SET_DATA_LINK = new TDL_TYPE(60, "TDL_RADAR_DATA_TRANSMITTING_SET_DATA_LINK", "Radar Data Transmitting Set Data Link", true),
       TDL_SURVEILLANCE_AND_CONTROL_DATA_LINK_SCDL = new TDL_TYPE(61, "TDL_SURVEILLANCE_AND_CONTROL_DATA_LINK_SCDL", "Surveillance And Control Data Link (SCDL)", true),
       TDL_TACTICAL_UAV_VIDEO = new TDL_TYPE(62, "TDL_TACTICAL_UAV_VIDEO", "Tactical UAV Video", true),
       TDL_UHF_SATCOM_DATA_LINK_IMP_UAV = new TDL_TYPE(63, "TDL_UHF_SATCOM_DATA_LINK_IMP_UAV", "UHF Satcom Data Link Implementation (UAV)", true),
       TDL_TACTICAL_COMMON_DATA_LINK_TCDL = new TDL_TYPE(64, "TDL_TACTICAL_COMMON_DATA_LINK_TCDL", "Tactical Common Data Link (TCDL)", true),
       TDL_LOW_LEVEL_AIR_PICTURE_INTERFACE_LLAPI = new TDL_TYPE(65, "TDL_LOW_LEVEL_AIR_PICTURE_INTERFACE_LLAPI", "Low Level Air Picture Interface (LLAPI)", true),
       TDL_WEAPONS_DATA_LINK_AGM_130 = new TDL_TYPE(66, "TDL_WEAPONS_DATA_LINK_AGM_130", "Weapons Data Link (AGM-130)", true),
       TDL_GC3 = new TDL_TYPE(99, "TDL_GC3", "GC3", true),
       TDL_LINK_16_STANDARDIZED_FORMAT_JTIDS_MIDS_TADIL_J = new TDL_TYPE(100, "TDL_LINK_16_STANDARDIZED_FORMAT_JTIDS_MIDS_TADIL_J", "Link 16 Standardized Format (JTIDS/MIDS/TADIL J)", true),
       TDL_LINK_16_ENHANCED_DATA_RATE_EDR_JTIDS_MIDS_TADIL_J = new TDL_TYPE(101, "TDL_LINK_16_ENHANCED_DATA_RATE_EDR_JTIDS_MIDS_TADIL_J", "Link 16 Enhanced Data Rate (EDR JTIDS/MIDS/TADIL-J)", true),
       TDL_JTIDS_MIDS_NET_DATA_LOAD_TIMS_TOMS = new TDL_TYPE(102, "TDL_JTIDS_MIDS_NET_DATA_LOAD_TIMS_TOMS", "JTIDS/MIDS Net Data Load (TIMS/TOMS)", true),
       TDL_LINK_22 = new TDL_TYPE(103, "TDL_LINK_22", "Link 22", true),
       TDL_AFIWC_IADS_COMM_LINKS = new TDL_TYPE(104, "TDL_AFIWC_IADS_COMM_LINKS", "AFIWC IADS Communications Links", true),
       TDL_INTER_FLIGHT_DATA_LINK = new TDL_TYPE(105, "TDL_INTER_FLIGHT_DATA_LINK", "Inter Flight Data Link (IFDL)", true),
       TDL_L_BAND_SATCOM = new TDL_TYPE(106, "TDL_L_BAND_SATCOM", "L-Band SATCOM", true),
       TDL_TSAF_COMM_LINK = new TDL_TYPE(107, "TDL_TSAF_COMM_LINK", "TSAF Communications Link", true),
       TDL_ENHANCED_SINCGARS_7_3 = new TDL_TYPE(108, "TDL_ENHANCED_SINCGARS_7_3", "Enhanced SINCGARS 7.3", true),
       TDL_MULTIFUNCTION_ADV_DATA_LINK = new TDL_TYPE(109, "TDL_MULTIFUNCTION_ADV_DATA_LINK", "Multifunction Advanced Data Link (MADL)", true),
       TDL_CURSOR_ON_TARGET = new TDL_TYPE(110, "TDL_CURSOR_ON_TARGET", "Cursor on Target", true);

    private TDL_TYPE(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, TDL_TYPE.class);
    }

    /** @see Value#values(Class) */
    public static List<TDL_TYPE> values() {

        return values(TDL_TYPE.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<TDL_TYPE> values(boolean known) {

        return values(TDL_TYPE.class, known);
    }

    /** @see Value#get(int, Class) */
    public static TDL_TYPE get(int value) {

        return get(value, TDL_TYPE.class);
    }
}

