package discover.vdis.enums;

import java.util.List;

/**
 * TERMINAL_PRIMARY: This class is auto-generated by vdis.EnumGenerator
 */
public final class TERMINAL_PRIMARY extends Value {

    public static final TERMINAL_PRIMARY
       NONE = new TERMINAL_PRIMARY(0, "NONE", "None", true),
       NTR = new TERMINAL_PRIMARY(1, "NTR", "NTR", true),
       JTIDS_UNIT_PARTICIPANT = new TERMINAL_PRIMARY(2, "JTIDS_UNIT_PARTICIPANT", "JTIDS Unit Participant", true);

    private TERMINAL_PRIMARY(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, TERMINAL_PRIMARY.class);
    }

    /** @see Value#values(Class) */
    public static List<TERMINAL_PRIMARY> values() {

        return values(TERMINAL_PRIMARY.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<TERMINAL_PRIMARY> values(boolean known) {

        return values(TERMINAL_PRIMARY.class, known);
    }

    /** @see Value#get(int, Class) */
    public static TERMINAL_PRIMARY get(int value) {

        return get(value, TERMINAL_PRIMARY.class);
    }
}

