package discover.vdis.enums;

import java.util.List;

/**
 * TRANSMIT_LINE: This class is auto-generated by vdis.EnumGenerator
 */
public final class TRANSMIT_LINE extends Value {

    public static final TRANSMIT_LINE
       TRANSMIT_TRANSMIT_LINE_STATE_NOT_APPLICABLE = new TRANSMIT_LINE(0, "TRANSMIT_TRANSMIT_LINE_STATE_NOT_APPLICABLE", "Transmit Line State Not Applicable", true),
       TRANSMIT_NOT_TRANSMITTING = new TRANSMIT_LINE(1, "TRANSMIT_NOT_TRANSMITTING", "Not Transmitting", true),
       TRANSMIT_TRANSMITTING = new TRANSMIT_LINE(2, "TRANSMIT_TRANSMITTING", "Transmitting", true);

    private TRANSMIT_LINE(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, TRANSMIT_LINE.class);
    }

    /** @see Value#values(Class) */
    public static List<TRANSMIT_LINE> values() {

        return values(TRANSMIT_LINE.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<TRANSMIT_LINE> values(boolean known) {

        return values(TRANSMIT_LINE.class, known);
    }

    /** @see Value#get(int, Class) */
    public static TRANSMIT_LINE get(int value) {

        return get(value, TRANSMIT_LINE.class);
    }
}

