package discover.vdis.enums;

import java.util.List;

/**
 * TRANSMIT_STATE: This class is auto-generated by vdis.EnumGenerator
 */
public final class TRANSMIT_STATE extends Value {

    public static final TRANSMIT_STATE
       TRANSMIT_OFF = new TRANSMIT_STATE(0, "TRANSMIT_OFF", "Off", true),
       TRANSMIT_ON_BUT_NOT_TRANSMITTING = new TRANSMIT_STATE(1, "TRANSMIT_ON_BUT_NOT_TRANSMITTING", "On But Not Transmitting", true),
       TRANSMIT_ON_AND_TRANSMITTING = new TRANSMIT_STATE(2, "TRANSMIT_ON_AND_TRANSMITTING", "On And Transmitting", true);

    private TRANSMIT_STATE(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, TRANSMIT_STATE.class);
    }

    /** @see Value#values(Class) */
    public static List<TRANSMIT_STATE> values() {

        return values(TRANSMIT_STATE.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<TRANSMIT_STATE> values(boolean known) {

        return values(TRANSMIT_STATE.class, known);
    }

    /** @see Value#get(int, Class) */
    public static TRANSMIT_STATE get(int value) {

        return get(value, TRANSMIT_STATE.class);
    }
}

