package discover.vdis.enums;

import java.util.List;

/**
 * TRANSFER_TYPE: This class is auto-generated by vdis.EnumGenerator
 */
public final class TRANSFER_TYPE extends Value {

    public static final TRANSFER_TYPE
       OTHER = new TRANSFER_TYPE(0, "OTHER", "Other", true),
       PUSH_TRANSFER_ENTITY = new TRANSFER_TYPE(1, "PUSH_TRANSFER_ENTITY", "Push - Transfer Entity", true),
       AUTO_PULL_TRANSFER_ENTITY = new TRANSFER_TYPE(2, "AUTO_PULL_TRANSFER_ENTITY", "Automatic Pull - Transfer Entity", true),
       MUTUAL_XCH_ENTITY = new TRANSFER_TYPE(3, "MUTUAL_XCH_ENTITY", "Mutual Exchange Entity", true),
       PUSH_TRANSFER_ENV_PROC = new TRANSFER_TYPE(4, "PUSH_TRANSFER_ENV_PROC", "Push - Transfer Environmental Process", true),
       AUTO_PULL_TRANSFER_ENV_PROC = new TRANSFER_TYPE(5, "AUTO_PULL_TRANSFER_ENV_PROC", "Automatic Pull - Transfer Environmental Process", true),
       MUTUAL_XCH_ENV_PROC = new TRANSFER_TYPE(6, "MUTUAL_XCH_ENV_PROC", "Mutual Exchange Environmental Process", true),
       CANCEL_TRANSFER = new TRANSFER_TYPE(7, "CANCEL_TRANSFER", "Cancel Transfer", true),
       MAN_PULL_TRANSFER_ENTITY = new TRANSFER_TYPE(8, "MAN_PULL_TRANSFER_ENTITY", "Manual Pull - Transfer Entity", true),
       MAN_PULL_TRANSFER_ENV_PROC = new TRANSFER_TYPE(9, "MAN_PULL_TRANSFER_ENV_PROC", "Manual Pull - Transfer Environmental Process", true),
       REMOVE_ENTITY = new TRANSFER_TYPE(10, "REMOVE_ENTITY", "Remove Entity", true);

    private TRANSFER_TYPE(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, TRANSFER_TYPE.class);
    }

    /** @see Value#values(Class) */
    public static List<TRANSFER_TYPE> values() {

        return values(TRANSFER_TYPE.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<TRANSFER_TYPE> values(boolean known) {

        return values(TRANSFER_TYPE.class, known);
    }

    /** @see Value#get(int, Class) */
    public static TRANSFER_TYPE get(int value) {

        return get(value, TRANSFER_TYPE.class);
    }
}

