package discover.vdis.enums;

import java.util.List;

/**
 * UA_FUNCTION: This class is auto-generated by vdis.EnumGenerator
 */
public final class UA_FUNCTION extends Value {

    public static final UA_FUNCTION
       UA_FUNC_OTHER = new UA_FUNCTION(0, "UA_FUNC_OTHER", "Other", true),
       UA_FUNC_PLATFORM_SEARCH = new UA_FUNCTION(1, "UA_FUNC_PLATFORM_SEARCH", "Platform Search/Detect/Track", true),
       UA_FUNC_NAVIGATION = new UA_FUNCTION(2, "UA_FUNC_NAVIGATION", "Navigation", true),
       UA_FUNC_MINE_HUNTING = new UA_FUNCTION(3, "UA_FUNC_MINE_HUNTING", "Mine Hunting", true),
       UA_FUNC_WEAPON_SEARCH = new UA_FUNCTION(4, "UA_FUNC_WEAPON_SEARCH", "Weapon Search/Detect/Track/Detect", true);

    private UA_FUNCTION(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, UA_FUNCTION.class);
    }

    /** @see Value#values(Class) */
    public static List<UA_FUNCTION> values() {

        return values(UA_FUNCTION.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<UA_FUNCTION> values(boolean known) {

        return values(UA_FUNCTION.class, known);
    }

    /** @see Value#get(int, Class) */
    public static UA_FUNCTION get(int value) {

        return get(value, UA_FUNCTION.class);
    }
}

