package discover.vdis.enums;

import java.util.List;

/**
 * UA_PROP_PLANT: This class is auto-generated by vdis.EnumGenerator
 */
public final class UA_PROP_PLANT extends Value {

    public static final UA_PROP_PLANT
       OTHER = new UA_PROP_PLANT(0, "OTHER", "Other", true),
       DIESEL_ELECTRIC = new UA_PROP_PLANT(1, "DIESEL_ELECTRIC", "Diesel/Electric", true),
       DIESEL = new UA_PROP_PLANT(2, "DIESEL", "Diesel", true),
       BATTERY = new UA_PROP_PLANT(3, "BATTERY", "Battery", true),
       TURBINE_REDUCTION = new UA_PROP_PLANT(4, "TURBINE_REDUCTION", "Turbine Reduction", true),
       STEAM = new UA_PROP_PLANT(6, "STEAM", "Steam", true),
       GAS_TURBINE = new UA_PROP_PLANT(7, "GAS_TURBINE", "Gas Turbine", true);

    private UA_PROP_PLANT(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, UA_PROP_PLANT.class);
    }

    /** @see Value#values(Class) */
    public static List<UA_PROP_PLANT> values() {

        return values(UA_PROP_PLANT.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<UA_PROP_PLANT> values(boolean known) {

        return values(UA_PROP_PLANT.class, known);
    }

    /** @see Value#get(int, Class) */
    public static UA_PROP_PLANT get(int value) {

        return get(value, UA_PROP_PLANT.class);
    }
}

