package discover.vdis.enums;

import java.util.List;

/**
 * UA_SCAN: This class is auto-generated by vdis.EnumGenerator
 */
public final class UA_SCAN extends Value {

    public static final UA_SCAN
       UNUSED = new UA_SCAN(0, "UNUSED", "Unused", true),
       CONICAL = new UA_SCAN(1, "CONICAL", "Conical", true),
       HELICAL = new UA_SCAN(2, "HELICAL", "Helical", true),
       RASTER = new UA_SCAN(3, "RASTER", "Raster", true),
       SECTOR_SEARCH = new UA_SCAN(4, "SECTOR_SEARCH", "Sector Search", true),
       CONTINUOUS_SEARCH = new UA_SCAN(5, "CONTINUOUS_SEARCH", "Continuous Search", true);

    private UA_SCAN(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, UA_SCAN.class);
    }

    /** @see Value#values(Class) */
    public static List<UA_SCAN> values() {

        return values(UA_SCAN.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<UA_SCAN> values(boolean known) {

        return values(UA_SCAN.class, known);
    }

    /** @see Value#get(int, Class) */
    public static UA_SCAN get(int value) {

        return get(value, UA_SCAN.class);
    }
}

