package discover.vdis.enums;

import java.util.List;

/**
 * UA_SYS_NAME: This class is auto-generated by vdis.EnumGenerator
 */
public final class UA_SYS_NAME extends Value {

    public static final UA_SYS_NAME
       OTHER = new UA_SYS_NAME(0, "OTHER", "Other", true),
       AN_BQQ_5 = new UA_SYS_NAME(1, "AN_BQQ_5", "AN/BQQ-5", true),
       AN_SSQ_62 = new UA_SYS_NAME(2, "AN_SSQ_62", "AN/SSQ-62", true),
       AN_SQS_23 = new UA_SYS_NAME(3, "AN_SQS_23", "AN/SQS-23", true),
       AN_SQS_26 = new UA_SYS_NAME(4, "AN_SQS_26", "AN/SQS-26", true),
       AN_SQS_53 = new UA_SYS_NAME(5, "AN_SQS_53", "AN/SQS-53", true),
       ALFS = new UA_SYS_NAME(6, "ALFS", "ALFS", true),
       LFA = new UA_SYS_NAME(7, "LFA", "LFA", true),
       AN_AQS_901 = new UA_SYS_NAME(8, "AN_AQS_901", "AN/AQS-901", true),
       AN_AQS_902 = new UA_SYS_NAME(9, "AN_AQS_902", "AN/AQS-902", true);

    private UA_SYS_NAME(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, UA_SYS_NAME.class);
    }

    /** @see Value#values(Class) */
    public static List<UA_SYS_NAME> values() {

        return values(UA_SYS_NAME.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<UA_SYS_NAME> values(boolean known) {

        return values(UA_SYS_NAME.class, known);
    }

    /** @see Value#get(int, Class) */
    public static UA_SYS_NAME get(int value) {

        return get(value, UA_SYS_NAME.class);
    }
}

