package discover.vdis.enums;

import java.util.List;

/**
 * UNMODULATED: This class is auto-generated by vdis.EnumGenerator
 */
public final class UNMODULATED extends Value {

    public static final UNMODULATED
       UNMOD_OTHER = new UNMODULATED(0, "UNMOD_OTHER", "Other", true),
       UNMOD_CONTINUOUS_WAVE_EMISSION = new UNMODULATED(1, "UNMOD_CONTINUOUS_WAVE_EMISSION", "Continuous Wave Emission of an Unmodulated Carrier", true);

    private UNMODULATED(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, UNMODULATED.class);
    }

    /** @see Value#values(Class) */
    public static List<UNMODULATED> values() {

        return values(UNMODULATED.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<UNMODULATED> values(boolean known) {

        return values(UNMODULATED.class, known);
    }

    /** @see Value#get(int, Class) */
    public static UNMODULATED get(int value) {

        return get(value, UNMODULATED.class);
    }
}

