package discover.vdis.enums;

import java.util.List;

/**
 * USMTF_VERSION_ENUM: This class is auto-generated by vdis.EnumGenerator
 */
public final class USMTF_VERSION_ENUM extends Value {

    public static final USMTF_VERSION_ENUM
       USMTF_VERSION_1993 = new USMTF_VERSION_ENUM(0, "USMTF_VERSION_1993", "USMTF 1993", true),
       USMTF_VERSION_1995 = new USMTF_VERSION_ENUM(1, "USMTF_VERSION_1995", "USMTF 1995", true),
       USMTF_VERSION_1997 = new USMTF_VERSION_ENUM(2, "USMTF_VERSION_1997", "USMTF 1997", true),
       USMTF_VERSION_1998 = new USMTF_VERSION_ENUM(3, "USMTF_VERSION_1998", "USMTF 1998", true),
       USMTF_VERSION_1999 = new USMTF_VERSION_ENUM(4, "USMTF_VERSION_1999", "USMTF 1999", true),
       USMTF_VERSION_2000 = new USMTF_VERSION_ENUM(5, "USMTF_VERSION_2000", "USMTF 2000", true),
       USMTF_VERSION_2001 = new USMTF_VERSION_ENUM(6, "USMTF_VERSION_2001", "USMTF 2001", true),
       USMTF_VERSION_2002 = new USMTF_VERSION_ENUM(7, "USMTF_VERSION_2002", "USMTF 2002", true),
       USMTF_VERSION_2003 = new USMTF_VERSION_ENUM(8, "USMTF_VERSION_2003", "USMTF 2003", true),
       USMTF_VERSION_2004 = new USMTF_VERSION_ENUM(9, "USMTF_VERSION_2004", "USMTF 2004", true);

    private USMTF_VERSION_ENUM(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, USMTF_VERSION_ENUM.class);
    }

    /** @see Value#values(Class) */
    public static List<USMTF_VERSION_ENUM> values() {

        return values(USMTF_VERSION_ENUM.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<USMTF_VERSION_ENUM> values(boolean known) {

        return values(USMTF_VERSION_ENUM.class, known);
    }

    /** @see Value#get(int, Class) */
    public static USMTF_VERSION_ENUM get(int value) {

        return get(value, USMTF_VERSION_ENUM.class);
    }
}

