package discover.vdis.enums;

import java.util.List;

/**
 * VMF_VERSION_ENUM: This class is auto-generated by vdis.EnumGenerator
 */
public final class VMF_VERSION_ENUM extends Value {

    public static final VMF_VERSION_ENUM
       VMF_VERSION_TIDP_TE_R2 = new VMF_VERSION_ENUM(0, "VMF_VERSION_TIDP_TE_R2", "TIDP-TE R2", true),
       VMF_VERSION_TIDP_TE_R3 = new VMF_VERSION_ENUM(1, "VMF_VERSION_TIDP_TE_R3", "TIDP-TE R3", true),
       VMF_VERSION_TIDP_TE_R4 = new VMF_VERSION_ENUM(2, "VMF_VERSION_TIDP_TE_R4", "TIDP-TE R4", true),
       VMF_VERSION_TIDP_TE_R5 = new VMF_VERSION_ENUM(3, "VMF_VERSION_TIDP_TE_R5", "TIDP-TE R5", true),
       VMF_VERSION_TIDP_TE_R6 = new VMF_VERSION_ENUM(4, "VMF_VERSION_TIDP_TE_R6", "TIDP-TE R6", true),
       VMF_VERSION_TIDP_TE_R7 = new VMF_VERSION_ENUM(5, "VMF_VERSION_TIDP_TE_R7", "TIDP-TE R7", true),
       VMF_VERSION_6017 = new VMF_VERSION_ENUM(6, "VMF_VERSION_6017", "6017", true),
       VMF_VERSION_6017A = new VMF_VERSION_ENUM(7, "VMF_VERSION_6017A", "6017A", true),
       VMF_VERSION_6017B = new VMF_VERSION_ENUM(8, "VMF_VERSION_6017B", "6017B", true),
       VMF_VERSION_6017C = new VMF_VERSION_ENUM(9, "VMF_VERSION_6017C", "6017C", true),
       VMF_VERSION_DCX2_AV = new VMF_VERSION_ENUM(16, "VMF_VERSION_DCX2_AV", "DCX2 AV", true);

    private VMF_VERSION_ENUM(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, VMF_VERSION_ENUM.class);
    }

    /** @see Value#values(Class) */
    public static List<VMF_VERSION_ENUM> values() {

        return values(VMF_VERSION_ENUM.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<VMF_VERSION_ENUM> values(boolean known) {

        return values(VMF_VERSION_ENUM.class, known);
    }

    /** @see Value#get(int, Class) */
    public static VMF_VERSION_ENUM get(int value) {

        return get(value, VMF_VERSION_ENUM.class);
    }
}

