package discover.vdis.enums;

import java.util.List;

/**
 * VP_RECORD_TYPE: This class is auto-generated by vdis.EnumGenerator
 */
public final class VP_RECORD_TYPE extends Value {

    public static final VP_RECORD_TYPE
       ARTICULATED_PART = new VP_RECORD_TYPE(0, "ARTICULATED_PART", "Articulated Part", true),
       ATTACHED_PART = new VP_RECORD_TYPE(1, "ATTACHED_PART", "Attached Part", true),
       SEPARATION = new VP_RECORD_TYPE(2, "SEPARATION", "Separation", true),
       ENTITY_TYPE = new VP_RECORD_TYPE(3, "ENTITY_TYPE", "Entity Type", true),
       ENTITY_ASSOC = new VP_RECORD_TYPE(4, "ENTITY_ASSOC", "Entity Association", true),
       EXT_PLATFORM_APP = new VP_RECORD_TYPE(20, "EXT_PLATFORM_APP", "Extended Platform Appearance", true),
       EXT_LIFEFORM_APP = new VP_RECORD_TYPE(21, "EXT_LIFEFORM_APP", "Extended Lifeform Appearance", true),
       HIFI_LIGHTS = new VP_RECORD_TYPE(22, "HIFI_LIGHTS", "High Fidelity Lights", true),
       CHEVRON_MARKING = new VP_RECORD_TYPE(23, "CHEVRON_MARKING", "Chevron Marking", true),
       HIFI_THERMAL = new VP_RECORD_TYPE(24, "HIFI_THERMAL", "High Fidelity Thermal Sensor", true),
       ENTITY_OFFSET = new VP_RECORD_TYPE(25, "ENTITY_OFFSET", "Entity Offset", true),
       DEAD_RECKONING = new VP_RECORD_TYPE(26, "DEAD_RECKONING", "Dead Reckoning", true),
       ARMY_TASK_ORG = new VP_RECORD_TYPE(27, "ARMY_TASK_ORG", "Army Task Organization", true),
       HEAD_GAZING_WPN_AIM = new VP_RECORD_TYPE(28, "HEAD_GAZING_WPN_AIM", "Head Gazing / Weapon Aiming", true),
       LIFEFORM_ACT_SEQ = new VP_RECORD_TYPE(29, "LIFEFORM_ACT_SEQ", "Lifeform Action Sequence", true),
       LEGACY_EXT_LIFEFORM_APP = new VP_RECORD_TYPE(30, "LEGACY_EXT_LIFEFORM_APP", "Legacy Extended Lifeform Appearance", true),
       EXT_CULT_FEAT_APP = new VP_RECORD_TYPE(31, "EXT_CULT_FEAT_APP", "Extended Cultural Feature Appearance", true),
       EXT_SUPPLY_APP = new VP_RECORD_TYPE(32, "EXT_SUPPLY_APP", "Extended Supply Appearance", true);

    private VP_RECORD_TYPE(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, VP_RECORD_TYPE.class);
    }

    /** @see Value#values(Class) */
    public static List<VP_RECORD_TYPE> values() {

        return values(VP_RECORD_TYPE.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<VP_RECORD_TYPE> values(boolean known) {

        return values(VP_RECORD_TYPE.class, known);
    }

    /** @see Value#get(int, Class) */
    public static VP_RECORD_TYPE get(int value) {

        return get(value, VP_RECORD_TYPE.class);
    }
}

