package discover.vdis.enums;

import java.util.List;

/**
 * WARHEAD_BURST_DESC: This class is auto-generated by vdis.EnumGenerator
 */
public final class WARHEAD_BURST_DESC extends Value {

    public static final WARHEAD_BURST_DESC
       OTHER = new WARHEAD_BURST_DESC(0, "OTHER", "Other", true),
       CARGO = new WARHEAD_BURST_DESC(10, "CARGO", "Cargo (Variable Submunitions)", true),
       FUEL_AIR_EXPLOSIVE = new WARHEAD_BURST_DESC(20, "FUEL_AIR_EXPLOSIVE", "Fuel/Air Explosive", true),
       GLASS_BEADS = new WARHEAD_BURST_DESC(30, "GLASS_BEADS", "Glass Beads", true),
       VALUE_1_UM = new WARHEAD_BURST_DESC(31, "VALUE_1_UM", "1 um", true),
       VALUE_5_UM = new WARHEAD_BURST_DESC(32, "VALUE_5_UM", "5 um", true),
       VALUE_10_UM = new WARHEAD_BURST_DESC(33, "VALUE_10_UM", "10 um", true),
       HIGH_EXPLOSIVE = new WARHEAD_BURST_DESC(1000, "HIGH_EXPLOSIVE", "High Explosive (HE)", true),
       HE_PLASTIC = new WARHEAD_BURST_DESC(1100, "HE_PLASTIC", "HE, Plastic", true),
       HE_INCENDIARY = new WARHEAD_BURST_DESC(1200, "HE_INCENDIARY", "HE, Incendiary", true),
       HE_FRAGMENTATION = new WARHEAD_BURST_DESC(1300, "HE_FRAGMENTATION", "HE, Fragmentation", true),
       HE_ANTITANK = new WARHEAD_BURST_DESC(1400, "HE_ANTITANK", "HE, Antitank", true),
       HE_BOMBLETS = new WARHEAD_BURST_DESC(1500, "HE_BOMBLETS", "HE, Bomblets", true),
       HE_SHAPED_CHARGE = new WARHEAD_BURST_DESC(1600, "HE_SHAPED_CHARGE", "HE, Shaped Charge", true),
       HE_CONTINUOUS_ROD = new WARHEAD_BURST_DESC(1610, "HE_CONTINUOUS_ROD", "HE, Continuous Rod", true),
       HE_TUNGSTEN_BALL = new WARHEAD_BURST_DESC(1615, "HE_TUNGSTEN_BALL", "HE, Tungsten Ball", true),
       HE_BLAST_FRAGMENTATION = new WARHEAD_BURST_DESC(1620, "HE_BLAST_FRAGMENTATION", "HE, Blast Fragmentation", true),
       HE_STEERABLE_DARTS_WITH_HE = new WARHEAD_BURST_DESC(1625, "HE_STEERABLE_DARTS_WITH_HE", "HE, Steerable Darts with HE", true),
       HE_DARTS = new WARHEAD_BURST_DESC(1630, "HE_DARTS", "HE, Darts", true),
       HE_FLECHETTES = new WARHEAD_BURST_DESC(1635, "HE_FLECHETTES", "HE, Flechettes", true),
       HE_DIRECTED_FRAG = new WARHEAD_BURST_DESC(1640, "HE_DIRECTED_FRAG", "HE, Directed Fragmentation", true),
       HE_SEMI_ARMOR_PIERCING = new WARHEAD_BURST_DESC(1645, "HE_SEMI_ARMOR_PIERCING", "HE, Semi-Armor Piercing (SAP)", true),
       HE_SHAPED_CHARGE_FRAG = new WARHEAD_BURST_DESC(1650, "HE_SHAPED_CHARGE_FRAG", "HE, Shaped Charge Fragmentation", true),
       HE_SEMI_ARMOR_PIERCING_FRAG = new WARHEAD_BURST_DESC(1655, "HE_SEMI_ARMOR_PIERCING_FRAG", "HE, Semi-Armor Piercing, Fragmentation", true),
       HE_HOLLOW_CHARGE = new WARHEAD_BURST_DESC(1660, "HE_HOLLOW_CHARGE", "HE, Hollow Charge", true),
       HE_DOUBLE_HOLLOW_CHARGE = new WARHEAD_BURST_DESC(1665, "HE_DOUBLE_HOLLOW_CHARGE", "HE, Double Hollow Charge", true),
       HE_GENERAL_PURPOSE = new WARHEAD_BURST_DESC(1670, "HE_GENERAL_PURPOSE", "HE, General Purpose", true),
       HE_BLAST_PENETRATOR = new WARHEAD_BURST_DESC(1675, "HE_BLAST_PENETRATOR", "HE, Blast Penetrator", true),
       HE_ROD_PENETRATOR = new WARHEAD_BURST_DESC(1680, "HE_ROD_PENETRATOR", "HE, Rod Penetrator", true),
       HE_ANTIPERSONNEL = new WARHEAD_BURST_DESC(1685, "HE_ANTIPERSONNEL", "HE, Antipersonnel", true),
       SMOKE = new WARHEAD_BURST_DESC(2000, "SMOKE", "Smoke", true),
       ILLUMINATION = new WARHEAD_BURST_DESC(3000, "ILLUMINATION", "Illumination", true),
       PRACTICE = new WARHEAD_BURST_DESC(4000, "PRACTICE", "Practice", true),
       KINETIC = new WARHEAD_BURST_DESC(5000, "KINETIC", "Kinetic", true),
       MINES = new WARHEAD_BURST_DESC(6000, "MINES", "Mines", true),
       NUCLEAR = new WARHEAD_BURST_DESC(7000, "NUCLEAR", "Nuclear", true),
       NUCLEAR_IMT = new WARHEAD_BURST_DESC(7010, "NUCLEAR_IMT", "Nuclear, IMT", true),
       CHEMICAL_GENERAL = new WARHEAD_BURST_DESC(8000, "CHEMICAL_GENERAL", "Chemical, General", true),
       CHEMICAL_BLISTER_AGENT = new WARHEAD_BURST_DESC(8100, "CHEMICAL_BLISTER_AGENT", "Chemical, Blister Agent", true),
       HD_MUSTARD = new WARHEAD_BURST_DESC(8110, "HD_MUSTARD", "HD (Mustard)", true),
       THICKENED_HD_MUSTARD = new WARHEAD_BURST_DESC(8115, "THICKENED_HD_MUSTARD", "Thickened HD (Mustard)", true),
       DUSTY_HD_MUSTARD = new WARHEAD_BURST_DESC(8120, "DUSTY_HD_MUSTARD", "Dusty HD (Mustard)", true),
       CHEMICAL_BLOOD_AGENT = new WARHEAD_BURST_DESC(8200, "CHEMICAL_BLOOD_AGENT", "Chemical, Blood Agent", true),
       AC_HCN = new WARHEAD_BURST_DESC(8210, "AC_HCN", "AC (HCN)", true),
       CK_CNCI = new WARHEAD_BURST_DESC(8215, "CK_CNCI", "CK (CNCI)", true),
       CG_PHOSGENE = new WARHEAD_BURST_DESC(8220, "CG_PHOSGENE", "CG (Phosgene)", true),
       CHEMICAL_NERVE_AGENT = new WARHEAD_BURST_DESC(8300, "CHEMICAL_NERVE_AGENT", "Chemical, Nerve Agent", true),
       VX = new WARHEAD_BURST_DESC(8310, "VX", "VX", true),
       THICKENED_VX = new WARHEAD_BURST_DESC(8315, "THICKENED_VX", "Thickened VX", true),
       DUSTY_VX = new WARHEAD_BURST_DESC(8320, "DUSTY_VX", "Dusty VX", true),
       GA_TABUN = new WARHEAD_BURST_DESC(8325, "GA_TABUN", "GA (Tabun)", true),
       THICKENED_GA_TABUN = new WARHEAD_BURST_DESC(8330, "THICKENED_GA_TABUN", "Thickened GA (Tabun)", true),
       DUSTY_GA_TABUN = new WARHEAD_BURST_DESC(8335, "DUSTY_GA_TABUN", "Dusty GA (Tabun)", true),
       GB_SARIN = new WARHEAD_BURST_DESC(8340, "GB_SARIN", "GB (Sarin)", true),
       THICKENED_GB_SARIN = new WARHEAD_BURST_DESC(8345, "THICKENED_GB_SARIN", "Thickened GB (Sarin)", true),
       DUSTY_GB_SARIN = new WARHEAD_BURST_DESC(8350, "DUSTY_GB_SARIN", "Dusty GB (Sarin)", true),
       GD_SOMAN = new WARHEAD_BURST_DESC(8355, "GD_SOMAN", "GD (Soman)", true),
       THICKENED_GD_SOMAN = new WARHEAD_BURST_DESC(8360, "THICKENED_GD_SOMAN", "Thickened GD (Soman)", true),
       DUSTY_GD_SOMAN = new WARHEAD_BURST_DESC(8365, "DUSTY_GD_SOMAN", "Dusty GD (Soman)", true),
       GF = new WARHEAD_BURST_DESC(8370, "GF", "GF", true),
       THICKENED_GF = new WARHEAD_BURST_DESC(8375, "THICKENED_GF", "Thickened GF", true),
       DUSTY_GF = new WARHEAD_BURST_DESC(8380, "DUSTY_GF", "Dusty GF", true),
       BIOLOGICAL = new WARHEAD_BURST_DESC(9000, "BIOLOGICAL", "Biological", true),
       BIOLOGICAL_VIRUS = new WARHEAD_BURST_DESC(9100, "BIOLOGICAL_VIRUS", "Biological, Virus", true),
       BIOLOGICAL_BACTERIA = new WARHEAD_BURST_DESC(9200, "BIOLOGICAL_BACTERIA", "Biological, Bacteria", true),
       BIOLOGICAL_RICKETTSIA = new WARHEAD_BURST_DESC(9300, "BIOLOGICAL_RICKETTSIA", "Biological, Rickettsia", true),
       BIOGEN_MOD_MICRO_ORGANISMS = new WARHEAD_BURST_DESC(9400, "BIOGEN_MOD_MICRO_ORGANISMS", "Biological, Genetically Modified Micro-organisms", true),
       BIOLOGICAL_TOXIN = new WARHEAD_BURST_DESC(9500, "BIOLOGICAL_TOXIN", "Biological, Toxin", true);

    private WARHEAD_BURST_DESC(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, WARHEAD_BURST_DESC.class);
    }

    /** @see Value#values(Class) */
    public static List<WARHEAD_BURST_DESC> values() {

        return values(WARHEAD_BURST_DESC.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<WARHEAD_BURST_DESC> values(boolean known) {

        return values(WARHEAD_BURST_DESC.class, known);
    }

    /** @see Value#get(int, Class) */
    public static WARHEAD_BURST_DESC get(int value) {

        return get(value, WARHEAD_BURST_DESC.class);
    }
}

