package discover.vdis.enums;

import java.util.List;

/**
 * WS_CLOUDS_STATUS: This class is auto-generated by vdis.EnumGenerator
 */
public final class WS_CLOUDS_STATUS extends Value {

    public static final WS_CLOUDS_STATUS
       WSC_CLOUD_STATUS_OFF = new WS_CLOUDS_STATUS(0, "WSC_CLOUD_STATUS_OFF", "Off", true),
       WSC_CLOUD_STATUS_ON = new WS_CLOUDS_STATUS(1, "WSC_CLOUD_STATUS_ON", "On", true);

    private WS_CLOUDS_STATUS(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, WS_CLOUDS_STATUS.class);
    }

    /** @see Value#values(Class) */
    public static List<WS_CLOUDS_STATUS> values() {

        return values(WS_CLOUDS_STATUS.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<WS_CLOUDS_STATUS> values(boolean known) {

        return values(WS_CLOUDS_STATUS.class, known);
    }

    /** @see Value#get(int, Class) */
    public static WS_CLOUDS_STATUS get(int value) {

        return get(value, WS_CLOUDS_STATUS.class);
    }
}

