package discover.vdis.enums;

import java.util.List;

/**
 * WS_CLOUDS_DENS: This class is auto-generated by vdis.EnumGenerator
 */
public final class WS_CLOUDS_DENS extends Value {

    public static final WS_CLOUDS_DENS
       WSC_DENSITY_NOT_SPECIFIED = new WS_CLOUDS_DENS(0, "WSC_DENSITY_NOT_SPECIFIED", "Not Specified", true),
       WSC_DENSITY_CLEAR = new WS_CLOUDS_DENS(1, "WSC_DENSITY_CLEAR", "Clear", true),
       WSC_DENSITY_SCATTERED = new WS_CLOUDS_DENS(2, "WSC_DENSITY_SCATTERED", "Scattered", true),
       WSC_DENSITY_BROKEN = new WS_CLOUDS_DENS(3, "WSC_DENSITY_BROKEN", "Broken", true),
       WSC_DENSITY_OVERCAST = new WS_CLOUDS_DENS(4, "WSC_DENSITY_OVERCAST", "Overcast", true);

    private WS_CLOUDS_DENS(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, WS_CLOUDS_DENS.class);
    }

    /** @see Value#values(Class) */
    public static List<WS_CLOUDS_DENS> values() {

        return values(WS_CLOUDS_DENS.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<WS_CLOUDS_DENS> values(boolean known) {

        return values(WS_CLOUDS_DENS.class, known);
    }

    /** @see Value#get(int, Class) */
    public static WS_CLOUDS_DENS get(int value) {

        return get(value, WS_CLOUDS_DENS.class);
    }
}

