package discover.vdis.enums;

import java.util.List;

/**
 * WS_CEL_TOD_SCENE: This class is auto-generated by vdis.EnumGenerator
 */
public final class WS_CEL_TOD_SCENE extends Value {

    public static final WS_CEL_TOD_SCENE
       WSC_TODSCENE_DAWN = new WS_CEL_TOD_SCENE(0, "WSC_TODSCENE_DAWN", "Dawn", true),
       WSC_TODSCENE_DAY = new WS_CEL_TOD_SCENE(1, "WSC_TODSCENE_DAY", "Day", true),
       WSC_TODSCENE_DUSK = new WS_CEL_TOD_SCENE(2, "WSC_TODSCENE_DUSK", "Dusk", true),
       WSC_TODSCENE_NIGHT = new WS_CEL_TOD_SCENE(3, "WSC_TODSCENE_NIGHT", "Night", true);

    private WS_CEL_TOD_SCENE(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, WS_CEL_TOD_SCENE.class);
    }

    /** @see Value#values(Class) */
    public static List<WS_CEL_TOD_SCENE> values() {

        return values(WS_CEL_TOD_SCENE.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<WS_CEL_TOD_SCENE> values(boolean known) {

        return values(WS_CEL_TOD_SCENE.class, known);
    }

    /** @see Value#get(int, Class) */
    public static WS_CEL_TOD_SCENE get(int value) {

        return get(value, WS_CEL_TOD_SCENE.class);
    }
}

