package discover.vdis.enums;

import java.util.List;

/**
 * WS_CLOUDS_TYPE: This class is auto-generated by vdis.EnumGenerator
 */
public final class WS_CLOUDS_TYPE extends Value {

    public static final WS_CLOUDS_TYPE
       WSC_TYPE_NONE = new WS_CLOUDS_TYPE(0, "WSC_TYPE_NONE", "None", true),
       WSC_TYPE_ALTOCUMULUS = new WS_CLOUDS_TYPE(1, "WSC_TYPE_ALTOCUMULUS", "Altocumulus", true),
       WSC_TYPE_ALTOSTRATUS = new WS_CLOUDS_TYPE(2, "WSC_TYPE_ALTOSTRATUS", "Altostratus", true),
       WSC_TYPE_CIRROCUMULUS = new WS_CLOUDS_TYPE(3, "WSC_TYPE_CIRROCUMULUS", "Cirrocumulus", true),
       WSC_TYPE_CIRROSTRATUS = new WS_CLOUDS_TYPE(4, "WSC_TYPE_CIRROSTRATUS", "Cirrostratus", true),
       WSC_TYPE_CIRRUS = new WS_CLOUDS_TYPE(5, "WSC_TYPE_CIRRUS", "Cirrus", true),
       WSC_TYPE_CUMULONIMBUS = new WS_CLOUDS_TYPE(6, "WSC_TYPE_CUMULONIMBUS", "Cumulonimbus", true),
       WSC_TYPE_CUMULUS = new WS_CLOUDS_TYPE(7, "WSC_TYPE_CUMULUS", "Cumulus", true),
       WSC_TYPE_NIMBOSTRATUS = new WS_CLOUDS_TYPE(8, "WSC_TYPE_NIMBOSTRATUS", "Nimbostratus", true),
       WSC_TYPE_STRATOCUMULUS = new WS_CLOUDS_TYPE(9, "WSC_TYPE_STRATOCUMULUS", "Stratocumulus", true),
       WSC_TYPE_STRATUS = new WS_CLOUDS_TYPE(10, "WSC_TYPE_STRATUS", "Stratus", true);

    private WS_CLOUDS_TYPE(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, WS_CLOUDS_TYPE.class);
    }

    /** @see Value#values(Class) */
    public static List<WS_CLOUDS_TYPE> values() {

        return values(WS_CLOUDS_TYPE.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<WS_CLOUDS_TYPE> values(boolean known) {

        return values(WS_CLOUDS_TYPE.class, known);
    }

    /** @see Value#get(int, Class) */
    public static WS_CLOUDS_TYPE get(int value) {

        return get(value, WS_CLOUDS_TYPE.class);
    }
}

