package discover.vdis.enums;

import java.util.List;

/**
 * WS_CEL_NIGHT_ILL: This class is auto-generated by vdis.EnumGenerator
 */
public final class WS_CEL_NIGHT_ILL extends Value {

    public static final WS_CEL_NIGHT_ILL
       WSC_NIGHT_ILL_NONE = new WS_CEL_NIGHT_ILL(0, "WSC_NIGHT_ILL_NONE", "None", true),
       WSC_NIGHT_ILL_STARLIGHT = new WS_CEL_NIGHT_ILL(1, "WSC_NIGHT_ILL_STARLIGHT", "Starlight", true),
       WSC_NIGHT_ILL_QUARTER_MOON = new WS_CEL_NIGHT_ILL(2, "WSC_NIGHT_ILL_QUARTER_MOON", "Quarter Moon", true),
       WSC_NIGHT_ILL_HALF_MOON = new WS_CEL_NIGHT_ILL(3, "WSC_NIGHT_ILL_HALF_MOON", "Half Moon", true),
       WSC_NIGHT_ILL_THREE_QUARTER_MOON = new WS_CEL_NIGHT_ILL(4, "WSC_NIGHT_ILL_THREE_QUARTER_MOON", "Three Quarter Moon", true),
       WSC_NIGHT_ILL_FULL_MOON = new WS_CEL_NIGHT_ILL(5, "WSC_NIGHT_ILL_FULL_MOON", "Full Moon", true);

    private WS_CEL_NIGHT_ILL(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, WS_CEL_NIGHT_ILL.class);
    }

    /** @see Value#values(Class) */
    public static List<WS_CEL_NIGHT_ILL> values() {

        return values(WS_CEL_NIGHT_ILL.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<WS_CEL_NIGHT_ILL> values(boolean known) {

        return values(WS_CEL_NIGHT_ILL.class, known);
    }

    /** @see Value#get(int, Class) */
    public static WS_CEL_NIGHT_ILL get(int value) {

        return get(value, WS_CEL_NIGHT_ILL.class);
    }
}

