package discover.vdis.enums;

import java.util.List;

/**
 * WS_CLOUDS_SCUD_FLAGS: This class is auto-generated by vdis.EnumGenerator
 */
public final class WS_CLOUDS_SCUD_FLAGS extends Value {

    public static final WS_CLOUDS_SCUD_FLAGS
       WSC_SCUD_FLAGS_OFF = new WS_CLOUDS_SCUD_FLAGS(0, "WSC_SCUD_FLAGS_OFF", "Off", true),
       WSC_SCUD_FLAGS_BOTTOM = new WS_CLOUDS_SCUD_FLAGS(1, "WSC_SCUD_FLAGS_BOTTOM", "Bottom", true),
       WSC_SCUD_FLAGS_TOP_ON = new WS_CLOUDS_SCUD_FLAGS(2, "WSC_SCUD_FLAGS_TOP_ON", "Top On", true),
       WSC_SCUD_FLAGS_TOP_AND_BOTTOM = new WS_CLOUDS_SCUD_FLAGS(3, "WSC_SCUD_FLAGS_TOP_AND_BOTTOM", "Top and Bottom", true);

    private WS_CLOUDS_SCUD_FLAGS(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, WS_CLOUDS_SCUD_FLAGS.class);
    }

    /** @see Value#values(Class) */
    public static List<WS_CLOUDS_SCUD_FLAGS> values() {

        return values(WS_CLOUDS_SCUD_FLAGS.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<WS_CLOUDS_SCUD_FLAGS> values(boolean known) {

        return values(WS_CLOUDS_SCUD_FLAGS.class, known);
    }

    /** @see Value#get(int, Class) */
    public static WS_CLOUDS_SCUD_FLAGS get(int value) {

        return get(value, WS_CLOUDS_SCUD_FLAGS.class);
    }
}

