package discover.vdis.enums;

import java.util.List;

/**
 * WS_GR_FOG_STATUS: This class is auto-generated by vdis.EnumGenerator
 */
public final class WS_GR_FOG_STATUS extends Value {

    public static final WS_GR_FOG_STATUS
       WSGF_FOG_STATUS_OFF = new WS_GR_FOG_STATUS(0, "WSGF_FOG_STATUS_OFF", "Off", true),
       WSGF_FOG_STATUS_ON = new WS_GR_FOG_STATUS(1, "WSGF_FOG_STATUS_ON", "On", true);

    private WS_GR_FOG_STATUS(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, WS_GR_FOG_STATUS.class);
    }

    /** @see Value#values(Class) */
    public static List<WS_GR_FOG_STATUS> values() {

        return values(WS_GR_FOG_STATUS.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<WS_GR_FOG_STATUS> values(boolean known) {

        return values(WS_GR_FOG_STATUS.class, known);
    }

    /** @see Value#get(int, Class) */
    public static WS_GR_FOG_STATUS get(int value) {

        return get(value, WS_GR_FOG_STATUS.class);
    }
}

