package discover.vdis.enums;

import java.util.List;

/**
 * WS_HAZE_TYPE: This class is auto-generated by vdis.EnumGenerator
 */
public final class WS_HAZE_TYPE extends Value {

    public static final WS_HAZE_TYPE
       WSH_TYPE_NO_HAZE = new WS_HAZE_TYPE(0, "WSH_TYPE_NO_HAZE", "No Haze", true),
       WSH_TYPE_OTHER_HAZE = new WS_HAZE_TYPE(1, "WSH_TYPE_OTHER_HAZE", "Other Haze", true),
       WSH_TYPE_RURUAL_HAZE = new WS_HAZE_TYPE(2, "WSH_TYPE_RURUAL_HAZE", "Rurual Haze", true),
       WSH_TYPE_MARITIME_HAZE = new WS_HAZE_TYPE(3, "WSH_TYPE_MARITIME_HAZE", "Maritime Haze", true),
       WSH_TYPE_URBAN_HAZE = new WS_HAZE_TYPE(4, "WSH_TYPE_URBAN_HAZE", "Urban Haze", true),
       WSH_TYPE_TROPOSPHERIC_HAZE = new WS_HAZE_TYPE(5, "WSH_TYPE_TROPOSPHERIC_HAZE", "Tropospheric Haze", true),
       WSH_TYPE_ADVECTIVE_FOG_HAZE = new WS_HAZE_TYPE(6, "WSH_TYPE_ADVECTIVE_FOG_HAZE", "Advective Fog Haze", true),
       WSH_TYPE_RADIATIVE_FOG_HAZE = new WS_HAZE_TYPE(7, "WSH_TYPE_RADIATIVE_FOG_HAZE", "Radiative Fog Haze", true),
       WSH_TYPE_DESERT_HAZE = new WS_HAZE_TYPE(8, "WSH_TYPE_DESERT_HAZE", "Desert Haze", true),
       WSH_TYPE_DESERT_SUMMER_HAZE = new WS_HAZE_TYPE(9, "WSH_TYPE_DESERT_SUMMER_HAZE", "Desert Summer Haze", true),
       WSH_TYPE_DESERT_WINTER_HAZE = new WS_HAZE_TYPE(10, "WSH_TYPE_DESERT_WINTER_HAZE", "Desert Winter Haze", true),
       WSH_TYPE_TEMPERATE_SUMMER_DAY = new WS_HAZE_TYPE(11, "WSH_TYPE_TEMPERATE_SUMMER_DAY", "Temperate Summer Day", true),
       WSH_TYPE_TEMPERATE_SUMMER_NIGHT = new WS_HAZE_TYPE(12, "WSH_TYPE_TEMPERATE_SUMMER_NIGHT", "Temperate Summer Night", true),
       WSH_TYPE_TEMPERATE_WINTER = new WS_HAZE_TYPE(13, "WSH_TYPE_TEMPERATE_WINTER", "Temperate Winter", true),
       WSH_TYPE_DUST_STORM_HAZE = new WS_HAZE_TYPE(14, "WSH_TYPE_DUST_STORM_HAZE", "Dust Storm Haze", true),
       WSH_TYPE_SNOW_HAZE_ = new WS_HAZE_TYPE(15, "WSH_TYPE_SNOW_HAZE_", "Snow Haze ", true),
       WSH_TYPE_BLOWING_SNOW_HAZE = new WS_HAZE_TYPE(16, "WSH_TYPE_BLOWING_SNOW_HAZE", "Blowing Snow Haze", true),
       WSH_TYPE_FOG_AND_SNOW_HAZE = new WS_HAZE_TYPE(17, "WSH_TYPE_FOG_AND_SNOW_HAZE", "Fog and Snow Haze", true);

    private WS_HAZE_TYPE(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, WS_HAZE_TYPE.class);
    }

    /** @see Value#values(Class) */
    public static List<WS_HAZE_TYPE> values() {

        return values(WS_HAZE_TYPE.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<WS_HAZE_TYPE> values(boolean known) {

        return values(WS_HAZE_TYPE.class, known);
    }

    /** @see Value#get(int, Class) */
    public static WS_HAZE_TYPE get(int value) {

        return get(value, WS_HAZE_TYPE.class);
    }
}

