package discover.vdis.enums;

import java.util.List;

/**
 * WS_HAZE_STATUS: This class is auto-generated by vdis.EnumGenerator
 */
public final class WS_HAZE_STATUS extends Value {

    public static final WS_HAZE_STATUS
       WSH_HAZE_STATUS_OFF = new WS_HAZE_STATUS(0, "WSH_HAZE_STATUS_OFF", "Off", true),
       WSH_HAZE_STATUS_ON = new WS_HAZE_STATUS(1, "WSH_HAZE_STATUS_ON", "On", true);

    private WS_HAZE_STATUS(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, WS_HAZE_STATUS.class);
    }

    /** @see Value#values(Class) */
    public static List<WS_HAZE_STATUS> values() {

        return values(WS_HAZE_STATUS.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<WS_HAZE_STATUS> values(boolean known) {

        return values(WS_HAZE_STATUS.class, known);
    }

    /** @see Value#get(int, Class) */
    public static WS_HAZE_STATUS get(int value) {

        return get(value, WS_HAZE_STATUS.class);
    }
}

