package discover.vdis.enums;

import java.util.List;

/**
 * WS_LIGHT_STATUS: This class is auto-generated by vdis.EnumGenerator
 */
public final class WS_LIGHT_STATUS extends Value {

    public static final WS_LIGHT_STATUS
       WSL_LIGHTING_STATUS_OFF = new WS_LIGHT_STATUS(0, "WSL_LIGHTING_STATUS_OFF", "Off", true),
       WSL_LIGHTING_STATUS_INSTANTANEOUS = new WS_LIGHT_STATUS(1, "WSL_LIGHTING_STATUS_INSTANTANEOUS", "Instantaneous Lightning", true),
       WSL_LIGHTING_STATUS_RANDOM = new WS_LIGHT_STATUS(2, "WSL_LIGHTING_STATUS_RANDOM", "Random Lightning", true);

    private WS_LIGHT_STATUS(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, WS_LIGHT_STATUS.class);
    }

    /** @see Value#values(Class) */
    public static List<WS_LIGHT_STATUS> values() {

        return values(WS_LIGHT_STATUS.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<WS_LIGHT_STATUS> values(boolean known) {

        return values(WS_LIGHT_STATUS.class, known);
    }

    /** @see Value#get(int, Class) */
    public static WS_LIGHT_STATUS get(int value) {

        return get(value, WS_LIGHT_STATUS.class);
    }
}

