package discover.vdis.enums;

import java.util.List;

/**
 * WS_LAYER_TYPE: This class is auto-generated by vdis.EnumGenerator
 */
public final class WS_LAYER_TYPE extends Value {

    public static final WS_LAYER_TYPE
       WSLY_LAYER_TYPE_GROUND_FOG = new WS_LAYER_TYPE(0, "WSLY_LAYER_TYPE_GROUND_FOG", "Ground Fog", true),
       WSLY_LAYER_TYPE_CLOUD_LAYER_1 = new WS_LAYER_TYPE(1, "WSLY_LAYER_TYPE_CLOUD_LAYER_1", "Cloud Layer 1", true),
       WSLY_LAYER_TYPE_CLOUD_LAYER_2 = new WS_LAYER_TYPE(2, "WSLY_LAYER_TYPE_CLOUD_LAYER_2", "Cloud Layer 2", true),
       WSLY_LAYER_TYPE_CLOUD_LAYER_3 = new WS_LAYER_TYPE(3, "WSLY_LAYER_TYPE_CLOUD_LAYER_3", "Cloud Layer 3", true),
       WSLY_LAYER_TYPE_RAIN = new WS_LAYER_TYPE(4, "WSLY_LAYER_TYPE_RAIN", "Rain", true),
       WSLY_LAYER_TYPE_SNOW = new WS_LAYER_TYPE(5, "WSLY_LAYER_TYPE_SNOW", "Snow", true),
       WSLY_LAYER_TYPE_SLEET = new WS_LAYER_TYPE(6, "WSLY_LAYER_TYPE_SLEET", "Sleet", true),
       WSLY_LAYER_TYPE_HAIL = new WS_LAYER_TYPE(7, "WSLY_LAYER_TYPE_HAIL", "Hail", true),
       WSLY_LAYER_TYPE_SAND_ = new WS_LAYER_TYPE(8, "WSLY_LAYER_TYPE_SAND_", "Sand ", true),
       WSLY_LAYER_TYPE_DUST = new WS_LAYER_TYPE(9, "WSLY_LAYER_TYPE_DUST", "Dust", true),
       WSLY_LAYER_TYPE_HAZE = new WS_LAYER_TYPE(10, "WSLY_LAYER_TYPE_HAZE", "Haze", true);

    private WS_LAYER_TYPE(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, WS_LAYER_TYPE.class);
    }

    /** @see Value#values(Class) */
    public static List<WS_LAYER_TYPE> values() {

        return values(WS_LAYER_TYPE.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<WS_LAYER_TYPE> values(boolean known) {

        return values(WS_LAYER_TYPE.class, known);
    }

    /** @see Value#get(int, Class) */
    public static WS_LAYER_TYPE get(int value) {

        return get(value, WS_LAYER_TYPE.class);
    }
}

