package discover.vdis.enums;

import java.util.List;

/**
 * WS_PREC_TYPE: This class is auto-generated by vdis.EnumGenerator
 */
public final class WS_PREC_TYPE extends Value {

    public static final WS_PREC_TYPE
       WSP_TYPE_NONE = new WS_PREC_TYPE(0, "WSP_TYPE_NONE", "None", true),
       WSP_TYPE_OTHER = new WS_PREC_TYPE(1, "WSP_TYPE_OTHER", "Other", true),
       WSP_TYPE_RAIN = new WS_PREC_TYPE(2, "WSP_TYPE_RAIN", "Rain", true),
       WSP_TYPE_SNOW = new WS_PREC_TYPE(3, "WSP_TYPE_SNOW", "Snow", true),
       WSP_TYPE_HAIL = new WS_PREC_TYPE(4, "WSP_TYPE_HAIL", "Hail", true),
       WSP_TYPE_SLEET = new WS_PREC_TYPE(5, "WSP_TYPE_SLEET", "Sleet", true),
       WSP_TYPE_FREEZING_RAIN = new WS_PREC_TYPE(6, "WSP_TYPE_FREEZING_RAIN", "Freezing Rain", true);

    private WS_PREC_TYPE(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, WS_PREC_TYPE.class);
    }

    /** @see Value#values(Class) */
    public static List<WS_PREC_TYPE> values() {

        return values(WS_PREC_TYPE.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<WS_PREC_TYPE> values(boolean known) {

        return values(WS_PREC_TYPE.class, known);
    }

    /** @see Value#get(int, Class) */
    public static WS_PREC_TYPE get(int value) {

        return get(value, WS_PREC_TYPE.class);
    }
}

