package discover.vdis.enums;

import java.util.List;

/**
 * WS_PREC_RATE: This class is auto-generated by vdis.EnumGenerator
 */
public final class WS_PREC_RATE extends Value {

    public static final WS_PREC_RATE
       WSP_RATE_NO_PRECIPITATION = new WS_PREC_RATE(0, "WSP_RATE_NO_PRECIPITATION", "No Precipitation", true),
       WSP_RATE_LIGHT_PRECIPITATION = new WS_PREC_RATE(1, "WSP_RATE_LIGHT_PRECIPITATION", "Light Precipitation", true),
       WSP_RATE_MODERATE_PRECIPITATION = new WS_PREC_RATE(2, "WSP_RATE_MODERATE_PRECIPITATION", "Moderate Precipitation", true),
       WSP_RATE_HEAVY_PRECIPITATION = new WS_PREC_RATE(3, "WSP_RATE_HEAVY_PRECIPITATION", "Heavy Precipitation", true);

    private WS_PREC_RATE(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, WS_PREC_RATE.class);
    }

    /** @see Value#values(Class) */
    public static List<WS_PREC_RATE> values() {

        return values(WS_PREC_RATE.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<WS_PREC_RATE> values(boolean known) {

        return values(WS_PREC_RATE.class, known);
    }

    /** @see Value#get(int, Class) */
    public static WS_PREC_RATE get(int value) {

        return get(value, WS_PREC_RATE.class);
    }
}

