package discover.vdis.enums;

import java.util.List;

/**
 * WS_PREC_RAIN: This class is auto-generated by vdis.EnumGenerator
 */
public final class WS_PREC_RAIN extends Value {

    public static final WS_PREC_RAIN
       WSP_RAIN_OFF = new WS_PREC_RAIN(0, "WSP_RAIN_OFF", "Off", true),
       WSP_RAIN_ON = new WS_PREC_RAIN(1, "WSP_RAIN_ON", "On", true);

    private WS_PREC_RAIN(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, WS_PREC_RAIN.class);
    }

    /** @see Value#values(Class) */
    public static List<WS_PREC_RAIN> values() {

        return values(WS_PREC_RAIN.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<WS_PREC_RAIN> values(boolean known) {

        return values(WS_PREC_RAIN.class, known);
    }

    /** @see Value#get(int, Class) */
    public static WS_PREC_RAIN get(int value) {

        return get(value, WS_PREC_RAIN.class);
    }
}

