package discover.vdis.enums;

import java.util.List;

/**
 * YES_NO: This class is auto-generated by vdis.EnumGenerator
 */
public final class YES_NO extends Value {

    public static final YES_NO
       NO = new YES_NO(0, "NO", "No", true),
       YES = new YES_NO(1, "YES", "Yes", true);

    private YES_NO(int value, String name, String description, boolean known) {

        super(value, name, description, known);

        cache(this, YES_NO.class);
    }

    /** @see Value#values(Class) */
    public static List<YES_NO> values() {

        return values(YES_NO.class);
    }

    /** @see Value#values(Class, boolean) */
    public static List<YES_NO> values(boolean known) {

        return values(YES_NO.class, known);
    }

    /** @see Value#get(int, Class) */
    public static YES_NO get(int value) {

        return get(value, YES_NO.class);
    }
}

